### ISSUE TITLE
Bugged?

### ISSUE THREAD

**Issue by RickC100SarcRP** [rauenzi/BetterDiscordApp#10]
I turned some switches on the panel, and now I cant see my settings, channel bar, or my friends list.  I have removed both the plugins and the Discord app its self.  I dont know what to do, any Ideas?

**Comment by RickC100SarcRP** [comment]
I will try to get a screenshot

**Comment by RickC100SarcRP** [comment]
![screenshot 3](https://user-images.githubusercontent.com/40503703/41799262-70bb8c9c-7636-11e8-8e1e-7ee9150fdf70.png)
This is what I see

**Comment by rauenzi** [comment]
You turned on minimal mode and hide channels. In this combination you rely heavily on keyboard shortcuts. Use control+comma to re-enter settings from there you can disable both of those modes.
