### ISSUE TITLE
Script not working when put in console.

### ISSUE THREAD

**Issue by Kaboongo** [rauenzi/BetterDiscordApp#102]
Hi bro, I was talking to this guy about an app and he said that I need better discord for it to work so he sent me the link to download it, I download it, I press CTRL+SHIFT+I, the console opens and then he told me to paste something into the console, I paste that into the console and it says ''Uncaught SyntaxError: Invalid or unexpected token'' and i tried reinstalling it 100 times and in the end that guy said he cant help me anymore because its not working for me and he doesnt know how to fix that, he said the problem is from my end, do you know what I could do to make it not give me that error anymore? thanks
![eeerror](https://user-images.githubusercontent.com/16637108/47622150-6a4dde00-daf9-11e8-8130-92122d309f65.PNG)

**Comment by rauenzi** [comment]
Stop opening this issue, it has been explained once. You are advertising a malicious script. 

I don't recommend you paste things in there without either knowing what you're doing or given instructions by someone who does. Clearly they don't know what they are doing. And now looking into what is being attempted, it is a malicious script that they even attempted to obfuscate so any suspecting persons wouldn't know what the code is attempting to do.

**Comment by Kaboongo** [comment]
Ok but can you tell me how to fix it pls? 
 
  On Sun, 28 Oct 2018 at 21:49, Zack<notifications@github.com> wrote:   
Stop opening this issue, it has been explained once. You are advertising a malicious script.

I don't recommend you paste things in there without either knowing what you're doing or given instructions by someone who does. Clearly they don't know what they are doing. And now looking into what is being attempted, it is a malicious script that they even attempted to obfuscate so any suspecting persons wouldn't know what the code is attempting to do.

**Comment by rauenzi** [comment]
No I will not tell you how to use a malicious script. This is not even an issue with BD/BBD.
