### ISSUE TITLE
BBD V0.2.4: Automatic loading bugs

### ISSUE THREAD

**Issue by CompletelyUnbelievable** [rauenzi/BetterDiscordApp#103]
I hope this is a false flag but automatic loading seems to have broken on my end, console was displaying this every time I saved a theme file:
![image](https://user-images.githubusercontent.com/39345185/47645544-8fa90f00-db2e-11e8-8b10-4e744230b6f1.png)

Also the on/off switch for automatic loading does not visually update unless you re-click the tab.

**Comment by rauenzi** [comment]
that error is fixed, will look into the enabling/disabling auto loading bug
