### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by swqux** [rauenzi/BetterDiscordApp#1038]
**Describe the Bug**

Whenever I try to open Discord, it says update failed retrying... Then, I uninstalled all plugins and themes and restarted my computer but its still like it. 

**To Reproduce**

Just open discord (for me)

**Expected Behavior**

I expected it to open normally.
**Screenshots**

<img width="278" alt="Screenshot 2021-09-17 at 9 37 56 AM" src="https://user-images.githubusercontent.com/90880201/133709885-8fbd4dc5-e67b-4224-9e4c-1ea9a0845426.png">
**Discord Version**

Stable

**Additional Context**

**Comment by fowlis** [comment]
Not convinced this is a BetterDiscord issue, rather a problem with your internet.

If you're on Windows, fully close Discord, press `Windows key` + `R` and paste this:
`%USERPROFILE%\AppData\Local\Discord\app-1.0.9002\Discord.exe --vanilla`
Then hit `Enter`

This should load Discord with BetterDiscord completely disabled, see if it can work this way.
If not, it's an error with Discord and/or your internet, so try again later.

If and/or when it eventually works, close Discord and open it normally to load BD again.

**Comment by swqux** [comment]
> Not convinced this is a BetterDiscord issue, rather a problem with your internet.
> 
> If you're on Windows, fully close Discord, press `Windows key` + `R` and paste this:
> `%USERPROFILE%\AppData\Local\Discord\app-1.0.9002\Discord.exe --vanilla`
> Then hit `Enter`
> 
> This should load Discord with BetterDiscord completely disabled, see if it can work this way.
> If not, it's an error with Discord and/or your internet, so try again later.
> 
> If and/or when it eventually works, close Discord and open it normally to load BD again.

Thanks

**Comment by swqux** [comment]
Also can you send me how to do this on mac? im on mac Thanks

**Comment by fowlis** [comment]
> Also can you send me how to do this on mac? im on mac Thanks

I have no clue how to do it on Mac, I'm waiting to find out if its possible and how.

Because BetterDiscord only modifies the client of Discord, it wouldn't interfere with anything server-side.
I would just close Discord and try again later.

**Comment by swqux** [comment]
kk thanks

**Comment by yourfriendoss** [comment]
This should be closed.
