### ISSUE TITLE
New installer color scheme (dark gray on almost black)

### ISSUE THREAD

**Issue by Hennricko** [rauenzi/BetterDiscordApp#105]
I might be nitpicking here, but I thought something was buggy when I couldn't click on "repair". Turns out I missed an almost impossible to see dark-gray-on-almost-black tickbox in front of "Repair On Stable". Maybe change the tickbox color to something a bit more visible?

Here's an example (excuse the crappy phone camera)
[bandagedbd.jpg](https://user-images.githubusercontent.com/44590626/47686658-98f0b500-dbdc-11e8-8af5-52bc258f5510.jpg)

On my 2nd monitor (60Hz IPS) it's relatively easy to see. Still not great, but at least distinguishable. On my main one however (crappy TN but 120Hz, which is the only reason I'm using it) it's damn near invisible (see example above)

I know the severity of this will be different based on the contrast/gamma settings and/or panel tech of the display you view this on, but dark gray on damn near black isn't a great color combo regardless of that IMO

**Comment by rauenzi** [comment]
The general idea is whether or not the big blue checkmark is there which is quite noticeable. I suggest future versions of the installer to go to the installer repo
