### ISSUE TITLE
Wont let me try to install

### ISSUE THREAD

**Issue by bengineer8** [rauenzi/BetterDiscordApp#106]
![image](https://user-images.githubusercontent.com/30581162/47833193-88207a80-dd67-11e8-87a5-a594cc7abd73.png)
running it as admin, outside of downloads, and it wont let me install it

**Comment by bengineer8** [comment]
Yes, i even tried installing the other 2 versions too

**Comment by rauenzi** [comment]
Click the checkmark next to "Install to Stable"

**Comment by bengineer8** [comment]
aaaaaaahhhhhhhh
was hard to see the check box
