### ISSUE TITLE
It just doesnt work

### ISSUE THREAD

**Issue by lOPPOl420** [rauenzi/BetterDiscordApp#107]
I have installed betterdiscord but whenever i start up discord i just cant find the place to change my background so im assuming it didnt work so i tried reinstalling it and it still didnt work and i did put it out of my download folder and opened it with admin so i have no clue what the problem is i have windows 10 btw

**Comment by rauenzi** [comment]
Can you elaborate on this:
>cant find the place to change my background

BBD doesn't just "have a place to change the background" you need a theme for that.
