### ISSUE TITLE
Cant download it

### ISSUE THREAD

**Issue by overthelimitsz** [rauenzi/BetterDiscordApp#1072]
Starting Install...

Creating required directories...
✅ Directory exists: C:\Users\Desktop\AppData\Roaming\BetterDiscord
✅ Directory exists: C:\Users\Desktop\AppData\Roaming\BetterDiscord\data
✅ Directory exists: C:\Users\Desktop\AppData\Roaming\BetterDiscord\themes
✅ Directory exists: C:\Users\Desktop\AppData\Roaming\BetterDiscord\plugins
✅ Directories created

Downloading asar file
❌ Failed to download package https://api.github.com/repos/rauenzi/BetterDiscordApp/releases
❌ Cannot read property 'assets' of undefined

The install seems to have failed. If this problem is recurring, join our discord community for support. https://discord.gg/0Tmfo5ZbORCRqbAd

When i try to download bd, that happens. What should i do?

**Comment by M4xter** [comment]
Starting Install...

Creating required directories...
✅ Directory exists: C:\Users\maxmo\AppData\Roaming\BetterDiscord
✅ Directory exists: C:\Users\maxmo\AppData\Roaming\BetterDiscord\data
✅ Directory exists: C:\Users\maxmo\AppData\Roaming\BetterDiscord\themes
✅ Directory exists: C:\Users\maxmo\AppData\Roaming\BetterDiscord\plugins
✅ Directories created

Downloading asar file
✅ Package downloaded

Injecting shims...
Injecting into: C:\Users\maxmo\AppData\Local\Discord\app-1.0.9003\resources
✅ Injection successful
✅ Shims injected

Restarting Discord...
Attempting to kill Discord
