### ISSUE TITLE
[Bug] Public Servers button has disappeared!

### ISSUE THREAD

**Issue by fowlis** [rauenzi/BetterDiscordApp#1074]
**Describe the Bug**
As the title says. With the setting enabled and all themes/plugins disabled, it is still gone :(

Making this issue since I'm not sure if its officially known or not.

**To Reproduce**
Enable the Public Servers button setting (if not already enabled)

**Expected Behavior**
Public Servers button should show

**Discord Version**
Stable

**Comment by mila6969** [comment]
Everything about the server list has broken because Discord changed class names again
