### ISSUE TITLE
Won't update???

### ISSUE THREAD

**Issue by VulpixHeart** [rauenzi/BetterDiscordApp#109]
I downloaded both zip files and the mac osx file but it won't update better discord. it keeps saying it's run across some sort of issue but it's too fast for me to read before discord itself launches. Once Discord launches it says that betterdiscord isn't supported anymore in this version and then betterdiscord says that it needs an update, but it just won't do the thing???

**Comment by rauenzi** [comment]
What are "both zip files" you only need to download the mac installer to install it. I can't help without the issue.
