### ISSUE TITLE
Status covering Profile pictures

### ISSUE THREAD

**Issue by NursuryRhyme** [rauenzi/BetterDiscordApp#11]
Recently ive been getting this bug where the person's status colour covers 90% of the persons profile when I click on their names like this:
![image](https://user-images.githubusercontent.com/32021152/42173730-0700106a-7dee-11e8-89c9-8e18179b2355.png)
how do i fix this?

**Comment by Inve1951** [comment]
this is not a BD issue. update your theme(s).
