### ISSUE TITLE
(Canary) BD Not Installed

### ISSUE THREAD

**Issue by Shoumil** [rauenzi/BetterDiscordApp#110]
Running the installer outside of the downloads folder with Admin works and says everything was installed to Canary. However, when Canary actually opens up BetterDisocrd is nowhere to be found. I have tried the new installer and the previous one. It was working fine right before the update. After the update, well you already know. 
Not sure if this has anything to do with it but, this was recently announced "Canary has been updated to Electron 4.x. Please be on the look out for new issues across all desktop platforms!"

**Comment by PtrKR** [comment]
Same issue.

**Comment by rauenzi** [comment]
This is known. Discord updated to Electron 4.0.0 which is a beta/unstable release. Realistically they shouldn't be using this at all but I am trying to develop a new way to inject into this new system.

**Comment by weeryan17** [comment]
Just tested the fix. it appears to be working again. good job on the fast fix
