### ISSUE TITLE
Stopped working after last canary updates

### ISSUE THREAD

**Issue by PtrKR** [rauenzi/BetterDiscordApp#111]
OS: Windows 10 Pro Insider Preview 18272.1000
Discord: DiscordCanary 0.0.218

Same as issue title. BandagedBD has stopped working after last discord canary updates. I have installed refactored version. but when i restarted discordcanary, bandagedbd icon and menu was disappeared.

※ Sorry for my bad english :(

**Comment by rauenzi** [comment]
Duplicate of #110
