### ISSUE TITLE
Themes not working

### ISSUE THREAD

**Issue by Mous133131** [rauenzi/BetterDiscordApp#12]
Like the title says, every theme I download doesn't show up in the themes tab.

**Comment by rauenzi** [comment]
It's quite possible you are not downloading them correctly. Ensure that they are named `ThemeName.theme.css` and that you have downloaded the **RAW** file from github.

**Comment by Mous133131** [comment]
Hmm, I've added ".theme" to each however now everytime I reload I am missing the meta.

**Comment by rauenzi** [comment]
It's very likely you didn't download the file properly. You may have downloaded the webpage instead of the theme. Ensure you click **RAW** before attempting to save the theme.

**Comment by Mous133131** [comment]
As you said, it seems like I had downloaded it wrong.
