### ISSUE TITLE
Can't click emoji

### ISSUE THREAD

**Issue by FelixMayer123** [rauenzi/BetterDiscordApp#121]
I did installed Discord, DiscordCanary and DiscordPTB.
and then i opens up, and when i click emoji, it won't open!
Is there issues with it?
(sorry bad grammar)

**Comment by FelixMayer123** [comment]
I did install the Betterdiscord Installer.
and then when i click emoji button, it won't shows up the library emoji!

**Comment by FelixMayer123** [comment]
I did try Discord, DiscordCanary and DiscordPTB.

**Comment by rauenzi** [comment]
I don't understand the issue

**Comment by FelixMayer123** [comment]
Nevermind, it works! thank you i didn't see that.

**Comment by rauenzi** [comment]
This has just been fixed, reload and go to settings > bandages > and click the button up top

**Comment by nxzlem** [comment]
oh sorry, it worked. thank you so much for it. i forgot to response.
