### ISSUE TITLE
'Repair' option on the installer requires one of the problem check boxes to be checked.

### ISSUE THREAD

**Issue by AndrioCelos** [rauenzi/BetterDiscordApp#122]
It seems that the installer currently won't let me 'Repair' my BetterDiscord installations unless I tell it one of the listed problems exists (they don't; the actual problem was Discord crashing on the Activity page). This should be fixed, or an 'Other' option added at least.

![image](https://user-images.githubusercontent.com/6897624/50036892-a49b1c80-0060-11e9-9729-75dcb349fbe4.png)

**Comment by rauenzi** [comment]
An `Other` option is unrealistic because it can't repair things it doesn't know how to repair. For problems that aren't listed, there is a link right there. It is even visible in your screenshot. Although based on your description a `Fatal JavaScript error on launch` fits your description.

**Comment by AndrioCelos** [comment]
Thanks for the clarification. I wasn't aware it did something different depending on the problem as I understood that 'Repair' usually just means 'make sure all the files and such are there'.

**Comment by rauenzi** [comment]
Unfortunately due to how volatile modding another program is there is a lot that can go wrong so even checking that the files are there isn't really enough to ensure it's working.
