### ISSUE TITLE
Scrolling in Repo pages

### ISSUE THREAD

**Issue by mumblz101** [rauenzi/BetterDiscordApp#123]
When trying to use the theme or plugin repos I see a list of themes/plugins but am unable to scroll down the list and the list itself is extending past the window. I will post a gyazo picture to show what I mean.

https://i.gyazo.com/ef4728575d6427948f0a2f488e4bf375.png

**Comment by rauenzi** [comment]
That's an issue with those plugins, not BBD. @mwittrien
