### ISSUE TITLE
Public Servers Search

### ISSUE THREAD

**Issue by WeirdScience06** [rauenzi/BetterDiscordApp#125]
I rarely use the public servers search function but today when trying it I ran into the following issue:

When hitting enter on the search nothing happens.

[https://i.imgur.com/bVAxJ2s.png](url)
If I try pressing Connect I get the following message

[https://i.imgur.com/TFNd0ld.png](url)

Clicking download leads me to a [Windows] Corrupt Installation page on the Discord website and advise manually deleting:

%AppData%/Discord
%LocalAppData%/Discord

I'm not sure how to proceed to fix the issue or if I should just ignore it as apart from the search everything else seems okay.

**Comment by rauenzi** [comment]
The public servers module is having issues interacting with discordservers.com and is broken for now

**Comment by rauenzi** [comment]
Will be fixed in next version
