### ISSUE TITLE
Discord always freezes after install - Windows

### ISSUE THREAD

**Issue by ryaniskira** [rauenzi/BetterDiscordApp#126]
While BetterDiscord is installed, Discord will always freeze 5-10 seconds after opening until BetterDiscord is uninstalled no matter if it's stable, PTB, or Canary.

**Comment by rauenzi** [comment]
A fresh install would be attempting to download emotes like I said above, you can check if this is the case by viewing the logs in console.

**Comment by ryaniskira** [comment]
If that's the case, would it be possible to copy the already downloaded files from my working install on my Laptop?
