### ISSUE TITLE
BandagedBD BdApi TypeScript @types now exist

### ISSUE THREAD

**Issue by Acidic9** [rauenzi/BetterDiscordApp#128]
This isn't an issue, more just a comment saying that my pull request for the official @types npm scope contains TypeScript typings for `BdApi` based from the [Creating Plugins docs](https://github.com/rauenzi/BetterDiscordApp/wiki/Creating-Plugins#bdapi).

**You can acess the typings here:**
https://www.npmjs.com/package/@types/bandagedbd__bdapi

**Or install with:**
```
yarn add @types/bandagedbd__bdapi
# or
npm i @types/bandagedbd__bdapi
```

I've scoped the package under `bandagedbd` as this isn't the BdApi from the official BetterDiscord from Jiiks.

Hopefully this will help any TypeScript plugin developers :)

**Comment by rauenzi** [comment]
I'll add this to the wiki
