### ISSUE TITLE
Latest Discord update broke.

### ISSUE THREAD

**Issue by Rietty** [rauenzi/BetterDiscordApp#129]
Latest Discord update broke BBD. Can't load anything/see any custom menus or options or use plugins. Feels just like stock discord again.

**Comment by rauenzi** [comment]
Try the repair option in the installer and/or reinstalling before opening an issue.

**Comment by Rietty** [comment]
Apologies! I'll be sure to do that next time. Thank you. :)

**Comment by rauenzi** [comment]
No problem, glad it worked.
