### ISSUE TITLE
Trying to attach files crashes Discord completely.

### ISSUE THREAD

**Issue by Dispenz0r** [rauenzi/BetterDiscordApp#13]
Basically I have this issue (that I've had since BetterDiscord times) that whenever I try to attach files, _sometimes_ it'll freeze the Discord completely and make it unresponsive. 

This only seems to happen with BetterDiscord installed, I've also completely re-installed Discord over and over again (including with BetterDiscord and Bandaged BD, I've also made sure to clear out leftover files) but was never able to fix this issue, at least with BD installed.

Is there anything I can do to fix this? Is this an issue people are having in general? I'd really love to know.

**Comment by rauenzi** [comment]
Remove all plugins and ensure you do not run discord as admin.

**Comment by Dispenz0r** [comment]
I also made sure to remove BetterDiscord files as well while re-installing, including BetterDiscord files, it only seems to happen during some of them. I usually have a folder with a lotta shitpost pics in it, uploading a few times doesn't seem to crash it at first but there's around 30% chance it'll crash after I pick the image or after the upload is finished. 

I also have no plugins installed, but just themes that I'm running, I also do not run discord as admin but open it normally.

**Comment by rauenzi** [comment]
try deleting this folder `%appdata%\discord\0.0.301` and running discord (without installing bd) to try and recreate the issue.

**Comment by intrnl** [comment]
Removing BD files from `%appdata%\BetterDiscord`?

**Comment by Dispenz0r** [comment]
Yup, I did remove old BD files last time.

I was also able to re-produce the crash after deleting that folder, oof this is troublematic, I'm not sure what is causing the crashes and how I can fix them, re-installing Discord/BD completely doesn't help either anymore.

**Comment by intrnl** [comment]
Yeah if you removed the folder `%appdata%\discord\0.0.301` (completely removes BD) and still encounter the crash then you should try reporting it to Discord instead.
