### ISSUE TITLE
[Bug] Website seems to be down

### ISSUE THREAD

**Issue by Fancy2209** [rauenzi/BetterDiscordApp#1307]
**Describe the Bug**

The BetterDiscord website seems to be down

**To Reproduce**

Try to open the Website https://betterdiscord.app/

**Expected Behavior**

The site to load

**Screenshots**

![image](https://user-images.githubusercontent.com/64917206/169354006-6d92b4ed-56c7-4339-9aa0-fde19940ae9b.png)

**Discord Version**

N/A

**Additional Context**

The site seems to be down, not sure if globally or just from my side, doesn't work in any of my 3 Internets

**Comment by Saltssaumure** [comment]
It's up for me.

**Comment by Fancy2209** [comment]
> It's up for me.

Looks like it was fixed now, it's also up for me now
I think it went down but it was just 4 or 3 minutes
