### ISSUE TITLE
Recent Discord Update Keeps Breaking BD

### ISSUE THREAD

**Issue by Z3ROGRAV1TYx** [rauenzi/BetterDiscordApp#131]
Recent Discord update broke BetterDiscord. I did a repair on BandagedD and it works. But when I close discord and relaunch, Discord runs an update again which seems to patch out BetterDiscord and Bandaged, so I need to rerepair using bandaged.

**Comment by survivplususer** [comment]
I've got the same problem but i can't repair BandagedBD

**Comment by rauenzi** [comment]
@Z3ROGRAV1TYx Yes Discord pushed a series of updates however the repair does work after each one.

**Comment by survivplususer** [comment]
Working thank you koyomi 👍

**Comment by Z3ROGRAV1TYx** [comment]
I made my post because I already did repair it, it works as I stated.. but when I completely close out of discord then reopen it I have to RErepair it because it keeps reverting to normal discord.
