### ISSUE TITLE
New Update Issues

### ISSUE THREAD

**Issue by Suftum** [rauenzi/BetterDiscordApp#135]
After Discord's latest updates my Discord seems to close and sign me out every so often while using BBD.

Wouldn't be as annoying if I didn't have 2FA on.

**Comment by intrnl** [comment]
can't really tell what's causing this issue, it should only be when you close Discord with devtools opened, but it seems that it also happens without for some people.

**Comment by rauenzi** [comment]
This is an issue with Discord's token hiding logic which they are aware of.
