### ISSUE TITLE
BD wont start up at all after recent update

### ISSUE THREAD

**Issue by KingFishy492** [rauenzi/BetterDiscordApp#136]
Updated discord with the most recent update that came in after discord updated it then restarted itself to finish its installation after installation was completed better discord no longer functions i have tried uninstalling discord and re dowloading better discord as well neither of these options have worked i have also deleted the discords core files left on the computer after the discord was uninstalled and it has had no effect on better discord working

**Comment by wvbigdave** [comment]
Where is this option at in the launcher?  Mine doesn't show this.

**Comment by rauenzi** [comment]
Sounds like you have an outdated installer.

**Comment by rauenzi** [comment]
@KingFishy492 did the repair option work for you?

**Comment by wvbigdave** [comment]
Thanks, I didn't know a new one came out.  Tried it and it works!!  Thanks!

**Comment by KingFishy492** [comment]
> @rauenzi  would you mind providing the link to the most recent one i believe i have got the most recent one downloaded this one does not seem to have a repair option tho

**Comment by intrnl** [comment]
it's in the [releases](https://github.com/rauenzi/BetterDiscordApp/releases) page

**Comment by KingFishy492** [comment]
idk what it was but for some reason that is the one i had i deleted it and re downloaded and installed it and its working fine now
