### ISSUE TITLE
Discord app starts hanging

### ISSUE THREAD

**Issue by crispymeow3000** [rauenzi/BetterDiscordApp#138]
Since installing Bandged BD my Discord app starts hanging 15 seconds or so after opening. It is running on Windows 10 Pro on Microsoft Surface (i7, 16gb ram, 512gb ssd)

**Comment by rauenzi** [comment]
It is likely trying to download emotes (or load them from file) in the background you can check console (ctrl+shift+i) and see if that's the case. There are also performance issues on Discord's side right now that they are trying to fix.

**Comment by crispymeow3000** [comment]
Nothing in the console looks wrong, and it is working fine now!
