### ISSUE TITLE
Extracting Core.asar

### ISSUE THREAD

**Issue by CodenameToxic** [rauenzi/BetterDiscordApp#14]
My installer for windows is just stopping at extracting the core.asar file. Help?

**Comment by rauenzi** [comment]
Ensure your discord is at least version 0.0.300

**Comment by CJ101** [comment]
Same issue, version is 0.0.301

**Comment by rauenzi** [comment]
Make sure you have run discord at least once so the files populate before running installer. Be sure to move the installer out of the downloads folder before running it.

**Comment by CJ101** [comment]
Moving it to a different folder worked, thanks boss
