### ISSUE TITLE
Discord Freezing

### ISSUE THREAD

**Issue by En3rgyBoy** [rauenzi/BetterDiscordApp#140]
Discord just stops responding after install
it takes like 30 seconds and then it freezes

**Comment by hamsterben5** [comment]
This is also happening to me since the latest Discord update.

**Comment by Cheapek** [comment]
Yeah, same here.

**Comment by rauenzi** [comment]
If it freezes give it a minute to try and overcome it, if it still fails let me know.

**Comment by WilfordBrimley** [comment]
Still freezing. I've gotten it to work on reinstall, but it goes back to frozen after a few launches.

**Comment by rauenzi** [comment]
Please check console within Discord to see the most recent logs before it freezes

**Comment by Wavy3000** [comment]
My discord is also freezing when I install.

**Comment by rauenzi** [comment]
Then I need the same info as above

**Comment by EnderDoes** [comment]
I'm also having this error, and whenever it happens, I can only scroll up and down. I can't click anything

I tried posting this error in the Discord, but I can't seem to get into it as whenever I join, I get this error
![image](https://user-images.githubusercontent.com/39538638/51495268-6096e800-1d81-11e9-9942-2ae6bded28ed.png), and I can't join it anymore because discord says this: Error: You are being rate limited

**Comment by rauenzi** [comment]
The logs pictured show that it's Discord's own fault. By 30 seconds in BD would be fully loaded and already started anyways.

**Comment by EnderDoes** [comment]
Is there any way to fix this? @rauenzi

**Comment by WilfordBrimley** [comment]
I'm no longer having the issue. I was never able to get to the console to see the output. Let me explain what I did to fix :
Uninstall bd and discord.
Restart your pc. 
Install bd. 
Enjoy.

**Comment by intens0** [comment]
Still freezing.

**Comment by WilfordBrimley** [comment]
Guys, if you don't have any new data to add besides what the topic already states, please shut it. I'm tired of getting these notifications and none are a resolution or any new information.

**Comment by whalehub** [comment]
@rauenzi While the Discord client only remains frozen for some time after startup, you can't actually enable any plugins because Discord freezes indefinitely when you try to do it. Please investigate and fix this issue ASAP since it breaks BetterDiscord's main functionality completely.

**Comment by RevanProdigalKnight** [comment]
@WilfordBrimley, you can unsubscribe from the thread if you don't want to get notifications.

I've found that BetterDiscord stops freezing for me after disabling the Twitch/FrankerFaceZ/BetterTTV emotes.

**Comment by intrnl** [comment]
@whalehub That doesn't help, it's either the emotes or Discord itself, more logs of the console before the freeze is needed.

**Comment by rauenzi** [comment]
I think the issue to be `JSON.parse` for TwitchSubscriber emotes. For anyone with the issue the temporary workaround is to set `emoteCacheDate` in `bdstorage.json` to something like `2019-01-23T03:22:03.099Z` and unzipping and putting the attached file in the `%appdata%\BetterDiscord` folder

[emote_data.zip](https://github.com/rauenzi/BetterDiscordApp/files/2785854/emote_data.zip)

**Comment by minijoker2o0** [comment]
I have tried your work around no dice !, there is no set emoteCacheDate in the bdstorage.json and 2 the emote_date.zip keeps freezing when extracted and editing in note pad ++

**Comment by minijoker2o0** [comment]
>           I'm no longer having the issue. I was never able to get to the console to see the output. Let me explain what I did to fix :
> Uninstall bd and discord.
> Restart your pc.
> Install discord and bd.
> Enjoy.
> Edit: sorry for the confusion.

can confirm this is the working method discord has not froze since :D thank you dude 👍

**Comment by littlebroto1** [comment]
I got these errors.
![image](https://user-images.githubusercontent.com/38365568/51646699-486cc780-1f3f-11e9-84bc-93178f6c0cc6.png)

**Comment by littlebroto1** [comment]
I know a friend who was having some problems with their bot after it became 2019 due to the year change. Could something similar be happening here?

**Comment by intrnl** [comment]
No? The year issue is when it hits 2038, not 2019.

**Comment by AxillaryPower** [comment]
My Discord keeps freezing after launch after installing BetterDiscord, but it does start working again after a minute or so. I tried uninstalling Discord, restart, and reinstalling, but it didn't change anything. I don't know what would be useful in the console, so here's everything after the first warning,
![image](https://user-images.githubusercontent.com/19981357/52463495-09e12a80-2b45-11e9-89fa-400994491e85.png)
