### ISSUE TITLE
BD not loading plugins

### ISSUE THREAD

**Issue by somerandomuser1** [rauenzi/BetterDiscordApp#141]
So I have been having this issue for a few weeks now, finally out of options/things to try, so here ya go...fix it plox kthx.

Symptoms:
1: discord opens, loads up nice and fast (its installed on an SSD), after a second or 2, it freezes (I know this is an issue with emotes, keep reading)
2: after it unfreezes, it says it has "started" all my plugins, but its actually not starting them at all.
3: going into the plugins menu and turning them off and on again sometimes makes them start, but sometimes it doesnt
4: if you can manage to get them to start, then you hit CTRL+R to refresh discord, they wont start again and then no amount of turning them off and back on again will get them to come back (literally, the plugins either load on the first opening of discord, or its a RIP, quit discord and open again and pray)

List of things I've tried to fix it:
1: updating all plugins to the latest versions available (no dice)
2: removing all plugins, then testing them 1 at a time to see if its a specific plugin causing the issue (no dice)
3: noticed that "Emotes loaded" was taking forever (it used to be super fast, literally the very first thing that popped up before any plugins loaded), figured maybe thats the issue, deleted the Emote cache, turned off downloading emotes, disabled all emotes in the emote menu (no dice, although this does fix the freezing issue, which I also noticed others talking about in a different issue report)
4: using the newest bandagedbd for windows (the new GUI) to run a repair (which literally just reinstalls BD) (no dice)
5: uninstall BD completely (also wipe all BD data) and reinstall fresh, then put plugins back in (no dice)
6: uninstall both BD and Discord completely, and delete all relavent data (including roaming files) and then reinstall both (no dice)

welp, thats about it. Im all out of stuff to try. soooooooo...................can we get a fix sometime soonish???

**Comment by rauenzi** [comment]
>soooooooo...................can we get a fix sometime soonish???
BBD is still working just fine. It sounds like an issue with the startup of the plugins you have, it is something that plagues plugins on occasion. A list of what plugins you're attempting to load would be helpful.

**Comment by somerandomuser1** [comment]
Lib Discord Internals by Samogot (required for next plugin)
Quoter by Samogot
MemberCount by Arashiryuu
ReadAllNotifications Button by DevilBro
ServerFolders by DevilBro

**Comment by rauenzi** [comment]
Is there anything in console about errors?
