### ISSUE TITLE
Minimal mode breaks new Server Discovery button

### ISSUE THREAD

**Issue by SCOTT0852** [rauenzi/BetterDiscordApp#147]
I really like using minimal mode so more stuff can fit on screen, but the server discovery button is misplaced with it.
![image](https://user-images.githubusercontent.com/33875157/53317946-68ffa880-3882-11e9-995d-d389cc20133f.png)
It still occurs when using my theme, which is a modified Clearvision Sapphire. If it can't be repositioned, the ability to at least hide it would be nice.

**Comment by TwinDragon** [comment]
```css
.container-11WMXy{
	display: none;
}```

I use that to hide the Server Discovery button in the themes I use. Works for now at least until they change the class again.

**Comment by rauenzi** [comment]
Will be fixed in next version
