### ISSUE TITLE
Minimal Mode (and other settings) not working

### ISSUE THREAD

**Issue by SanMarino11** [rauenzi/BetterDiscordApp#148]
It seems that Minimal Mode (and I think other settings) won't change for me. This started when I restarted my PC yesterday. I wiped and deleted Discord, reinstalled, installed BBD and nothing. My client is stuck in default, non-minimal mode. BBBD is loaded, I can see emotes and the BD settings, but changing the settings changes nothing.

**Comment by rauenzi** [comment]
Discord changed a bunch of CSS that makes it seem like it isn't working but it still is.

**Comment by SanMarino11** [comment]
Is there anything I can do to force it back into minimal mode?

**Comment by rauenzi** [comment]
No, I'll have to fix it eventually

**Comment by SanMarino11** [comment]
Alright, thanks for responding.
