### ISSUE TITLE
Bad performance.

### ISSUE THREAD

**Issue by LucozadeKing** [rauenzi/BetterDiscordApp#15]
Hey I've just installed since the official version on the better discord site wouldn't work at all for me and I've installed around 30 plugins recommended to me by a friend. I'm get pretty bad performance when hovering over channels, switching channels and servers etc it takes a second to catch up which shouldn't be happening on my PC.
6700k
GTX 970
16GB of RAM

Pretty confused, is it likely to be one of the plugins I installed or something else? Thanks.

**Comment by rauenzi** [comment]
It's very likely a plugin. To minimize BBD's impact turn off anything emote related and turn off the class normalizer. If the slowdowns still occur it is a plugin.

**Comment by Inve1951** [comment]
you should only use official plugins (those are listed on the BD discord servers). and yes, it's likely a plugin causing that. not all plugins are well optimized and some may cause a short freeze when switching servers.

**Comment by LucozadeKing** [comment]
All of the plugins I use are by DevilBro. Are these official?

**Comment by rauenzi** [comment]
Official, but not necessarily efficient. Which are you using, there are several by him that users have reported as causing slowdowns

**Comment by LucozadeKing** [comment]
![9l238x25](https://user-images.githubusercontent.com/25966784/42354561-96190152-80bf-11e8-9de3-a4fe52921ca7.png)

**Comment by rauenzi** [comment]
Try disabling them and see if you still experience slowdowns. You also don't need those first two files "BDFunctions..."

**Comment by LucozadeKing** [comment]
Doesn't seem like it, even enabling the Friend Count plugin brings back the slowdowns. Feels like any plugins do

**Comment by rauenzi** [comment]
So if they're all disabled there is no slowdown?

**Comment by LucozadeKing** [comment]
Yes

**Comment by rauenzi** [comment]
Have you tried using ones not made by DevilBro to compare?

**Comment by LucozadeKing** [comment]
The BD Server is down so I'm not sure where to find any

**Comment by rauenzi** [comment]
Well I have some on my BetterDiscordAddons repo

**Comment by rauenzi** [comment]
Consider testing a few of his and reporting the slowdowns to him
