### ISSUE TITLE
Doesn't start on master

### ISSUE THREAD

**Issue by shiewa** [rauenzi/BetterDiscordApp#155]
If I use the master branch, I get that error when starting Discord.
https://imgur.com/dPCQ7K5
OS: Arch Linux with latest updates
Discord Version: DiscordCanary 0.0.74

**Comment by rauenzi** [comment]
Latest Canary is using a non-stable version of electron for whatever reason and I don't support that.

**Comment by rauenzi** [comment]
Master branch is not an injection branch so it shouldn't work
