### ISSUE TITLE
[MAC - 10.14.4] Installer cant find Discord

### ISSUE THREAD

**Issue by knackrack615** [rauenzi/BetterDiscordApp#157]
So after updating to 10.14.4 the installer can no longer find my Discord instance (I'm using the Canary Build) and copy-pasting the file path manually in the box doesn't help either (As shown in screenshot)

![image](https://user-images.githubusercontent.com/2822335/55682243-950a5100-5939-11e9-9134-816f12dd47d1.png)

Also the Exit button doesn't seem to be functional.

**Comment by rauenzi** [comment]
@qwerasd can you look at this?

**Comment by rauenzi** [comment]
@qwerasd205 can you look into this?

**Comment by qwerasd205** [comment]
Currently I don't have time to test, but I'm guessing this problem has to do with a recent update to Discord Canary, for the time being you could use stable and it _should_ be fine. Within a few days I should hopefully be able to resolve the problem.

**Comment by knackrack615** [comment]
So here's something interesting, i installed regular Discord and ran the BBD installer and guess what? BOTH DISCORD INSTANCES WERE DETECTED, went ahead and installed into Canary and now everything works again. I have no idea why that happened and what could have caused this but hey now it works :)

**Comment by coldreactor64** [comment]
@knackrack615 I can confirm that this is the current thing with PTB.I had the same error, and repeated the steps by installing the stable version and after it detected the PTB and regular discord.

**Comment by rauenzi** [comment]
@qwerasd205 when you get a chance it seems like an issue with your electron hijacking based on the update by @knackrack615

**Comment by n3oney** [comment]
@qwerasd205 Looks like the issue is still not fixed. Any chance you will look into that?

**Comment by qwerasd205** [comment]
> @qwerasd205 Looks like the issue is still not fixed. Any chance you will look into that?

Have been pretty busy lately, and since the issue doesn't have a very large impact (few macOS + Canary users) and is non-critical (people can just install stable), I haven't been very motivated to fix it. I figure I'll just fix it when the breaking change is made to stable.

**Comment by rekkisomo** [comment]
Looks like this is happening as well on Sierra. (10.12.6)
