### ISSUE TITLE
[suggestion] Support for Android

### ISSUE THREAD

**Issue by OzoneHelix** [rauenzi/BetterDiscordApp#158]
would it be out of the realm of possibility to make an android app version of better discord for android I'm sure there are better ways to do it but maybe use chromium (open source version of chrome) to built a better discord app Discord is a web based app on linux windows and mac os so building it out of open source chromium may be one way to achieve

**Comment by intrnl** [comment]
1. Android support? that's effort.
2. No one's willing to do it.
3. You don't have to go through such effort to bundle Chrome, it's not like you can't modify the native Android app.
4. Use Substratum, this is assuming that people only needed the theming aspect of BetterDiscord.

**Comment by rauenzi** [comment]
Yes it's much out of the realm. Android is an entirely different environment and nothing that currently exists in the BD world would work there. There are many other factors that go into not doing this as well but that is a big one.
