### ISSUE TITLE
Discord crashes upon hovering over the Mute, Deafen, and User Settings buttons

### ISSUE THREAD

**Issue by JG-GIT** [rauenzi/BetterDiscordApp#159]
I don't know why this happens, but it just does.

**Comment by intrnl** [comment]
We can't reproduce without more details.

Does the window just closes or does it just shows a crash screen?

If it shows a crash screen, don't reload or close it. Press Ctrl + Shift + I and head to the Console tab, then screenshot the errors, those are usually highlighted with red.

**Comment by Zmxhawrhbg** [comment]
Hi, just throwing in there that this happens to me too, it shows a crash screen.
![image](https://user-images.githubusercontent.com/25387744/56336858-e941dc00-6156-11e9-8d2b-69c51918ba5b.png)
On Discord Canary.

**Comment by intrnl** [comment]
Reproduced, here's the nitty gritty.

Discord somehow complains if the layerContainer class is modified, class normalizer needs to ignore it.

**Comment by Chazza** [comment]
Yeah I am experiencing this as well..

**Comment by JG-GIT** [comment]
Alright, now it works.
