### ISSUE TITLE
Instructions for compiling from source

### ISSUE THREAD

**Issue by DavidRazdolski** [rauenzi/BetterDiscordApp#16]
Hello, 
Unsure if this is the right place, but would you be able to provide the instructions for compiling the source code from source?

Thanks in advance

**Comment by Inve1951** [comment]
looks like zere forgot to include some files. you build with grunt afaik.

**Comment by rauenzi** [comment]
There is no compilation step.

**Comment by Inve1951** [comment]
is it really a single 4k LoC file now? :eyes:

**Comment by rauenzi** [comment]
It has been for like a year, so I kept it the same when I forked. Was debating separating it out but keep hoping BDv2 will come out before that becomes super convenient.
