### ISSUE TITLE
Can't open guild

### ISSUE THREAD

**Issue by MinerChAI** [rauenzi/BetterDiscordApp#162]
I can't open Satoru's guild (https://disc.gg/chikara) with clean BD (no plugins or themes) - Discord crashes. But other guilds open normally lmao (I haven't checked all the guilds, I have 70+)

**Comment by MinerChAI** [comment]
Fixed now somehow

**Comment by MinerChAI** [comment]
Ok I realized the real problem.
There's some symbol that crashes BD

**Comment by rauenzi** [comment]
Can you elaborate on "Some symbol"?

**Comment by MinerChAI** [comment]
You should the server owner I think, because he've deleted these messages

**Comment by MinerChAI** [comment]
There was a message that a user with void nickname left the server, i think that nickname contains that symbol

**Comment by rauenzi** [comment]
BD doesn't do any processing of usernames
