### ISSUE TITLE
Crashes instantly on the latest Canary

### ISSUE THREAD

**Issue by bgiesing** [rauenzi/BetterDiscordApp#163]
On the latest Canary (app-0.0.234 on Windows 10), Discord crashes instantly upon loading (it shows the "Well this is awkward" screen with the reload button). BandagedBD is being loaded since the icon shows at the bottom right and the toasts for emote loading appear for a split second before the crash.

Crash log from DevTools: https://pastebin.com/Bs4ZrZES

**Comment by Pryhzma** [comment]
The same problem happens on all versions I think, I crash instantly as well.

**Comment by pobgithub** [comment]
I'm in many servers but it only crash if I go to my main server

**Comment by ancient-ai** [comment]
> I'm in many servers but it only crash if I go to my main server

do you own it? main server as in your most frequently used or the one/only one you manage

**Comment by BiBi88** [comment]
Member of a server with mod powers. Main server I visit with discord ptb. Crashes. Had to uninstall.

**Comment by pobgithub** [comment]
> 
> 
> > I'm in many servers but it only crash if I go to my main server
> 
> do you own it? main server as in your most frequently used or the one/only one you manage

I meant as my default, I own a couple servers but it only crashes on one of them.

**Comment by AyanamiRei1** [comment]
Crashes on my own servers here hoping for a fix soon on Stable also.

**Comment by Arill** [comment]
The error is triggered when emotes are being injected on chat. Switching to a chat with emotes or typing/having someone type an emote crashes instantly. Changing to a channel without emotes and/or turning off emotes completely makes the crashes disappear.

**Comment by kLee02** [comment]
For me it crashes on only one server for me (the server with the most channels, I also own the server) and the crashes only occur sometimes when I click on different text channels or on the server itself regardless of there being emotes on them. It can sometimes reload discord and at times fail all the time for me. I am on Stable.

**Comment by Vsyncrooo** [comment]
It started with me installing a lot of plugins but after disabling these it still kept crashing

**Comment by marcussacana** [comment]
same here, but i'm using the stable build

**Comment by kLee02** [comment]
> It started with me installing a lot of plugins but after disabling these it still kept crashing

I uninstalled everything including discord, then reinstalled BandagedBD and nothing else, the problem still persists. maybe its something on discord's end messing with BD?

**Comment by rauenzi** [comment]
Please reload Discord and see if the issue persists (also ensure BBD version is 0.2.8 after reloading)

**Comment by Pryhzma** [comment]
It's fixed for me. I use stable, if that helps.

**Comment by bgiesing** [comment]
Not fixed for me on Canary, now it doesn't crash but it's infinitely loading at the bottom right even if I reinstall or repair BD

**Comment by rauenzi** [comment]
Can you show me a screenshot of console? And type in console `bbdVersion` and tell me the output?

**Comment by bgiesing** [comment]
https://i.imgur.com/7Ca6INb.png bbdVersion: "0.2.8"

**Comment by rauenzi** [comment]
Hmm I will look into this then

**Comment by ptrkr** [comment]
same here on latest canary build

**Comment by kLee02** [comment]
Fixed for me! I am on Stable, I cannot live without BBD, many thanks!

**Comment by rauenzi** [comment]
Should be fixed now on canary with 0.2.9. @bgiesing are you still having your issue?

**Comment by bgiesing** [comment]
It's working now 👍
