### ISSUE TITLE
Crashes once entering server on stable

### ISSUE THREAD

**Issue by AyanamiRei1** [rauenzi/BetterDiscordApp#164]
Pretty much whats happening is it's crashing while clicking on a server without fail I've already tested that it doesn't happen on regular Discord but only crashes on Better Discord. So far I've reset all my settings no plugins or themes enabled but the crashes still happen.

This has been happening since an hour ago and I have no idea why.

**Comment by andymwat** [comment]
You closed the issue, did you manage to find out a fix?

**Comment by marcussacana** [comment]
I think he closed because is because is duplicate

**Comment by AyanamiRei1** [comment]
I closed it because I saw the Canary issue after I posted this so I thought it's a duplicate.
