### ISSUE TITLE
Switching servers with emotes causes crash

### ISSUE THREAD

**Issue by Technetium1** [rauenzi/BetterDiscordApp#165]
Having emotes enabled causes a crash when you switch servers, or to a private message. You can load in to the default channel normally.

**Comment by Glaived** [comment]
# Here is a temporary solution to disable the Emotes options, which will prevent you from crashing

Location : `C:\Users\<USERNAME>\AppData\Roaming\BetterDiscord`
File : `bdstorage.json`

Open the file and pass the following parameters to FALSE :
- bda-es-0
- bda-es-1
- bda-es-2
- bda-es-4
- bda-es-6
- bda-es-7
- bda-es-8
- bda-es-9

**Comment by rauenzi** [comment]
Please reload Discord and see if the issue persists (also ensure BBD version is 0.2.8 after reloading)

**Comment by Technetium1** [comment]
@rauenzi that fixed it https://github.com/rauenzi/BetterDiscordApp/commit/335019322123aaa18e412b3a98b79635476a5b6c

**Comment by rauenzi** [comment]
Alright, that is just a hotpatch for now to prevent crashing... proper fix to come later.

**Comment by Vsyncrooo** [comment]
How do you update to 2.8, still running old
