### ISSUE TITLE
Crash when entering server

### ISSUE THREAD

**Issue by andymwat** [rauenzi/BetterDiscordApp#166]
Possibly a duplicate of #164, but that issue was closed.

On the latest release (BD v0.3.0, BBD v0.2.7), opening a server causes Discord to crash. The crash only happens shortly after the server icon is clicked on; the rest of Discord, including settings, themes, plugins, DMs, etc appears to work fine.

The full console log: https://pastebin.com/gMDtQU2s
The errors seem to be around line 220.

I'm using several plugins, but the crash still happens when they're removed.

**Comment by Technetium1** [comment]
@andymwat Possible duplicate of #165? Try to disable your emotes in bdstorage.

**Comment by rauenzi** [comment]
Please reload Discord and see if the issue persists (also ensure BBD version is 0.2.8 after reloading)

**Comment by AneiDoru** [comment]
> Please reload Discord and see if the issue persists (also ensure BBD version is 0.2.8 after reloading)

I tried reloading discord, re-installing discord, re-installing BBD, trying regular BD, only disabling all emote settings in BBD worked, there's something wrong with the emote settings.

**Comment by rauenzi** [comment]
Did you ensure BBD version is 0.2.8?

**Comment by AneiDoru** [comment]
Also I'm using the latest version (october 28) and turning off all BBD emote settings are the only way to fix it.

**Comment by AneiDoru** [comment]
> Did you ensure BBD version is 0.2.8?

There is no 0.2.8 that I can find, the latest one up is the October version which is 0.2.7
The discord server for BD2 is down so I can't get a link to the new version

**Comment by rauenzi** [comment]
It seems you quoted my statement before but did not read it. I asked you to reload at that point because a remote update had been made. Please reload and check that the BBD version in settings says 0.2.8 (note a remote update **does not** require you to reinstall BBD).

**Comment by AneiDoru** [comment]
> It seems you quoted my statement before but did not read it. I asked you to reload at that point because a remote update had been made. Please reload and check that the BBD version in settings says 0.2.8 (note a remote update **does not** require you to reinstall BBD).
I've reloaded many times and it stayed at BBD v0.2.7, reinstalled it even, it didn't update. Can you put an installer for 0.2.8 up so I can update it?

**Comment by rauenzi** [comment]
That's not how that works no. Fully close your Discord and reopen it to see if it appears at 0.2.8. The installer does not affect the remote.

**Comment by AneiDoru** [comment]
> That's not how that works no. Fully close your Discord and reopen it to see if it appears at 0.2.8. The installer does not affect the remote.

Oh, it did it, thank you! I'm sorry for being so silly, that fixed it!

**Comment by rauenzi** [comment]
@andymwat Does this work for you as well?

**Comment by KevinParnell** [comment]
Doesn't work for me.

**Comment by Silentz0r** [comment]
@KevinParnell Check plugins, mine was crashing with 'HideServersChannelsRedux' plugin.

**Comment by CptDinosaur** [comment]
I get the same issue with emotes disabled and plugins disabled.

**Comment by lLeezy** [comment]
I had this issue went thought and disabled all the plugins and themes and then started re enabling them 1 by one.. for me it was the "Reply System v0.0.8 Zerebos" with this disabled im back to normal use.

**Comment by Jome666999** [comment]
This also appeared for me today. Seems that disabling all plugins doesn't fix the issue. I've also tried repairing BBD, but that didn't work. I'm on the latest version.

**Comment by DakuGekko** [comment]
Have the same issues with BBD.
I'm also on 0.2.8

**Comment by Silentz0r** [comment]
> This also appeared for me today. Seems that disabling all plugins doesn't fix the issue. I've also tried repairing BBD, but that didn't work. I'm on the latest version.

Reinstall just in case, rename/backup 'plugins' folders to make sure it's a clean install.

**Comment by rauenzi** [comment]
Yeah be sure to remove all plugins from the plugin folder

**Comment by CptDinosaur** [comment]
Version 0.2.9 fixed, plus updating ReplySystem addon and restarting.

**Comment by rauenzi** [comment]
@andymwat @KevinParnell @Jome666999 does that work for you as well?

**Comment by andymwat** [comment]
Sorry for the late response, but unchecking all of the options in the "emotes" tab, relaunching Discord, and then rechecking them fixed it.
