### ISSUE TITLE
[BBD] Infinite loading plugins&themes on Canary

### ISSUE THREAD

**Issue by fixator10** [rauenzi/BetterDiscordApp#167]
Discord starts just fine, but BBD settings, plugins and themes doesnt works

```js
Uncaught TypeError: Cannot read property 'split' of undefined
    at t (cdn.staticaly.com/gh/rauenzi/BetterDiscordApp/e737b0c343ba4fe7f6f3a17da59983586b980ace/js/main.min.js:4)
    at o (345ae7ded6064a0fccb7.js:49)
```

This happens even without plugins

**Comment by DontStalkMebro** [comment]
same

**Comment by Glaived** [comment]
same problem for me, remove BBD and re-install it does not solve the problem

**Comment by rauenzi** [comment]
Make sure you try it again, a fix was pushed less than half an hour ago.

**Comment by Glaived** [comment]
I tried after the patch was deployed. I am in stable version
