### ISSUE TITLE
Plugins duplicating

### ISSUE THREAD

**Issue by Vsyncrooo** [rauenzi/BetterDiscordApp#168]
I don't know when it happend but a lot of my plugins are duplicating for a reason. In the plugins folder and tab on Bd it saids only 1 plugin but the same plugin acts as 2 for a reason.

![image](https://user-images.githubusercontent.com/43010892/56471301-3bce1180-6451-11e9-84b2-124faf010576.png)

**Comment by rauenzi** [comment]
Go delete `%appdata%\discord\0.0.305` and restart Discord

**Comment by Vsyncrooo** [comment]
That seems to have fixed it. Thank you

**Comment by rauenzi** [comment]
Glad it worked!
