### ISSUE TITLE
BD Not Loading

### ISSUE THREAD

**Issue by PaulZappia** [rauenzi/BetterDiscordApp#169]
I've tried repairing BandagedBD multiple times already but it didn't work. What's the problem?

**Comment by minter567** [comment]
I am experiencing the same issue on Mac. Tried reinstalling several times BD will not launch.

**Comment by rauenzi** [comment]
Just pushed another fix, reload in 5 minutes and see if it works.

**Comment by tinman66** [comment]
Is Discord constantly trying sabotage the BD app?
Seems like this happens many times after they update.
Anyway, great app, I love it!

**Comment by PaulZappia** [comment]
It's like Discord's trying to pull a Nintendo on BD right now

**Comment by minter567** [comment]
Works fine now thank you!

**Comment by PaulZappia** [comment]
All good now. Thanks!
