### ISSUE TITLE
BetterDiscord Server

### ISSUE THREAD

**Issue by divinitydivine** [rauenzi/BetterDiscordApp#17]
I'm not sure whats going on, (maybe it has too many members??) but when I try to join the BetterDiscord server for themes and such it doesn't join and just loads for 20sec before displaying no channels and no selected server? is the server bugged, or something I did wrong along the steps of installing?

**Comment by rauenzi** [comment]
The server is just full, you'll have to wait for a spot to open up. If you want to browse plugins and themes get the PluginRepo and ThemeRepo plugins from here https://github.com/mwittrien/BetterDiscordAddons/tree/master/Plugins

It will add buttons to the plugin and theme pages (at the top) so you can browse them without being in the server.
