### ISSUE TITLE
Problem with many instances

### ISSUE THREAD

**Issue by MinerChAI** [rauenzi/BetterDiscordApp#170]
When they are many Discord instances running (e. g. I have all of them - Stable, PTB and Canary) something strange happens: some plugins and themes become broken, some enabling and disabling on their own, sometimes event turning off **ALL** plugins, themes, bandages, etc.

**Comment by rauenzi** [comment]
That's not likely due to BBD. There are differences in the internals of those versions of Discord which can cause plugins to fail (and auto-disable). The class names and html structure is changing in canary so themes may appear broken.

**Comment by MinerChAI** [comment]
> That's not likely due to BBD. There are differences in the internals of those versions of Discord which can cause plugins to fail (and auto-disable). The class names and html structure is changing in canary so themes may appear broken.

It isn't only canary problem but ok.

**Comment by rauenzi** [comment]
Canary was just one example. Classes have changed in all 3 releases but Canary had the most. I can't really diagnose this without many more details.
