### ISSUE TITLE
can't join BD discord and installation doesn't put files in discord location

### ISSUE THREAD

**Issue by cursedscripts** [rauenzi/BetterDiscordApp#172]
The title says it all, it doesn't let me join the BD Discord, the "join" button doesn't work and I'm not banned because I never went on there.
And also I've tried installing BD a lot of times and it didn't start up, plus I saw the files of the installation weren't even there.
(I have also got some JavaScript errors, and I've already tried to fix them with the option JavaScript fatal error)

**Comment by cursedscripts** [comment]
Discord problem fixed.

**Comment by rauenzi** [comment]
Can't join due to server being full. Will have to wait until it becomes available
