### ISSUE TITLE
New Discord Update broke better discord

### ISSUE THREAD

**Issue by SpaceCucumber** [rauenzi/BetterDiscordApp#174]
The latest update to Discord seemed to break a lot of graphical things, mainly on the left side of the screen and the activity section, the custom color for text and background seems to be messed up with the new update.
[![Screenshot from Gyazo](https://gyazo.com/6fc671f484fec6921305da701caa3c53.jpg/raw)](https://gyazo.com/6fc671f484fec6921305da701caa3c53.jpg)
[![Screenshot from Gyazo](https://gyazo.com/d60edde25285f0b774bb83a8dae33fb2.png/raw)](https://gyazo.com/d60edde25285f0b774bb83a8dae33fb2.png)

**Comment by rauenzi** [comment]
This is an issue with your theme, not BBD. Ask the Theme Developer nicely to update it.
