### ISSUE TITLE
Settings don't save

### ISSUE THREAD

**Issue by jacobmix** [rauenzi/BetterDiscordApp#175]
Can't disable Twitch Emotes, FrankerFaceZ Emotes or BetterTTV Emotes.
Loads of other settings don't seem to save changes.

**Comment by rauenzi** [comment]
You mean it doesn't persist between reloads or doesn't persist between opening settings or what

**Comment by jacobmix** [comment]
Nevermind. Disabling all plugins, restarting, and then changing the settings works.
I can then just enable them all again. Maybe a plugin or multiple stops settings changes for some reason.
