### ISSUE TITLE
Discord Canary not launching with BBD

### ISSUE THREAD

**Issue by Halo-Chan** [rauenzi/BetterDiscordApp#178]
(I'm using BBD Update 318)
Ok so my Discord Canary had to update and I updated it and then BBD didn't launch. 
So I went to repair it and next thing I know, Fatal JavaScript error. 
Yes I have reinstalled/repaired several times.
And there's also an issue of text turning black for no reason 
(This may be my custom theme or BBD I don't know)

**Comment by rauenzi** [comment]
This has been fixed, please reinstall.
