### ISSUE TITLE
BD не устанавливается

### ISSUE THREAD

**Issue by bei1e** [rauenzi/BetterDiscordApp#181]
When installed, bd freezes in half of the installation. Already tried different versions, but nothing helped. In the latest bd version, the slider did not move at all during installation.
![bandicam 2019-05-16 00-59-23-620](https://user-images.githubusercontent.com/50681472/57812535-ff52b480-7775-11e9-82ad-e16459501dcf.jpg)
![bandicam 2019-05-16 01-00-15-062](https://user-images.githubusercontent.com/50681472/57812536-ffeb4b00-7775-11e9-8b39-eda6b9aeab51.jpg)

**Comment by rauenzi** [comment]
That means your internet is preventing the installer from downloading the resources it needs.
