### ISSUE TITLE
Rendering issues preventing users from installing BBD

### ISSUE THREAD

**Issue by snappyapple632** [rauenzi/BetterDiscordApp#182]
The installer, when selecting which version(s) to be installed, scales the window incorrectly and cuts off the tick boxes, preventing the user from installing BBD. The tick box for restarting Discord is also weird. See screenshot.

![Capture](https://user-images.githubusercontent.com/40573129/57961813-549ddb80-78c6-11e9-9070-6b177b31a5ec.PNG)

**Comment by intrnl** [comment]
HiDPI displays huh.

**Comment by rauenzi** [comment]
Duplicate of https://github.com/rauenzi/BBDInstaller/issues/3
