### ISSUE TITLE
Android? 

### ISSUE THREAD

**Issue by Merith-TK** [rauenzi/BetterDiscordApp#184]
Would it be possible to make a android version? Willing to test everything and report logs.

**Comment by intrnl** [comment]
It is possible, with a few exceptions

1. Modding an Android app is bothersome
2. We don't have the necessary resource and time to do so
3. Is there any that are going to use it? If only a few, then it's probably not worth the effort

**Comment by Merith-TK** [comment]
one might be surprised how many people would use it, And I have a lot of free time usually so I can learn and work on it a bit more, i really just need to know what aspects im editing and i should be fine

**Comment by rauenzi** [comment]
Nothing in the current codebase could be used in an android version of this. It would have to be a completely different project with different plugins and themes.

**Comment by Merith-TK** [comment]
Ah, alright
(note, have successfully decompiled the latest apk from apkpure for this and will go through the code on my own time then)
