### ISSUE TITLE
public server button [Bug]

### ISSUE THREAD

**Issue by mwittrien** [rauenzi/BetterDiscordApp#187]
**Describe the Bug**
The public server button: 
1. does not get hidden on start up even if disabled
2. vanishes when switching between servers/dms
**To Reproduce**
1. reload while settings for public seevers are disabled
2. switch between servers/dms/server discovery

**Expected Behavior**
1. hide button if disabled
2. readd the button if the guildswrapper is rerendered

**Discord Version**
all versions

**Comment by peacefulpocket** [comment]
I also am experiencing this bug

**Comment by rauenzi** [comment]
Part 1 (showing up on startup when disabled) has been fixed.

**Comment by MasicoreLord** [comment]
Hope the 2nd bug in this report gets fixed soon.
