### ISSUE TITLE
[Bug] Bandages button not working

### ISSUE THREAD

**Issue by Gibbu** [rauenzi/BetterDiscordApp#188]
**Describe the Bug**
Clicking "Bandages" button doesn't show the bandages options

**To Reproduce**
Click on the Bandages button

**Expected Behavior**
Show the user the Bandages options

**Screenshots**
![image](https://user-images.githubusercontent.com/20338746/58232131-113ae580-7d7c-11e9-99a3-39ff67180f7f.png)

**Discord Version**
Stable

**Additional Context**
I've disabled all my plugins and themes and fully restarted Discord.

**Comment by williamjcm** [comment]
Can't reproduce here. :/

Are there any errors in the console ? Press <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>i</kbd> to open it.

**Comment by Gibbu** [comment]
None.

**Comment by williamjcm** [comment]
Right. I was one version behind. And now I can reproduce... 🤔
