### ISSUE TITLE
discord canary forces update when modified

### ISSUE THREAD

**Issue by Bluscream** [rauenzi/BetterDiscordApp#19]
Kind of related to https://github.com/Jiiks/BetterDiscordApp/issues/829

Currently whenever i install bbd, discord updates itself and theirfore looses bbd. is there anything we can do about that?

**Comment by rauenzi** [comment]
That really only happens on Canary, they don't update the files that often on stable. There aren't a lot of ways to fix this anyways besides attempting to patche their updater which isn't the easiest feat.

**Comment by Bluscream** [comment]
Im pretty sure this aren't just normal updates. It basically forces an update everytime you reinstall bd and start discord (every 30 seconds if you're fast enough) maybe it should be removed from the installer idk. I want bd for new features and canary for new features :/

**Comment by rauenzi** [comment]
I don't know of anyone that experienced this

**Comment by intrnl** [comment]
With how BDv1 is designed, I don't think there's any way to survive over module updates that easily.

**Comment by Bluscream** [comment]
Is it possible to bypass updates at all except when there are real ones?

**Comment by CollinScripter** [comment]
I don't have the issue of the constant updating, but I am on Canary and it's a bit of a pain. Something you *could* do is have it launch another process to wait for the update to finish, then kill Discord and reinstall BD, which wouldn't really require you to patch the updater itself.

**Comment by intrnl** [comment]
that's too much of a bodge.

**Comment by Inve1951** [comment]
tried flagging the modules read-only?

**Comment by intrnl** [comment]
updater gets stuck in an update loop that way

**Comment by Inve1951** [comment]
lame
what about changing discord's version number to `0.0.0`?

**Comment by Bluscream** [comment]
What about starting the actuak binary instead of squirrel?

**Comment by rauenzi** [comment]
Nope, it still updates the modules, but not the file in local appdata.

**Comment by Bluscream** [comment]
Could i redirect the update check to another webserver and always return that i have the latest version?
