### ISSUE TITLE
[Bug] Popup for update but none available (Linux)

### ISSUE THREAD

**Issue by FichteFoll** [rauenzi/BetterDiscordApp#190]
**Describe the Bug**

When BBD initialized, a popup is shown hinting at an update being available. However, the download page links to the 0.3.1 release page which was made in October last year.

Since I run **Arch Linux**, I cannot use the installer and used to fetch the AUR package for this, which points to the `stable16` branch. That still works fine.

However, installing either the 0.3.1 branch or current `master` with `betterdiscordctl` results in an error message on startup and then discord closing.

**Screenshots**
![2019-05-28_20-38-06](https://user-images.githubusercontent.com/931051/58503533-18e9f800-8189-11e9-9aee-d12b8bc00368.png)

![2019-05-28_20-38-33](https://user-images.githubusercontent.com/931051/58503537-1a1b2500-8189-11e9-83e2-f7dcd053c9b2.png)

**Discord Version**

stable 0.0.9

**Comment by rauenzi** [comment]
This is due to the Linux installer *still* using the old injection method with `stable16` I will push an update for the `stable16` this time but no longer in the future. Please bug the maker of the installer to move to the injection BBD is using as of almost a year ago.

**Comment by FichteFoll** [comment]
Thanks for looking into it. There are issues for this on betterdiscordctl's side, but they are very recent (https://github.com/bb010g/betterdiscordctl/issues/37, https://github.com/bb010g/betterdiscordctl/issues/38).

Will you push a new tag for the new stable version?

**Comment by rauenzi** [comment]
I talked to bb010g about a year ago about these changes that they never made.

I won't push a new tag no*--but you can use bdctl to update using the `stable16` branch once more and the popup should go away now.

*The reason I'm not pushing a new tag is because most of the installation stuff happens by grabbing directly from the repo and the releases are for the installers. (Note: this was something that was set in place by Jiiks with the original BD which makes it very difficult to suddenly switch how everything works)

**Comment by FichteFoll** [comment]
All right, makes sense. No reason to use the tags for fetching the latest version, then. Thanks again and hopefully the new method will be supported soon.

**Comment by ObserverOfTime** [comment]
bb010g has been MIA for a while. Let me know how the new injection works and I'll try to implement it one of these days. I think you mentioned in the past but I can't recall the specifics.

**Comment by rauenzi** [comment]
@ObserverOfTime just put it over on bb010g/betterdiscordctl#37
