### ISSUE TITLE
[Bug] No 0.3.2?

### ISSUE THREAD

**Issue by feikname** [rauenzi/BetterDiscordApp#191]
On startup my BandagedDiscord said 0.3.2 is available (probaly this commit's fault: 52f538169986cd3e84c074b086ecf26c1123a365), but latest version in Release pages is 0.3.1.

**Comment by Paulaob79** [comment]
Happens to me too.

**Comment by rauenzi** [comment]
I know how confusing it seems due to the version numbers being similar but the `0.3.1` on the releases page refers to the installer's version and the `0.3.2` requested refers to the injector's version. You can use your current installer (version `0.3.1`) to reinstall and get the updated injector.

**Comment by PassiveModding** [comment]
Might be helpful to have a distinction between the two in the popup message

**Comment by rauenzi** [comment]
Considering this, as well as resetting the installer's version to `1.0.0` since it was rewritten (which is what I probably should have done). And possibly using the releases page for the injection.
