### ISSUE TITLE
[Bug] Issues with the new injection under Linux

### ISSUE THREAD

**Issue by ObserverOfTime** [rauenzi/BetterDiscordApp#194]
I've started implementing the new injection for betterdiscordctl (see #190) and ran into a few issues.

## Discord's resources are system-wide

Discord's `resources` directory is normally located in `/opt/discord` or `/usr/share/discord`.
This raises 2 issues:
1. Injecting BD into it requires `sudo`, which means that a user without sufficient permissions cannot install it.
2. This forces all users sharing a Linux PC to use BetterDiscord if it's installed, even if they don't want it.

## Symlinks fail to resolve properly

It seems that the injector looks for `app.asar` in the parent directory.

https://github.com/rauenzi/BetterDiscordApp/blob/32821834d01428c29390bfb8bebbf4806241cd7b/index.js#L4-L5

However, this doesn't resolve properly if BD is symlinked from another location:

```
$ discord
Uncaught Exception:
Error: Cannot find module '/home/johan/.local/share/betterdiscordctl/bd/app.asar/package.json'
    at Module._resolveFilename (internal/modules/cjs/loader.js:584:15)
    at Function.Module._resolveFilename (/opt/discord/resources/electron.asar/common/reset-search-paths.js:43:12)
    at Function.Module._load (internal/modules/cjs/loader.js:510:25)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/johan/.local/share/betterdiscordctl/bd/0/index.js:5:13)
    at Object.<anonymous> (/home/johan/.local/share/betterdiscordctl/bd/0/index.js:34:3)
    at Module._compile (internal/modules/cjs/loader.js:693:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)
$ file /opt/discord/resources/app
/opt/discord/resources/app: symbolic link to /home/johan/.local/share/betterdiscordctl/bd/0
```
## Cannot inject to a Discord installed via Snap

```
cp: cannot create directory '/snap/discord/93/usr/share/discord/resources/app': Read-only file system
```

Snap apps are placed under [confinement](https://docs.snapcraft.io/snap-confinement) and mounted read-only. This can be changed by setting the `--classic` flag on installation which, for some reason, the Discord package seems to ignore:

```
$ snap install --classic discord
Warning: flag --classic ignored for strictly confined snap discord

discord 0.0.9 from Snapcrafters installed
```

**Comment by rauenzi** [comment]
So Discord shares the same binaries across all release channels? (stable, canary, ptb)

It isn't mean to resolve a symlink there as the injector is (rightfully) expecting it to be in the proper location. Sometimes electron goes crazy with symlinks inside the `app` dir.

Snap and the portable discord have never been officially supported and I don't feel like rewriting everything to do so.

**Comment by ObserverOfTime** [comment]
Canary and PTB are suffixed accordingly (e.g. `/usr/share/discord-canary`) but each release channel installs its resources system-wide.

**Comment by rauenzi** [comment]
Ah I see what you meant now, well that is truly idiotic.

BD isn't meant to serve all release channels from the same injection though. The configs in BD's injection are meant to be per-channel.

I don't know enough about snap or how it works to do anything about it.


I will look into alternatives for injecting with Linux but I make no guarantees

**Comment by rauenzi** [comment]
So just to double check the only place that works for all of those above was the Linux equivalent of `roaming` right?

**Comment by ObserverOfTime** [comment]
I suppose?

* Stable, Canary & PTB use `$XDG_CONFIG_HOME/discord` (suffixed accordingly) where `$XDG_CONFIG_HOME` falls back to `~/.config` when unset.
* Snap uses `$SNAP_USER_DATA/.config/discord` where `$SNAP_USER_DATA` is only set in Discord's Snap shell.
* Flatpak uses `~/.var/app/com.discordapp.Discord/config/discord`.

I also found two more issues with the new injection:
1. Since it's now installed via `sudo`, Discord can't write to it when running as a regular user.
2. The default `"frame": false` setting hides the native titlebar completely since Discord doesn't have a custom titlebar on Linux.

**Comment by rauenzi** [comment]
Hmm I have a few thoughts about getting the new injector to work properly in the old location... Can you shoot me a DM on Discord when you have a chance?

**Comment by rauenzi** [comment]
Seems (with a small update to the `injector` branch) we were able to find steps that worked:

1. Locate `discord_desktop_core` for the release channel
2. Create an `injector` folder there.
3. Download or clone the `injector` branch from the repo.
4. Place the contents of the branch to inside the `injector` folder.
5. Modify `discord_desktop_core/index.js` to add `require("./injector");` on a line of it's own before the `module.exports` statement (top of file).
6. Restart Discord

**Comment by MasicoreLord** [comment]
As long as the injection method allows things like the transparency option to be set it would be good to go if users could install it only per user as well, rauenzi and ObserverOfTime

**Comment by MasicoreLord** [comment]
Finally the injection is being updated on linux.

Hopefully users are able to actually upgrade DIscord through the repo w/o problems w/ the recent injection update.

**Comment by ObserverOfTime** [comment]
Implemented in bb010g/betterdiscordctl@a0f24e1.

Works in Arch Linux for
* Stable: `0.0.9`
* Canary: `0.0.78`
* PTB: `0.0.15`
* Snap: `stable 0.0.9 (93)`
* Flatpak: `0.0.9 (installation: user)`

The transparency can be enabled but I don't have a transparent theme to test whether it actually works.

**Comment by rauenzi** [comment]
Comfortable with me closing this in that case?

**Comment by ObserverOfTime** [comment]
I think you should leave it open for visibility for a little while.

**Comment by rauenzi** [comment]
Well you can pin closed issues, but sure I'll leave it open for a day or so.
