### ISSUE TITLE
[Bug] Installer Fails On Downloading

### ISSUE THREAD

**Issue by TylerJF** [rauenzi/BetterDiscordApp#196]
**Describe the Bug**
When I run the BandagedBD installer it fails on the download period, closing the installer.

**Discord Version**
Stable, Canary, and PTB

**Comment by rauenzi** [comment]
Can you show me a screenshot of the installer and/or a gif of this occurring?

**Comment by juress** [comment]
It's asking me on every startup to update to 0.3.2 and to reinstall from a new installer, which I did like twice already. In settings it says I have 0.3.0

**Comment by rauenzi** [comment]
Stale.
