### ISSUE TITLE
[Bug] Better Discord not Installing in the Newer Version,

### ISSUE THREAD

**Issue by EmperorKermit** [rauenzi/BetterDiscordApp#198]
After seeing the new Version of Better Discord for 2 Days now, I decided to go Install it. After I tried I went through all the Steps and when I was installing it it was at the half way mark at the ''Renaming DIR'' and I tried different things, even trying the Windows notice the Creator put there. Nothing seems to work, I also cannot join the better Discord Server as it becomes a ''1 Server is unavailable due to a temporary outage'' why I do not know. But if anyone knows a solution to this, would be much appreciated.

**Comment by rauenzi** [comment]
Try manually closing all discord processes using task manager before attempting to reinstall bbd

**Comment by EmperorKermit** [comment]
Alright, I just tried it and it finishes Downloading. Thank you very much, have a good day!
