### ISSUE TITLE
can't added role to user

### ISSUE THREAD

**Issue by LightningScarlet** [rauenzi/BetterDiscordApp#200]
i can't added role to user but i can added role with bot command only

**Comment by rauenzi** [comment]
Can you please provide a lot more information? There's a reason we have issue templates.

**Comment by prezeskusix** [comment]
Same thing here. It's a clean installation discord and BandagedBD without any plugins / themes
https://gyazo.com/4138772ba16a21d1e3a0f30109ed6747

**Comment by LightningScarlet** [comment]
yes can't add role but can remove roles
if uninstall betterdiscord don't have any problems

**Comment by mwittrien** [comment]
disable normalized classes in the BD settings to fix it

**Comment by prezeskusix** [comment]
@mwittrien Works, thanks.

**Comment by Therewatchingus** [comment]
I cant add role

**Comment by piks** [comment]
Just adding on, this isn't just on adding roles, additionally you can't create new channel overrides
