### ISSUE TITLE
[Bug] No config shown, plugins don't load

### ISSUE THREAD

**Issue by S-B99** [rauenzi/BetterDiscordApp#202]
**Describe the Bug**
Plugins don't load, no configuration options shown in Discord settings

**To Reproduce**
1. Install BBD
2. Launch, check settings

**Expected Behavior**
Plugins do load, I can customize BBD

**Screenshots**
![image](https://user-images.githubusercontent.com/17222512/58764649-cff2c480-8537-11e9-9525-edee39041baa.png)

**Discord Version**
Stable

**Additional Context**
On Linux, using this to install https://github.com/bb010g/betterdiscordctl

**Comment by rauenzi** [comment]
Can you check console for errors?

**Comment by S-B99** [comment]
`[FAST CONNECT] wss://gateway.discord.gg/?encoding=etf&v=6&compress=zlib-stream, encoding: etf, version: 6
9833a7395829bb4e2d56.js:49 Initializing voice engine with audio subsystem: standard
9833a7395829bb4e2d56.js:49 [BUILD INFO] Release Channel: stable, Build Number: 38950, Version Hash: 4483a2c7d8be95c80b8555ec0c25c778fc221af0
9833a7395829bb4e2d56.js:49 [NATIVE INFO] host 0.0.9, modules: discord_desktop_core: 1, discord_erlpack: 1, discord_spellcheck: 1, discord_utils: 1, discord_voice: 1, discord_game_utils: 1, discord_rpc: 2, discord_contact_import: 1, discord_zstd: 1
9833a7395829bb4e2d56.js:49 unsupported locale en-GB
e.(anonymous function) @ 9833a7395829bb4e2d56.js:49
9833a7395829bb4e2d56.js:49 unsupported locale en
e.(anonymous function) @ 9833a7395829bb4e2d56.js:49
9833a7395829bb4e2d56.js:49 [FAST CONNECT] connected in 565ms
9833a7395829bb4e2d56.js:49 CloudSync is not supported on this platform
e.(anonymous function) @ 9833a7395829bb4e2d56.js:49
9833a7395829bb4e2d56.js:49 [GatewayDiscovery] [STICKY] wss://gateway.discord.gg
9833a7395829bb4e2d56.js:49 [GatewaySocket] [CONNECT] wss://gateway.discord.gg, encoding: etf, version: 6, compression: zlib-stream
9833a7395829bb4e2d56.js:49 [GatewaySocket] [CONNECTED] wss://gateway.discord.gg/?encoding=etf&v=6&compress=zlib-stream in 0 ms
9833a7395829bb4e2d56.js:49 [GatewaySocket] [IDENTIFY]
9833a7395829bb4e2d56.js:49 [GatewaySocket] [HELLO] via gateway-prd-main-8w26, heartbeat interval: 41250, took 5 ms
9833a7395829bb4e2d56.js:49 [RPCServer:WSS] Starting on 6463
9833a7395829bb4e2d56.js:49 [RPCServer:IPC] Starting on /run/user/1000/discord-ipc-0
9833a7395829bb4e2d56.js:49 [BandagedBD] [Startup] Initializing Settings
9833a7395829bb4e2d56.js:49 [BandagedBD] [Startup] Initializing EmoteModule
9833a7395829bb4e2d56.js:49 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
(anonymous) @ 9833a7395829bb4e2d56.js:49
9833a7395829bb4e2d56.js:49 [BandagedBD] [Emotes] Loading emotes from local cache.
9833a7395829bb4e2d56.js:49 [GatewaySocket] [READY] via gateway-prd-main-8w26 -> discord-sessions-prd-1-24 as 097a5c5db377ecf1a1454966ec18935e, took 980 ms
9833a7395829bb4e2d56.js:49 [GuildAvailabilityStore] 4 guilds are unavailable on connection open: 86004744966914048,227543998590353408,280806472928198656,327892735963037696
e.(anonymous function) @ 9833a7395829bb4e2d56.js:49
9833a7395829bb4e2d56.js:49 Tried getting Dispatch instance before instantiated
e.(anonymous function) @ 9833a7395829bb4e2d56.js:49
9833a7395829bb4e2d56.js:49 patch render of TabBar
9833a7395829bb4e2d56.js:49 patch default of Object
9833a7395829bb4e2d56.js:49 patch render of Guild
9833a7395829bb4e2d56.js:49 patch render of Guilds
9833a7395829bb4e2d56.js:49 [BandagedBD] [Startup] Updating Settings
9833a7395829bb4e2d56.js:49 [BandagedBD] [Emotes] Emotes loaded from cache.
9833a7395829bb4e2d56.js:49 patch render of MessageContent
9833a7395829bb4e2d56.js:49 [BandagedBD] [Startup] Initializing QuickEmoteMenu
9833a7395829bb4e2d56.js:49 Uncaught TypeError: Cannot read property 'remove' of null
    at setTimeout (cdn.staticaly.com/gh/rauenzi/BetterDiscordApp/c268371144a5ac3dbeaa6b2af0aebcba055d10b5/js/main.min.js:55)
    at i (9833a7395829bb4e2d56.js:49)
9833a7395829bb4e2d56.js:49 [GuildAvailabilityStore] Guild has become available: 227543998590353408
9833a7395829bb4e2d56.js:45 [Deprecation] Using unescaped '#' characters in a data URI body is deprecated and will be removed in M71, around December 2018. Please use '%23' instead. See https://www.chromestatus.com/features/5656049583390720 for more details.
n.setFullScrollerState @ 9833a7395829bb4e2d56.js:45
my_god_v3.2.png:1 Failed to load resource: the server responded with a status of 504 ()
9833a7395829bb4e2d56.js:49 Hold Up!
9833a7395829bb4e2d56.js:49 If someone told you to copy/paste something here you have an 11/10 chance you're being scammed.
9833a7395829bb4e2d56.js:49 Pasting anything in here could give attackers access to your Discord account.
9833a7395829bb4e2d56.js:49 Unless you understand exactly what you are doing, close this window and stay safe.
9833a7395829bb4e2d56.js:49 If you do understand exactly what you are doing, you should come work with us https://discordapp.com/jobs`

**Comment by rauenzi** [comment]
Nothing pops up when going to settings?

**Comment by S-B99** [comment]
Nope. in the first screenshot that's basically it. BBD logo in bottom right, credits link at the bottom, nothing changed. The emoji picker is changed in the way of the background color and borders

**Comment by rauenzi** [comment]
Not sure why it's not loading properly. Are you sure your installation is up to date and the local config is pointing to the right branch?

**Comment by S-B99** [comment]
Yes. I already checked that and have done a clean install as of today. Is it possible the Linux injector is broken?

**Comment by rauenzi** [comment]
It's possible your version is out of date, but the Linux installer and the injection was just updated and redone very recently

**Comment by S-B99** [comment]
It's not possible since this is the first time I've installed BBD on this machine.

**Comment by S-B99** [comment]
Resolved after a full X session restart, it might be useful to pin this or add to faq

**Comment by S-B99** [comment]
If I quit BBD, and reopen it again, I have the same issue. You have to restart your pc or even just X in order to fix it

**Comment by rauenzi** [comment]
I cannot personally recreate this. Perhaps another Linux user has seen something similar? @ObserverOfTime

**Comment by ObserverOfTime** [comment]
I can't reproduce it either but @JeremyStepp's [issue](https://github.com/bb010g/betterdiscordctl/issues/38#issuecomment-497397913) might be related.

**Comment by S-B99** [comment]
What do your setups look like?
Ubuntu 18.10 (switching to 04 soon)
AwesomeWM

**Comment by Meizwe** [comment]
I am still having issues after upgrading to 1.6.0 and installing/reinstalling, it now doesn't give even a popup or the loading gif now.

**Comment by rauenzi** [comment]
Version 1.6.0 of what?

**Comment by Meizwe** [comment]
Betterdiscordctl

**Comment by ObserverOfTime** [comment]
@Meizwe You're using snap, right? Please post the output of:
```sh
snap info discord
betterdiscordctl reinstall -v -v --snap
betterdiscordctl update -v -v --snap
```

**Comment by JeremyStepp** [comment]
I get the same issue, but the emotes loaded message will show up. I'm on Linux Mint 19 using the flatpak Discord and the ppa for betterdiscordctl. The error I get after betterdiscord starts up is 
```
(node:4) UnhandledPromiseRejectionWarning: Error: ENOSPC: no space left on device, watch '/home/jeremy/.var/app/com.discordapp.Discord/config/BetterDiscord/plugins'
    at FSWatcher.start (internal/fs/watchers.js:164:26)
    at Object.watch (fs.js:1232:11)
    at Object.watchContent (https://cdn.staticaly.com/gh/rauenzi/BetterDiscordApp/c268371144a5ac3dbeaa6b2af0aebcba055d10b5/js/main.min.js:55:18798)
    at V2_SettingsPanel.initializeSettings (https://cdn.staticaly.com/gh/rauenzi/BetterDiscordApp/c268371144a5ac3dbeaa6b2af0aebcba055d10b5/js/main.min.js:55:79707)
    at Core.init (https://cdn.staticaly.com/gh/rauenzi/BetterDiscordApp/c268371144a5ac3dbeaa6b2af0aebcba055d10b5/js/main.min.js:4:580)
(node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
/app/bin/discord: line 9: kill: (3) - No such process
```

**Comment by ObserverOfTime** [comment]
@JeremyStepp That seems like a Flatpak issue and thus unrelated to BBD. Move your comment to a new issue in betterdiscordctl and I'll look into it.

**Comment by Meizwe** [comment]
`miw@q8D-AX370-K7:~$` betterdiscordctl reinstall -v -v --snap
VV: Checking /snap/discord/93/usr/share/discord
V: Using Discord at /snap/discord/93/usr/share/discord
V: Found modules in /home/miw/snap/discord/93/.config/discord/0.0.9/modules
Killing Discord processes...
No active processes found.
V: Removing old injector folder.
V: Copying BetterDiscord injector...
Reinstalled.
miw@q8D-AX370-K7:~$ betterdiscordctl update -v -v --snap
VV: Checking /snap/discord/93/usr/share/discord
V: Using Discord at /snap/discord/93/usr/share/discord
V: Found modules in /home/miw/snap/discord/93/.config/discord/0.0.9/modules
Updating Git repository...
remote: Enumerating objects: 62, done.
remote: Counting objects: 100% (62/62), done.
remote: Compressing objects: 100% (31/31), done.
remote: Total 58 (delta 28), reused 49 (delta 26), pack-reused 0
Unpacking objects: 100% (58/58), done.
From https://github.com/rauenzi/BetterDiscordApp
 * branch            injector   -> FETCH_HEAD
HEAD is now at 1c2e6f6 update for linux
``

**Comment by Meizwe** [comment]
`miw@q8D-AX370-K7:~$ snap info discord
name:      discord
summary:   All-in-one voice and text chat for gamers
publisher: Snapcrafters
contact:   https://github.com/snapcrafters/discord/issues
license:   unset
description: |
  All-in-one voice and text chat for gamers that's free, secure, and
  works on both your desktop and phone.
  
  This snap is maintained by the Snapcrafters community, and is not necessarily endorsed or
  officially maintained by the upstream developers.
commands:
  - discord
snap-id:      qHVefGEBezeuCeSfTND40uoUD6GRw8BO
tracking:     stable
refresh-date: 2019-03-12
channels:
  stable:    0.0.9 2019-03-12 (93) 69MB -
  candidate: ↑                          
  beta:      ↑                          
  edge:      0.0.9 2019-05-31 (94) 69MB -
installed:   0.0.9            (93) 69MB -
`

**Comment by S-B99** [comment]
After update and reinstall this issue doesn't seem to persist, I can reliably close and reopen and BBD loads each time.
```
Discord: /usr/share/discord
Modules: /home/usr/.config/discord/0.0.9/modules
Index modified: yes
Linked injector directory: /home/usr/.local/share/betterdiscordctl/bd/0
Linked injector repository: ssh://git@github.com/rauenzi/BetterDiscordApp
```
