### ISSUE TITLE
[Bug] BandagedBD is loading indefinitely

### ISSUE THREAD

**Issue by Obbama** [rauenzi/BetterDiscordApp#203]
When I start discord the bottom right icon starts flashing and says that bandagedbd is loading. Sometimes it takes 30 minutes, sometimes 3 hours, sometimes never loads. Was fine until a couple weeks ago.

Happens everytime I open discord. The update before it was fine as I said (2 weeks ago)

[Screenshot](https://imgur.com/a/5BVKQNj)

Discord Stable version, Already tried fresh installs of both BD and discord, with folder removal and such.

**Comment by rauenzi** [comment]
What operating system are you on?

**Comment by Obbama** [comment]
Windows 10, latest update as well.

**Comment by rauenzi** [comment]
Can you try reinstalling (using the latest installer) and share a screenshot of the installer logs at the end?

**Comment by rauenzi** [comment]
Stale.
