### ISSUE TITLE
[Bug] [Linux] Discord crashes on startup

### ISSUE THREAD

**Issue by loper12** [rauenzi/BetterDiscordApp#205]
**Describe the Bug**
There is an JS error in the startup.
**To Reproduce**
install via betterdiscordctl

**Expected Behavior**
I expected it to launch

**Screenshots**
![image](https://user-images.githubusercontent.com/20266744/59138643-d17c1c80-897d-11e9-818c-276fa97b8307.png)

**Discord Version**
Stable

**Additional Context**
Running linux mint x86-64

**Comment by rauenzi** [comment]
Reinstall/update discord

**Comment by loper12** [comment]
fixed thx
