### ISSUE TITLE
[Bug] electron.deprecate.promisify fails on newer electron builds

### ISSUE THREAD

**Issue by ComfyKernel** [rauenzi/BetterDiscordApp#206]
When starting discord, a javascript error occurs claiming that promisify is null preventing discord from starting. The error points to index.js at line 19

**To Reproduce**
Update to the latest discord and start it with betterdiscord installed

**Expected Behavior**
Discord starts

**Discord Version**
Stable

**Additional Context**
Platform is Linux, using betterdiscordctl to help with installation

**Comment by rauenzi** [comment]
I've actually had the opposite reported in #205 -- that updating/reinstalling discord fixes the issue.

**Comment by ComfyKernel** [comment]
Strange, I was able to fix it by commenting out lines 19 and 20 in index.js and it worked just fine

**Comment by rauenzi** [comment]
That would be a tempfix, yes.

**Comment by ComfyKernel** [comment]
`if(electron.deprecate) {    const originalDeprecate = electron.deprecate.promisify; // Grab original deprecate promisify
    electron.deprecate.promisify = (originalFunction) => originalFunction ? originalDeprecate(originalFunction) : () => void 0; // Override with falsey check}`

Here's a less sketch fix that worked, it seems that on some electron versions 'electron.deprecate' doesn't exist, I think it might be a flag set when building electron to enable deprecated features or not

**Comment by rauenzi** [comment]
Added a check just in case.
