### ISSUE TITLE
"Database not found"

### ISSUE THREAD

**Issue by ProwlingPython** [rauenzi/BetterDiscordApp#208]
I can't use BetterDiscord, it's telling me "Database Not Found: Enter a Password [Create Database]"
![image](https://user-images.githubusercontent.com/48689535/59456513-51b1e000-8dcb-11e9-8734-7a3292e08bb4.png)

**Comment by intrnl** [comment]
That's not from BetterDiscord, that's from your plugins.

**Comment by rauenzi** [comment]
This is from the discord crypt plugin
