### ISSUE TITLE
Can't use slash commands

### ISSUE THREAD

**Issue by SonOfDiablo** [rauenzi/BetterDiscordApp#21]
So I'm not 100% sure if this is a BBD or BD issue to be honest, but seen as BBD is trying to fix/improve on BD I will start here and move to BD if this is not your issue.

Okay now to the actual issue:
When trying to use slash commands that does some kind of emote text (like /shrug, /tableflip, /unflip) I'm not able to send the message if I don't add any other text. 
However without BBD, just plain vanilla Discord I'm able to do this.

Is this an issue that actually exist or am I just messing it up somehow?

**Comment by rauenzi** [comment]
BBD & BD don't do anything to the textarea of Discord, it could be caused by a plugin, but would not be caused by BBD/BD. I recommend disabling all plugins and reloading and retrying.

**Comment by SonOfDiablo** [comment]
Yup seems like it's one of my plugins.. Welp time to enable them one at a time!

Thanks!
