### ISSUE TITLE
BetterDiscord's gone again.

### ISSUE THREAD

**Issue by fhuewhd** [rauenzi/BetterDiscordApp#211]
After a Discord update (though that's not saying much, there seems to be a Discord update of some sort almost every day as far as I can tell), BetterDiscord has disappeared - all my customisations are gone and BetterDiscord doesn't appear on the settings page.

Tried uninstalling and reinstalling using BetterDiscordCTL. It said BetterDiscord had installed successfully, but when I restarted Discord there was still no sign of BetterDiscord.

Any idea how to fix this, please? Is anyone else having a problem?

**Comment by ObserverOfTime** [comment]
See https://github.com/bb010g/betterdiscordctl/issues/38#issuecomment-497049666
