### ISSUE TITLE
[Bug] Can't have a custom font.

### ISSUE THREAD

**Issue by LaraFenrir** [rauenzi/BetterDiscordApp#213]
When i put a theme and activate it, nothing happening. 

![image](https://user-images.githubusercontent.com/39006711/59797575-49343a80-92e0-11e9-85df-3dd5702d3a28.png)

Any idea ? I tried uninstall, reinstall, but still nothing..

**Comment by rauenzi** [comment]
Does this happen with all themes?

**Comment by celina** [comment]
I am also experiencing this issue with all themes, even ones that I made myself that do very little like changing emoji size.

**Comment by rauenzi** [comment]
I think I know what is happening

**Comment by LaraFenrir** [comment]
Yep, with every themes

**Comment by Articclaw** [comment]
Yep, themes aren't working can confirm it's happening with everyone, at one point I had to reinstall discord itself cause it crashed and was in an infinite update loop then it had javascript failures.

**Comment by LaraFenrir** [comment]
I wan't my themeesss ;-;

**Comment by rauenzi** [comment]
Reload, this was closed as it was fixed.
