### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Cleiti** [rauenzi/BetterDiscordApp#218]
The installer text looks weird, see screenshot. 
Downloaded the windows installer .exe, launched, that's all.
![Screenshot_34](https://user-images.githubusercontent.com/52427029/60462730-635c0a00-9c4a-11e9-8659-ae70f9a87af4.png)

**Comment by rauenzi** [comment]
This is a duplicate of rauenzi/BBDInstaller#3
