### ISSUE TITLE
Discord crashes and won't start after deletion of all BetterDiscord files and re-install of Discord

### ISSUE THREAD

**Issue by whitemonkeyyy** [rauenzi/BetterDiscordApp#22]
I've deleted everything to do with BetterDiscord including installation files, executables, all the /AppData in both /Local and /Roaming and cleaned the registry after all this. I've reinstalled Discord several times and restarted my computer but for some reason Discord is still looking for BetterDiscord.

Any ideas?
![screenshot_4](https://user-images.githubusercontent.com/41385332/42899650-af26bf3e-8a94-11e8-9a8b-03eab70bfe44.png)

Error: Cannot find module 'BetterDiscord'
	at Module._resolveFilename (module.js:470:15)
	at Function.Module._resolveFilename
(C:\Users\%%%\AppData\Local\Discord\app-0.0.301\resources\electron.asar\common\...:12)
	at Function.Module._load (module.js:418:25)
	at Module.require (module.js:498:17)
	at require (internal/moduler:20:19)
	at Object.<anonymous>
(C:\Users\%%%\AppData\Roaming\discord\0.0.301\modules\discord_desktop_core\cor...:22)
	at Object.<anonymous>
(C:\Users\%%%\AppData\Roaming\discord\0.0.301\modules\discord_desktop_core\core...:3)
	at Module._compile (module.js:571:32)
	at Object.Module._extensions.js (module.js:580:10)
at Module.load (module.js:488:32)

**Comment by Inve1951** [comment]
reinstall BBD and confirm that the installation finishes successfully

**Comment by whitemonkeyyy** [comment]
OK, did that. Now, it loads but crashes soon after. I didn't reinstall without moving the .exe outside of the downloads folder the first time, so I reinstalled it again after doing so. Same issue.

> Searching for Discord core in: C:\Users\philw\AppData\Roaming\Discord\0.0.301\modules\discord_desktop_core
Located core.asar in: C:\Users\philw\AppData\Roaming\Discord\0.0.301\modules\discord_desktop_core
Killing Discord Processes
Deleting old core
Extracting core.asar
Finished extracting core.asar
Injecting BandagedBD to C:\Users\philw\AppData\Roaming\Discord\0.0.301\modules\discord_desktop_core\core
Rewriting index.js
Finished injecting BandagedBD
Downloading BandagedBD package
Finished downloading BandagedBD package
Deleting old BetterDiscord
Extracting BandagedBD package
Deleting temp file C:\Users\philw\AppData\Roaming\Discord\0.0.301\modules\discord_desktop_core\BetterDiscord.zip
Verifying installation
Verifying: Discord files
Verifying BandagedBD package
Verification successful
Finished installing BandagedBD!

![screenshot_1](https://user-images.githubusercontent.com/41385332/42941349-79c73c10-8b2a-11e8-9ba1-5772854dc465.png)

**Comment by whitemonkeyyy** [comment]
OK, did that. Now, it loads but crashes soon after. I didn't reinstall without moving the .exe outside of the downloads folder the first time, so I reinstalled it again after doing so. Same issue.

> Searching for Discord core in: C:\Users\%%%\AppData\Roaming\Discord\0.0.301\modules\discord_desktop_core
Located core.asar in: C:\Users\%%%\AppData\Roaming\Discord\0.0.301\modules\discord_desktop_core
Killing Discord Processes
Killing Discord process 7732
Killing Discord process 13736
Killing Discord process 1496
Deleting old core
Extracting core.asar
Finished extracting core.asar
Injecting BandagedBD to C:\Users\%%%\AppData\Roaming\Discord\0.0.301\modules\discord_desktop_core\core
Rewriting index.js
Finished injecting BandagedBD
Downloading BandagedBD package
Using channel: https://github.com/rauenzi/BetterDiscordApp/archive/stable16.zip
Downloading to: C:\Users\%%%\AppData\Roaming\Discord\0.0.301\modules\discord_desktop_core\BetterDiscord.zip
Finished downloading BandagedBD package
Deleting old BetterDiscord
Extracting BandagedBD package
Renaming package dir
Deleting temp file C:\Users\%%%\AppData\Roaming\Discord\0.0.301\modules\discord_desktop_core\BetterDiscord.zip
Verifying installation
Verifying: Discord files
Verifying BandagedBD package
Verification successful
Restarting Discord
Finished installing BandagedBD!

![screenshot_1](https://user-images.githubusercontent.com/41385332/42941501-f5e9ef40-8b2a-11e8-846b-39ee16d963d2.png)

**Comment by whitemonkeyyy** [comment]
haha soon ok

thank you

**Comment by rauenzi** [comment]
Most recent update should fix your issue, go ahead and restart discord and give it a go

**Comment by whitemonkeyyy** [comment]
no bueno, sorry. still crashing.

**Comment by rauenzi** [comment]
can you try reinstalling BBD and see if that fixes your issue?

**Comment by whitemonkeyyy** [comment]
The first reinstall and restart directly after the update didn't work, but tried it again now and it seems to be working so far! Thanks!
