### ISSUE TITLE
[Feature] [Normalise Classes] Revert changes to how avatars are displayed.

### ISSUE THREAD

**Issue by TheDarkBomber** [rauenzi/BetterDiscordApp#220]
**Is your feature request related to a problem? Please describe.**
Problem: In the new PTB Discord updated, Discord has unnecessarily changed how avatars are displayed by using foreign objects, which makes it a lot harder for theme developers to change the avatar in any way, usually by changing the circular avatar into a square or rounded square avatar. This will be a problem for existing themes when this update is pushed to stable.

**Describe the feature you'd like**
Feature: The ability for Normalise Classes to normalise how avatars are displayed, by reverting the changes Discord has made, which will not only not disrupt existing themes, but also make editing how avatars are displayed via CSS much easier.

**Additional context**
Before: Avatars normal, can be simply edited with CSS.
After: Avatars are foreign objects, hard to edit, and I think one may actually have to utilise a plugin to edit how they are displayed by replacing the HTML, not sure if editing them with CSS alone is even possible.

**Comment by TheDarkBomber** [comment]
@rauenzi ?

**Comment by MasicoreLord** [comment]
Zerebos isn't going to go maintain something like that LMAO
That's a bit much 😂

**Comment by TheDarkBomber** [comment]
@MasicoreLord it is important

**Comment by KyzaGitHub** [comment]
Could be done with a plugin. You wouldn't need it integrated into BD.

**Comment by TheDarkBomber** [comment]
@KyzaGitHub Anybody you know planning on making this plugin?

**Comment by rauenzi** [comment]
No need to add an additional comment to an issue you opened just to add a mention. Especially not a couple hours later--I don't just sit here waiting to respond to new issues.

That said, reverting the new Discord avatars is out of the scope of the class normalizer. It's also outside the scope of BD. Additional helper classes may come, but that would be about it.
