### ISSUE TITLE
[Bug] No text in user ban options

### ISSUE THREAD

**Issue by XIshArkIX** [rauenzi/BetterDiscordApp#221]
**Describe the Bug**
No text in user ban options

**To Reproduce**
1. Select Russian language in settings (Русский)
2. Open ban menu

**Expected Behavior**
Expected - Emptiness

**Screenshots**
https://imgur.com/a/Yts1vHY

**Discord Version**
Stable

**Additional Context**
No Additional Context

**Comment by rauenzi** [comment]
How is this a BD bug?

**Comment by XIshArkIX** [comment]
Really. Just before that, all the names were there and everything was, and after that I didn’t particularly ban anyone, but I noticed such a thing recently. Sorry.
