### ISSUE TITLE
Emote database outdated? (Twitch subscriber)

### ISSUE THREAD

**Issue by Lombra** [rauenzi/BetterDiscordApp#225]
As far as I can tell (from checking the emote data files in this repository), Twitch subscriber emotes have not been updated in several months. Just wanted to check whether this is a known issue or what's going on.

**Comment by rauenzi** [comment]
The version on the repo only serves as a backup when it can't get an up to date copy directly from the API. As such the backup doesn't need to be that up to date.

**Comment by Lombra** [comment]
Confirm that this is the case for *subscriber* emotes? In that case, it hasn't been able to get an up to date copy directly from the API in months. I have tried clearing the emote cache.

I can see that the global Twitch emotes has a ´backup´, but not the others.
https://github.com/rauenzi/BetterDiscordApp/blob/master/js/main.js#L669

**Comment by intrnl** [comment]
I really doubt that you would want to let BD load the current subscriber emotes, mostly because Discord gets unbearable for few seconds and even so on lower-end machines.

**Comment by Lombra** [comment]
I don't know how this worked on the back end, but up until a few months ago sub emotes seemed to get updated pretty much instantly. Just had to reload Discord. Now it's as though the code that fetches new emotes hasn't worked for some time.
