### ISSUE TITLE
Allow time delay before attempting to re-downlaod (after creating firewall rule)

### ISSUE THREAD

**Issue by diVineProportion** [rauenzi/BetterDiscordApp#226]
Title says it all. Can be bypassed by hitting the back button, but user has to cycle checkbox (as install / proceed is greyed out) for install button will be enabled.

**Comment by rauenzi** [comment]
I'm not sure that's a common enough use-case

**Comment by diVineProportion** [comment]
Understandable, Just wanted to make it known
