### ISSUE TITLE
Canary: Colored text

### ISSUE THREAD

**Issue by TheStrato** [rauenzi/BetterDiscordApp#23]
The colored text option in Core Settings doesn't function properly after the recent Canary updates. I have cycled the option, reinstalled BBD, and there have been a few updates since the problem first showed up. I waited a while to report as some issues resolve themselves in future updates but this time it seems to be persistent.

**Comment by TheStrato** [comment]
Oh, and emote conversion isn't happening either.

**Comment by rauenzi** [comment]
fixed as of a1b44b49b2b6b0ecade39f5e7b885624f22358ee

**Comment by TheStrato** [comment]
Problem with colored text returned.
