### ISSUE TITLE
[Bug..?] [Linux] Discord crashes on startup

### ISSUE THREAD

**Issue by Kazanami** [rauenzi/BetterDiscordApp#230]
**Describe the Bug**

Discord does not start

**To Reproduce**

**Expected Behavior**

**Screenshots**

![Screenshot from 2019-08-08 14-28-56](https://user-images.githubusercontent.com/6745680/62677380-1574b780-b9e9-11e9-8b51-003f7b4940a1.png)

**Discord Version**

**Additional Context**

Hello, to send for the first time Issues.
I am using BetterDiscord.
When I visited github today, I confirmed that the update was updated in the [injector] branch, and updated with betterdiscordctl.
Then, an error similar to the image below was displayed, and I was unable to start up.
I'm using Ubuntu, but I was wondering if it was causing errors on other platforms.
Thank you.

**Comment by intrnl** [comment]
Must have forgotten that on Linux we're injecting on roaming and not local like on Windows and Mac.

**Comment by Kazanami** [comment]
I see…
Thank you for your reply.
Is it okay to wait for rauenzi to correct this?

**Comment by Kazanami** [comment]
I confirmed that the update was in the [injector] branch and reinstalled it.
Thank you, rauenzi, for the correction!
Thank you for supporting intrnl!
Now that we ’ve solved it, we ’ll close this issue.
