### ISSUE TITLE
Enable Transparency Not Working [Bug]

### ISSUE THREAD

**Issue by ZuranaSuki** [rauenzi/BetterDiscordApp#231]
**Describe the Bug**
The Enable Transparency switch does not work even after restart it does not even turn on I manually turned it on through the config restarted a few times but it doesn't work there is no transparency

**Expected Behavior**
The Enable transparency should work but it doesn't

**Discord Version**
Stable

**Comment by rauenzi** [comment]
Are you using a theme or some custom css in combination with it?

**Comment by ZuranaSuki** [comment]
ive used a few themes to try and get it to work but it just turns into a solid color

**Comment by rauenzi** [comment]
Try adding ```
:root { opacity: 0.7!important; }
```
to your custom css

**Comment by ZuranaSuki** [comment]
dosent seem to work just creates this grey overlay on everything

**Comment by rauenzi** [comment]
Can you share a screenshot? Or join my support server?

**Comment by ZuranaSuki** [comment]
this is what happens
![image](https://user-images.githubusercontent.com/16857139/62753233-b2ab0c80-ba38-11e9-8d30-6e934e35619d.png)

**Comment by rauenzi** [comment]
Sounds like the transparency setting didn't truly take effect. Go into settings then disable and reenable it. Then open task manager and kill all instances of Discord (make sure there are no solo ones left over). Then reopen discord and try that snippet from above.

**Comment by ZuranaSuki** [comment]
im unable to make the switch work im only able to toggle it by changing it from the config file

**Comment by rauenzi** [comment]
Which config? What operating system are you using?

**Comment by ZuranaSuki** [comment]
im using windows 10 and the bdstorage.json file

**Comment by ZuranaSuki** [comment]
its not just that one switch im unable to toggle any of bds switches

**Comment by rauenzi** [comment]
That config actually has no affect on whether it attempts to make the window transparent, that's just an indicator of what BD thinks is trying to happen.

If your switches aren't working that's a whole other issue. I would recommend deleting your bdstorage.json file and fully restarting (not reloading) Discord and see if the toggles are fixed.

**Comment by ZuranaSuki** [comment]
that worked switches are all working again and the transparency is working now thanks!

**Comment by rauenzi** [comment]
No problem glad that solved it
