### ISSUE TITLE
[Bug] no theme listed with ubuntu

### ISSUE THREAD

**Issue by x0rld** [rauenzi/BetterDiscordApp#236]
**Describe the Bug**
i'm on ubuntu bionic i have install betterdiscord i create my theme in the right folder but i don't see any theme list in discord
**Screenshots**

![image](https://user-images.githubusercontent.com/45242856/63654178-1cd0ea80-c777-11e9-8f7b-e974cb91b0b6.png)

![image](https://user-images.githubusercontent.com/45242856/63654174-0f1b6500-c777-11e9-9506-31c88b65372c.png)

**Discord Version**
Stable

**Comment by rauenzi** [comment]
The filename needs to be `name.theme.css`
