### ISSUE TITLE
[Bug] Misaligned menus

### ISSUE THREAD

**Issue by bob-carter** [rauenzi/BetterDiscordApp#239]
**Describe the Bug**

All plugins that add in expanded menus are broken, it generates them on hover over like an inch from the menu, so that when you move the mouse over to them it closes

**To Reproduce**

Step 1: Install discord, install Bandage BD, add a plugin like EditUsers, or SpellCheck, and try and right click on something (With EditUsers a user, with SpellCheck something in red) and then hover on that menu. [I can reproduce this on fresh installs] This is a 64 bit Windows 7 PC. 

**Expected Behavior**

I expect it to work like all other right click hover over menus that show up on discord.

**Screenshots**

Will do so later if needed

**Discord Version**

Stable

**Additional Context**

This just started happening today.

**Comment by rauenzi** [comment]
What you're describing is an issue with the plugins themselves, not BandagedBD.

**Comment by bob-carter** [comment]
But this is an issue that only pop'ed up with the latest version of BandagedBD, nothing about Spell checker has been changed in the like 5 mouths, and it's menu is broke, and nothing else.

**Comment by qwerasd205** [comment]
The bug was likely introduced by an update to Discord, not BandagedBD. There is absolutely nothing in BandagedBD that would cause this.
