### ISSUE TITLE
Nox emulator shows up above name constantly

### ISSUE THREAD

**Issue by Norsixa** [rauenzi/BetterDiscordApp#241]
Since I always have the nox emulator open to play a mobile game, after installing bandagedbd, noxplayer constantly shows over my username. There doesnt seem to be a setting to remove this?
I dont stream so this is pretty useless to me and is in the way for me at all times.

**Comment by rauenzi** [comment]
I don't know what you mean, can you show a screenshot?

Next time please use the provided issue template -- it allows us to get the info we need like screenshots right from the start.

**Comment by Norsixa** [comment]
![bandagebd](https://user-images.githubusercontent.com/44646256/64495479-c85b5e00-d292-11e9-89fa-d8e8bf1963ac.png)

Noxplayer above my name, didnt find any setting to remove this.

**Comment by rauenzi** [comment]
That's not a BandagedBD feature. That's one of Discord's new features of autodetecting what you're doing/using and prompting you to either stream or use rich presence.

**Comment by Norsixa** [comment]
Well it only popped up the moment I installed bandage though, I've never had that before.

**Comment by rauenzi** [comment]
BandagedBD does not do that. Feel free to uninstall BBD and double check. Be sure this isn't something you as the user added via a plugin or as an experiment (through discord experiments plugin).

**Comment by Norsixa** [comment]
guess discord must have went into a newer version or beta when I installed bandaged, thanks for the help.
