### ISSUE TITLE
Not sure if a bug or just something i've done wrong.

### ISSUE THREAD

**Issue by ghost** [rauenzi/BetterDiscordApp#242]
**Describe the Bug**
I've installed the rauenzi-betterdiscord fork using betterdiscordctl on discord-canary, IT says that it's installed but I can't seem to see the plugins or themes menu in the settings. 
I've uploaded some logs here; https://0x0.st/zJJi.txt.

**Comment by Milksters** [comment]
This actually is happening to me too. I can't see any themes or plugins that are offered.

**Comment by Jearl51** [comment]
This is happening to me as well I saw it at 1st then it just went away
