### ISSUE TITLE
New Update broke BBD?[help wanted]

### ISSUE THREAD

**Issue by ShadowOnTheMoon** [rauenzi/BetterDiscordApp#246]
**Describe the Bug**
I'm not sure if it _is_ a bug or just the update breaking discord. The themes are not working properly, neither are the plug ins, but the plug-ins aren't my main concern at the moment as they'll be updated by the people they're made by. I'm just trying to get some info seeing as i can't get into either BD servers to get help.

**To Reproduce**
Just started up discord. Having a transparent theme, only the top bar has the them and the rest s just the dark theme/black bg.

**Expected Behavior**
I expected that there would be some issues, as there are with any update to discord, but usually their fixed some what fast. 

**Screenshots**
![Screenshot (762)_LI](https://user-images.githubusercontent.com/55153156/64633808-eaa3c780-d3c9-11e9-86ea-2ead801be024.jpg)

**Discord Version**
Stable.

**Additional Context**
Like i said, I'm not sure what happened, I just want some answers. Any help would be much appreciated.

**Comment by rauenzi** [comment]
It is caused by the discord update yes. It is not an issue with BBD, the themes need to be updated.
