### ISSUE TITLE
[Bug] Crashing on launch

### ISSUE THREAD

**Issue by UnknownCoding** [rauenzi/BetterDiscordApp#247]
**Describe the Bug**
The bug is every time i load up the newest version of discord and go to click on anything it crashes

**To Reproduce**
i dont know if its just me, but i had reinstalled betterdiscord and removed all plugins and it still crashed when i tried to do anything

**Expected Behavior**
Discord wouldn't crash

**Screenshots**
Cant screenshot an app that isn't open

**Discord Version**
Stable

**Additional Context**
None

**Comment by kuplion** [comment]
Can confirm, is also happening to me too since the Discord update.
