### ISSUE TITLE
Stable not found

### ISSUE THREAD

**Issue by TakaraFED** [rauenzi/BetterDiscordApp#25]
![image](https://user-images.githubusercontent.com/41545934/43046882-0c313414-8e02-11e8-9f42-a9399dbdd91f.png)
Normally the file destination is already placed, but in my case it cant't be found
Pls Help.

**Comment by Inve1951** [comment]
install discord and run it at least once (Update.exe) before installing BBD

**Comment by Ashleyz4** [comment]
why did you make two of the same issue o.o

**Comment by TakaraFED** [comment]
I tried to use the No admin one
and it worked
