### ISSUE TITLE
Install button dark blue will not install[Bug]

### ISSUE THREAD

**Issue by Mom-Kat** [rauenzi/BetterDiscordApp#250]
**Describe the Bug**

It simply doesn't work. The Install button is darker blue than the others and does nothing.
**To Reproduce**

Downloaded installer.
Moved file to C:
Ran as Admin
Accepted agreement
Choose install
All installs show but the Install button is darker blue than the others and does nothing.
**Expected Behavior**

**Screenshots**

**Discord Version**

All, newly upddated

**Additional Context**

Win7 pro 64bit
![BBD](https://user-images.githubusercontent.com/32440184/65059903-d66d4680-d944-11e9-92ad-40acb032f87a.png)

**Comment by NFLD99** [comment]
youll need to fix your dpi in windows settings
im not sure if its the same on win7 however the setting is this: 
![ApplicationFrameHost_2019-09-27_10-00-42](https://user-images.githubusercontent.com/24623601/65769267-c5bf8c00-e10d-11e9-97a9-b54f3bdb529a.png)

**Comment by neoarc** [comment]
It's not dpi issue, "Install" button is disabled, so he can't click it.
same thing happened to me. :(

**Comment by rauenzi** [comment]
No it's a dpi issue. The button becomes enabled when you click one of the checkboxes that are pushed off-screen in the first screenshot due to scaling.

**Comment by rauenzi** [comment]
Duplicate of rauenzi/BBDInstaller#5
