### ISSUE TITLE
Themes have been destroyed by the new discord update.

### ISSUE THREAD

**Issue by EthanYatsumaru** [rauenzi/BetterDiscordApp#251]
Discord recently updated the light theme, at first that just broke my transparent theme, so I just put a background on it. For some reason, now every theme that I own has been destroyed, nothing works. Little bits of the background are there with gray everywhere else. Please see if you can update this to fix these issues.

**Comment by D-Vin** [comment]
I noticed the same issue earlier today. This is quite frustrating considering I only have Better Discord for the purpose of custom themes, and now they're broken!

**Comment by PaulZappia** [comment]
I'm having the same kinda issue. The background my theme was using would only show up in certain spots in discord. Hopefully, this gets fixed soon

**Comment by EthanYatsumaru** [comment]
Im pretty sure this is happening to everyone, my guess is the new light theme and updates to the dark theme broke themes.

**Comment by PaulZappia** [comment]
> Im pretty sure this is happening to everyone, my guess is the new light theme and updates to the dark theme broke themes.

Could it mainly be due to changes in the Discord layout css? Maybe stuff isn't working properly due to Discord changing class names or something.

**Comment by EthanYatsumaru** [comment]
> > Im pretty sure this is happening to everyone, my guess is the new light theme and updates to the dark theme broke themes.
> 
> Could it mainly be due to changes in the Discord layout css? Maybe stuff isn't working properly due to Discord changing class names or something.

Possibly, im not great at CSS or coding in general so I doubt I could fix it on my own though.

**Comment by rauenzi** [comment]
This is an issue with the themes themselves. You can ask the author to update the theme, but this is not an issue with BBD itself.
