### ISSUE TITLE
I don't know what happened. 

### ISSUE THREAD

**Issue by NotActuallyT** [rauenzi/BetterDiscordApp#252]
**Describe the Bug**

It might be my fault. But when I try to join the servers on the public servers thing it doesn't work. Also, I can't change the background of my Discord. I put my pictures in the folder but it wasn't shown in the settings thing.  
**To Reproduce**

All I did was install the add-on.
**Expected Behavior**

I have no idea.

**Comment by NotActuallyT** [comment]
I actually ended up joining a server but I can't join the Betterdiscord server...

**Comment by EthanYatsumaru** [comment]
The background issue is happening with me too. Discord updates broke it.

**Comment by NotActuallyT** [comment]
I got it to work. These links help a lot. 
https://youtu.be/VPoSl_ua5W8
https://github.com/puckzxz/NotAnotherAnimeTheme

**Comment by rauenzi** [comment]
It's likely you did join the BD server but due to outage it doesn't show it. The issue with themes is just that--an issue with the themes and not BD.
