### ISSUE TITLE
Discord update broke my background 

### ISSUE THREAD

**Issue by MoonCakeGod** [rauenzi/BetterDiscordApp#253]
Ummmm the discord and the background is overlaying each other.
So what i mean is that there is some parts that is the custom background and there is some parts which are the normal discord please help

**Comment by EthanYatsumaru** [comment]
Me too, I also posted here on Issues. Its really annoying, and even before that transparent themes broke D:

**Comment by rauenzi** [comment]
This is an issue with the themes themselves. You can ask the author to update the theme, but this is not an issue with BBD itself.
