### ISSUE TITLE
Version Numbers dont seem to be correct across repository. [Bug]

### ISSUE THREAD

**Issue by coreyzev** [rauenzi/BetterDiscordApp#254]
**Describe the Bug**
You've released as version 1.0, but the package.json still says 0.2.3, the Menus in Discord still say 0.2.17, etc. 

**To Reproduce**
Look at the areas stated above, or any place the version number should be represented. 

**Expected Behavior**
All version numbers should match the version I installed. 

**Discord Version**
latest stable

**Additional Context**
This bug makes confirming issues very difficult.

**Comment by rauenzi** [comment]
Version in package.json is not for users. Release version refers to the installer since that is what is actually there (as can be seen in the installer UI). Versions in the menu are what is relevant for users.

**Comment by coreyzev** [comment]
Really? It's not for users, but it's still important to keep everything organized. And that's so confusing. If the installer needs its own version number, it needs its own repository. Use the version tags to label your code responsibly. 

![image](https://user-images.githubusercontent.com/2052536/65395598-3f045b00-dd6b-11e9-8c87-c7bac144f7e9.png)

You can see how this is confusing right? I'm in "releases" for your codebase. They are all in line on the left. There are several differnt references you're making, they should ONLY refer to the listed repository we're looking at and working with. 

And then why if it says 0.2.83 here, does my discord say 0.2.17

This should not be closed.

**Comment by rauenzi** [comment]
The installer does have its own repository but users are unaware of it. I would also prefer not to use releases of this repository for the installer but that workflow/architecture predates me. As you can see this is a fork and the weirdness was set in place before I forked. Normalizing all the version numbers and reworking how releases is used would require a massive rework of how BD itself works (everything currently points to the releases page for installing, and uses GitHub pages to load remotely as opposed to actually packaging and releasing the code). It would also cause a disruption to the users themselves and given the userbase's tendency to freak out over any little change, I don't really like that option.

If this project were wholly my own from the start I would definitely have no issue with keeping things consistent.

I am currently working on a rewrite where I _should_ be able to do what you would like so I will reopen this. But unfortunately I wouldn't expect too much on this front other than a version change in package.json for now.

**Comment by coreyzev** [comment]
The whole point of forking is to make it better, and to fix those parts that are broken. create a new branch, recruit people to work on the issues with you. Offer contributors credit. Not just donors. And actually solve this issues, dont just bandage them. If i was still an engineer I'd help, but I've put that behind me, but I still know how the process works. 

That all seems very roundabout, and users dont care about the "installer version number" one slight bit. We do need to make sure that our software matches documentation so that we can bugfix correctly. 

Glad to hear you're working on it, dont do it all on your own if you dont have to, that's what pull requests are for, you still have control but people can contribute. And if you make a Trello roadmap, or even just do it here in Github it'll get done faster. 

Thanks for reopening.

**Comment by rauenzi** [comment]
I agree with your sentiment about forking, but this project was made the "main version" of product as opposed to just a fork so breaking changes really need to be kept to a minimum. Contributors are always welcome but they seem to be few and far between on this project. Unfortunately the main idea was for this to be a "bandaged" hence the name, the rewrite is a real solution.

Normally I'd agree with you but people do seem to care in the Discord server oddly enough. The process for everything is definitely roundabout but again I didn't just want to break it for the thousands of people to get angry about. The minimal documentation does still match the codebase currently.

The rewrite has made good progress and is nearly done which is why I haven't made a roadmap as such but people are still welcome to contribute there as well. They've been more apt to contribute there since the codebase is readable and organized as opposed to this nasty spaghetti code.

**Comment by coreyzev** [comment]
Looking forward to it. Where is it?

**Comment by rauenzi** [comment]
`development` branch

**Comment by coreyzev** [comment]
It might be worth adding to the ReadMe so people know where to find it, to contribute. As well as maybe some contribution guidelines?

**Comment by rauenzi** [comment]
I honestly don't believe that would have any affect. Maybe if I have some free time, but I haven't had much time to work on it let alone do organizational things.

**Comment by rauenzi** [comment]
At long last, the version numbers are finally consistent between the repo and the releases
