### ISSUE TITLE
[Bug] [Development] Custom CSS editor can be dragged outside of the window.

### ISSUE THREAD

**Issue by KyzaGitHub** [rauenzi/BetterDiscordApp#255]
**Describe the Bug**
You can drag the custom CSS editor above the top of the window, essentially making you lose the ability to move it anymore.

**To Reproduce**
Detach the editor and drag it above the top of the titlebar.

**Expected Behavior**
The editor should snap back below the titlebar.
_This is 22px from the top on Windows machines._

**Screenshots**
![wbHcqhvRqF](https://user-images.githubusercontent.com/40003440/65803521-c7f50b00-e14c-11e9-9ff2-dd3e9f954a6f.gif)
![image](https://user-images.githubusercontent.com/40003440/65801235-a4c75d00-e146-11e9-8302-fc12178f4b90.png)

**Discord Version**
Stable.

**Additional Context**
Development branch.

**Comment by rauenzi** [comment]
@CHEF-KOCH why down you thumbs down this?

**Comment by rauenzi** [comment]
This has been fixed in the development branch.
