### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by sarayuuki** [rauenzi/BetterDiscordApp#256]
Latest Update of PluginRepo makes pluginrepo button in plugins section disappear, to combat this need to turn off and turn on plugin repo. even after plugins are fetched. Closing out settings causes pluginrepo button to disappear. needs to be fixed. discord update probably broke it.

**Comment by sarayuuki** [comment]
affected on discord canary update channel.

**Comment by rauenzi** [comment]
This is an issue with that plugin specifically, not with BD.
