### ISSUE TITLE
[Bug] BBD long load times, despite use of additional options to attempt to fix on user end.

### ISSUE THREAD

**Issue by FennisOT** [rauenzi/BetterDiscordApp#257]
**Describe the Bug**
BBD being held up very long load times.

**To Reproduce**
Following the installation process.

**Expected Behavior**
Should've began running normally after startup within a few seconds.

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/14151917/66358342-9516f800-e940-11e9-8abc-204bdf4eadf8.png)

**Discord Version**
Stable.

**Additional Context**
I tried uninstalling and reinstalling BBD, done the same for Discord, but the hold up still keeps happening. Even with the repair BBD option of infinite loading or any of the other options. Judging from the console, BBD is stuck at Initializing QuickEmoteMenu, as well bringing the Violation 'setTimeout' continuously reproduces itself (over 1000 while I'm looking over the console.). It looks to keep going on forever. The issue first started for me after Discord made the update of improving their UI. I had made a comment in a now closed request and it appeared to that user's solved solution didn't help me.

While I was waiting for BBD to continue loading it also prompt'd a [Violation] 'requestAnimationFrame' handler took 106ms as well, if this means anything.

Update: BBD actually did start up, but it took hours to do so. It never actually took this long before. What's the explanation to this?

**Comment by whynot3k** [comment]
im having same issue initializing quickemotemenu cant seem to get it to load my plugins its really painful as i use BBD to switch accounts from my gaming one to a work one

**Comment by rauenzi** [comment]
> BBD actually did start up, but it took hours to do so. It never actually took this long before. What's the explanation to this?

I don't have a direct explanation of this, it becomes easier with the full logs. Usually issues with infinite loads is related to corrupted `bdstorage.json` or `bdsettings.json` but I've never been able to fully understand the why. Especially not in this case where it seems to eventually load.

> im having same issue initializing quickemotemenu cant seem to get it to load my plugins its really painful as i use BBD to switch accounts from my gaming one to a work one

Please don't use account switching plugins with BBD. They can get you in trouble which gets us in trouble because the blame always ends up back on BBD. There's a reason you won't find such plugins in official sources.

**Comment by FennisOT** [comment]
Full logs coming from the user's end? If it's like that, could you explain how I can make a full log. Corrupted files? Even though I reinstalled, uninstalled both BBD and Discord multiple times, it still can lead to corruptions? I even cleared out the BBD files manually at one point after something finicky happened, which I'm probably positive it wasn't anything serious?

At one point start-up I did get this error as well, but I think it only happened on that one occasion. 
![Untitled](https://user-images.githubusercontent.com/14151917/66588976-8eb09800-eb5b-11e9-9fa3-9287ff7139c9.png)

**Comment by rauenzi** [comment]
Are you still experiencing this?

**Comment by FennisOT** [comment]
Yes. I had also tried the method of changing one of the lines in a specific file to a different number, reading that it worked for others in a closed issue. It didn't work for me. The console says it's still stuck on Initializing QuickEmoteMenu.

**Comment by FennisOT** [comment]
Okay. The issue appears to have been fixed for me now. Restarted a few times just to make sure. Thank you very much.
