### ISSUE TITLE
do you know how to fix this custom css?

### ISSUE THREAD

**Issue by claire-rouge** [rauenzi/BetterDiscordApp#26]
.avatar-large dosnt work, neither does .markup
I tried looking into discord shift+ctrl+i
and saw that they changed the name on them, but when changing it looks like 

![bilde](https://user-images.githubusercontent.com/15875197/43177015-8c8f297a-8fc6-11e8-82fb-c6be735da391.png)

original css without the new name's
```
/* Main Chat Stuff */

.markup {
font-size: 20px !important;
}

.avatar-large { 
    width: 100px; 
    height: 100px; 
    background-size: 100px 100px; 
    border-radius: 50px; 
    
} 

/* Hide Blocked msg */

.message-group-blocked {
    display: none !important;    
}
```

**Comment by rauenzi** [comment]
This is not an issue with BBD.
