### ISSUE TITLE
[Bug] my plugins load but aren't working

### ISSUE THREAD

**Issue by AgentBUB** [rauenzi/BetterDiscordApp#260]
**Describe the Bug**
None of the plugins that I have installed and active are working. The notification sounds, owner tag, badges everywhere, ect. All of them are not working. The themes still work though.

**To Reproduce**
I do not know how it is happening, but I've reinstalled the plugins, Better Discord its self, and reload Discord more times then I can count.

**Expected Behavior**
I expect the plugins to work and do what they are meant to; it is annoying and kinda weird without them.

**Screenshots**
A few of my plugins:
https://gyazo.com/f4e73de8e88b11c0aa470adb567fc3b5
https://gyazo.com/7e069bd1d617a03237c833d0aa654013

Proof that the are not work:
https://gyazo.com/f365ddfac520d9a46c686aef16c8499b
https://gyazo.com/77d42fc6528a08161762fa9f3ec620c8

**Discord Version**
PTB

**Additional Context**
None of my plugins work at all, and as I said, my themes still do work.

**Comment by AgentBUB** [comment]
It started to work again today. I will contact you guys again if I have issues!

**Comment by rauenzi** [comment]
Sounds like this was an issue with the plugins themselves anyways, better off talking to the plugin devs than blaming BBD in those cases
