### ISSUE TITLE
[Bug] it cannot find discord despite it being installed in both appdata and desktop

### ISSUE THREAD

**Issue by EthanMikl101** [rauenzi/BetterDiscordApp#263]
**Describe the Bug**
Hello, I am here to express my problem. It says it cannot find Discord.exe despite the fact I know it can because it's in the right spots.

**To Reproduce**
I have no clue what reproduce means? If I could get some feedback on that...

**Expected Behavior**
I expected it do acknowledge it, but it didn't and I don't know

**Discord Version**
Stable, I do not wish to add it to canary, so don't even go there

**Additional Context**
I have ti installed and it is in appdata, also on desktop. I'm not sure but maybe it is supposed to be somewhere else? There wasn't very clear installation instructions as far as installation goes, so I always am very confused as to what it even wants me to do causing me to get very frustrated with it.
![dis some bullshit](https://user-images.githubusercontent.com/51799218/67153064-d4cad180-f2a8-11e9-8ecc-fa01d12eb958.PNG)

**Comment by rauenzi** [comment]
If you know where your Discord.exe is, you can use the `Browse` button to browse to the correct folder.
