### ISSUE TITLE
[Bug] Transparency is broken

### ISSUE THREAD

**Issue by EthanYatsumaru** [rauenzi/BetterDiscordApp#264]
**Describe the Bug**
I use a theme called clearvision and set the background to a transparent image. It used to work until the recent update and now its just black. Transparency IS on in the settings.

**To Reproduce**
Try and use a transparent theme. I used https://github.com/Zerthox/ClearVision and edited the background to a gray transparent color. It is black instead of transparent.

**Expected Behavior**
The window to be partly clear like I had it before this update.

**Screenshots**
I don't have any screenshots of before the update. Heres what it looks like now.
![image](https://user-images.githubusercontent.com/49452992/67237447-80d6fe80-f408-11e9-9adb-060d5f51d230.png)

**Discord Version**
Stable

**Additional Context**
I don't have any additional context.

**Comment by rauenzi** [comment]
Will double check this later, but it should be functioning fine I don't believe Electron changed this. I would recommend toggling the setting off and on again and ensure your CSS is right for the main window.

**Comment by EthanYatsumaru** [comment]
> Will double check this later, but it should be functioning fine I don't believe Electron changed this. I would recommend toggling the setting off and on again and ensure your CSS is right for the main window.

Alright, thanks.
