### ISSUE TITLE
[Feature] BetterDiscord for Android

### ISSUE THREAD

**Issue by CamperSamu** [rauenzi/BetterDiscordApp#265]
I was thinking random stuff when I realized that with some work BD can be "ported" to Android via Xposed.

Now that edXposed is out might be worth trying this "port"

I am planning to mod discord in the future.

**Comment by rauenzi** [comment]
You are free to mod the Android version as you see fit, however it cannot really be "ported" to Android as the desktop version is based exclusively on Electron and Discord's stack.

You would need a completely separate mod to affect the Android version, written in another language using other methods. Existing plugins and themes would not work either, so it would really be an entirely separate project.

Unfortunately I have neither the time or interest in maintaining another project like that in this space.
