### ISSUE TITLE
[Bug] BetterDiscord installation broken after latest update

### ISSUE THREAD

**Issue by ImperatorRex** [rauenzi/BetterDiscordApp#266]
Installing Better Discord seems to be broken after updating Discord to support Custom Statuses. The BBD installer will say that everything has been installed fine but none of the Better Discord option(CSS, Emotes, etc.) are visible in User Settings. Uninstalling discord has not solved this.

**Comment by MeLver0** [comment]
ye same problem

**Comment by Wohoollomooloo** [comment]
same

**Comment by rauenzi** [comment]
This has been fixed
