### ISSUE TITLE
Emotes menu not saving change

### ISSUE THREAD

**Issue by Mattlau04** [rauenzi/BetterDiscordApp#267]
**Describe the Bug**

Whenever i go to the emotes menu to disable something, then close the settings / change setting tab and come back everything is enabled again

**To Reproduce**

Disable something in the emotes menu, exit setting then come back

**Expected Behavior**

Save the changes made

**Discord Version**

Stable

**Comment by rauenzi** [comment]
I cannot recreate this, are you still experiencing this?
