### ISSUE TITLE
install gives no errors but it doesn't work

### ISSUE THREAD

**Issue by tim5000tim** [rauenzi/BetterDiscordApp#268]
my account was deleted and when i made a new one betterdiscord was uninstalled for unknown reasons since i never deleted i tried to reinstall it and now it just simply wont work the only thing i can think of is maybe its because my new account

**Comment by rauenzi** [comment]
BD has nothing to do with accounts. I would need a lot more info in order to help you such as the installer's log. BD's log or the Discord console.

**Comment by TheAlcanian** [comment]
I have the same issue. I'll provide some console output here, if it helps.

Output from `betterdiscordctl reinstall --verbose`
```
V: Using Discord at /opt/discord
V: Found modules in /home/shardion/.config/discord/0.0.9/modules
Killing Discord processes...
Discord killed (pid 379311)
Discord killed (pid 379313)
Discord killed (pid 379339)
Discord killed (pid 379378)
V: Removing old injector folder.
V: Linking BetterDiscord injector...
Reinstalled.
```


Output from `betterdiscordctl install --verbose`
```
V: Using Discord at /opt/discord
V: Found modules in /home/shardion/.config/discord/0.0.9/modules
V: Injecting into index.js...
V: Linking BetterDiscord injector...
Installed. (Restart Discord if necessary.)
```


Output from `betterdiscordctl uninstall --verbose`
```
V: Using Discord at /opt/discord
V: Found modules in /home/shardion/.config/discord/0.0.9/modules
Killing Discord processes...
No active processes found.
V: Removing BetterDiscord injection...
Uninstalled.
```

Output from `betterdiscordctl status --verbose`
```
V: Using Discord at /opt/discord
V: Found modules in /home/shardion/.config/discord/0.0.9/modules
Discord: /opt/discord
Modules: /home/shardion/.config/discord/0.0.9/modules
Index modified: yes
Linked injector directory: /home/shardion/.local/share/betterdiscordctl/bd/0
Linked injector repository: https://github.com/rauenzi/BetterDiscordApp
```

If this helps or you need more information, contact me.

**Comment by rauenzi** [comment]
Are you still facing this issue?

**Comment by TheAlcanian** [comment]
No, I am not. Nobody knows why it doesn't work the first time. BetterDiscord is a strange little thing.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by rauenzi** [comment]
Seems like it was a linux-specific issue. Unfortunately I didn't create the installer for it so I can't really say what could've been the issue
