### ISSUE TITLE
[Bug] Crashes on new discord update

### ISSUE THREAD

**Issue by MaxKruse** [rauenzi/BetterDiscordApp#269]
**Describe the Bug**
When changing "guilds", discord crashes with an error and the option to reload.

**To Reproduce**
Install BandagedBD, Change servers a little, crash occur

**Expected Behavior**
No crash

**Screenshots**
https://i.imgur.com/gehKto8.png

**Discord Version**
stable

**Additional Context**
https://www.reddit.com/r/discordapp/comments/dt41i6/discord_crashes_again_again_again_and_again/ to see some people talking about the problem

**Comment by dstN** [comment]
Some insights for rauenzi:

Bug is happening because of Emotes.

If you turn off Twitch, FFF and BetterTTV Emotes in Bandaged Discords Emotes-Settings it doesn't crash anymore.

**Comment by MaximzMugen** [comment]
yea, I honestly thought it was my computer. I uninstalled bandaged discord completely and delted discord folders from appdata and local appdata and reinstalled and nope it still happens, then i turned off twitch,FFZ and BetterTTV emotes and it doesnt happen anymore, though i would like to turn them back on so hoping this gets fixed.

**Comment by rauenzi** [comment]
Bug and reason are known. I am unfortunately out of town for the weekend with only my phone and can't really code. PRs for even a tempfix are welcome.
