### ISSUE TITLE
[Bug] BD doesn't load when not in any guilds.

### ISSUE THREAD

**Issue by criminal** [rauenzi/BetterDiscordApp#275]
Applicable to all Discord Versions (Stable/Canary/PTB)

If you aren't in any guilds BD won't actually load, you just get the endless loading icon on the bottom right. Same result on fresh install and with trying the installer "loading forever" fixes. BD will instantly start working as soon as you join a guild.

No errors in the log, the last message is that BD is starting.

**Comment by MasicoreLord** [comment]
In the meantime, I do have a workaround for you.
Just create a dummy Discord server.

Hope that helps you for now, @criminal

**Comment by rauenzi** [comment]
I'm not sure this is the case, it should recognize the discovery and add/create server buttons. If not, then I'll have to fix that
