### ISSUE TITLE
[Bug] BetterDiscord don't work

### ISSUE THREAD

**Issue by xSylla** [rauenzi/BetterDiscordApp#276]
BetterDiscord don't load, I mean Discord work but don't load anything from the module
Discord stable versione 0.0.305

**Comment by kittywitty1363** [comment]
Same thing for me, it refuses to load, no matter how many times I reinstall both BetterDiscord and Discord.

**Comment by AlastorStrixEfuartus** [comment]
same here

**Comment by Godchiru** [comment]
Same here? I tried restarting the client/my pc/ re-installing.

**Comment by KyzaGitHub** [comment]
Discord pushed an update which breaks BetterDiscord. Please wait for it to be fixed, that could take any amount of days.

**Comment by TheSweetLily** [comment]
Can also confirm!

**Comment by xSylla** [comment]
Yeah guys it's so strange, I tried to restart my pc and nothing.. i tried to re install better discord (unistalling that and re installing) nothing
i tried to repair and nothing too

**Comment by HentaiSucks** [comment]
not working for me either :/

**Comment by gibmadikka** [comment]
Alright stop spamming it, we know it's not working and repeating it won't make the solving process faster

**Comment by Rhyme** [comment]
Temporary fix:
- Go to %localappdata%\Discord\app-0.0.305\resources\app\betterdiscord
- open the file index.js 
- go to line 111, look for 5000
- change it 3889 and save. 
- Full close and restart Discord client

**Comment by Mattis6666** [comment]
> Temporary fix:
> 
> * Go to %localappdata%\Discord\app-0.0.305\resources\app\betterdiscord
> * open the file index.js
> * go to line 111, look for 5000
> * change it 3889 and save.
> * Full close and restart Discord client

Worked flawlessly, thanks for this! @Rhyme

**Comment by IcesyWisy** [comment]
> Temporary fix:
> 
> * Go to %localappdata%\Discord\app-0.0.305\resources\app\betterdiscord
> * open the file index.js
> * go to line 111, look for 5000
> * change it 3889 and save.
> * Full close and restart Discord client

I tried still no results, maybe it does work with on other people devices.

**Comment by AlastorStrixEfuartus** [comment]
I tested it and when i first restarted discord nothing happend then i tried restarting it once more waiting like 10 seconds and started it again this time it worked

**Comment by Wryyyong** [comment]
> To acces that index.js file you will need to have a code editor like Visual studio or Atom.

A text editor like NPP works too...

**Comment by Godchiru** [comment]
Totally worked, thanks! When the devs fix the problem do we have to change 3889 back to 5000?

**Comment by Rhyme** [comment]
> Totally worked, thanks! When the devs fix the problem do we have to change 3889 back to 5000?

Not a dev, hard for me to say. Assuming they change the file that gets installed to BBD by default to 3889, you wouldn't need to do it again. However if Discord changes this value again we'd need to find and edit the value until it gets changed in the installer again.. etc etc. Loop continues.

**Comment by criminal** [comment]
> Temporary fix:
> 
> * Go to %localappdata%\Discord\app-0.0.305\resources\app\betterdiscord
> * open the file index.js
> * go to line 111, look for 5000
> * change it 3889 and save
> * Full close and restart Discord client
> 
> Not sure where the file is located on *nix or Mac FYI
> 

For Mac OS, the file is located at /Applications/Discord.app/Contents/Resources/app/betterdiscord/index.js

**Comment by graphixillusion** [comment]
@criminal 
your workaround works good.

**Comment by duckspacito** [comment]
didnt work for me :(

**Comment by warsix4** [comment]
Same issue, also modifying line 111 of `index.js` does not seem to fix it.

**Comment by RandomRage** [comment]
Same problem 111 of index.js is not working... BetterDiscord worked amazing before until today. :(

**Comment by Fijikku** [comment]
I just opened it with normal NotePad and use Ctrl F for 5000, changed it it and saved. Worked Fine

**Comment by ZuranaSuki** [comment]
Temp fix worked like a charm for me and my sister thanks for the share!

**Comment by RandomRage** [comment]
> I just opened it with normal NotePad and use Ctrl F for 5000, changed it it and saved. Worked Fine

Nope i tried it again. Not working.

**Comment by mocchimon** [comment]
setting 5000 to 0 fixed it for me

**Comment by RandomRage** [comment]
> setting 5000 to 0 fixed it for me

Didn't work for me either.

**Comment by dh-are-you-ok** [comment]
> Temporary fix:
> 
>     * Go to %localappdata%\Discord\app-0.0.305\resources\app\betterdiscord
> 
>     * open the file index.js
> 
>     * go to line 111, look for 5000
> 
>     * change it 3889 and save
> 
>     * Full close and restart Discord client
> 
> 
> Not sure where the file is located on *nix or Mac FYI
> 
> Edit: For some reason it takes a few seconds for BDD to load after this so if it seems like it still doesn't work triple check you saved your change and wait a bit

The file is in `~/.local/share/betterdiscordctl/bd/0/betterdiscord` on Linux

**Comment by vperpl** [comment]
> 
> 
> Temporary fix:
> 
>     * Go to %localappdata%\Discord\app-0.0.305\resources\app\betterdiscord
> 
>     * open the file index.js
> 
>     * go to line 111, look for 5000
> 
>     * change it 3889 and save
> 
>     * Full close and restart Discord client
> 
> 
> Not sure where the file is located on *nix or Mac FYI
> 
> Edit: For some reason it takes a few seconds for BDD to load after this so if it seems like it still doesn't work triple check you saved your change and wait a bit

works, tanks.

**Comment by Velvex-Vancreed** [comment]
not loading when it starts and making me relogin to my acc on my pc

**Comment by rauenzi** [comment]
Just gunna quote @gibmadikka and lock this.
> Alright stop spamming it, we know it's not working and repeating it won't make the solving process faster
