### ISSUE TITLE
cant find discord.exe???????

### ISSUE THREAD

**Issue by ppsuck77** [rauenzi/BetterDiscordApp#278]
**Describe the Bug**

**To Reproduce**

**Expected Behavior**

**Screenshots**

**Discord Version**

**Additional Context**

**Comment by ppsuck77** [comment]
waddhek it says i cant find discord.exe for windows, tried this like 15 times its broken
i cant be the only one having this problem right?

**Comment by ppsuck77** [comment]
![what the hell](https://user-images.githubusercontent.com/57708680/68755155-f8f7a500-05ff-11ea-8273-b15ed904bd82.PNG)

**Comment by Gibbu** [comment]
Dude. It''s not that hard. Click "Browse" and follow this gif. If you can't see the `AppData` folder you need to enable show hidden folders. How to do that here: <https://i.imgur.com/HZhDKM8.jpg>
![gif](https://user-images.githubusercontent.com/20338746/68757482-1b210f80-0660-11ea-9ce1-e6898eeb6304.gif)

**Comment by ppsuck77** [comment]
i cant find appdata on users?

**Comment by ppsuck77** [comment]
tysm dude i  got this to work and yes the folder was hidden i see why now ty
