### ISSUE TITLE
A few issues I have had.

### ISSUE THREAD

**Issue by MrBlazzar** [rauenzi/BetterDiscordApp#28]
First issue is for some time now in minimal mode the server icons has shrunk of the but the pictures inside of them have not
Without Minimal:
![discord_2018-07-25_13-31-03](https://user-images.githubusercontent.com/5840012/43217225-0aa0c4d4-900f-11e8-8d1e-d7fc125b3f83.png)

With minimal:
![discord_2018-07-25_13-32-09](https://user-images.githubusercontent.com/5840012/43217262-27ef1798-900f-11e8-851b-223198c861d5.png)

The second issue just started today were as before in minimal mod the messages in a chat channel would be shrunk and everything rized to a much smaller size but I loaded it up today and the sizes of the chat messages are not shrinking in size so with minimal mode on or off they are the same size.

Note: the only custom CSS I use is these three:

.channel-members {
    max-width: 300px;
}

.channel-members-wrap {
    width: 300px;
}

.channel-members-wrap .channel-members .member .member-inner {
    width: 300px;
}

Which I've had since before these issues came up.

**Comment by MrBlazzar** [comment]
Example of the difference:
When minimal mod worked for chat messages
![unknown](https://user-images.githubusercontent.com/5840012/43219089-59a450dc-9014-11e8-9c8a-59715ccbad93.png)

Current minimal mode:
![discord_2018-07-25_14-10-01](https://user-images.githubusercontent.com/5840012/43219137-7a700a72-9014-11e8-8d8f-ecb53ad10ea9.png)

**Comment by rauenzi** [comment]
Discord pushed a large update which affected this.

**Comment by MrBlazzar** [comment]
apologies for complaining more but in minimal mode the messages seem really far to the right like they aren't moved with the avatar and such example image
![discord_2018-07-26_22-32-13](https://user-images.githubusercontent.com/5840012/43298382-c17339b6-9123-11e8-8c5f-3d756748edfa.png)
