### ISSUE TITLE
[Bug] Vertical white lines next to messages

### ISSUE THREAD

**Issue by aluu4445** [rauenzi/BetterDiscordApp#280]
When I turn on minimal mode I get these vertical white lines next to messages - any suggestions how to fix?

![image](https://user-images.githubusercontent.com/55626632/69103855-9fd5b880-0aba-11ea-8690-e679ec68ff3f.png)

**Comment by rauenzi** [comment]
Those are intended, I would suggest you join the css channel of the BD server for customizations.
