### ISSUE TITLE
"Hide Channels" in minimal mode is not working

### ISSUE THREAD

**Issue by Ltecruz** [rauenzi/BetterDiscordApp#281]
**Describe the Bug**
Using BD in minimal mode, with "Hide Channels in minimal mode" ticked, doesn't do anything to the channel list. 

**To Reproduce**
Activate minimal mode, tick Hide Channels. You will see it doesn't hide the channel list.

**Expected Behavior**
When you have Hide Channels in minimal mode, and you have minimal mode activatated, the channel list should hide.

**Comment by rauenzi** [comment]
Is this a feature you tend to use a lot? I don't know of any users that really use it and was going to deprecate and remove this feature.

**Comment by Ltecruz** [comment]
Me and a couple friends both installed this solely for this feature. But if you want to remove the feature go ahead, it's been a few months since the last time it worked. It's a useful feature though, for people who chat with friends without using servers and for people who don't usually change channel. 

In an ideal world Discord would make it work as a collapsable list that would only show when your mouse hovered over it. The channel list can take like 25% of the UI so I guess more people would use it this way (there's demand for something like this, just google).

**Comment by Hartsai** [comment]
Would also love this feature. Its pretty much only thing at the moment im missing for making the ui more or less like irssi

**Comment by jordanbertasso** [comment]
Request for a fix and continued support!

**Comment by rauenzi** [comment]
@Ltecruz do you use the minimal + hide channels _solely_ for hiding channels? Or do you also like the minimal mode part? If you just want to hide channels I would suggest the plugin HideServersChannelsRedux by Arashiryuu.

**Comment by Ltecruz** [comment]
@rauenzi I liked them both but being honest Hide channels was 95% of the deal to me. I can't get the plugin you mentioned to work as well unfortunately. Thank you for your work and for getting back to me.

**Comment by rauenzi** [comment]
I had just tested the plugin two days ago so I'm sure it works. Get in touch on Discord https://discord.gg/TyFxKer

**Comment by Hartsai** [comment]
I just tested it and it does indeed work. Its exactly what I was looking for. Crazy I didn't find it by googling because, no kidding, I must've spent hours trying to find a up to date plugin for hiding the channel list.

**Comment by Ltecruz** [comment]
Crazy cause there's no buttons appearing on my end. Can u @Hartsai link a screenshot to what a working version should be?

**Comment by Hartsai** [comment]
> Crazy cause there's no buttons appearing on my end. Can u @Hartsai link a screenshot to what a working version should be?

Here is how the topbar looks for me. I have some other themes installed too so yours may vary.
Toggle channels and toggle servers are to the left of the default buttons found in the ui

![hidechannelsbutton](https://user-images.githubusercontent.com/8059068/80332872-cca1af00-8854-11ea-914d-e9e6282bcd35.png)

**Comment by Ltecruz** [comment]
@Hartsai @rauenzi manged to get it to work after a clean installation of discord and bd, so all is good now. The plugin is exactly what I wanted. Thank you for pointing it out, couldn't find it by googling.

**Comment by rauenzi** [comment]
No problem, I will keep this as a low priority to-do.

**Comment by rauenzi** [comment]
I think this is better left to the plugin and will remove this from BD
