### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by CoverKun** [rauenzi/BetterDiscordApp#282]
**Describe the Bug**
 Saying Discord isn't installed when it is installed both in appdata and on desktop

**To Reproduce**
 ?

**Expected Behavior**
 Should show that its installed

**Screenshots**

![image](https://user-images.githubusercontent.com/44449827/69279649-d1ca4600-0bb2-11ea-847f-d75d5b1a250a.png)

**Discord Version**
 Stable

**Additional Context**

**Comment by Divisibly** [comment]
Have you tried reinstalling Discord?

**Comment by rauenzi** [comment]
This indicated your ENV variables could be messed up or the installer lacked permission to find Discord. You can either run the l*latest* installer while Discord is open (it helps the installer find it), or manually browse to the installation.
