### ISSUE TITLE
Custom CSS to remove animations has stopped working.

### ISSUE THREAD

**Issue by fhuewhd** [rauenzi/BetterDiscordApp#283]
I had some custom CSS code that removed some animations, specifically the three prancing dots when somebody is typing and a few others.  It worked very well.  Here's the thread where the code and what it was for were first described (I used the second one): https://github.com/rauenzi/BetterDiscordApp/issues/228

However, I've just had to reinstall Discord after maybe two months' absence, copied and pasted in the same code again, and it doesn't work any more, the dots are still prancing.  I'm not sure whether this is a legitimate subject for an Issue, but thought I'd post it in case one of you did see your way to suggesting anything, if you could.  I've checked the code carefully and I have copied it correctly without leaving anything out or adding anything, and I did press Save and Update (which seems to have worked, as it's still there when I check), and I don't really know what else to try.

**Comment by rauenzi** [comment]
As said in your last issue, this is not an issue with BBD. People are free to contribute you some css here, personally, in the wiki or otherwise.

**Comment by fhuewhd** [comment]
But I have CSS, it's just not doing its job.  It's not the CSS that's wrong, it worked perfectly before.  Unless something has changed about Discord in the last few weeks that makes that code no longer applicable.  That said, custom CSS is not entirely broken - I have another chunk above that that reads
* {
    -moz-animation: none !important;
    animation: none !important;
    transition: none !important;
}
and that does still work as intended (the spinning pair of blue squares no longer appears when images are loading, for instance), but it doesn't catch everything.

**Comment by intrnl** [comment]
Still not an issue with BBD itself though...

**Comment by rauenzi** [comment]
Right, it is possible that Discord changed something making your CSS wrong. BBD's job with the custom CSS is just to apply it, which it is correctly doing. It cannot detect that it is or is not having the desired effect.

**Comment by fhuewhd** [comment]
You reckon it's definitely Discord's fault rather than BD's, then?  Blast.  It's rather difficult because I don't suppose anyone will see the thread now it's closed, and I don't know anybody else who can write CSS.  It really is making Discord very hard to use at all for me.  Oh well.
