### ISSUE TITLE
[Bug] Game Activity feature not working properly post-BetterDiscord install

### ISSUE THREAD

**Issue by EnderDoes** [rauenzi/BetterDiscordApp#288]
**Describe the Bug**
Once BetterDiscord is installed, the Game Activity feature of standard Discord stops working, leading me to have to manually force Discord to recognize I'm playing a game so I can get Discord's in game overlay, and this issue also leads to me having to restart Discord once I'm done playing the game so I can stop showing I'm playing the game in the status menu

**To Reproduce**
From what I can find, this happens once BetterDiscord is installed

**Expected Behavior**
Normally, once I start playing a game, Discord will recognize that and show it, allowing me to use the in game overlay. When I would stop playing the game, Discord will stop showing me playing the game

**Discord Version**
I am on the Stable version of Discord

**Additional Context**
This only recently started, which I think was after the Custom Statuses update

**Comment by rauenzi** [comment]
This is due to the DoNotTrack plugin and not BetterDiscord.
