### ISSUE TITLE
emotes issues

### ISSUE THREAD

**Issue by d0ppller** [rauenzi/BetterDiscordApp#29]
When i write a emote in my message they disappear after few secondes but i see them if i try to delete my message for example. Or if i write a message with a emote alone, then i write another message, the emote will be "behind" the new message

**Comment by Lombra** [comment]
This sounds like the same issues we (and evidently at least a few others) are having. I'm mostly curious whether it's working for anyone at all right now? Are we doing something wrong? Have downloaded and installed the latest release from this project.

**Comment by Inve1951** [comment]
emotes vanishing is a known issue atm. everyone supposedly has it happening. discord re-renders the entire chat area (probably more) everytime the window loses focus. it also recreates entire message groups when their message count changes. why BD doesn't just insert the emotes again when that happens, i can't tell you. the _hooks_ to do so are in place. as a non-developer there's nothing you can do really.

**Comment by rauenzi** [comment]
This should now be fixed and be even better than before =)
