### ISSUE TITLE
[Bug] BBD menu in settings doesn't load if language was changed

### ISSUE THREAD

**Issue by AlexejheroYTB** [rauenzi/BetterDiscordApp#290]
**Describe the Bug**
When you switch the client's language, Discord opens directly in the settings menu, and the BBD menu doesn't render

**To Reproduce**
1. Press on User Settings
2. Press on Language
3. Select any other language

**Expected Behavior**
The window should reload, and the BBD menu should be there.

**Discord Version**
Stable 50836

**Comment by rauenzi** [comment]
To confirm the menu is there again upon closing and re-opening the menu?

**Comment by AlexejheroYTB** [comment]
Yes.


On Jan 30, 2020 at 18:17, Zack <notifications@github.com> wrote:

To confirm the menu is there again upon closing and re-opening the menu?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/rauenzi/BetterDiscordApp/issues/290?email_source=notifications&email_token=AHV6XKBDQP3XPYRVBBZ3RI3RAL4S7A5CNFSM4JWCUEBKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEKLSRVY#issuecomment-580331735>,
or unsubscribe

**Comment by rauenzi** [comment]
Then this is unfortunately a wontfix for this version of BBD, this is already addressed in the rewrite however.
