### ISSUE TITLE
[Bug] BetterDiscord not loading emotes at all suddenly

### ISSUE THREAD

**Issue by IntoComatose** [rauenzi/BetterDiscordApp#291]
**Describe the Bug**
As of a few days ago(?), Discord updated and my theme is slightly broken and emotes do not load at all (twitch based emotes)

**To Reproduce**
n/a

**Expected Behavior**
Emotes should load up properly and allow me to see them.

**Screenshots**
n/a

**Discord Version**
Build number 51387, Stable

**Additional Context**
I've just fully uninstalling as well as repairing, but nothing helps.

Thank you for your time.

**Comment by BurnySc2** [comment]
The emotes suddenly (randomly) work again for me after 27 days of not working either.

**Comment by rauenzi** [comment]
It's not really random... I pushed updates to fix them.
