### ISSUE TITLE
[Bug]Unable to open BBD

### ISSUE THREAD

**Issue by Rebisoft** [rauenzi/BetterDiscordApp#293]
**Describe the Bug**

When i click BBD it says discord is damaged etc then it tells me to move it to bin.After moving to bin it says discord does not seem to be installed
**To Reproduce**

i think i got ip banned from discord temporarily for using an autoclicker by accident on a reaction. When i redownloaded discord etc BBD didnt work
**Expected Behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/58822137/71158788-81143e80-227f-11ea-857c-405180fb8b9a.png)
![image](https://user-images.githubusercontent.com/58822137/71158836-8c676a00-227f-11ea-8b1d-cbf44f191121.png)

**Discord Version**

Idk,latest i guess,i redownloaded
**Additional Context**

**Comment by rauenzi** [comment]
You need to repair your Discord installation.

**Comment by Nebula-Developer** [comment]
Necro, but I do also get this when installing before initially opening discord after macOS runs the verification system.
Running
```sh xattr -d com.apple.quarantine /Applications/Discord.app/ ```
Fixes it for me.
