### ISSUE TITLE
[Bug] Unable to click the "Open Plugin/Theme Folder" buttons in settings.

### ISSUE THREAD

**Issue by Link1147** [rauenzi/BetterDiscordApp#294]
**Describe the Bug**
Recently, I've found out about BetterDiscord, and wanted to try and get it for my discord on my personal laptop. I own a Chromebook. It runs Linux, and that's how I was able to get Discord, and after a few hours of tinkering, BD. Everything seems to be working fine, and its been around 15-18 hours since I successfully installed BD. My only issue is that the "Open Plugin Folder" and "Open Theme Folder" buttons don't work upon clicking them. What I found REALLY odd is that when I reinstalled BD to try and get the buttons to work, they did, and then all of a sudden just stopped working when attempting to put plugins into the plugin folder. I have no idea why this happens, and i'd love to hear any sort of response or solution.

**To Reproduce**
-Reinstall the app using this within the terminal: $ betterdiscordctl reinstall
-Once reinstalled, open Discord, if successfully installed, go to either "Plugins" or "Themes"
-Once in the desired tab click "Open Plugin/Theme Folder"
-Now, go to your file directory, and add the desired file to either one of the two folders of theme or plugin
-Once done, go back to your discord and click "Open Plugin/Theme Folder" again, neither will open.

**Expected Behavior**

I expected to see the page open once clicked, and be able to enable a theme/plugin.

**Screenshots**

![Screenshot 2020-01-18 at 3 41 54 PM](https://user-images.githubusercontent.com/43656909/72670214-1898b880-3a09-11ea-84a6-50db5eabba9d.png)

**Discord Version**

The latest version of Discord(LINUX), and latest version of BD.

**Comment by rauenzi** [comment]
I would ask you to check Discord's console for errors, if there are none, the issue is between electron and your OS not agreeing on how to open the folder

**Comment by rauenzi** [comment]
Without the requested information, there isn't much I can do to help. Closing as stale, please re-open if you end up getting the information.
