### ISSUE TITLE
[Bug] Broken friends/activity panel

### ISSUE THREAD

**Issue by EthanYatsumaru** [rauenzi/BetterDiscordApp#295]
**Describe the Bug**
Recently all of my themes have a broken element. The activity/friends panel is no longer affected by themes and has reverted to the original discord look. Only this panel is affected.

**To Reproduce**
Use any theme and look at your friends/activity panel. I was using ClearVision and a few other themes in the screenshots.

**Expected Behavior**
It should look similar to a DM page https://cdn.discordapp.com/attachments/516768619921670155/669631918261665802/unknown.png

**Screenshots**
https://cdn.discordapp.com/attachments/516768619921670155/669631952856416267/unknown.png

**Discord Version**
Stable

**Additional Context**
I have also tried this with other themes and they all appear to be broken.

**Comment by rauenzi** [comment]
This is an issue with the themes themselves, not BBD.
