### ISSUE TITLE
Cant download better discord with injector(Pls Answer)

### ISSUE THREAD

**Issue by IcyFist** [rauenzi/BetterDiscordApp#296]
When i activated the injector it says no connection to remote server

**Comment by rauenzi** [comment]
I need significantly more information than what has been provided. What "injector" was activated? Is there a screenshot of this error about the connection to the server? What installer did you use and what version?

**Comment by IcyFist** [comment]
https://gyazo.com/49b4621ca319d9cb87b78b1f0bc91bcb - Link to error
error says no connection to remote server.
i used the normal windows injector

**Comment by IcyFist** [comment]
@ @hello?

**Comment by IcyFist** [comment]
i used the windows injector on the newest injector

**Comment by IcyFist** [comment]
hello?

**Comment by rauenzi** [comment]
No need to continually comment, I'm a busy person with a job.

Check that you can or cannot access the url in your web browser. Issues like this are 99% of the time from your antivirus, pc network settings, router, or isp, none of which is something that I can easily debug for you.

**Comment by IcyFist** [comment]
i cant download from the link but if i use vpn i can download manually but not with the injector.
there is any way i can do it myself?

**Comment by IcyFist** [comment]
i get ERR_CONNECTION_REFUSED when i try to enter the link

**Comment by IcyFist** [comment]
hello?

**Comment by Technetium1** [comment]
@IcyFist If this remains an issue -- but not with VPN on; then something is likely blocking Github. That is not something that is in the control of this developer. That should help you isolate your problem. There are no other reports of this happening, so it is almost certainly an issue exclusive to your network. If this issue is no longer active please close.

**Comment by rauenzi** [comment]
Yes unfortunately I have to agree with Technetium1, this is something that you'll have to diagnose yourself. I apologize.
