### ISSUE TITLE
javascript error on start on os x

### ISSUE THREAD

**Issue by lillypone** [rauenzi/BetterDiscordApp#297]
starting discord, i get this error:
![image](https://user-images.githubusercontent.com/49787675/73170520-8a05f480-40f6-11ea-898f-d5ce7c89eb5c.png)
sometimes i'm able to pass the error and still use betterdiscord, however some things are broken. for example, i am unable to change settings of plugins.
i'm running macos 10.15 catalina.

**Comment by Vladabdf** [comment]
Confirmed happening on Windows 10 as well. Running the repair works, however over time my PC shuts down entirely and then the error comes again until I repair. It then turns into an endless cycle of being able to use Discord for five minutes, then it breaks again and I have to repair BBD.

**Comment by rauenzi** [comment]
The error shown in the screenshot comes from a very old installer and injection process. BBD has not used that form of injection in well over a year. I would suggest making sure you have the up to date mac installer.
