### ISSUE TITLE
[Bug] stopped working on stable / default Discord today

### ISSUE THREAD

**Issue by infiSTAR** [rauenzi/BetterDiscordApp#299]
Hey
for some reason it simply doesn't loader anymore. Whatever I try.

Was there some kind of BetterDiscordAppBlock update or what is going on?

**Comment by DragonGodGrapha** [comment]
Unsure if you're experiencing a similar issue to what I just had, but I had to manually redirect the installer to a new location. Try changing the install location to `C:\Users\<username>\AppData\Local\Discord\app-<newest number>` instead of the default location.

**Comment by rauenzi** [comment]
Try grabbing the most recent installer and reinstalling with Discord running.
