### ISSUE TITLE
Discord Custom Badges?

### ISSUE THREAD

**Issue by GitSimonHub** [rauenzi/BetterDiscordApp#30]
Hey,
wäre es möglich ein Custom/Fake Badges Plugin für Discord zu schreiben?
Es gibt ja dieses Nitro Member Badge und Discord Hype squad
Danke!

**Comment by rauenzi** [comment]
es ist möglich. Das wäre ein Plugin und kein Problem für dieses Projekt

**Comment by GitSimonHub** [comment]
Also würdet ihr es versuchen bzw Mal anschauen?
Danke rauenzi

**Comment by PoorPocketsMcNewHold** [comment]
@GitSimonHub Es wäre nicht der richtige Ort, um das zu fragen, egal wie. Versuchen Sie, ihn direkt zu kontaktieren, wenn Sie es wirklich wollen.

**Comment by Inve1951** [comment]
@GitSimonHub <https://github.com/mwittrien/BetterDiscordAddons/tree/master/Plugins/EditUsers>. Alles andere würd serverseitigen code erfordern. BD ist allerdings ausschließlich client-seitig.
