### ISSUE TITLE
[Feature] Enable Chromium Experimental Features

### ISSUE THREAD

**Issue by PseudoResonance** [rauenzi/BetterDiscordApp#300]
**Is your feature request related to a problem? Please describe.**
The inability to use experimental features, like the CSS property `backdrop-filter` is disappointing.

**Describe the feature you'd like**
I'd like for experimentalFeatures to be enabled at startup in Electron.

**Additional context**
Under [webPreferences](https://www.electronjs.org/docs/api/browser-window#static-methods), experimentalFeatures defaults to false, but if set to true, it works fine.

I was able to simply add `options.webPreferences.experimentalFeatures = true;` in Discord's index.js, but it must come before `super(options);` is run, or else the setting won't take effect, and unfortunately BetterDiscord loads in after that. Sorry I can't be of much help, I know next to nothing about Electron, but would it make a difference if experimentalFeatures was added to the `get windowOptions()` method [here](https://github.com/rauenzi/BetterDiscordApp/blob/master/js/main.js)?

**Comment by rauenzi** [comment]
I will not be adding this, as it is not needed. `backdrop-filter` is only behind the `experimentalFeatures` flag for chromium versions `47` through `76`. Current Discord stable is using version `69`. Canary/PTB are using version `78` which means when this updated version comes to stable it will be entirely unnecessary to set this flag to use `backdrop-filter`.

**Comment by PseudoResonance** [comment]
Ah I see, thank you.
