### ISSUE TITLE
BandagedBD causes "Well this is awkward" error on launch

### ISSUE THREAD

**Issue by Ayooyauwu** [rauenzi/BetterDiscordApp#301]
Since today, BD has caused my discord to keep crashing on that error message and reloading just ends in the exact same message. I've tried launching discord without BD, and works just fine. 
Is there a fix for this issue?

**Comment by rauenzi** [comment]
I would recommend removing all plugins before retrying.

**Comment by RazerMoon** [comment]
Probably a broken plugin, I'd also recommend removing all plugins and retrying

**Comment by rauenzi** [comment]
It was very likely a plugin.
