### ISSUE TITLE
"The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel."

### ISSUE THREAD

**Issue by Zaneclodon** [rauenzi/BetterDiscordApp#303]
The installer doesn't seem to be working. Attempting to install makes the following appear in the installer console with "Details" checked:
> Killing Discord Processes
> Downloading BandagedBD package
> Using channel: https://github.com/rauenzi/BetterDiscordApp/archive/injector.zip
> Downloading to: C:\Users\Zane\AppData\Local\Discord\app-0.0.305\\resources\BetterDiscord.zip
> Download error: The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.
> Download seems to have failed, will try once more.
> Downloading BandagedBD package
> Using channel: https://github.com/rauenzi/BetterDiscordApp/archive/injector.zip
> Downloading to: C:\Users\Zane\AppData\Local\Discord\app-0.0.305\\resources\BetterDiscord.zip
> Download error: The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.

I am able to download the .zip archive by connecting to the link in my browser, but the installer keeps returning this download error and I don't know of a way to pass the archive I downloaded to the installer, if that's even possible.

**Comment by rauenzi** [comment]
This could be an issue with your firewall and/or permissions. Are you running the installer with administrator permissions?

**Comment by Zaneclodon** [comment]
Just tried running as administrator and got the exact same result. I don't have any firewall set up, as far as I'm aware.

**Comment by rauenzi** [comment]
Might be some sort of cache mismatch. If you want you can manually install by downloading that zip file and extracting the contents of the folder inside to `C:\Users\Zane\AppData\Local\Discord\app-0.0.305\resources\app`

**Comment by Zaneclodon** [comment]
Thanks, that manual install worked!
