### ISSUE TITLE
[Bug] Twitch Emojis are gone again, only default discord emojis show

### ISSUE THREAD

**Issue by egold555** [rauenzi/BetterDiscordApp#305]
**Describe the Bug**
Twtch emojis do not show up in the emoji panel. They also do not show up when typing them into chat.

Things I have tried: 

1. Restarting Discord
2. Reinstalling Discord
3. Reinstalling BBD
4. Clearing emoji Cache
5. Disabling all plugins and themes

**To Reproduce**

1. Install Latest Discord
2. Install Latest stable BBD
3. Go to a DM conversation or a guild chat
4. Click the emoji button

**Expected Behavior**
See Twitch emojis, and Discord emojis, and be able to use them in the chat

**Screenshots**
![image](https://user-images.githubusercontent.com/2999543/73903469-1084a980-484e-11ea-8d4a-03842cb8db49.png)
![image](https://user-images.githubusercontent.com/2999543/73903529-3611b300-484e-11ea-9978-c90161471434.png)

**Discord Version**
Stable

**Additional Context**
BBD v0.2.21
BD v0.3.2
Discord Stable 53946 (6fceff4)
Windows 10 64-Bit (10.0.18363)

**Comment by johnnyapol** [comment]
It also seems the channel UI redesign broke colored text as well.

**Comment by egold555** [comment]
> It also seems the channel UI redesign broke colored text as well.

Didn't even notice that until now

**Comment by rauenzi** [comment]
These are both expected and will be fixed eventually

**Comment by egold555** [comment]
![image](https://user-images.githubusercontent.com/2999543/74292636-61cce700-4ced-11ea-942c-bfb39cc12156.png)
Hey they are back, just not functional (For those who haven't noticed yet)

**Comment by egold555** [comment]
Closing because it is fixed now. Thank you so much!
