### ISSUE TITLE
[Bug] "Restart all instances" checkbox doesn't load BD

### ISSUE THREAD

**Issue by DragonGodGrapha** [rauenzi/BetterDiscordApp#308]
**Describe the Bug**
"Restart all instances" checkbox causes Discord to start after installation, but a full quit and reload is still required to load BetterDiscord.

**Discord Version**
PTB 0.0.51

**Comment by rauenzi** [comment]
I am unable to reproduce this. Does this happen consistently?

**Comment by DragonGodGrapha** [comment]
I've noticed it the past few times when there are major updates, the ones which create a new folder and require me to reinstall BD.  I am unable to reproduce the issue with uninstalling and reinstalling BD, however. Feel free to close this for now, and I'll update if I continue to see this issue with future updates.

**Comment by shinji257** [comment]
I have noticed this issue when reinstalling via the installer and choosing a troubleshooting option.  It will remove BD and kill it but never start Discord back up once it has completed.
