### ISSUE TITLE
[Bug] BetterDiscord don't work

### ISSUE THREAD

**Issue by vugi99** [rauenzi/BetterDiscordApp#309]
**Describe the Bug**
BetterDiscord is not working since the last update of discord

**To Reproduce**
Launch discord with the latest discord version with betterdiscord

**Expected Behavior**
BetterDiscord should be loaded

**Discord Version**
Stable

**Additional Context**
Latest discord update

**Comment by Ondra97** [comment]
@vugi99 reinstall better discord

**Comment by vugi99** [comment]
It works @Ondra97
