### ISSUE TITLE
[Bug] after new update the extension doesn't work anymore

### ISSUE THREAD

**Issue by XxMrFiresxX** [rauenzi/BetterDiscordApp#311]
after the auto update for discord the extension doesn't work anymore

**Comment by okami-x** [comment]
If you mean that BetterDiscord is not working with the last update you should try to move the "app" folder located in C:\Users\%UserName%\AppData\Local\Discord\app-0.0.305\resources to  C:\Users\%UserName%\AppData\Local\Discord\app-0.0.306\resources

**Comment by XxMrFiresxX** [comment]
oh i see will try and update you on it

**Comment by XxMrFiresxX** [comment]
my app was located as roaming at the end

**Comment by rauenzi** [comment]
Then you located the wrong folder. Just run the installer and install BD again. Duplicate of #310 #309
