### ISSUE TITLE
[Feature] Make the "Plugin loaded" Notifications toggleable

### ISSUE THREAD

**Issue by lollilol** [rauenzi/BetterDiscordApp#312]
**Describe the feature you'd like**
A toggle in the BetterDiscord Settings that toggles these kind of messages:
![image](https://user-images.githubusercontent.com/38194372/75561784-d9b64380-5a47-11ea-8029-684e8f7303b3.png)

**Comment by rauenzi** [comment]
They should already be toggleable: https://i.imgur.com/Qd2GM5v.png
