### ISSUE TITLE
[Bug] Discord throws Javascript error affter installing BD

### ISSUE THREAD

**Issue by Ryonez** [rauenzi/BetterDiscordApp#313]
**Describe the Bug**

After updating Discord and reinstalling BD, Discord fails to load, throwing a JavaScript error.

**To Reproduce**

1. Update Discord.
2. Installed BD
3. Start Discord

**Expected Behavior**

For Discord to launch and BD to load.

**Screenshots**

BD Installation log:
![image](https://user-images.githubusercontent.com/16157130/75608498-d1075f80-5b64-11ea-95f0-f8b001b8f765.png)

Discord error:
![image](https://user-images.githubusercontent.com/16157130/75608502-dcf32180-5b64-11ea-8df2-8d362e00d48f.png)

**Discord Version**

Stable

**Additional Context**

**Comment by rauenzi** [comment]
You are using a very outdated installer. Please redownload the latest version and use that.

**Comment by Ryonez** [comment]
Thank you, that appears to be it.

Though I'd advise in the future not to close things until there's been a confirmation that the issue is resolved.

**Comment by rauenzi** [comment]
I've seen this exact issue before so I considered it resolved. Also using outdated software is generally grounds for rejection->try reproduce at latest level.
