### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Arion-Kun** [rauenzi/BetterDiscordApp#315]
BD Shows: Update Available
"An update for BandagedBD is available (0.3.3) Please Reinstall 
Download Installer"

Link takes us to installer version 1.0.3 which hasn't been updated since 2019 and which is the one I am currently using.

**Comment by williamjcm** [comment]
This isn't a bug. The installer's version only affects the installer itself, not the version of BandagedBD it can install.

**Comment by Arion-Kun** [comment]
oh yeah, forgot the installer acts rather as a installer like battle.net does for a battle.net game, fetching the .zip package when installing right?

**Comment by williamjcm** [comment]
Kinda, yeah.

**Comment by KaKi87** [comment]
Where can we find the changelog then ?

**Comment by ransagy** [comment]
I've re-downloaded the installer just in case and installed over the stable a few times, i still get the same message (and BBD shows its still version 0.2.24). What am i missing?

**Comment by Paulaob79** [comment]
> I've re-downloaded the installer just in case and installed over the stable a few times, i still get the same message (and BBD shows its still version 0.2.24). What am i missing?

Exactly the same happens to me.

**Comment by HanabishiRecca** [comment]
Same issue. No matter how many times I downloading and reinstalling - it still wants an update.

**Comment by HanabishiRecca** [comment]
Hmm, I've resolved the problem. Looks like BandagedDB was installing at one discord version, but application was launching from another.
To solve the problem, ensure you have only 1 discord version folder
![изображение](https://user-images.githubusercontent.com/13597663/76161016-12919f00-6151-11ea-8764-d5d6f51b6c39.png)

Or simply reinstall Discord.

**Comment by ransagy** [comment]
Hah, You're right. My links were broken and still set to 0.0.305 where 306 was also installed and where BBD was obviously being pointed at. Great job finding this!
