### ISSUE TITLE
Crash when right click [Bug]

### ISSUE THREAD

**Issue by AzenoX** [rauenzi/BetterDiscordApp#316]
Hello,

**Describe the Bug**
Sometimes, when I use my right click somewhere, on a user, on a message or on a channel, my discord suddenly crash...

**To Reproduce**
It happen randomly so I can't tell you how reproduce it...

**Discord Version**
I don't know which one I need to give you, so this is a screenshot http://prntscr.com/rez0qt :D

**Comment by rauenzi** [comment]
Can you at least tell me what plugins of mine you're using? You didn't really give me much of anything to go on

**Comment by rauenzi** [comment]
Oh I didn't realize this was on the BetterDiscordApp repo. This is very very likely caused by your plugins and not BBD. Please disable all your plugins and reload. Then see if that still occurs

**Comment by AzenoX** [comment]
This is the list of all plugins I use http://prntscr.com/rez4lc .

I'll try to disable all of them and reload. I'll come back to you if I always got the issue ;)
Thank you

**Comment by AzenoX** [comment]
For now, I think it solved when I disable all plugin. I'll enable plugins one by one, and send a message here when I'll find which one cause crashes.

**Comment by rauenzi** [comment]
That's what I suspected, you can comment here and I'll try to direct you to the plugin author's github.
