### ISSUE TITLE
Smaller Names

### ISSUE THREAD

**Issue by midnightvoyager** [rauenzi/BetterDiscordApp#32]
After the latest update, everyone's usernames in the username panel and in chat are smaller than the normal text.
![names](https://user-images.githubusercontent.com/16024801/43370423-6d0685b8-9344-11e8-85cc-04f7fd576bf5.png)

**Comment by midnightvoyager** [comment]
Ah yes, I'm in minimal mode. I've always been in minimal mode though, and it's never been like this until just today.

**Comment by rauenzi** [comment]
Ah yeah it wasn't like that before because the selector had broken. The username smaller than the text is intended for both Cozy and Compact modes.
