### ISSUE TITLE
[Bug]Cannot connect to discord after BD update.

### ISSUE THREAD

**Issue by Boii1** [rauenzi/BetterDiscordApp#321]
**Describe the Bug**
Stuck during connecting at bottom left.

**To Reproduce**
Launch discord.

**Expected Behavior**
Should load past discord into the main app where it shows discord plugin updates.

**Screenshots**
https://imgur.com/a/sss0gsL

**Discord Version**
Stable

**Additional Context**
Just it was working perfectly like 2 seconds ago, I hit Ctrl+R because an image didn't sent (randomly hangs sometimes if I send an image too fast). Now it can't connect and it said BandagedBD had just updates so.

**Comment by rauenzi** [comment]
Discord is having connection issues, that's why your stuff didn't send and it isn't connecting.

**Comment by Boii1** [comment]
Yeah just realized this afterwords. Very weird time to go out and update BD lmao. Sorry for issue.
