### ISSUE TITLE
[Bug] BandageDB is available (0.3.3) Please reinstall

### ISSUE THREAD

**Issue by Owned67** [rauenzi/BetterDiscordApp#322]
**Describe the Bug**
message => BandageDB is available (0.3.3) Please reinstall

**To Reproduce**
launch discord

**Expected Behavior**
where is the good version for solve this please?

**Screenshots**
![bug](https://user-images.githubusercontent.com/1497809/76835561-9b829780-682f-11ea-91c4-30868d3f9b64.jpg)

**Discord Version**
Stable

**Additional Context**
Downloading https://github.com/rauenzi/BetterDiscordApp/releases/download/v1.0.0/BandagedBD_Windows.exe don't help me....

**Comment by rauenzi** [comment]
Use that to install, then **_manually_** restart Discord.

**Comment by Owned67** [comment]
Already done but it's same, this bug persist....

**Comment by rauenzi** [comment]
Show your versions here https://i.imgur.com/kG2GE1Z.png

**Comment by Owned67** [comment]
![bug](https://user-images.githubusercontent.com/1497809/76877597-f211c500-6873-11ea-9499-e00c6f58292a.jpg)

**Comment by rauenzi** [comment]
You are running an old version of Discord (0.0.305) and the installer installed to a newer version (0.0.306)

**Comment by Owned67** [comment]
Thanks for the tip, i've modified my shorcut  C:\Users\Tanki\AppData\Local\Discord\app-0.0.305 to C:\Users\Tanki\AppData\Local\Discord\app-0.0.306.

Restarted discord without his message, thanks very much ;)
