### ISSUE TITLE
[Bug] error message ''Discord does not seem to be installed on your system.''

### ISSUE THREAD

**Issue by huntermarche** [rauenzi/BetterDiscordApp#324]
**Describe the Bug**

I can't use BandageDB when i open i gor an error message but discord is installed i already unistall/installed
**To Reproduce**

**Expected Behavior**

**Screenshots**

**Discord Version**

**Additional Context**

**Comment by rauenzi** [comment]
You will have to either have Discord running when launching the BBD installer, or browse manually to your Discord.exe
