### ISSUE TITLE
[Bug] Repo search box broken for themes tab

### ISSUE THREAD

**Issue by Gibbu** [rauenzi/BetterDiscordApp#327]
**Describe the Bug**
Cannot search with the new inbuilt repo search on the themes tab.

**To Reproduce**
Typing in the repo search on the themes tab.

**Expected Behavior**
Return themes that contain those letters.

**Screenshots**

![image](https://user-images.githubusercontent.com/20338746/77807879-57b84980-70dd-11ea-8702-e7d5b401c6fd.png)

**Discord Version**
Stable 56718 (584d8ed)
Host 0.0.306
Windows 10 64-Bit (10.0.18362)
BBD Injector 0.3.3 By Zerebos
BandagedBD 0.3.0 By Zerebos

**Comment by rauenzi** [comment]
Can you show me a list of the themes you are using? One must have some weird symbols as I am [unable to recreate.](https://i.imgur.com/IvbUgXz.gifv)

**Comment by Gibbu** [comment]
Ahh I see. Themes without a description create that issue

**Comment by rauenzi** [comment]
Hmm I thought I made it more tolerant of that, but perhaps I overlooked it for themes... will look into it

**Comment by rauenzi** [comment]
Did that omit the `description` value entirely? Or just have a blank string?

**Comment by Gibbu** [comment]
Ahhh woops. I turns out to be other fields that don't have any string

![gif](https://user-images.githubusercontent.com/20338746/77809096-55a4b980-70e2-11ea-974f-8719b0a27448.gif)

**Comment by rauenzi** [comment]
Okay I think I see the issue now, fix coming
