### ISSUE TITLE
BetterDiscord v0.3.1 does not support this old version error

### ISSUE THREAD

**Issue by elliotttate** [rauenzi/BetterDiscordApp#328]
I'm getting a: BetterDiscord v0.3.1 does not support this old version (0.0.256) of Discord. Please update your Discord installation before proceeding.

The latest version on OS X is 0.0.256

**Comment by MasicoreLord** [comment]
@elliotttate reload, and you shouldn't get that kind of message for now.  There was a bug in it where it only worked right for windows users.

**Comment by rauenzi** [comment]
Solved

**Comment by elliotttate** [comment]
Thanks!!
