### ISSUE TITLE
[Feature] Ability to change toast notfrication location

### ISSUE THREAD

**Issue by ent3r** [rauenzi/BetterDiscordApp#329]
**Is your feature request related to a problem? Please describe.**
When i am reading a message, and some notfrication shows up, like checking for updates, it covers the message, and i have to wait for it to disappear

**Describe the feature you'd like**
Add a dropdown that changes the location of the toast, like bottom center, top center, bottom right, etc

**Additional context**
![Discord_FkvFACCV1F](https://user-images.githubusercontent.com/32072697/77833946-5d477b00-7141-11ea-8e23-653a85f2c042.png)

**Comment by rauenzi** [comment]
I think this is a better case for the use of some custom css. Especially as many plugins use their own toasts so BD can't really do too much about them. Please reach out to people in the css channels of the support servers for more info.
