### ISSUE TITLE
slow 

### ISSUE THREAD

**Issue by reuben142** [rauenzi/BetterDiscordApp#33]
when i use the latest relese of betetrdiscord it lages out the discord canery client

**Comment by PoorPocketsMcNewHold** [comment]
Don't use the unstable development of Discord then.
_Other than that, Could we get more details about it? Which plugins/themes are you using? Any modifications to it? System specifications ?_

**Comment by reuben142** [comment]
its discord canery using bandeg bd 
plugins: DiscordCakeDay v0.1.2 by Mega_Mewthree
FriendNotifications v1.1.0 by DevilBro
Mention Aliases v0.8.17 by Metalloriff
PinDMs v1.0.8 by DevilBro
The Clap Best Clap Plugin Clap Ever v0.4.2 by Metalloriff
theme is Frosted glass Rewrite v1.0.0 by Alten
i have 2 pcs i use my surface has 2 GB of RAM and my laptop has 4 GB of ram both have the same problem

**Comment by rauenzi** [comment]
This *should* be fixed in the latest update. I would recommend disabling those plugins and trying the latest update of BBD on it's own.
