### ISSUE TITLE
[Bug] Discord crashes when betterdiscord is installed.

### ISSUE THREAD

**Issue by Mirrored6** [rauenzi/BetterDiscordApp#330]
**Describe the Bug**
when i start discord with better discord installed it crashes.

**To Reproduce**

install betterdiscord on the latest discord release

**Expected Behavior**

Discord is expected to launch just fine even with betterdiscord installed.

**Screenshots**

![image](https://user-images.githubusercontent.com/47297746/78120944-08d72080-740b-11ea-9738-a5f484750afc.png)

**Discord Version**

Stable

**Additional Context**

i have also tried removing betterdiscord and then discord starts normally. and when i install betterdiscord again it get the same screen.

**Comment by AlexHaber** [comment]
Try removing the plugins folder in %AppData%\BetterDiscord

**Comment by Mirrored6** [comment]
ill try

**Comment by Mirrored6** [comment]
ehh that worked
i also found out (by getting into console) that one of my plugins is broken.
i removed it, restarted discord, added it back to the plugin folder, restarted discord, and then it updated the plugin.

**Comment by Mirrored6** [comment]
thanks
