### ISSUE TITLE
[Bug] Plugins don't stay turned on version 0.32

### ISSUE THREAD

**Issue by red1134** [rauenzi/BetterDiscordApp#331]
**Describe the Bug**
 Turning on any plugins with the current version results in nothing loading and when I leave and return to the plugin menu they are turned off, save for zereslibrary. They don't even try to load, no success OR error message appears like before. 

**To Reproduce**
 Not sure if this affects everyone, but try turning plugins on or off. I currently have: ZeresPluginLibrary, StaticAvatars, NoDeleteMessages, and SilentTyping. 

**Expected Behavior**
 The plugins stay turned on and load as they always have. 

**Screenshots**
 https://www.youtube.com/watch?v=K556Dbi05SQ&feature=youtu.be - Screen recording of issue 

**Discord Version**
 Stable

**Comment by rauenzi** [comment]
NoDeleteMessages is not an official plugin and can get your account banned. You will not receive support on official servers either.
