### ISSUE TITLE
Installation error because the injector.zip is missing on git

### ISSUE THREAD

**Issue by kackhaufen** [rauenzi/BetterDiscordApp#332]
here is the log i got on screen:
Starting installation for Discord
Killing Discord Processes
Downloading BandagedBD package
Using channel: https://github.com/rauenzi/BetterDiscordApp/archive/injector.zip
Downloading to: C:\Users\marpr\AppData\Local\Discord\app-0.0.306\\resources\BetterDiscord.zip
Download error: The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.
Download seems to have failed, will try once more.
Downloading BandagedBD package
Using channel: https://github.com/rauenzi/BetterDiscordApp/archive/injector.zip
Downloading to: C:\Users\marpr\AppData\Local\Discord\app-0.0.306\\resources\BetterDiscord.zip
Download error: The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.

**Comment by rauenzi** [comment]
The `zip` is not missing on GitHub, either GitHub is/was having issues, or there are some DNS settings on your end preventing the connection.
