### ISSUE TITLE
[Feature]Install through command-line

### ISSUE THREAD

**Issue by PythonCoderAS** [rauenzi/BetterDiscordApp#334]
**Is your feature request related to a problem? Please describe.**

**Describe the feature you'd like**

I want to be able to install BetterDiscord through a command-line program, so that I can set up something similar to Homebrew Cask to auto-inject for me.

**Additional context**

**Comment by qwerasd205** [comment]
Due to your mention of Homebrew I assume you mean on macOS?

**Comment by PythonCoderAS** [comment]
Yes

**Comment by rauenzi** [comment]
I'll post some manual installation instructions on the README and you can create your own script from there. However, I do not plan to create an official command line installer.

**Comment by rauenzi** [comment]
Manual instructions can now be found on the README
