### ISSUE TITLE
[Feature] Improve the Custom CSS design.

### ISSUE THREAD

**Issue by julian-fairfax** [rauenzi/BetterDiscordApp#335]
**Is your feature request related to a problem? Please describe.**
The design of the Custom CCS section is out-of-date compared to the rest of the Discord and BetterDiscord sections.  

**Describe the feature you'd like**
An improvement to the design of the Custom CSS section.  

**Additional context**
I'm currently using my own theme file to improve the design myself. I'm not sure how this could be integrated into BetterDiscord's code but I'm attaching it in case it might be useful.  

![Screenshot 2020-04-15 at 13 07 25](https://user-images.githubusercontent.com/43753131/79330667-3a2b1280-7f1a-11ea-9ab9-71470ea36a66.png)
[Untitled.theme.css.zip](https://github.com/rauenzi/BetterDiscordApp/files/4480840/Untitled.theme.css.zip)

**Comment by RazerMoon** [comment]
I think it's fine the way it is in my opinion, it's has all the basic features you need for quick CSS editing. If someone wants something a bit more fancy I think a theme does the job. Are there any specific design features you would like to be improved?

My editor with a theme.
![Screencap of my custom css](https://user-images.githubusercontent.com/33849459/79436556-f216f900-7fc8-11ea-91f7-505ab6b816b8.png)

**Comment by julian-fairfax** [comment]
> I think it's fine the way it is in my opinion, it has all the basic features you need for quick CSS editing. If someone wants something a bit more fancy I think a theme does the job. Are there any specific design features you would like to be improved?
> 
> My editor with a theme.
> ![Screencap of my custom css](https://user-images.githubusercontent.com/33849459/79436556-f216f900-7fc8-11ea-91f7-505ab6b816b8.png)

The main bothers are the color scheme (which doesn't match the rest of Discord) and the buttons at the bottom (which also don't match). I think it should be more in line with code blocks and the standard Discord interface.
![image](https://user-images.githubusercontent.com/43753131/79438661-1cba7f00-7fd4-11ea-8e52-26d9f629a3bc.png)
![image](https://user-images.githubusercontent.com/43753131/79438698-2cd25e80-7fd4-11ea-8dc5-80ba3cda7289.png)

**Comment by rauenzi** [comment]
The look has already been updated in the rewrite. This is not a straightforward port to master so I will not be adding this in right now.

![wbHcqhvRqF](https://user-images.githubusercontent.com/40003440/65803521-c7f50b00-e14c-11e9-9ff2-dd3e9f954a6f.gif)
