### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by purowolf** [rauenzi/BetterDiscordApp#336]
**Describe the Bug**
i have a issue when i try to install the better discord 
the check box is missing so i cant click to install the bteer discord

**To Reproduce**
follow as the step by step 
**Expected Behavior**
the better discord call me to update it so yeah i do it  

**Screenshots**
[https://media.discordapp.net/attachments/699077361257283658/700628320068435978/msi.PNG?width=1005&height=565](url)

**Discord Version**
the newst verison 

**Additional Context**
i use the new windows update 1909

**Comment by TobiasSN** [comment]
You selected the option to repair BetterDiscord, not the one to install it.

**Comment by rauenzi** [comment]
Please try the new installer, you had DPI issues which were fixed in the latest version.
