### ISSUE TITLE
[Feature] Button/Argument to launch Vanilla Discord

### ISSUE THREAD

**Issue by NeloBlivion** [rauenzi/BetterDiscordApp#337]
**Is your feature request related to a problem? Please describe.**
At most minor lag issues, but otherwise just a QoL feature.

**Describe the feature you'd like**
It would be great if there was a button in settings or a launch argument that would allow you to launch Vanilla Discord while having BetterDiscord installed.

Alternatively, a button/argument that launches BetterDiscord without plugins/themes.

**Comment by rauenzi** [comment]
Can I ask why?

**Comment by NeloBlivion** [comment]
I love BD, but sometimes I kinda wanna use it without plugins, and without having to switch clients entirely to accomplish that. Primarily, There are some events in which this is necessary to get rid of the slight extra lag that comes with the combination of plugins I use (and on some occasions this lag grows exponentially to the point of reset) - one use case that i've found necessary in recent is faster moderation in the event of raiders/spammers in the server. 

I understand that this feature request isn't the most important for a lot of people (as i'd expect most aren't the most heavy plugin users), however i'd certainly find extended use in it.

**Comment by rauenzi** [comment]
Hmm... let me think on it... But in the meantime you should be able to use ToggleYourStuff to help out with this. It should allow you to disable all plugins with a keyboard combo say `ctrl`+`d`. So then relaunching with none would be `ctrl`+`d` then `ctrl`+`r`.

**Comment by NeloBlivion** [comment]
Thanks for your consideration and advice!

**Comment by rauenzi** [comment]
If a command line argument was used, what would prefer it to be? `--no-betterdiscord`? `--no-bd`? `--vanilla`?

**Comment by NeloBlivion** [comment]
`--vanilla` seems pretty straightforward and to the point.

**Comment by rauenzi** [comment]
`--vanilla` flag will be respected in the next update
