### ISSUE TITLE
DiscordBD Not launching with DNS blocker

### ISSUE THREAD

**Issue by Xiseous** [rauenzi/BetterDiscordApp#339]
If you are using PiHole or any other type of DNS blocker, whitelist the domain "cdn.jsdelivr.net" this will allow BD to inject into discord.

Seems that a new gravity update to the lists has added this domain as a cookie collector or something

**Discord Version**
Stable, Canary, PTB

**Comment by rauenzi** [comment]
What would you like me to do? I cannot add a whitelist to other persons DNS settings.
