### ISSUE TITLE
Krappa not working

### ISSUE THREAD

**Issue by kevinkrs** [rauenzi/BetterDiscordApp#34]
When you type Krappa in the chat, the emoji seems to refer to a dead link. When you type Kappa twice it will show the icon properly. Is there any fix for this?

**Comment by Modder4869** [comment]
Kappa or Krappa , Kapp also `Krappa:ffz`

**Comment by kevinkrs** [comment]
Kappa works fine, only Krappa is broken. 

2x times Krappa and the second Krappa will work correctly for some reason.

**Comment by Modder4869** [comment]
yea i can reproduce for some reason second emote is getting loaded from ffz (not broken) but mainly loads from bttv (broken) , anyway you can just use `Krappa:ffz` and it will load it from ffz instead of bttv 🤷‍♀️
