### ISSUE TITLE
[Feature] Plugin load priority

### ISSUE THREAD

**Issue by Xenorio** [rauenzi/BetterDiscordApp#340]
**Is your feature request related to a problem? Please describe.**
In some cases, the order plugins are loaded in breaks them.

**Describe the feature you'd like**
A good way of solving this would be an option in the plugin settings to choose the order. For example, grouping the plugins into high, medium, and low priority. By default, every plugin would be on medium priority and everything would load like always, but if the load order messes up something, you would be able to put the conflicting plugins into high or low priority, which would be loaded first or last respectively. It would probably be best to put a dropdown list next to the load/unload toggle switch in the plugin settings that allows you to choose the priority.

**Comment by williamjcm** [comment]
IIRC, the plugins are loaded in the order of their filenames.

What you could do in the meantime is rename the files, but I think it would break plugin updates.

**Comment by Xenorio** [comment]
oh, well, i did not know that. gonna try that out to see if that fixes the problem i'm personally having. still, quite a dirty workaround.

**Comment by rauenzi** [comment]
What plugins are having issues like that? This should not be the case.

**Comment by Xenorio** [comment]
for example, if ["ServerFolders" by DevilBro](https://github.com/mwittrien/BetterDiscordAddons/tree/master/Plugins/ServerFolders) loads after ["Game Activity Toggle" by Egrodo](https://github.com/Egrodo/DiscordPlugins), the button that GAT adds gets removed and only re-appears after manually reloading the plugin. Sure, the plugin devs could fix that themselves, but having configurable priority would be a catch-all solution for everything.

**Comment by rauenzi** [comment]
There is a bug with Game Activity Toggle where it doesn't add the button. The dev is working on a fix, it is not a bug exclusive to ServerFolders. GAT should load before ServerFolders anyways, just depends on when the code written by the plugin dev decides to execute, that is not something that BD can control.

I don't really intend to add loading priority, that's an unnecessarily complicated system to add for a very very rare issue.

**Comment by MasicoreLord** [comment]
Plus something like load priority sounds like a band-aid solution.
