### ISSUE TITLE
You can't make Discord fullscreen by dragging the top bar to the top of your screen [Bug]

### ISSUE THREAD

**Issue by BraneVrane** [rauenzi/BetterDiscordApp#341]
**Describe the Bug**

After installing BetterDiscord you can't make the window fullscreen by dragging the top of the Discord window, like you can for instance many browsers, and Discord before installing BetterDiscord. Why I'm frustrated is because if you use two screens and click the button to make your Discord fullscreen it might go to the wrong screen if only a sliver is on the one you don't want.

**Expected Behavior**
Discord is supposed to go fullscreen once you drag the top of it to the top of the screen.

**Screenshots**

![image](https://user-images.githubusercontent.com/64309867/80278151-2b034c00-86f4-11ea-9096-5f5b96cb10ed.png)

![image](https://user-images.githubusercontent.com/64309867/80278156-3787a480-86f4-11ea-90b1-ba50fe15b267.png)

It doesn't do anything as you can see, And it's supposed to go fullscreen

![image](https://user-images.githubusercontent.com/64309867/80278159-3eaeb280-86f4-11ea-9444-3aa8c4427c61.png)

Like this

**Comment by rauenzi** [comment]
This is because you have enabled the transparent window setting. It is a bug with electron and something I cannot fix.
