### ISSUE TITLE
[Bug] Cannot install BD, Ran as admin and put it on desktop

### ISSUE THREAD

**Issue by DJDylanP** [rauenzi/BetterDiscordApp#342]
**Describe the Bug**

Windows will not open the installer even though it's in desktop.
**To Reproduce**

Running installer as admin and trying to download the latest BD
**Expected Behavior**

To be able to download BD
**Screenshots**

![image](https://user-images.githubusercontent.com/48156309/80278683-49674880-86f0-11ea-9f49-f53bc302dc64.png)

**Discord Version**

Stable
**Additional Context**

**Comment by BenxProductionz** [comment]
Same Problem.
Fix: disable Windows Defender SmartScreen for Apps while installation.

**Comment by rauenzi** [comment]
Read above by BenxProductionz.
