### ISSUE TITLE
[Bug] [Canary] Custom emojis doesn't load until hover

### ISSUE THREAD

**Issue by fixator10** [rauenzi/BetterDiscordApp#343]
**Describe the Bug**
Custom emojis in emoji picker doesn't load until hover

**To Reproduce**
1. Install BD on Discord Canary
2. Open emoji selector
3. Only default (unicode) emojis loading properly

**Expected Behavior**
Emojis loading on emoji selector open

**Screenshots**
![gif](https://moeka.is-a-good-waifu.com/9gs2KdS.gif)

**Discord Version**
Canary 58861 (e350530)
BBD 0.3.4 (65bf2ab)
Host 0.0.264
Injector 0.4.1
Windows 10 64-Bit (10.0.18363)

**Additional Context**
Happens because of class normalization:
```js
Uncaught DOMException: Failed to execute 'remove' on 'DOMTokenList': The token provided ('emojiItemImageLoading-1yEIxx da-emojiItemImageLoading') contains HTML space characters, which are not valid in tokens.
```

**Comment by rauenzi** [comment]
Thanks for reporting, I will patch that.

**Comment by rauenzi** [comment]
Just pushed out a fix!
