### ISSUE TITLE
[Bug] (Minor) Minimize and close animations not playing

### ISSUE THREAD

**Issue by Kitteh6660** [rauenzi/BetterDiscordApp#344]
**Describe the Bug**
A minor bug but if you click on minimize or close, it doesn't play the animation. On vanilla Discord, the animation plays properly.

I tested by uninstalling BandagedBD and the animation works again. But when BandagedBD is installed again, the animation no longer works. I don't have GlassCord.

Just to be sure, I disabled custom themes and cleared custom CSS, but the bug still happens.

**To Reproduce**
Step 1: Make sure BandagedBD is installed.
Step 2: Click on Minimize or Close.
Step 3: Observe that it suddenly disappears without playing the animation. 

**Expected Behavior**
I expected that if I minimize, it would appear as if it's shrinking towards the taskbar like other programs.

**Discord Version**
Stable

**Additional Context**
I'm running Windows 10 so the animations should have played but sadly they don't.

**Comment by rauenzi** [comment]
Check if you have this setting enabled:

![Image](https://i.imgur.com/PbDhMNN.png)

If you do, disable it and fully restart Discord and it should be fine.

**Comment by cloneman** [comment]
There should probably be a message that says "enabling this will disable Aero Snap"
