### ISSUE TITLE
[Bug]Discord crashes when opened

### ISSUE THREAD

**Issue by Lamamoo** [rauenzi/BetterDiscordApp#345]
**Describe the Bug**
Since earlier today I have been experiencing the issue of having discord crash on me. I open the app I have installed onto my PC and immediately it just crashes. I tried to un-install better discord and the problem was fixed, put it on again and boom, it crashed! 

**To Reproduce**
Step 1:Make sure BD is installed
Step 2:Open discord
Step 3:It just crashes

**Expected Behavior**
I expect the app to work. When I open it I expect for everything to load and be able to access my servers and other conversations instead of staring at a crash screen

**Screenshots**
![image](https://user-images.githubusercontent.com/64480745/80496260-a0c81b80-8971-11ea-9c26-ef97cc33331a.png)

**Discord Version**
Stable

**Additional Context**
I didn't have this problem yesterday, and I am almost 80% sure that my discord did not have an update.

**Comment by rauenzi** [comment]
Can you try renaming your plugins folder and restarting Discord? That would eliminate the fault of any plugins.

**Comment by rauenzi** [comment]
This is likely due to an outdated copy of ZeresPluginLibrary. Reopen otherwise.

**Comment by Lamamoo** [comment]
Thanks for the help!
