### ISSUE TITLE
[Bug] Copy Selelctor hides Image Preview options

### ISSUE THREAD

**Issue by radzo73** [rauenzi/BetterDiscordApp#346]
**Describe the Bug**
Right-click options are gone when "Copy Selector" is enabled.

**To Reproduce**
Turn on "Developer Mode" and "Copy Selector", and right-click an image popup.

**Expected Behavior**
Options to copy/save image previews, copy/open links, in addition to Copy Selector.

**Screenshots**

![image](https://user-images.githubusercontent.com/26673668/80513012-68621680-894c-11ea-98e3-e07f62a6f690.png)

**Discord Version**
Stable, Mac OS X 10.11.6

**Comment by rauenzi** [comment]
I can recreate this, but it is low on the priority list.

**Comment by rauenzi** [comment]
This feature has been sunset and will be discontinued in the restructure.
