### ISSUE TITLE
Better discord crashes when opened (round II)[Bug]

### ISSUE THREAD

**Issue by Lamamoo** [rauenzi/BetterDiscordApp#347]
**Describe the Bug**

(The old bug report was closed so I decided to make a new one. Sorry if I am getting a bit annoying!)

I am sorry for being back so soon with the same problem but I tried to fix the issue. My dad who is really good with computers tried to help but we got nowhere. We decided to delete the whole discord folder and install the app once more. But again it crashes when BD is installed. I notice that the themes and plugins still seem to be installed even after deleting the discord folder and uninstalling BD. But I cannot seem to fin where the folders for the themes and plugins are. I tried searching for them by the names of the items they contain but nothing comes up even when I try to search from This PC. The only way I know how to open them is through discord, but like said it crashes and so I cannot access them. I have installed a newer version of the plugin library that might be causing the problem but I can't replace the old one because I don't know where the folders are as said

**To Reproduce**
Step one)Install BD
Step two)Open discord
Step three)It crashes

**Expected Behaviour**
I expect the app to work. When I open it I expect for everything to load and be able to access my servers and other conversations instead of staring at a crash screen

**Screenshots**
![image](https://user-images.githubusercontent.com/64480745/80866821-8f488180-8c99-11ea-873a-8b8cc9ad2e5d.png)

**Discord Version**
Stable

**Additional Context**
Again I am sorry for making another report and probably being a dumbo by not knowing where the folders are!

**Comment by rauenzi** [comment]
They are installed in `%appdata%\BetterDiscord`. You should see both a plugins and themes folder there. Based on your crash it would appear to be an outdated version of ZeresPluginLibrary. Once you navigate to the plugins folder just delete 0PluginLibrary.plugin.js and restart Discord

**Comment by AustinGitHub** [comment]
Better discord is still crashing!!

**Comment by DeQuex** [comment]
BD Crashes when writing on dm's, example: if I press Shift + Enter crashes

**Comment by emretebir** [comment]
![resim](https://user-images.githubusercontent.com/59513632/114853858-e41ed280-9dec-11eb-88bc-6ad34429ee9a.png)

**Comment by emretebir** [comment]
![resim](https://user-images.githubusercontent.com/59513632/114854060-192b2500-9ded-11eb-9450-5be19bc51831.png)
BetterDiscord Crashed. I reinstalled.

**Comment by SuperGateway** [comment]
> ![resim](https://user-images.githubusercontent.com/59513632/114854060-192b2500-9ded-11eb-9450-5be19bc51831.png)
> BetterDiscord Crashed. I reinstalled.

Similar to him i found that this crash is happening after the rewrite
should this have a new issue thread?

**Comment by Tesco0** [comment]
Yeah I have the same thing

**Comment by Max-Power-7** [comment]
I have same error!!

**Comment by Luigi00601** [comment]
I'm having the same difficulties.

**Comment by Karrot40** [comment]
Solved! well for me at least, win + r and enter %appdata%\BetterDiscord then go to the plugins folder and delete everything, same with the themes folder. then do not repair bd, install it and it should fix the issue

**Comment by yeou123** [comment]
![화면 캡처 2021-04-27 140705](https://user-images.githubusercontent.com/82258922/116188156-dc9ee800-a761-11eb-9a12-5375c8a05473.png)

**Comment by AkshathRaghav** [comment]
rauenzi's solution works for me, something to do with the zeres lib and gifsaver ig (idk these were the only two I had)
I went and removed all the plugins and themes - appdata -> betterdiscord -> plugins, then installed BD again. Works normally now

**Comment by LoneDev6** [comment]
@rauenzi 
Is there any log file to read what the hell is the cause of the crash instead of a generic message?
Thanks a lot

**Comment by canshadyy** [comment]
0PluginLibrary.plugin.messages do not appear when I delete the JS file and restart discord

**Comment by Ella-hyper** [comment]
> Solved! well for me at least, win + r and enter %appdata%\BetterDiscord then go to the plugins folder and delete everything, same with the themes folder. then do not repair bd, install it and it should fix the issue

Thank you so much for the advise! It works for me aswell!

**Comment by SteadyStatus21** [comment]
I deleted everything, repaired and reinstalled bd and nothing fixed itself :(

**Comment by zyugyzarc** [comment]
any updates?
getting the same error on discord stable, ptb, canary and development versions on linux (ubuntu)

**Comment by Hel4gate** [comment]
Hello I found the problem better discord is crashing because of BDFDB Plugin so if you do those steps you can fix it 
Step One = Go to your Betterdiscord Plugin Folder (C:\Users\YourFolderName\AppData\Roaming\BetterDiscord\plugins)
Step Two = Deleted the Plugin JS of 0BDFDB.js Including CSS and Json Files
Step Three = Open your Discord and it asking Automatic BDFDB Plugin Installation Click Download Now
Then You're Done

**Comment by mimsy55** [comment]
> 
> 
> Hello I found the problem better discord is crashing because of 0BDFDB plugin so if you do those steps you can fix it
> Step one = go to your betterdiscord plugin folder (c:\users\yourfoldername\appdata\roaming\betterdiscord\plugins)
> Step two = delete the plugin js of 0BDFDB.JS including CSS and JSON files
> Step three = open your discord and it asking automatic 0BDFDB plugin installation click download now
> Then you're done
> Better discord mostly crashing because of plugins load if you installed more it costs more processor and ram basically we all know discord is eating processor so if you installed better discord in it its consume more.

thanks fixed the issue right up 1 time thing right?

**Comment by imgustavo** [comment]
> Hello I found the problem better discord is crashing because of 0BDFDB plugin so if you do those steps you can fix it
> Step one = go to your betterdiscord plugin folder (c:\users\yourfoldername\appdata\roaming\betterdiscord\plugins)
> Step two = delete the plugin js of 0BDFDB.JS including CSS and JSON files
> Step three = open your discord and it asking automatic 0BDFDB plugin installation click download now
> Then you're done
> Better discord mostly crashing because of plugins load if you installed more it costs more processor and ram basically we all know discord is eating processor so if you installed better discord in it its consume more.

@Hel4gate OMG tysm!!!!!!!!!! <3 <3 i was around 1 month with this bug and couldn't log in into my discord but with your post I fixed the problem. Do you have any idea what was that plugin? I installed so many that I cant remember which one was that one 🤔

**Comment by Hel4gate** [comment]
@imgustavo  I mostly got 0BDFDB.JS plugin error but if you getting other errors like that u can mention plugins you use then I can figure it out, for example, I'm using 15 plugins including goosemod even I have 2 core laptops so I always take a backup of those plugins. but the problem is they didn't show us which plugin has the problem so I deleting all plugins and replace the backup with my saved JSON file but if u mention your plugins I can see we both using the same things or not be honest those days I got account creation date plugin error but today better discord update fixed that we getting errors mostly cause of better discord module didn't develop it correctly that's why.

**Comment by imgustavo** [comment]
> @imgustavo I mostly got 0BDFDB.JS plugin error but if you getting other errors like that u can mention plugins you use then I can figure it out, for example, I'm using 15 plugins including goosemod even I have 2 core laptops so I always take a backup of those plugins. but the problem is they didn't show us which plugin has the problem so I deleting all plugins and replace the backup with my saved JSON file but if u mention your plugins I can see we both using the same things or not be honest those days I got account creation date plugin error but today better discord update fixed that we getting errors mostly cause of better discord module didn't develop it correctly that's why.

these are my plugins: [](https://i.imgur.com/Ee6QZXs.png)

**Comment by rauenzi** [comment]
This is an old issue, please don't hijack them for new issues.
