### ISSUE TITLE
[Bug] My name is shown as poop

### ISSUE THREAD

**Issue by JannikEmmerich** [rauenzi/BetterDiscordApp#348]
**Describe the Bug**
If someone types my name ("Jannik"), it is shown as poop.

**To Reproduce**
Type "Jannik" in any chat and press enter.

**Expected Behavior**
Don't show poop, show "Jannik" instead.

**Screenshots**
![image](https://user-images.githubusercontent.com/22866859/80895147-f5f18d80-8ce1-11ea-911d-c45df657d769.png)
![image](https://user-images.githubusercontent.com/22866859/80895154-fdb13200-8ce1-11ea-91e7-2bb3e881e040.png)

**Discord Version**
Stable

**Comment by rauenzi** [comment]
This is due to an emote, you can blacklist it using one of many plugins.

**Comment by JannikEmmerich** [comment]
I'm not using your software, but it's very confusing for others using Better Discord when my name appears as poop. So it would be very satisfying if you could fix that.

**Comment by rauenzi** [comment]
I have added your name to the global blacklist now
