### ISSUE TITLE
[Feature] Option to enable element picker shortcut globally, instead just when the inspector is open

### ISSUE THREAD

**Issue by Two-Tone** [rauenzi/BetterDiscordApp#349]
Currently the element picker shortcut can not be used unless the inspector is open.  However in Chrome, Firefox, etc the shortcut is enabled globally.  It'd be nice if the same could be true in Discord.

**Comment by rauenzi** [comment]
I'm not sure if this is possible within Electron, but I will look into it when I have much free time.

**Comment by rauenzi** [comment]
This is possible and will be included in the next update

**Comment by Two-Tone** [comment]
NICE
