### ISSUE TITLE
[Feature] Web Browser support

### ISSUE THREAD

**Issue by strikersh** [rauenzi/BetterDiscordApp#350]
I don't use the desktop app anymore (since most of the feature does work with chromium such has livestreaming), I was wondering if it was possible to use betterdiscord with a web browser with userscripts or an extension.

**Comment by rauenzi** [comment]
That is not possible, sorry.

**Comment by nonetrix** [comment]
Hmm interesting why so? From my understanding would be pretty easy since the App is based off the Web version
