### ISSUE TITLE
[Bug] Canary - infinite loading

### ISSUE THREAD

**Issue by fixator10** [rauenzi/BetterDiscordApp#351]
**Describe the Bug**
Discord starts, but nothing other than dark background with BD logo is appears

**To Reproduce**
1. Setup latest canary
2. Setup BBD
3. Run canary

**Expected Behavior**
Discord loads

**Screenshots**
![img](https://moeka.is-a-good-waifu.com/5YMjNje.png)

**Discord Version**
Canary

**Additional Context**
`Uncaught TypeError: a.default.getDiscordUtils(...).inputGetIdleMilliseconds is not a function`

**Comment by rauenzi** [comment]
The error you posted is not coming from BD. I would try uninstalling BD and see if the issue persists.

**Comment by fixator10** [comment]
Well.. Discord broken Canary.
