### ISSUE TITLE
Fatal Javascript error, tried repairing using install client but it still doesn't work?

### ISSUE THREAD

**Issue by ringoando** [rauenzi/BetterDiscordApp#354]
Every time I install BandagedBD it gives me a fatal js error whenever I open Discord. I've tried repairing it, uninstalling + reinstalling Discord, and it still doesn't work. How do I fix this?
![jserror](https://user-images.githubusercontent.com/65133022/81508814-55f9bc80-92fe-11ea-8e01-13f07c033ee1.jpg)

**Comment by MasicoreLord** [comment]
Remove the `bdstorage.json` file from `%appdata%\BetterDiscord`
Hope that helps, @ringoando
Not sure why that file gets corrupted sometimes, but that's the work-around.
