### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by LaloLawua123** [rauenzi/BetterDiscordApp#355]
**the Bug**
It Doesnt Works, I Opened the Installer as Administrator Outside The Downloads Carpets and it doesnt opens

**To Reproduce**
Open it as Administrator Outside or In The Download Carpet

**Expected Behavior**
Probably a New Discord Block?

**Discord Version**
Stable 59984

**Additional Context**
The Problem is in Windows Version
The Version launched at 16 Oct 2018 Can Be Launched but Doesnt Works on Discord

**Comment by rauenzi** [comment]
I don't understand the issue. You also seem to be citing a version from two years go...

**Comment by LaloLawua123** [comment]
The Issue Is... I Installed the last BetterDiscord Injector but it doesnt
Open, i tried launching it as administrator outside the Downloads Carpet,
but nothing Happened

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Libre
de virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by rauenzi** [comment]
I think there is a bit of a language barrier occurring. But I also think you might be using something very outdated. If you cannot provide versions, screenshots or any other definitive piece of information, then I cannot really help.

**Comment by LaloLawua123** [comment]
![image](https://user-images.githubusercontent.com/65257185/81765661-6d71aa80-94a2-11ea-868d-9d615616391b.png)
i Downloaded The Windows Installer of That Version, i opened it as administrator outside the downloads carpet, but the installer didnt opened, ill try the manual installation

**Comment by LaloLawua123** [comment]
the manual installation works!
