### ISSUE TITLE
[Bug] Emote menu broken

### ISSUE THREAD

**Issue by ydryer** [rauenzi/BetterDiscordApp#357]
The custom emojis through BD no longer show up in the emoji menu, nor do they work when manually typed in like :insert-emoji-here:

**Comment by rauenzi** [comment]
The custom _emote_ (not emoji) picker is broken yes. The emotes themselves still work. They would be typed in like `Kappa` and  not `:Kappa:`

**Comment by ydryer** [comment]
Ah I see, thanks for the info

**Comment by Keridos** [comment]
Pleasefix
