### ISSUE TITLE
[Feature] Installer script for Linux

### ISSUE THREAD

**Issue by utherbone** [rauenzi/BetterDiscordApp#358]
I really like BetterDiscord, and having the chance to customize it to my liking is exceptional, I recently migrated to linux and maybe I can make the script but I have to know how discord files are modified, the Windows discord binaries are different from Linux . at the moment I send this order, I am comparing the original discord files and after installing BetterDiscord.

**Comment by rauenzi** [comment]
This exists as stated on the README https://github.com/rauenzi/BetterDiscordApp#linux

**Comment by utherbone** [comment]
Sorry, thanks!
