### ISSUE TITLE
[Bug] Right-click menus have no new entries

### ISSUE THREAD

**Issue by Xetaxheb** [rauenzi/BetterDiscordApp#359]
**Describe the Bug**

Seems like all custom menus/entries under any right-click popup aren't working.

**To Reproduce**

Install bandagedbd, install a plugin that would add something, no entry shows up. (Not in right clicking server icons, voice/text channels, messages, users, nowhere)

**Expected Behavior**

Plugins/etc should work normally. 

**Discord Version**

Stable 60482 (ea86b39)
BBD 0.3.4 (731132c)
Host 0.0.306
Injector 0.4.1
Windows Server 2008 R2 / 7 64-Bit (6.1.7601)

**Additional Context**

It seems to have just broken in the last hour or few.
Could be the ZeresPluginLibrary v1.2.17 update? Or could be discord pushing a stealth update.

**Comment by rauenzi** [comment]
This is an issue with the plugins themselves, not BBD.
