### ISSUE TITLE
Minimal mode Issues

### ISSUE THREAD

**Issue by MrBlazzar** [rauenzi/BetterDiscordApp#36]
Apologies for showing more issues but since yesterday I've had a few more issues with minimal mod recently.

Starting yesterday after I restarted discord my channel icons were back to the normal size even when in minimal mode a picture of them with minimal mod on:
![discord_2018-08-02_07-22-44](https://user-images.githubusercontent.com/5840012/43580872-e41ac596-9624-11e8-80a9-5c94782cd038.png)

Also something I noticed is that before in minimal mod the messages were closer to the left and didn't have the space between the left side of the screen and the start of the messages. Not a huge thing but figured I'd mention it anyways.

Thanks for your time.

**Comment by williamjcm** [comment]
I recommend the use of [this theme.](https://github.com/Juicysteak117/MinimalImprovement)

It previously required the use of minimal mode, but not anymore.

**Comment by MrBlazzar** [comment]
Thanks for the recommendation but I made this mainly due to the fact these features use to be part of minimal mod before the recent updates so I figured I'd point them out.

**Comment by williamjcm** [comment]
Of course. But in the meantime, the theme will be a good substitute.

**Comment by rauenzi** [comment]
Minimal mode has been updated to accommodate the discord changes in guild list
