### ISSUE TITLE
BetterDiscord doesn't launch

### ISSUE THREAD

**Issue by 6kz** [rauenzi/BetterDiscordApp#360]
**Describe the Bug**
When I install BetterDiscord and click 'Exit' it doesn't install as predicted 

**To Reproduce**
Install - Exit and it doesn't open

**Expected Behavior**
I expected to open discord.

**Screenshots**
Can't explain by screenshots

**Discord Version**
Stable

**Comment by 6kz** [comment]
I need some help, I've tried everything.

**Comment by rauenzi** [comment]
Can you join the support servers? It would be easier to help you there.

**Comment by flexflower** [comment]
hello, i have the same problem and i cant join the server, can you resend an invite?
