### ISSUE TITLE
[Bug] Themes is not loaded, BD settings menu disapear

### ISSUE THREAD

**Issue by Eragonfr** [rauenzi/BetterDiscordApp#361]
**Describe the Bug**
The BD settings menu is not shown in the parameters, and no css theme is loaded but the plugins are loaded

**To Reproduce**
I don't know, I think discord has updated without telling it

**Expected Behavior**
Themes should be loaded and the BD menu is shown

**Screenshots**
![](https://transfer.sh/12Idap/{5086}.png)

**Discord Version**
Discord Stable 60935 (db877b4)
Host 0.0.10
Linux

**Comment by rauenzi** [comment]
Please try reinstalling and let me know the result. If it fails, please check the console for errors in Discord (ctrl+shift+i)

**Comment by Eragonfr** [comment]
I'v reinstalled using `betterdiscordctl update` and `betterdiscordctl reinstall` But it's still not working.

Screenshoots of the console. 
![image](https://user-images.githubusercontent.com/28783835/83943252-daa30200-a7fa-11ea-8660-5af0c264fefe.png)
Others errors are related to glitchy code inside `Citador` and `1lib_discord_internal`

**Comment by Rowmaster** [comment]
Same here. Updated to Stable Build 62028, tried multiple uninstalls and reinstalls.

something about the MIME type

![error](https://user-images.githubusercontent.com/63493424/85336543-c32b7080-b4ac-11ea-8090-7df9d68dba92.PNG)

**Comment by rauenzi** [comment]
@Eragonfr That console screenshot tells me that BD itself is working fine, your plugins are the ones causing the issues.

@Rowmaster that was an issue with github's service being down.

**Comment by Eragonfr** [comment]
So… the bug don't appear in my plugins, even if I move the plugin folder I don't get the menu back.

I'v reinstalled, updated, reinstalled betterdiscord many times. I can try with a "clean install" of betterdiscord, removing every betterdiscord related folders.
