### ISSUE TITLE
[Bug] Discord window doesn't Aero snap with enabled transparency

### ISSUE THREAD

**Issue by TheChilliPL** [rauenzi/BetterDiscordApp#362]
**Describe the Bug**
When the *Enable transparency* option is enabled, the Discord window doesn't snap to the edges of the screen.

**To Reproduce**
1. Settings → Bandaged BD → Settings → Window Preferences → Enable Transparency
2. Restart Discord
3. Try to snap the window with Aero snap—either by dragging Discord to an edge of the screen or by pressing `Win`+`←` or `Win`+`→`

**Expected Behavior**
Discord window should snap to the edge it's dragged to (or to the edge corresponding the arrow pressed with the `Win` key), taking half of the screen.

**Screenshots**
N/A

**Discord Version**
PTB 61002, but I've seen it happen on some stable versions, possibly Canary too.

**Additional Context**
Seems to be related somehow with #344.

**Comment by rauenzi** [comment]
This is an issue with electron/chromium and not something I can fix, sorry. https://bugs.chromium.org/p/chromium/issues/detail?id=854601

**Comment by ThaDaVos** [comment]
The issue still exists sadly - just letting people know when they run into the problem

**Comment by senposage** [comment]
this is still broken or has recently regressed disabling transparency restores the snap

**Comment by ingenarel** [comment]
i'm having this issue too...
