### ISSUE TITLE
[Bug] BBD not displaying his options when installed on Discord Canary latest version (also causing themes and plugins to not working anymore too)

### ISSUE THREAD

**Issue by Kimaul37** [rauenzi/BetterDiscordApp#363]
**Describe the Bug**
BBD is no longer working correctly with latest Discord Canary version installed as the options for BBD are not displayed anymore with it but it's still installed because we can see the version informations on the firsr screenshot and the 1.0.4 installer doesn't make it appear back (tried 2 times). Themes and plugins installed are not working anymore too.

**To Reproduce**
Launch Discord Canary in the latest version
Install Bandaged BD installer latest version
Install the Bandaged BD integration to Discord Canary latest version
Open the parameters section to see there's no option for Bandaged BD.
(Optional) Install a theme and/or a plugin to see it's not working.

**Expected Behavior**
Have the options for BBD in the parameters being displayed and have the themes and plugins working with the latest version of Discord Canary.

**Screenshots**
![image](https://user-images.githubusercontent.com/28737149/83903526-995d1480-a75e-11ea-87b3-27ca0d02e3d9.png)
![image](https://user-images.githubusercontent.com/28737149/83903669-d5907500-a75e-11ea-982e-150fe2da43fb.png)

**Discord Version**
Canary 61151 (d9b3bbf)
Host 0.0.264
Windows 10 64-Bit (10.0.19635)

**Additional Context**
Nothing more needed.

**Comment by rauenzi** [comment]
I just pushed a fix for Canary, please reinstall and give it a try!

**Comment by Kimaul37** [comment]
It's fixed ! Thank you !
