### ISSUE TITLE
Just answer and that's all

### ISSUE THREAD

**Issue by HideakiAtsuyo** [rauenzi/BetterDiscordApp#365]
https://github.com/rauenzi/BetterDiscordApp/blob/master/js/main.js
https://github.com/rauenzi/BetterDiscordApp/blob/master/js/main.min.js
https://github.com/rauenzi/BetterDiscordApp/blob/master/src/modules/v2.js

why the token is used?

**Comment by rauenzi** [comment]
Token is not used, that adds protections against potential malicious plugins that was to access your token.

You can see here <https://github.com/rauenzi/BetterDiscordApp/blob/master/src/modules/v2.js#L23> that it causes calls to `getToken` to return `undefined` instead of the user's actual token.
