### ISSUE TITLE
[Bug]no betterdiscord section in settings (mac)

### ISSUE THREAD

**Issue by flexflower** [rauenzi/BetterDiscordApp#367]
**Describe the Bug**
i installed betterdiscord, opened it, discord named bandagedBD opens (and works), but theres no bandagedbd section in the settings. 

**To Reproduce**
open bandagedBD

**Expected Behavior**
the bandagedBD section in settings

**Screenshots**
[https://imgur.com/a/E0TuH4m](url) (yes its in french)

**Discord Version**
stable

**Comment by rauenzi** [comment]
Reinstall, there were prior issues with the service.
