### ISSUE TITLE
[Bug] Fatal javascript error: cannot find module '/home/browser-window.js'

### ISSUE THREAD

**Issue by BRFNGRNBWS** [rauenzi/BetterDiscordApp#369]
I just ran betterdiscordctl install, then this window popped up when I try to run discord: 
![image](https://user-images.githubusercontent.com/11679863/84830265-fd44d000-afdd-11ea-9aee-6021565ad8f6.png)

I reinstalled discord and the same thing happened. I'm on opensuse tumbleweed btw

**Comment by rauenzi** [comment]
I would recommend consulting the linux installer team over at https://i.imgur.com/mT9w3qd.png it seems you are not the only one with a similar issue on linux. If they determine there is a BD compatibility issue, they will reach out to me with it.
