### ISSUE TITLE
[Bug] injector is missing despite existing

### ISSUE THREAD

**Issue by platyple** [rauenzi/BetterDiscordApp#370]
**Describe the Bug**
after whatever update happened yesterday my installation too, stopped working. however, when starting Discord (flatpak) after reinstalling BD through betterdiscordctl, i get a pop-up containing the first screenshot before the main window appears.  
injector is where it should be and looks exactly like it should, plus betterdiscordctl didn't update since may so it's probably a BD thing.

**To Reproduce**
install discord on Fedora 32 via flatpak, install BD via `betterdiscordctl install --discord /var/lib/flatpak/app/com.discordapp.Discord/current/active/files --modules ~/.var/app/com.discordapp.Discord/config/discord/0.0.10/modules`

**Expected Behavior**
discord should start normally along with BD

**Screenshots**
[https://i.imgur.com/EeJdR7Z.png](url)
[https://i.imgur.com/mT9w3qd.png](url)
[https://i.imgur.com/pRDex47.png](url)

**Discord Version**
stable (via flatpak)

**Additional Context**
adding `--flatpak` to the command line causes discord to launch normally but without BD

**Comment by rauenzi** [comment]
I would recommend opening the issue over with the linux installer team, they'd be better at helping you with this as BD hasn't adjusted the injection procedure or structure in a long time.  https://github.com/bb010g/betterdiscordctl

**Comment by ObserverOfTime** [comment]
When you use the `--discord` & `--modules` flags for flatpak you need to also add the `--copy` flag.
