### ISSUE TITLE
Attempting to connect to discordservers.com causes window that refuses to close

### ISSUE THREAD

**Issue by Jimmytbane** [rauenzi/BetterDiscordApp#372]
Instead of closing properly, the window that the action in the title causes does not close no matter how many times I try. I have to close it thru the taskbar on Windows

Attempt to connect to discordservers.com and try to close the window with the X in the window itself.

I would expect it to close if possible.

Discord Version: Stable

I had no plugins when I got the bug

**Comment by rauenzi** [comment]
Should be fixed now.
