### ISSUE TITLE
Custom CSS Editor has a bug that causes the editing field to become unusable.

### ISSUE THREAD

**Issue by Jimmytbane** [rauenzi/BetterDiscordApp#373]
When I use the Custom CSS Editor, I click on detach, and then on detach again, and the app bugs and the field becomes unusable.

1. Go into Custom CSS Editor
2. Press detach
3. Press attach
4. Profit(Or not?)

Editor should detach and reattach properly without bugging out.

There are two possible appearances for one error here. When the field has text, the text becomes morphed and shrunk vertically.
Otherwise, the field just disappears.

Discord Version: Stable

**Comment by rauenzi** [comment]
This has been a bug for as long as BD has existed. This won't be an issue in the rewrite, but I won't spend the time to debug current stable of this issue. Will leave this open until the rewrite is released.

**Comment by rauenzi** [comment]
Please use the new installers: https://github.com/BetterDiscord/Installer
