### ISSUE TITLE
Discord Bandage / BetterDiscordApp

### ISSUE THREAD

**Issue by CocainCompany** [rauenzi/BetterDiscordApp#374]
**Describe the Bug**

Starting installation for Discord
Killing Discord Processes
Downloading BandagedBD package
Using channel: https://github.com/rauenzi/BetterDiscordApp/archive/injector.zip
Downloading to: D:\Desktop\Discord\app-0.0.306\\resources\BetterDiscord.zip
Download error: Невозможно соединиться с удаленным сервером
Download seems to have failed, will try once more.
Downloading BandagedBD package
Using channel: https://github.com/rauenzi/BetterDiscordApp/archive/injector.zip
Downloading to: D:\Desktop\Discord\app-0.0.306\\resources\BetterDiscord.zip
Download error: Невозможно соединиться с удаленным сервером

Все уже пробовал. Но все равно не работает. Помогите уже плез

**To Reproduce**

Надеюсь что заработает

**Expected Behavior**

**Comment by z3n0x07** [comment]
Did you solve this problem?
