### ISSUE TITLE
[Bug] Minimal Mode is completely broken, and it's a shame to have to turn it off as it was awesome to manage my many servers.

### ISSUE THREAD

**Issue by mrfuzzyball** [rauenzi/BetterDiscordApp#378]
Images are unaligned with where the servers can be accessed, full images not shown on screen

**To Reproduce**
Turn on Minimal Mode

**Expected Behavior**
Images to be aligned with the box where I can use my mouse to access them

**Screenshots**

**Discord Version**
Stable

**Additional Context**

**Comment by rauenzi** [comment]
This is still broken but low priority

**Comment by mrfuzzyball** [comment]
> 
> 
> This is still broken but low priority

Understood, and makes sense. Seems like a lot of aspects have been screwed over. Hope it gets in working order soon.

**Comment by Tropix126** [comment]
Has been fixed on the development branch. See: #490

**Comment by rauenzi** [comment]
This is finally live
