### ISSUE TITLE
[Bug] Doesn't install on macOS 10.15.4

### ISSUE THREAD

**Issue by jkrosado** [rauenzi/BetterDiscordApp#379]
**Describe the Bug**
BetterDiscord does not install, instead it prompts you to install Discord, despite it being installed.

**To Reproduce**
1. Use macOS 10.15
2. Attempt to install BandagedBD (control-click, open, open)

**Expected Behavior**
It should begin the setup process for BandagedBD

**Screenshots**
![image](https://user-images.githubusercontent.com/26725277/86544013-9a19cf80-bef1-11ea-8479-bf484a3993d3.png)

**Discord Version**
macOS, Stable

**Comment by qwerasd205** [comment]
Where do you have Discord.app installed? The installer checks for it in `/Applications/` and `~/Applications/`.
