### ISSUE TITLE
[Question] Not seeing much activity on BDv2 (Github)?

### ISSUE THREAD

**Issue by LuaTenshi** [rauenzi/BetterDiscordApp#38]
This build of BetterDiscord is much cleaner and better then the standard build. It even survived through a Discord update! 

However I'm worried because according to https://github.com/Jiiks/BetterDiscordApp/tree/v2 this branch hasn't really been worked on in a while. So what's up? (Sorry for posting this as an issue, wasn't sure how else to contact you.)

P.S. I hope we continue to see updates here as this really is much better then the standard BetterDiscord package.

**Comment by rauenzi** [comment]
If you visit the repo on the master branch you'll see that we moved V2 development to an organization (JsSucks). I believe it is at the very top of the readme.

As for contacting me my discord username is plastered all over my GitHub and inside BBD. As are links to my support server.

**Comment by LuaTenshi** [comment]
Actually the V2 readme still says that all development is happening there
so, may want to change that. Also I must've missed your Discord contact
links. Sorry. But thank you for the response that was almost too fast.

**Comment by rauenzi** [comment]
I did specify the master branch of that repo though not the V2 branch which should really just be deleted.

**Comment by LuaTenshi** [comment]
Yeah it really should it would be way less confusing. Then I wouldn't have to ask stupid questions at 4 AM.

**Comment by rauenzi** [comment]
It's not like the default branch tells you to go there for active development though, so that part is kinda in you lol
