### ISSUE TITLE
[Bug] Min&Max button on top bar doesn't work correctly

### ISSUE THREAD

**Issue by mkcoldwolf** [rauenzi/BetterDiscordApp#380]
**Describe the Bug**
Min&Max button on the top bar now only works for maximizing discord but not minimizing back to the original size
Only installed BD have this behavior

**To Reproduce**
1. install BD
2. click the min&max button on top bar (upper right corner)

**Expected Behavior**
It should size to the max and size back to the original size when clicked again

**Screenshots**
![image](https://user-images.githubusercontent.com/32544898/86967283-0409d180-c19d-11ea-8423-e7586f35cde9.png)
this little cutie here

**Discord Version**
Stable, PTB Tested

**Additional Context**

**Comment by rauenzi** [comment]
Disable window transparency in settings and restart Discord.

**Comment by mkcoldwolf** [comment]
ok thanks, but im wondering is this supposed to not work when window transparency is enabled? @rauenzi

**Comment by kotx** [comment]
@rauenzi @mkcoldwolf Similar problem here. Window is still resizable after clicking the maximize button. I am unable to maximize the window with [AltDrag](https://stefansundin.github.io/altdrag/). Why/how is this tied to window transparency?

**Comment by kotx** [comment]
Also: this issue can presumably be fixed, why was this closed?

**Comment by rauenzi** [comment]
It's an issue with [Electron](https://github.com/electron/electron) itself, enabling transparency in BD settings just sets `transparent` to `true`. There are several open issues regarding transparency in electron including your issue regarding minimizing/maximizing (electron/electron#23275) the window as well as resizing (electron/electron#22915). Both of those will also mention issues with windows aero snap.

So this is something that can be fixed _by Electron_. Once they fix it, Discord would need to then upgrade to that version, and then you would have the fix.
