### ISSUE TITLE
Discord.exe not found [Bug]

### ISSUE THREAD

**Issue by ihaveaissue** [rauenzi/BetterDiscordApp#381]
I have tried moving better discord to different places in my folder, but it does not seem to work every time. It just keeps repeatedly keep saying "discord.exe not found". Please help me on this issue.. 

I download the file. It goes to my downloads folder. I move it to desktop. I click on better discord. I then go to agree then i click the first top button that says download. I also then go to "install to stable" it doesnt let me check it off as it says "discord.exe not found".

Here, I expected to happen was to find "discord.exe" to let me install it. It doesn't let me install.

Stable

Picture:
![issue1](https://user-images.githubusercontent.com/68261489/87379575-983db500-c55e-11ea-8a2c-ad26c628464c.PNG)

**Comment by rauenzi** [comment]
You can manually browse to your Discord installation using Browse. If the installer does not find it, that means you either installed in an unusual location or your environment variables. For both cases you will need to manually browse to your installation.

**Comment by Nick-Kate** [comment]
And which way to indicate?
