### ISSUE TITLE
Discord snap for window 10 users Enchancement

### ISSUE THREAD

**Issue by BarbakedQue21** [rauenzi/BetterDiscordApp#385]
I would like to request a QoL Feature for windows snapping idk if its just me.but for some reason discord doesn't snap to the side of your desktop.

**Comment by l0c4lh057** [comment]
That only is a problem when you have transparency enabled in the BD settings and apparently that is an issue with electron so nothing we can change.

**Comment by BarbakedQue21** [comment]
> That only is a problem when you have transparency enabled in the BD settings and apparently that is an issue with electron so nothing we can change.

ohh I see
