### ISSUE TITLE
relace v1.0.0 does not work[Bug]

### ISSUE THREAD

**Issue by saiv123** [rauenzi/BetterDiscordApp#386]
**Describe the Bug**

I was prompted with a message saying that Bandage had an update so i downloaded the newest release and installed it, and after doing so i was not able to use bandaid seems as if it does not run when i launch discord, i have tried the repair option and have uninstalled and reinstalled compleatly
**To Reproduce**

1. downloaded the latest relase for the bandaid installer
2. installed the newest version
3. saw it did not work so i tried to repair it
4. still does not work
**Expected Behavior**

i expected discord to launch with bandaid as it had done before
**Screenshots**

**Discord Version**

stable
**Additional Context**

**Comment by LuluTheThug** [comment]
Same. Also tried both manual and auto installation methods. Nada.

**Comment by rauenzi** [comment]
Try to fully reinstall BD, the issue has been solved.
