### ISSUE TITLE
[Bug] BD emotes sometimes don't replace text

### ISSUE THREAD

**Issue by shrey150** [rauenzi/BetterDiscordApp#387]
**Describe the Bug**
Sometimes when typing emote names, they won't be replaced by the images; this happens for all emotes in BD, both sent and received. I've found the only way to fix this to Ctrl+R and reload Discord.

**To Reproduce**
Not sure how to reproduce

**Expected Behavior**
Emote text should be replaced by the image itself

**Screenshots**
Self-explanatory

**Discord Version**
Stable 0.0.306

**Additional Context**
None

**Comment by rauenzi** [comment]
I haven't been able to recreate this
