### ISSUE TITLE
Themes sometimes not working

### ISSUE THREAD

**Issue by vykana** [rauenzi/BetterDiscordApp#39]
Random parts of the UI sometimes don't want to be themed, at first it was the left side bar which somehow fixed itself and now after a while its this center part. It just stays the regular grey. This theme worked correctly until yesterday.

Things I've tried:
1. Reinstalling Discord
2. Reinstalling BetterDiscord
3. Disabling all plugins
4. Restarting discord with and without the theme.
5. Tried going into light and dark mode under "Appearance" 
6. Removing and reapplying the theme

![image](https://user-images.githubusercontent.com/42095475/43678167-0e9ad4f6-97dc-11e8-9626-3d53f606d958.png)

**Comment by rauenzi** [comment]
You need to wait for your theme to be updated by the developer, this is not a BD issue.
