### ISSUE TITLE
[Bug] BD themes aren't showing up/ loading up 

### ISSUE THREAD

**Issue by x-jd4-x** [rauenzi/BetterDiscordApp#390]
**Describe the Bug**
Sometimes when I turn on Discord, my themes aren't showing up. 

**To Reproduce**
It's kinda rare to reproduce cause it happens to me once a month

**Expected Behavior**
Normally my theme would load up and that would be it

**Discord Version**
Stable 0.0.036 

**Additional Context**
After I restart discord 2 or 3 times it gets fixed, and themes finally show up in the Themes category (settings) and they actually load up.

**Comment by rauenzi** [comment]
It sounds like a timing issue on your system that I would be unable to fix.
