### ISSUE TITLE
Setting not showing up [Bug]

### ISSUE THREAD

**Issue by Ibirtem** [rauenzi/BetterDiscordApp#392]
BandagedBD settings are gone. Without any reason. Before that, I threw the desired themes into the themes folder and it happened. 
BD icon flashes in the lower right corner. Reinstallation and repair does not help.
![image](https://user-images.githubusercontent.com/54157950/88100530-5091db80-cba5-11ea-9ebb-b3381ed3bb57.png)

**Comment by Chew** [comment]
Might be an issue with latest Canary. This happens to me too

**Comment by rauenzi** [comment]
Posting the announcement from the servers here:

> Latest Discord Canary has broken BBD yet again, however this is a much more complicated and involved fix--it will take time until something is available. For now use Stable or PTB.

**Comment by Chew** [comment]
Thank you, godspeed

**Comment by rauenzi** [comment]
A fix was released, please try reinstalling BBD.

**Comment by Chew** [comment]
Works fine, thanks!

**Comment by Ibirtem** [comment]
Found problem. Yes, this is theme (maybe not). Just random drop into folder with themes and setting gone. Deleting this file is helpful
![image](https://user-images.githubusercontent.com/54157950/88163504-7063e680-cc1b-11ea-9213-c43635035943.png)
