### ISSUE TITLE
Can't open discord if BD is installed [Bug]

### ISSUE THREAD

**Issue by JasmineCA** [rauenzi/BetterDiscordApp#398]
**Describe the Bug**

JavaScript error occurs at starting, before anything shows up. 

**To Reproduce**

Install BD and then start Discord
**Expected Behavior**

Discord starting as usual
**Screenshots**

[![Image](https://i.goopics.net/oDoW7.png)](https://goopics.net/i/oDoW7)
**Discord Version**

Stable
**Additional Context**

OS: Windows 7

**Comment by Strencher** [comment]
try a reinstall of BD

**Comment by JasmineCA** [comment]
Not working. Same bug

**Comment by Strencher** [comment]
did you try to reinstall discord? it looks like your discord version is outdated.

**Comment by JasmineCA** [comment]
Did the trick! I don't know why my discord was outdated, maybe it been a while since i boot on windows. Thanks for your help!
