### ISSUE TITLE
Minimum emote length 3 or modifiable

### ISSUE THREAD

**Issue by Lombra** [rauenzi/BetterDiscordApp#40]
I distinctly remember the emote length minimum limit being changed to 3 at some point to allow for LUL. This does not seem to be the case in this version. Any chance this could be changed, or possibly in the form of an exposed variable that can be changed using a plugin?

**Comment by intrnl** [comment]
I don't remember the emote min to be at 3 chars long, only 4.

**Comment by Lombra** [comment]
Something was changed here, at least. Don't know if that ever had any effect, or where that has gone now, though.
https://github.com/Jiiks/BetterDiscordApp/commit/4fa0825bc7a7e358b89aa1c138a3aea57b924ce2

**Comment by rauenzi** [comment]
That was 2 years ago and had been changed since. 4 character minimum for emotes is intended.
