### ISSUE TITLE
Unsure of what to call this. Typing BOOF in all caps does something weird.

### ISSUE THREAD

**Issue by loof27** [rauenzi/BetterDiscordApp#400]
[This](https://i.imgur.com/dtYzNYO.png) is what happens when you type BOOF in all caps. When you hover over it, a [favorite button](https://i.imgur.com/2DWWT8D.png) appears. I have no idea what this is, it doesn't show up without caps and it doesn't show up in normal discord. Is this a new feature in development that I just happened to stumble upon?  Or what am I looking at.

**Comment by qwerasd205** [comment]
It's an emote. One of the main features of BD. You can disable emotes in the settings if you don't want them.
