### ISSUE TITLE
[Bug] Doesnt download in Russia, Yekatinburg.

### ISSUE THREAD

**Issue by Ogar-the-best** [rauenzi/BetterDiscordApp#401]
**Describe the Bug**

The bug is that when you try to install BandagedBetterDiscord, this error message pops out.
"Using channel: https://github.com/rauenzi/BetterDiscordApp/archive/injector.zip
Downloading to: C:\Users\Mixail\AppData\Local\Discord\app-0.0.306\\resources\BetterDiscord.zip
Download error: Unable to connect to the remote server
Download seems to have failed, will try once more.
Downloading BandagedBD package
Using channel: https://github.com/rauenzi/BetterDiscordApp/archive/injector.zip
Downloading to: C:\Users\Mixail\AppData\Local\Discord\app-0.0.306\\resources\BetterDiscord.zip
Download error: Unable to connect to the remote server"
**To Reproduce**

Try to install BandagedBD in Yekaterinburg.
**Expected Behavior**

I expected it to just install. And work.
**Screenshots**

<img width="406" alt="Screenshot_255" src="https://user-images.githubusercontent.com/29043391/88484867-64658500-cf8b-11ea-8adc-6d87514f5a55.png">
<img width="407" alt="Screenshot_256" src="https://user-images.githubusercontent.com/29043391/88484869-6596b200-cf8b-11ea-9fc7-4ee730496091.png">

**Discord Version**

Stable, Version 0.0.306
**Additional Context**

I was just wanting BetterDiscord when I got this error.

**Comment by rauenzi** [comment]
You can follow the manual installation instructions found in the README, but region lock is not something I can fix.
