### ISSUE TITLE
Verification Failed (Windows)

### ISSUE THREAD

**Issue by AeonCaptain** [rauenzi/BetterDiscordApp#403]
When trying to install Bandaged BD it says it can't find utils.js.

Normal:
Starting installation for Discord
Killing Discord Processes
Downloading BandagedBD package
Finished downloading BandagedBD package
Extracting BandagedBD package
Renaming package dir
Deleting temp file C:\Users\fang2\AppData\Local\Discord\app-0.0.306\\resources\BetterDiscord.zip
Verifying installation
Checking for old style injection
C:\Users\fang2\AppData\Local\Discord\app-0.0.306\\resources\app\betterdiscord\utils.js does not exist! Verification failed!

Details:
Starting installation for Discord
Killing Discord Processes
Downloading BandagedBD package
Using channel: https://github.com/rauenzi/BetterDiscordApp/archive/injector.zip
Downloading to: C:\Users\fang2\AppData\Local\Discord\app-0.0.306\\resources\BetterDiscord.zip
Finished downloading BandagedBD package
Extracting BandagedBD package
Renaming package dir
Deleting temp file C:\Users\fang2\AppData\Local\Discord\app-0.0.306\\resources\BetterDiscord.zip
Verifying installation
Checking for old style injection
Checking for old injection C:\Users\fang2\AppData\Roaming\discord\0.0.306\
Verifying C:\Users\fang2\AppData\Local\Discord\app-0.0.306\\resources\app\index.js
Verifying C:\Users\fang2\AppData\Local\Discord\app-0.0.306\\resources\app\config.json
Verifying C:\Users\fang2\AppData\Local\Discord\app-0.0.306\\resources\app\package.json
Verifying C:\Users\fang2\AppData\Local\Discord\app-0.0.306\\resources\app\betterdiscord\index.js
Verifying C:\Users\fang2\AppData\Local\Discord\app-0.0.306\\resources\app\betterdiscord\config.json
C:\Users\fang2\AppData\Local\Discord\app-0.0.306\\resources\app\betterdiscord\utils.js does not exist! Verification failed!

**Comment by rauenzi** [comment]
Download the latest version of the installer.

**Comment by KaKi87** [comment]
Hello, I'd like to add that it's impossible for us to guess that the installer has been updated if you only replace the files without creating a new release with a bumped version. Thanks

**Comment by rauenzi** [comment]
I've bumped the version in the installer's repo now. I update the binaries on this release page because all the old links redirect there. https://github.com/rauenzi/BBDInstaller/releases/tag/v1.0.5

**Comment by KaKi87** [comment]
Alright, here's a tip : on new links, you can use https://github.com/rauenzi/BBDInstaller/releases/latest which will always redirect to the latest version. Thanks !

**Comment by rauenzi** [comment]
I'm aware, and the installer even checks for updates through that repo.
