### ISSUE TITLE
[Bug] fatal js error ~/.config/.config dont exist

### ISSUE THREAD

**Issue by fuzebox1** [rauenzi/BetterDiscordApp#404]
**Describe the Bug**
I reinstalled with betterdiscord uninstall, install
Upon starting discord again i get a fatal JS error, '~/.config/.config/-BetterDiscord' no such file or dir.

I removed the .config in the join string near line 24 in index.js and the error is gone but now bd says storage has become corrupt.

**Discord Version**
Stable

**Comment by rauenzi** [comment]
You're right, it looks like I accidentally used path.join on the wrong stuff, I will fix it ASAP.

**Comment by rauenzi** [comment]
With the change you made in place can you restart Discord and see if the issue persists?

**Comment by fuzebox1** [comment]
closed discord and did betterdiscordctl uninstall/install again and still persists

**Comment by rauenzi** [comment]
Did you make the change from before after reinstalling? 
> I removed the .config in the join string near line 24 in index.js and the error is gone but now bd says storage has become corrupt.

**Comment by fuzebox1** [comment]
Does it take a while to update perhaps? 

~  betterdiscordctl update
Updating Git repository...
From https://github.com/rauenzi/BetterDiscordApp
 * branch            injector   -> FETCH_HEAD
HEAD is now at e91d71e Changes to use proper variable

**Comment by fuzebox1** [comment]
> Did you make the change from before after reinstalling?
> 
> > I removed the .config in the join string near line 24 in index.js and the error is gone but now bd says storage has become corrupt.

I did it before, then reverted, reinstalled, tried again, reverted and reinstalled.

**Comment by fuzebox1** [comment]
The CI didnt go trough on the push you did

**Comment by rauenzi** [comment]
The CI passed on the very next push though. I am also pushing out a change to the injector (which requires an update/reinstall) which should alleviate the issue.

**Comment by fuzebox1** [comment]
It went trough, and starts. BD didnt load the first tiome but restarted and now its all good, ty!
