### ISSUE TITLE
[Feature] Disable Media Key Hijacking

### ISSUE THREAD

**Issue by seagull** [rauenzi/BetterDiscordApp#410]
**Is your feature request related to a problem? Please describe.**
No, an unnecessary feature. Discord is based on Chromium which integrates with keyboard media keys and Windows 10's volume control. It hijacks your media keys and makes using the web a chore.

**Describe the feature you'd like**
A slider in the bandagedBD settings to disable media key integration

**Additional context**
[Looking at this thread](https://support.discord.com/hc/en-us/community/posts/360057093051-Disable-media-playback-with-media-keys), the setting can be configured by a command-line flag at runtime. BandagedBD operates as a loader; it doesn't seem beyond the realm of the possible to add this as a launch flag when running Discord. The setting would need a program reboot to take effect.

**Comment by rauenzi** [comment]
In the future, please add a :+1: reaction to the issue rather than commenting a +1, it makes it easier to tell at a glance what features are wanted by the community without cluttering my inbox.

**Comment by PseudoResonance** [comment]
All that is necessary is for the following JS to be added somewhere before Discord starts. `electron.app.commandLine.appendSwitch('disable-features', 'HardwareMediaKeyHandling,MediaSessionService');`

Probably just below [line 5 in the injector](https://github.com/rauenzi/BetterDiscordApp/blob/injector/index.js#L5), although it would probably be best if a new setting was added to toggle it, for in case someone liked the feature..

**Comment by rauenzi** [comment]
This will be added in the next update
