### ISSUE TITLE
Why did SmartScreen filter detect the BetterDiscord Installer as dangerous?

### ISSUE THREAD

**Issue by Hplr63** [rauenzi/BetterDiscordApp#412]
**Describe the Bug**
When the BetterDiscord Installer is opened, SmartScreen filter detects it as dangerous.

**To Reproduce**
Just open the BetterDiscord Installer.

**Expected Behavior**
The BetterDiscord Installer normally opens

**Screenshots**
https://imgur.com/a/NvsKjbY (sorry, my pc is in czech)

**Discord Version**
Stable

**Additional Context**

**Comment by rauenzi** [comment]
Because the installer is an unsigned (and unfamiliar) exe to SmartScreen that modifies paths for another program (Discord). I cannot afford to maintain a license for signing and there's no guarantee that would fix the issue because of how the installer works.
