### ISSUE TITLE
[Bug] BetterDiscord Host 0.0.11 Issues

### ISSUE THREAD

**Issue by CDAGaming** [rauenzi/BetterDiscordApp#413]
**Describe the Bug**
In Host 0.0.11, newly released to Discord on Linux, BetterDiscord is no longer working

**To Reproduce**
1) Install BetterDiscord to Host 0.0.11 (I used https://gist.github.com/ObserverOfTime/d7e60eb9aa7fe837545c8cb77cf31172)
2) Launch BetterDiscord

**Expected Behavior**
It should load BetterDiscord as Intended

**Screenshots**
![Screenshot from 2020-08-06 13-36-39](https://user-images.githubusercontent.com/16328918/89569284-1aca3500-d7ea-11ea-8060-f0df9223b1cf.png)

**Discord Version**
Stable 64675 (92c9fdf)
Host 0.0.11
Linux 64-Bit (5.4.0-7634-Generic)

**Comment by qwerasd205** [comment]
Try `betterdiscordctl update` then install. You may have outdated injector files (which it seems that betterdiscordctl stores for some odd reason)

**Comment by CDAGaming** [comment]
This worked, closing as resolved!

**Comment by galaxy119** [comment]
This didn't work for me.

**Comment by cheesits456** [comment]
@galaxy119 it didnt for me either at first, but after I did the following, all was good:

- Closed Discord
- `betterdiscordctl uninstall`
- `betterdiscordctl upgrade`
- `betterdiscordctl update`
- `betterdiscordctl install`
- `betterdiscordctl update`
- Opened Discord

I'm sure at least _some_ of those steps aren't necessary, but idk which ones exactly cuz I tried updating and upgrading a few times before this and it didn't work - this is the combination of steps that worked for me, so redundant or not, it _should_ for you too :+1:

**Comment by CDAGaming** [comment]
Ironically, when i brought up the storing old injector files at https://github.com/bb010g/betterdiscordctl/issues/75, my issue was marked as invalid and closed :/
