### ISSUE TITLE
Better discord unninstalled it self

### ISSUE THREAD

**Issue by xdjoee** [rauenzi/BetterDiscordApp#416]
**Describe the Bug**
Better discord deleted it self

**To Reproduce**
no idea it just happened today

**Expected Behavior**
-

**Screenshots**
-

**Discord Version**
latest

**Additional Context**
Idk it litteraly deleted it self

**Comment by JeanOUINA** [comment]
Discord just made an update, you have to reinstall BandagedBD with the installer.

**Comment by rauenzi** [comment]
@xdjoee please try reinstalling with the latest installer and let me know if the issue persists. It's likely that you got the versioned update of Discord so BD did not delete itself, but rather it was never injected into the new version.

**Comment by minervamaga** [comment]
Piping in on this one that I got a forced update today myself and couldn't get BD and BBD to reinstall.  Ran the installer like normal, but the BBD one kept failing on one of the JS verifications and wouldn't go further.  A manual install following the instructions in the readme here worked _after_ I unzipped the `app` folder, but not before (which wasn't mentioned in the manual instructions.  Seems to be working now - here's my version info if you need it!  https://cdn.discordapp.com/attachments/574799106124546069/743691340084150303/unknown.png

**Comment by qwerasd205** [comment]
> _after_ I unzipped the `app` folder, but not before (which wasn't mentioned in the manual instructions)
Hmmm, "Download _and extract_ this:"

**Comment by minervamaga** [comment]
D'oh. That's what I get for fixing things after a 16 hour shift.  Edited!

**Comment by qwerasd205** [comment]
But also, you were using an old installer if it failed to verify one of the files. Make sure to always download the latest installer.

**Comment by notnicknamed** [comment]
I agree to be honest. This is a dying mod client. Fuck them hackers.
