### ISSUE TITLE
[Bug] Injector doesn't load after update

### ISSUE THREAD

**Issue by Ertego** [rauenzi/BetterDiscordApp#418]
**Describe the Bug**
The injector script fails to load after the upgrade to 0.0.11 on Linux

**To Reproduce**
reinstall on 0.0.11

**Expected Behavior**
Injector *should* load and provide all the BD functionality

**Screenshots**
Logs:
`Refused to apply style from 'https://cdn.staticaly.com/gh/rauenzi/BetterDiscordApp/c687b97d665ffa24e749c9b04182a99eec96af21/css/main.min.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
cdn.staticaly.com/gh/rauenzi/BetterDiscordApp/c687b97d665ffa24e749c9b04182a99eec96af21/js/main.min.js:1 Failed to load resource: the server responded with a status of 404 ()`

**Discord Version**
Stable

**Comment by rauenzi** [comment]
Based on the error, your injector is quite out of date. You can try and follow the provided instructions here to fix it: https://github.com/rauenzi/BetterDiscordApp/issues/421#issuecomment-670964471

If that still does not work, I would recommend reaching out to those that made the linux installer. https://github.com/bb010g/betterdiscordctl
