### ISSUE TITLE
[bug] BandageBD on Windows now blocked by MalwareBytes

### ISSUE THREAD

**Issue by Vahid-Rahmani** [rauenzi/BetterDiscordApp#419]
**Describe the Bug**

MalwareBytes detects BD as malicious and doesn't allow the installer to run

**To Reproduce**

Try to open the BandageBD exe with premium MalwareBytes running

**Expected Behavior**

Not be detected as a virus

**Screenshots**

https://i.imgur.com/bMQGj3a.png

**Discord Version**

Stable

**Comment by rauenzi** [comment]
There's not much I can do about this from my end. By all accounts this is an unsigned exe modifying existing files for another program (Discord), so it makes sense that it gets flagged. For your specific case you can probably click `advanced` and restore the exe and use it. The installer is open source so you can check for nefarious things yourself. https://github.com/rauenzi/BBDInstaller
