### ISSUE TITLE
Verification failed

### ISSUE THREAD

**Issue by verzhenya27** [rauenzi/BetterDiscordApp#420]
**Describe the Bug**
 can't install BetterDiscord. Gives an error message

**To Reproduce**
 Steps to reproduce the behavior

**Expected Behavior**
I expected everything to be as usual. But it gives me an error. 

**Screenshots**
 ![image](https://user-images.githubusercontent.com/69363451/89676944-923cb900-d8fd-11ea-9649-0b8b186cb82d.png)

**Discord Version**
 PTB 

**Additional Context**
 Logs: Starting installation for DiscordPTB
Killing DiscordPTB Processes
Downloading BandagedBD package
Finished downloading BandagedBD package
Deleting old BetterDiscord
Extracting BandagedBD package
Renaming package dir
Deleting temp file C:\Users\Сергей\AppData\Local\DiscordPTB\app-0.0.54\\resources\BetterDiscord.zip
Verifying installation
Checking for old style injection
C:\Users\Сергей\AppData\Local\DiscordPTB\app-0.0.54\\resources\app\betterdiscord\utils.js does not exist! Verification failed!

**Comment by isham-b** [comment]
I fixed it by uninstalling BandagedBD, and then reinstalling using the newer BandagedBD installer (v1.05) from their repo: https://github.com/rauenzi/BetterDiscordApp

**Comment by rauenzi** [comment]
Your installer version (`1.0.3`) is out of date (latest `1.0.5`). You need to download the latest version of the installer.
