### ISSUE TITLE
[Bug] Crashes when Viewing profile through the User Logo

### ISSUE THREAD

**Issue by ZaneDragonBorn** [rauenzi/BetterDiscordApp#422]
**Describe the Bug**
My Discord Will give an error 9000 when I press someone's User logo When using Better Discord

**To Reproduce**
Click on Someone Profile Picture in a server.

**Expected Behavior**
Your Discord will enter a screen saying "YOU DIED" under saying "Looks Like you got slaughtered by Error Level 9000"

**Screenshots**
![YOU DIED](https://user-images.githubusercontent.com/68198648/89722808-f9b93e00-d9bb-11ea-9182-62e78d1f9665.png)

**Discord Version**
My Better Discord version is 0.3.5

**Additional Context**

**Comment by rauenzi** [comment]
That screen is either added by a theme or plugin. Sounds like you have the plugin StatusEverywhere. Can you confirm?

**Comment by ZaneDragonBorn** [comment]
> That screen is either added by a theme or plugin. Sounds like you have the plugin StatusEverywhere. Can you confirm?

Yeah I have status everywhere. How would I fix it?

**Comment by rauenzi** [comment]
Disable StatusEverywhere and reload (ctrl+r). Then see if clicking the "User logo" still crashes your Discord.

**Comment by Boii1** [comment]
Welp that fixed the issue for me. Ty rauenzi.

**Comment by ZaneDragonBorn** [comment]
yeah, it's fixed. Would there be a way to report the issue to that dev? I really like that plugin

**Comment by rauenzi** [comment]
There's an open issue for it already https://github.com/rauenzi/BetterDiscordAddons/issues/268

**Comment by K12XK** [comment]
Hey ! How i can disable StatusEverywhere ?

**Comment by K12XK** [comment]
I don't know where it is in my coumputer

**Comment by K12XK** [comment]
![Uploading image.png…]()

**Comment by 42069cell** [comment]
i have the same problem i dont know how to fix it its not doing it to my other pcs

**Comment by NishantMajumdar** [comment]
Same issue, it occurred even tho i dont have statusEverywhere  plugin. It happened after i updated ImageUtils, and now i removed it but no luck.

**Comment by saskijhuih** [comment]
how can i turn the  StatusEverywhere off
@ZaneDragonBorn

**Comment by ShadowHunterKK** [comment]
to turn off plugins, you have to restart discord( if you have seen the error. Go to settings, plugins and toggle.

Or using RUN. Press Win+R( idk for mac, type "%appdata%/BetterDiscord" without the "" marks. And delete the desired plugin.
