### ISSUE TITLE
[Bug] BDA not functioning properly

### ISSUE THREAD

**Issue by MicroWazzle** [rauenzi/BetterDiscordApp#424]
**Describe the Bug**

I noticed that BD was not up to date so I downloaded the latest version of the installer but it tells me that it's 1.04 and that there is a 1.05 version, when I install that some features of the app work like one of my plugins Character Counter loads but I have no opens in my settings for BD. Also even after updating i'm still getting the BD logo in the bottom right telling me to update. 

**To Reproduce**

All that I have done is download the installer from the github page and installed to stable.

**Expected Behavior**

**Screenshots**

https://prnt.sc/twvu0c
https://prnt.sc/twvu3y

**Discord Version**

Stable v1.05

**Additional Context**

**Comment by rauenzi** [comment]
Please try doing this with no plugins or themes added

**Comment by MicroWazzle** [comment]
> Please try doing this with no plugins or themes added

Thing is I cant go into the settings to remove them. I guess ill just move them out of the folders.

**Comment by MicroWazzle** [comment]
> Please try doing this with no plugins or themes added

This suggestion has worked, thank you for taking the time to help me.

**Comment by MicroWazzle** [comment]
> Please try doing this with no plugins or themes added



> Please try doing this with no plugins or themes added

Ok so I have a problem with this solution whenever i restart discord the same thing happens, it tells me I need to update and i dont have the settings in my settings.

**Comment by rauenzi** [comment]
So you did try with no plugins or themes? Try renaming your entire `%appdata%\BetterDiscord` to something else and fully restarting Discord
