### ISSUE TITLE
[Bug] Transparency not working

### ISSUE THREAD

**Issue by gamerboyleo** [rauenzi/BetterDiscordApp#426]
**Describe the Bug**
The window transparency setting doesn't work. I've restarted my computer, discord, and everything. Still nothing.

**To Reproduce**
Enable transparency mode.

**Expected Behavior**
It should allow me to see through the windows.

**Screenshots**
![image](https://user-images.githubusercontent.com/40919620/89971356-a3006e00-dc20-11ea-859e-e84cfe257a05.png)

**Discord Version**
Stable

**Additional Context**

**Comment by rauenzi** [comment]
Have you tried it in combination with a theme? That setting only enables the lower level, you need a transparent theme to take full advantage. With transparency mode does window snapping still work?

**Comment by gamerboyleo** [comment]
I actually tried both with and without a theme, neither worked. I don't know if snapping works but I'll try it when I get a chance

**Comment by Brucewastaken** [comment]
try going into the custom css and type in * {background: transparent!important;}

**Comment by rauenzi** [comment]
@gamerboyleo anything?

**Comment by gamerboyleo** [comment]
worked, thanks
