### ISSUE TITLE
[Cannot install or repair BD]

### ISSUE THREAD

**Issue by AdmiralPleasure** [rauenzi/BetterDiscordApp#428]
**Describe the Bug**
Can not install or repair BD, both give fatal java errors about 75% of the way through a download or repair.

**To Reproduce**
Using auto installer, attempt to install or repair stable (no canary or anything, just BD)

**Expected Behavior**
Automatically and quickly installs a working Better Discord, which should still have my settings and themes.

**Screenshots**
![BD Error](https://user-images.githubusercontent.com/69832097/90465889-37594d80-e0c5-11ea-85cc-afbcd7c67867.PNG)

**Discord Version**
Stable

**Additional Context**
I have used BD for a while now, but I have not been able to reinstall or repair. Even grabbed the most recent installer. I have no idea how to fix this with no coding experience.

**Comment by rauenzi** [comment]
You are using a very old version of Discord (0.0.305) which is unsupported. Please reinstall Discord, the latest version is 0.0.307

**Comment by AdmiralPleasure** [comment]
> You are using a very old version of Discord (0.0.305) which is unsupported. Please reinstall Discord, the latest version is 0.0.307

That was exactly it. I had to reinstall in order for it to recognize the update, even running as admin wouldn't force an update. Thank you very much!
