### ISSUE TITLE
BetterDiscord Does Not Appear

### ISSUE THREAD

**Issue by d34ddud3** [rauenzi/BetterDiscordApp#433]
I have used BetterDiscord in the past on Windows 10 with little to no issue. However I have recently switched to Debian 10 (Debian Buster) and have had nothing but difficulty with BetterDiscord. I installed Discord (using [this](https://linuxconfig.org/how-to-install-discord-on-linux) page), made sure it was working properly, then installed BetterDiscord. I followed the instructions of [this](https://gist.github.com/ObserverOfTime/d7e60eb9aa7fe837545c8cb77cf31172) page. (Before doing so I had installed _git_ using the link provided on that page) After some difficulty I had gotten BetterDiscord to work. (At the time I had forgotten that the page I used to install Discord said it was installing Canary, though even now it seems that it isn't Canary. I wouldn't really know the difference between the two in order to tell though.) It continued to work for a couple days and through a few reboots.

Then there's today. I was attempting to configure the **Oracle VM Virtual Box** and was given only 32-bit options despite having a 64-bit OS. After some troubleshooting I learned of a fix that required me to enter the BIOS and switch a setting. The setting was to allow virtual computing. When I returned to my desktop and launched Discord to reply to a friend I had noticed that my theme was gone. I checked the settings and all of the Better Discord options had disappeared.

To try solving it myself I had uninstalled and reinstalled both Discord and Better Discord multiple times, to no avail. Then I had jumped into the ".config" file, selected both Better Discord and Discord(after supposedly uninstalling them), and deleted them. Then I installed Discord again using the dpkg method used in the website linked above. I ran Discord and it works perfectly fine. I then went to the Better Discord installation guide (also linked above) and started from this line:
`user@hostname:~$ curl -O https://raw.githubusercontent.com/bb010g/betterdiscordctl/master/betterdiscordctl`
No errors.
`user@hostname:~$ chmod +x betterdiscordctl`
No errors.
`user@hostname:~$ sudo mv betterdiscordctl /usr/local/bin`
Still no errors.

Now this time I had remembered that the website for installing Discord above said that it would be a Canary installation. Thus I figured that perhaps it was because I installed the stable version that it broke after the reboot and BIOS settings adjustment. So this time I ran this:
`user@hostname:~$ betterdiscordctl install -f Canary`
And this was the outcome:
`ERROR: Discord installation not foun. Try specifying it with "--discord".`
So I tried adding "--discord" to the end of the line.
`user@hostname:~$ betterdiscordctl install -f Canary --discord`
Right... So I don't really know what "--discord" does or the syntax for using it. Here's the error message:
`ERROR: "--discord" requires a non-empty option argument.
Use "--help" for more information.`
Of course I've given up on trying to use the help command on anything. So I figured this command is intended to help the command find the right directory right? I'll add ".config" to the end of it.
`user@hostname:~$ betterdiscordctl install -f Canary --discord .config`
And the error message:
`ERROR: "--discord" requires "--modules" to also be set.
Use "--help" for more information.`
That's when I said, "Screw that! I'm just going to try installing it like I did last time."
`user@hostname:~$ betterdiscordctl install`
`Cloning https://github.com/rauenzi/BetterDiscordApp...`
`Cloning into '/home/user/.local/share/betterdiscordctl/bd/0'...`
`remote: Enumerating objects: 13, done.`
`remote: Counting objects: 100% (13/13), done.`
`remote: Compressing objects: 100% (10/10), done.`
`remote: Total 13 (delta 0), reused 6 (delta 0), pack-reused 0`
`Unpacking objects: 100% (13/13), done.`
`Installed. (Restart Discord if necessary.)`
`user@hostname:~$ betterdiscordctl upgrade`
`betterdiscordctl is already the latest version (1.7.0).`
`user@hostname:~$ betterdiscordctl update`
`Updating Git repository...`
`From https://github.com/rauenzi/BetterDiscordApp`
` * branch                   injector       -> FETCH_HEAD`
`HEAD is now at 521056b Fixes #417`

Looks the same as it did when it worked last time. So I pop into Discord, which has been closed during this entire process, and see that nothing changed. I went to the settings and couldn't find the Better Discord settings there.

I'm no programmer and I can't really code, but I've done some little dabbles. I think it's either because I enabled emulating in my BIOS settings or because of something to do with this line:
`ERROR: "--discord" requires "--modules" to also be set.`
Unfortunately, I'm not able to build command strings. I usually have to refer to an article or video on what commands to execute. It makes sense when I see them, but I'm unable to make the command strings myself.

**Comment by rauenzi** [comment]
This looks like you are having an issue with the installation itself on Linux. I think @ObserverOfTime or the people over at https://github.com/bb010g/betterdiscordctl might be of more help as they make the Linux installer. I recommend opening an issue over on that repository as they can be of more help (and the issue is with the installer, not BD).

In the meantime, you can refer to this gist for additional help. https://gist.github.com/ObserverOfTime/d7e60eb9aa7fe837545c8cb77cf31172
