### ISSUE TITLE
[Bug] Stream/Screen Share Doesn't Load When Clicking "Pop-Out".

### ISSUE THREAD

**Issue by Benjamoose** [rauenzi/BetterDiscordApp#434]
**Describe the Bug**
When clicking "Watch Stream", the stream works fine when embedded directly in the main Discord client window, however, if you click the small "pop-out" button to separate the stream into a separate window, the stream audio continues to play, but the video sticks on the Discord loading animation loop. Making the feature unusable.

**To Reproduce**
Join a user's stream, then click the pop-out button.

I've since heard that this may be known already, but figured I'd post it anyway, seeing as I couldn't see it mentioned in this section at a cursory glance (though apologies if I have missed it!).

**Comment by rauenzi** [comment]
Can you try reinstalling and see if the issue persists? Should have been fixed as part of #417

**Comment by Benjamoose** [comment]
Seems to be fixed now.

Sorry to bother you with old news. I submitted this back when it first happened, but I apparently got the wrong repo (I was posting to one specifically for the installer, which I didn't know was a separate thing), so by the time I got here, I realized it had already been posted in your link, and fixed.

Thanks again.
