### ISSUE TITLE
[Bug] multiple plugins causing some to not load

### ISSUE THREAD

**Issue by ZaneDragonBorn** [rauenzi/BetterDiscordApp#438]
**Describe the Bug**
 I have a total of 50 plugins installed and some like ServerSearch, Toggle Game Activity, and SpellCheck won't load. If I reload these some will but others won't

**To Reproduce**
 Have over 50 plugins loaded. Some won't load

**Expected Behavior**
 them to load

**Screenshots**

**Discord Version**
 Stable

**Additional Context**
 I'm using the clear Vision theme but these worked with it before with no issues

**Comment by ZaneDragonBorn** [comment]
If you need any more detail I can provide whatever you need tomorrow.

**Comment by PaxiTheAlchemist** [comment]
I too am having this issue. Every time Discord launches, various plugins seem to fail to run. Some fail more than others. Manually reenabling them seems to fix the problem, however, I feel like having to do that for every single time Discord launches can be a hassle. Perhaps a load order could be added to counteract this? I'm not sure if this is already incorporated in Better Discord, but maybe even a settable delay between loading up plugins? Maybe even a way to detect whether or not plugins are running or not and enabling them as a result if they aren't?

**Comment by rauenzi** [comment]
Plugins are delayed until the DOM is available, however sometimes plugins don't properly wait until the elements they want are available. When this happens, if they fail to handle the error properly BD disables them. This is why it appears as if they just didn't run at all. If you can get a list of what plugins are consistently failing on load we can confirm it. I know off the top of my head that this can happen for ServerSearch and ToggleGameActivity. Again, it would be on those plugins and not BD itself to properly check for the elements.
