### ISSUE TITLE
[Feature] adjustable Discord

### ISSUE THREAD

**Issue by ZaneDragonBorn** [rauenzi/BetterDiscordApp#439]
**Is your feature request related to a problem? Please describe.**
 It’s always frustrating to me when I'm resizing discord and the member list, channel list, or server list are in the way. The ability to change this like a slider would be great!

**Describe the feature you'd like**
 the ability to hover over the edge of a box (member list, server list, or channel list) and expand or condense them with a slider instead of the CSS.

**Additional context**
 this would just be a simple feature that would be very helpful.

**Comment by rauenzi** [comment]
This is something that would be best left to a plugin or theme, not as a central piece of BD itself.
