### ISSUE TITLE
BandagedBD Not Installing

### ISSUE THREAD

**Issue by KastVachez** [rauenzi/BetterDiscordApp#44]
It's just stuck on extracting core, even after moving it to the Desktop and running it as admin.

**Comment by rauenzi** [comment]
Make sure you have the latest release. Have you tried both the regular and the NoAdmin versions?

**Comment by KastVachez** [comment]
Yes, it's the latest release, and I've tried both.

**Comment by rauenzi** [comment]
Is your discord version 0.0.301? Has it been run once since installing?

**Comment by KastVachez** [comment]
My Discord is the latest version and it has been run lots of times. I've tried both leaving it open and letting the installer close it and running the installer without it open.

**Comment by timbooo1** [comment]
Did you place it in another folder instead of the downloads folder.

**Comment by PoorPocketsMcNewHold** [comment]
He/She did. Right in the description of the Issue. @timbooo1 Indicated to have been tested on the Desktop.

**Comment by timbooo1** [comment]
@PoorPocketsMcNewHold I only saw "BandagedBD Not installing" Where can I see these descriptions?

**Comment by PoorPocketsMcNewHold** [comment]
That's the first message on an Issue, written by the user who opened the issue in the first place.

**Comment by timbooo1** [comment]
I'm blind hahaha

**Comment by timbooo1** [comment]
@KastVachez My problem with such an issue is that my computer wasn't updated and a certain windows update was withholding my installer working. Try to update your computer?

**Comment by rauenzi** [comment]
Check that you have the latest versions of the .NET framework installed, it is often installed through windows update.
