### ISSUE TITLE
Transparent settings bug

### ISSUE THREAD

**Issue by Brucewastaken** [rauenzi/BetterDiscordApp#440]
**Describe the Bug**
Whenever I turn on the transparent option, I cannot access the windows toolbar by scrolling to the very bottom of the window.

**To Reproduce**
Enable transparent 
then reload discord
scroll to the bottom
try to access toolbar
**Expected Behavior**
I expected it to be the same when transparent is disabled, but the only thing that shows is the resize arrow when I try to access toolbar.

**Screenshots**

**Discord Version**
Stable
**Additional Context**

**Comment by rauenzi** [comment]
Stuff like that as well as window snapping and such all break with transparency on, but it is an issue with Electron itself (the engine behind Discord) and is not something I can fix. There is external transparency tool called Glasscord you can try however.

However, before I close this can you clarify what you mean by the "windows toolbar"?

**Comment by Brucewastaken** [comment]
The windows toolbar is the bar at the bottom (by default, though people can change it to put it wherever they want) that contains the app icons and useful things
heres a screenshot
![image](https://user-images.githubusercontent.com/68714491/91778107-69c77800-eba6-11ea-9649-be9845c93fe7.png)

**Comment by rauenzi** [comment]
Then I don't see how scrolling has anything to do with it. The taskbar should just be there if its not set to hide.

**Comment by Brucewastaken** [comment]
I have the settings set to hide, so if i just put my mouse on the bottom of my screen the taskbar shows up, but when transparent is on, the only thing that shows is the arrow for resizing it.

**Comment by Brucewastaken** [comment]
I can try to turn taskbar to always be on

**Comment by rauenzi** [comment]
Ah then yes indeed an Electron issue that I unfortunately cannot resolve.
