### ISSUE TITLE
[Bug] Cannot connect to recaptcha

### ISSUE THREAD

**Issue by growstackman123** [rauenzi/BetterDiscordApp#443]
**Describe the Bug**
If betterdiscord is installed, recaptcha fails to connect on discord when logging in.

**To Reproduce**
Type the wrong password or login from a new location so you'll get the captcha.

**Expected Behavior**
-

**Screenshots**
-

**Discord Version**
Stable

**Additional Context**
-

**Comment by Strencher** [comment]
betterdiscord only loads after you did login 🤔

**Comment by rauenzi** [comment]
As @Strencher said, BD will not load in until after you login. It sits and waits until that happens.

**Comment by nxhu64** [comment]
I've also been having this issue, and uninstalling BandagedBD solved it, i was then able to log in and reinstall it afterwards
