### ISSUE TITLE
Uninstalling from Canary after update[Bug]

### ISSUE THREAD

**Issue by jpie726** [rauenzi/BetterDiscordApp#444]
**Describe the Bug**
Is being uninstalled from Canary on launch, PTB is unaffected
**To Reproduce**
Install BandagedBD onto discord canary, launch once, restart discord
**Expected Behavior**
stay enabled/installed until manually uninstalled
**Screenshots**

**Discord Version**
Canary, ptb works as intended, unsure about stable
**Additional Context**

**Comment by jacklolidk** [comment]
same

**Comment by jpie726** [comment]
Just realized that there was an option in repair for it, going to try that and then reply if it works or not

**Comment by jpie726** [comment]
yep, worked and I'm going to close this unless it is an issue again
