### ISSUE TITLE
[Bug] Discord cdn links keep disappearing 

### ISSUE THREAD

**Issue by LiamDun** [rauenzi/BetterDiscordApp#445]
Discord cdn (media) links won't show up with betterdiscord, it would load for a couple seconds than show this 
![image](https://user-images.githubusercontent.com/62409548/92558988-0b3f7f80-f2b3-11ea-92ad-7eaf3c690c0f.png)

**To Reproduce**
just try to look at a discord cdn (media)

**Expected Behavior**

i expected to see the media that's being sent
**Screenshots**

**Discord Version**
Canary

**Additional Context**

![image](https://user-images.githubusercontent.com/62409548/92559371-d4b63480-f2b3-11ea-9316-2933082ddda0.png)

**Comment by rauenzi** [comment]
Is this still happening for you? It is not happening for me. Do you have plugins enabled?
