### ISSUE TITLE
[Bug] Discord Client Freezes Up

### ISSUE THREAD

**Issue by Cassiedee** [rauenzi/BetterDiscordApp#446]
**Bug:**
The whole Discord client freezes.

**To Reproduce:**
The bug occurs usually when writing up messages or when navigating through settings or DMs/Servers. 

**Expected Behavior:**
Discord freezes for a solid 30 seconds before resuming regular functionality. I'm able to move my cursor but cannot click anything within Discord as it's unresponsive. During the time that Discord freezes, incoming messages or animations within the application do not respond and update until the freeze is over. 

**Screenshots**
![image](https://user-images.githubusercontent.com/65631988/92832870-0e0ea300-f38d-11ea-8ccd-1fc771bf13ff.png)
I do not know if having a bunch of plugins is a problem. However, I'll be testing each and every one of them when I have time to try to see if any of the plugins causes the unresponsiveness.

Discord Version: Stable

**Additional Context**
This bug can sometimes occur for me without having any plugins installed at all.

**Comment by rauenzi** [comment]
> I do not know if having a bunch of plugins is a problem. 

Try disabling _all_ of them, reload Discord, then see if the issue persists.

**Comment by Cassiedee** [comment]
@rauenzi It still happens however less frequently this time. Should I do a clean install of both Discord and BandagedBD?

**Comment by rauenzi** [comment]
Worth a try

**Comment by Cassiedee** [comment]
@rauenzi Oh wait. I think I may have solved my problem. I had an instance of Discord running in Docker and the Message Logger caused my Windows Installation of Discord to freeze up while the Instance in Docker crashed as the plugins were in the same directory. Both installations of Discord were using it at once and ig t causes confusion and Discord just freezes up.

**Comment by Cassiedee** [comment]
Thank you for the help anyhow. If it wasn't for you, my mind wouldn't even think about my Discord installation on Docker messing things up.

**Comment by rauenzi** [comment]
For the record, message logger is unsupported.

**Comment by Cassiedee** [comment]
@rauenzi Well thank you for letting me know. I never knew that.
