### ISSUE TITLE
JS Error upon loading[Bug]

### ISSUE THREAD

**Issue by SirFuzzo** [rauenzi/BetterDiscordApp#447]
I've tried using the installer and the injector. When I tried the injector I saw that there was no app folder in ./resources but rather a file named app.asar which to my knowledge is packed node/electron application or data. I'm guessing this is why the installer isnt working nor is the repair tool in any capacity,  

![image](https://user-images.githubusercontent.com/32964311/93030340-dd767580-f5e7-11ea-8420-e8b3743315f1.png)

Please advise.

EDIT: I'm using stable, latest version as discord auto-updates to my knowledge.

**Comment by rauenzi** [comment]
You are using an old version of Discord. I see `0.0.305` there and the latest version is `0.0.308`. BD requires at minimum `0.0.306`. Reinstall Discord.

**Comment by rf236129** [comment]
Idc stop
