### ISSUE TITLE
discord killed

### ISSUE THREAD

**Issue by TimKAIFLOWW** [rauenzi/BetterDiscordApp#448]
Starting installation for Discord
Killing Discord Processes
Downloading BandagedBD package
Download seems to have failed, will try once more.
Downloading BandagedBD package

**Comment by StefEmcee** [comment]
wdym discord killed ? :)) 
killing discord processes means they closed everything that connects to discord

**Comment by rauenzi** [comment]
You have an issue with the installer downloading the installation payload. Follow the manual installation instructions.  https://github.com/rauenzi/BetterDiscordApp#manual-installation
