### ISSUE TITLE
[Bug] Game Activity toggle keeps turning off after restart

### ISSUE THREAD

**Issue by FluffyDiscord** [rauenzi/BetterDiscordApp#451]
**Describe the Bug**
Game Activity toggle keeps turning off whenever I restart BD.

**To Reproduce**
Start Discord > User Settings > toggle Game Activity > exit Discord (completely, not hide in tray) > restart Discord > check Game Activity > it's off again

**Expected Behavior**
Save this option - should be enabled.

**Screenshots**
No need.

**Discord Version**
Stable

**Additional Context**

**Comment by rauenzi** [comment]
Next time this occurs please check console for errors

**Comment by Rich246** [comment]
@rauenzi I am also having this issue, I don't know what to look for within the console.

**Comment by rauenzi** [comment]
Look for red or the word "error"

**Comment by FluffyDiscord** [comment]
For me, it was caused by a plugin named "DoNotTrack v0.0.6 by Zerebos", if you have that plugin, remove it.

**Comment by Strencher** [comment]
you can disable that feature in the settings of that plugin.

**Comment by Skies966** [comment]
> plugin, remove it.

Oh my gosh, Thank you so much that seems to have fixed it 👍
