### ISSUE TITLE
It says 'click to update' at the top of my screen

### ISSUE THREAD

**Issue by visqqq** [rauenzi/BetterDiscordApp#453]
randomly I check discord and it says "click here to update", i'm clicking it and it does nothing. i'm confused on how to fix it. I tried the repair bandagedbd and it did nothing. I uninstalled it multiple times aswell as discord. i turned off my plugins to see if that was the problem but it wasn't so idk. also when i was uninstalling and installing bandagedbd it said there was a new update, i clicked ok and it loaded up discord but it wasn't that. for now i'm just gonna stop using betterdiscord til i can fix it cus this really irritates me lmao

**Comment by 13Stewartc** [comment]
I have this issue too. Image below: 
![image](https://user-images.githubusercontent.com/62550490/94076571-54d0b400-fdf5-11ea-9e8a-5fd4b44bd52a.png)

**Comment by rauenzi** [comment]
Redownload ZeresPluginLibrary, this was an issue with the previous version.
