### ISSUE TITLE
[Bug] Unexpected token

### ISSUE THREAD

**Issue by TomerGamerTV** [rauenzi/BetterDiscordApp#454]
**Describe the Bug**
I'm just opening discord and it's showing its error

**To Reproduce**
maybe something broke with the pc idk because it started to happen after my pc started to crash a lot

**Expected Behavior**
restart the pc the see this (it can happen every day or 2)

**Screenshots**
![image](https://user-images.githubusercontent.com/44266242/94111065-39dd5e80-fe4c-11ea-96ba-c9dcfa27e4de.png)

**Discord Version**
Stable

**Additional Context**
discord sometimes freezes or crashes after reinstall better discord

**Comment by rauenzi** [comment]
Reinstall BD. This would only really happen if your PC or Discord is randomly killed during startup.

**Comment by TomerGamerTV** [comment]
it fixed now i dont remember how i fixed it
