### ISSUE TITLE
[Bug] BD doesn't load when discord start on system startup minimized

### ISSUE THREAD

**Issue by hsusanoo** [rauenzi/BetterDiscordApp#457]
**Describe the Bug**
When Discord runs automatically on system startup minimized BD doesn't load when I open it, I can't see it under settings and no plugins are loaded, I have to close discord from the system tray icon or end the process and restart discord for everything to load properly.

**To Reproduce**
- toggle on : "Open Discord" and "Start Minimized" under windows settings in Discord
- Restart computer
- Discord will automatically start minimized
- Open Discord -> No BD under settings or plugins loaded
- Restart Discord
- BD and plugins loaded

**Expected Behavior**
For BD to load automatically

**Discord Version**
Stable 68015

**Additional Context**
I have Automatic Loading turned on in BD settings

**Comment by rauenzi** [comment]
It sounds like the Discord running on startup in an old version. I would recommend deleting the old Discord versions just to be sure.
