### ISSUE TITLE
Settings colors don't match Discord's on light theme

### ISSUE THREAD

**Issue by RhapsodySL** [rauenzi/BetterDiscordApp#46]
I know it's apparently a sin to use the light theme on Discord, but the settings added by BetterDiscord don't follow the same text color and highlight color as the regular Discord settings do when highlighting. Instead, they use the Dark theme variant of the colors, even if the Dark theme isn't turned on.

**Comment by rauenzi** [comment]
This is intentional.

**Comment by RhapsodySL** [comment]
No, that's lazy. I don't want to use the dark theme, and I shouldn't have to be forced to if I want to read the description labels on the options.

**Comment by rauenzi** [comment]
If you or someone would like to add support for the light theme feel free. I will reopen the issue in case someone would like to. As of right now however my efforts are focused elsewhere and don't want to spend all that time re-coloring all of v1 (which is in maintenance mode) to support light theme for one person.

Or in terms similar to how you put it: I don't want to support the light theme, and I shouldn't have to be forced to.
