### ISSUE TITLE
Plugin Button Sliders Stuck In Off Position

### ISSUE THREAD

**Issue by NobUwU** [rauenzi/BetterDiscordApp#466]
The buttons for plugin settings are broken. When clicked they stay in off position.
Discord Stable Version.

![image](https://user-images.githubusercontent.com/61068742/95942477-d9857100-0da8-11eb-965c-49ca92e82c60.png)

**Comment by rauenzi** [comment]
This should be fixed now by the devs, but was never the fault of BD itself.
