### ISSUE TITLE
[Feature] Remove or rewrite minimal mode and voice mode.

### ISSUE THREAD

**Issue by Tropix126** [rauenzi/BetterDiscordApp#475]
**Is your feature request related to a problem? Please describe.**
Minimal mode in it's current state is completely unusable. It's caused more harm than good in support servers, and is as annoying to manage as a seperate theme.

**Describe the feature you'd like**
Completely remove voice mode, as it's completely pointless and degrades user experience. I cannot think of a single practical use for it. Either remove or rewrite minimal mode for the reasons listed above.

**Additional context**

**Comment by rauenzi** [comment]
You rewrote minimal mode, and voice mode was removed.
