### ISSUE TITLE
[Feature] Allow a transparency toggle/slider for pop-out video windows

### ISSUE THREAD

**Issue by Zefferis** [rauenzi/BetterDiscordApp#478]
**Is your feature request related to a problem? Please describe.**

While not inherently a problem, my primary use for discord is video calling; as such I use the pop-out window for calls and window sharing, because of that the popout window in my use case tends to be alot larger so I can actually *see* what's being shared, but I don't need to view the content in 100% opacity since it blocks a large portion of the screen.

**Describe the feature you'd like**

The ability to introduce transparency to the discord pop-out window.

**Comment by Tropix126** [comment]
This can be done with CSS and shouldn't be integrated into the client.

**Comment by Tropix126** [comment]
Give this a try.
```css
.pictureInPictureWindow-1B5qSe {
    opacity:.5;
}
```

**Comment by rauenzi** [comment]
Yes more things should be addons rather than client integrations.
