### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by OhSage** [rauenzi/BetterDiscordApp#481]
I seem to be having this issue that only came up today where when I download and enable 0BDFDB, my discord immediately pops up with the "YOU DIED Looks like you got slaughtered by an Error Level 9000." Therefore, none of the plugins that rely on this one are working. I was just wondering how I could fix this or if it's just an issue on my end because I'm lost and absolutely hate not having certain plugins. I also lost the plugin for a read all button and the plugin that lets you change discord's default sounds, so I was curious about those as well. 
![image](https://user-images.githubusercontent.com/73731183/97771428-14520d80-1afa-11eb-809d-ba2f8e0b6c51.png)

**Comment by rauenzi** [comment]
You need to manually update that plugin and/or wait for the developer of those plugins to fix those issues.

**Comment by OhSage** [comment]
> You need to manually update that plugin and/or wait for the developer of those plugins to fix those issues.

How would I manually update it?
