### ISSUE TITLE
BetterFolders crash[Bug]

### ISSUE THREAD

**Issue by BackslashGamer14** [rauenzi/BetterDiscordApp#485]
**Describe the Bug**
Starting BetterFolders will crash discord 

**To Reproduce**
1. Install the BetterFolders plugin
2. Start it and discord will crash

**Expected Behavior**
Start like normal

**Screenshots**
![image](https://user-images.githubusercontent.com/73790463/97808718-12896680-1c2e-11eb-846d-70f6d4990135.png)

**Discord Version**
Discord Canary 70805 (5b3d626)

**Additional Context**
```
BBD 0.3.5
Host 0.0.284
Injector 0.6.2
Windows 10 64-Bit (10.0.19041
```)

**Comment by rauenzi** [comment]
That's an issue with that plugin, you should go to the github or discord server for it.
