### ISSUE TITLE
[Bug] Ace editor saves but does not load settings

### ISSUE THREAD

**Issue by bonkmaykrQ** [rauenzi/BetterDiscordApp#486]
**Describe the Bug**

Ace CSS editor does not load saved settings.  

**To Reproduce**

Save custom CSS and change any Ace settings, then close.  

**Expected Behavior**

Ace loads your custom CSS file and remembers your Ace editor settings.  

**Discord Version**

Stable 70781 (6d2522f)
BD 1.0.0 (a59e2e4)
Host 0.0.12
Injector 0.6.2
Linux 64-Bit (5.8.13-Arch1-1)

**Comment by Tropix126** [comment]
note that ace will be completely replaced w/ monaco after the beta relase

**Comment by rauenzi** [comment]
This is also not something that BD itself manages.
