### ISSUE TITLE
Sending "valueOf" sends a weird message in chat

### ISSUE THREAD

**Issue by ransbachm** [rauenzi/BetterDiscordApp#495]
**Describe the Bug**
Writing "valueOf" in the chat sends a weird message

**To Reproduce**
Write "valueOf" in a chanel

**Expected Behavior**
Just send the text message

**Screenshots**
![image](https://user-images.githubusercontent.com/25692733/98743051-bb169380-23af-11eb-8896-042b47c11bca.png)

**Discord Version**
Stable

**Additional Context**
Does not happen in vanilla or web discord.

**Comment by rauenzi** [comment]
It's an emote, disable emotes.

**Comment by ransbachm** [comment]
Its not?
