### ISSUE TITLE
[Bug] the side bar with channels doesnt change from theme

### ISSUE THREAD

**Issue by apes0** [rauenzi/BetterDiscordApp#497]
**Describe the Bug**

the side bar with all channels is the default one no matter the theme

**To Reproduce**

enable a theme that changes the side bar

**Expected Behavior**

the side bar should be different, but it stays the same

**Discord Version**
Stable 71447 (29091ef)
BBD 0.3.5
Host 0.0.12
Injector 0.6.2
Linux 64-Bit (5.4.0-52-Generic)

**Comment by rauenzi** [comment]
There was a Discord update and themes need to update to this change.
