### ISSUE TITLE
[Bug]The Theme does not show on the voice chat and text channels on servers (Including Transparency on).

### ISSUE THREAD

**Issue by ChickenFriedWie** [rauenzi/BetterDiscordApp#498]
**Describe the Bug**

**To Reproduce**

**Expected Behavior**

**Screenshots**

**Discord Version**

**Additional Context**

**Comment by rauenzi** [comment]
Wait for your theme to be updated for the latest Discord changes.

**Comment by ChickenFriedWie** [comment]
thank you
