### ISSUE TITLE
Better Discord Mac, Reload screen lock.

### ISSUE THREAD

**Issue by KRUZZZZY** [rauenzi/BetterDiscordApp#499]
When you start better discord with some generic plugins and the clear glass theme, it gets stuck on a screen that simply says reload in the middle. Even if reloaded it just brings you back to the same screen.

To do this, just download it on mac, get some simple quality of life plugins and download the clear glass theme.

It loads and I can access discord.

<img width="1680" alt="Screenshot 2020-11-14 at 11 07 45" src="https://user-images.githubusercontent.com/74453315/99145817-afee8c80-2669-11eb-857a-1718700c73bc.png">

Stable version.

I am not on the latest Mac OS release that came out a few days ago, however, the problem was occurring before this

**Comment by Tropix126** [comment]
This is a plugin-specific issue.
![image](https://user-images.githubusercontent.com/42101043/99162432-63d03600-26c3-11eb-9e6a-458221565e7a.png)
