### ISSUE TITLE
LUL not working

### ISSUE THREAD

**Issue by oski165** [rauenzi/BetterDiscordApp#5]
It's not working

**Comment by Modder4869** [comment]
LUUL , smh

**Comment by intrnl** [comment]
You know that's not helpful at all right.

Well, there's an issue relating to the recently pushed commit which added the ability to save settings asynchronously.

The current workaround for now would be to remove the `user.json` and `bdsettings.json` from `%appdata%/BetterDiscord` folder and then restarting Discord. It's not permanent, but a workaround nevertheless.

**Comment by Inve1951** [comment]
BD requires a minimum of 4 letters for emotes, shorter ones are ignored

**Comment by intrnl** [comment]
Well, considering how vague the issue's name and description was.

Oh well, ¯\_(ツ)_/¯

**Comment by rauenzi** [comment]
Emotes less than 4 characters are ignored
