### ISSUE TITLE
Bandaged discord doesn't download (Solved Can be closed)

### ISSUE THREAD

**Issue by timbooo1** [rauenzi/BetterDiscordApp#50]
![jpeg_20180824_140940](https://user-images.githubusercontent.com/42674311/44585648-5611fb80-a7ad-11e8-9023-c972507217aa.jpg)
This happens with both the no admin installer used with and without admin privileges and the normal launcher with and without admin privileges. It's just stuck at Downloading to >user/blabla/blabla/blabla. As you can see in the image. Anyone has had this issue before? 

No antivirus is running as I turned those off beforehand to prevent this kind of things. Yet this is still happening. I also used the file outside of the downloads folder and used it from the desktop.

**Comment by intrnl** [comment]
Redownload the installer from [here](https://github.com/rauenzi/BetterDiscordApp/releases/latest), move it to another folder such as your Desktop, and run it as usual.

**Comment by timbooo1** [comment]
https://gyazo.com/f439bbdb7f74697a6097f6469992d972 Results in exactly the same thing. Those are the installers I was using.

**Comment by rauenzi** [comment]
Would be an issue on your side then, haven't had many reports of this and when there were it was due to their internet/firewall type things

**Comment by timbooo1** [comment]
That's very strange. Cause I totally turned off my firewall and antivirus to negate those issues in the first place. I'm doing my best at the moment to see if it was a system locale issue cause I had it set to united kingdom for some reason. I did reinstall my laptop yesterday. So it could be something with that.

**Comment by timbooo1** [comment]
I just checked if setting up my own local ip as the dmz host on my modem to circumvent the firewall of the network itself. Even this did not help. All my firewalls and antivirusses are down right now. Everything is open. And I mean literally everything.

**Comment by timbooo1** [comment]
Is there a way for me to manually install it?

**Comment by Modder4869** [comment]
You have to disable it not just turning off your anti-virus if that didn't work then use resources monitor to find if there is process using that folder or something

**Comment by timbooo1** [comment]
I deinstalled it.

**Comment by timbooo1** [comment]
Aka, I have no anti virus running. And that folder is not in use by anything.

**Comment by timbooo1** [comment]
So I guess there isn't a way to manually install this? Like place the files where they are supposed to go.

**Comment by timbooo1** [comment]
So apparently I should take note that if a windows 8.1 computer is not fully updated it inhibits the download from certain programs. Fucking windows updates were the problems. We can close this issue now. I have fixed it :D
![image](https://user-images.githubusercontent.com/42674311/44660827-2828f300-aa09-11e8-9eda-77014b1f16cf.png)

**Comment by intrnl** [comment]
You can pretty much close this issue by yourself since this is your issue afterall.
