### ISSUE TITLE
Close this threat please 

### ISSUE THREAD

**Issue by xdjoee** [rauenzi/BetterDiscordApp#504]
**Describe the Bug**
I get a popup where it says "A javascript error occurred in the main process  C:\ProgramData\kobos\Discord\app-0.0.308\resources\app\betterdiscord\config.json: Unexpected token"

**To Reproduce**
When I open discord

**Expected Behavior**
For discord to open normally

**Screenshots**
https://prnt.sc/vk3urv

**Discord Version**
Latest?

**Additional Context**
I have tried repairing bd but it doesnt fix it. When i tried re installing discord it got rid of all of my plugins except for when i open discord from the shortcut i already had. Atleast tell me the directory so i can get my themes back cause i dont remember where i got them from.

**Comment by l0c4lh057** [comment]
First, it is a JavaScript error, not a Java error. And second, to fix the issue you probably have to delete (or rename/move) the file it shows you in that message.

**Comment by xdjoee** [comment]
> First, it is a JavaScript error, not a Java error. And second, to fix the issue you probably have to delete (or rename/move) the file it shows you in that message.

I typed javascript error lol

**Comment by xdjoee** [comment]
i just reinstalled the whole thing please close this

**Comment by notnicknamed** [comment]
Guys I'm having the same problem. I don't want to have to reinstall the whole thing.
