### ISSUE TITLE
[Bug] [BBD Beta] ".jumboable" class isn't properly applied to BD emotes.

### ISSUE THREAD

**Issue by Tropix126** [rauenzi/BetterDiscordApp#508]
**Describe the Bug**
When a normal emoji is posted in chat, there is a class applied to differ whether it's a large emoji (jumboable), or an inline emoji. Looking through the js, there seems to be code in place to add this class, but it's probably years out of date. This causes emotes to be improperly sized when posted individually.

**To Reproduce**
Post an individual BD emote in chat with no extra characters and check it's classname. 

**Expected Behavior**
When an emote or emotes are posted with no text content, apply the jumboable class and scale up the dimensions.

**Screenshots**
![image](https://user-images.githubusercontent.com/42101043/99888492-e5b7e600-2c12-11eb-8356-a029ed12231e.png)

**Discord Version**
Canary 72074 (5f5d3f6)
BBD Beta (development branch). Applies on master branch as well.

**Additional Context**

**Comment by Tropix126** [comment]
Update: This appears to only happen on canary. Haven't tested PTB.

**Comment by rauenzi** [comment]
Fixed for next release
