### ISSUE TITLE
[Bug] 404 links for plugins and themes

### ISSUE THREAD

**Issue by steamsyyy** [rauenzi/BetterDiscordApp#512]
**Describe the Bug**

When you don't have any plugins or themes installed, the link in "Grab some from this website and add them to your plugin folder." send you to a 404 page.

**To Reproduce**

Use beta version of the app, and don't have any plugins or themes installed

**Expected Behavior**

Open the correct website

For example, instead of opening

https://betterdiscordlibrary.com/plugin

open

https://betterdiscordlibrary.com/plugins

**Discord Version**

Stable

**Additional Context**

Using beta BDA

**Comment by rauenzi** [comment]
Is this still occurring, I thought I had changed this.

**Comment by steamsyyy** [comment]
Not anymore

**Comment by steamsyyy** [comment]
Actually, after I restarted the Discord app it seems to still be broken

**Comment by rauenzi** [comment]
This was fixed in the latest versions
