### ISSUE TITLE
Bandaged BD stopped loading

### ISSUE THREAD

**Issue by BossBreh** [rauenzi/BetterDiscordApp#513]
I started up discord today, and BD was not integrated/injected (or whatever you want to call it.) I tried a reload and still didn't inject. i checked and all of the files are still there. Is it abandoned?

**Comment by jlortiz0** [comment]
Using the repair tool included with the installer fixed it for me.

**Comment by shotbyapony** [comment]
> Using the repair tool included with the installer fixed it for me.

fixed for me too, thanks!

**Comment by rauenzi** [comment]
Yep just need to reinject. Not sure how you would surmise that this project has been abandoned...
