### ISSUE TITLE
Discord Launcher Error Starting After Update

### ISSUE THREAD

**Issue by CodeEasyYT** [rauenzi/BetterDiscordApp#514]
**Describe the Bug**
This bug just appeared from no where. I was just starting discord,
it updated, and now it instantly crashes.

**To Reproduce**
Sorry, but I dunno how to reproduce hope screenshot can help.

**Expected Behavior**
Just start as usual.

**Screenshots**
![image](https://user-images.githubusercontent.com/59538669/101728588-b4bb2a80-3ac7-11eb-95b9-cee496a08827.png)

**Discord Version**
Stable

**Additional Context**
None

**Comment by CodeEasyYT** [comment]
Please, I can not open discord.

**Comment by UltraBlackLinux** [comment]
Reinstall discord, rerun the installer.

**Comment by CodeEasyYT** [comment]
Reinstalling didn't work, I ended up installing beta version (PTB) version.
Closing issue.
