### ISSUE TITLE
[Bug]Installer crashing

### ISSUE THREAD

**Issue by Wolferal** [rauenzi/BetterDiscordApp#516]
**Describe the Bug**
Installer crashed after a few seconds after startup

**To Reproduce**
Open the installer

**Expected Behavior**
Can choose to install/repair/delete

**Screenshots**
(video)https://drive.google.com/file/d/1-gTiBgUk6of9D85mOyhoRUHDU0Y0g-l8/view?usp=sharing

**Discord Version**
Stable

**Additional Context**
I can still install it if I click fast enough and that's what I did, but I still wanna know how to fix it.

**Comment by Strencher** [comment]
Can you upload the video to discord and send the directly link here? we don't have access to this Google Drive Repo.

**Comment by Wolferal** [comment]
Hello!
I did some research and found out the cause of the crash is Asus GPU Tweak II's monitor.
I deleted the app and the updater worked. 
Thanks and sorry for bothering.
