### ISSUE TITLE
[Bug]BetterDiscord disappears several times

### ISSUE THREAD

**Issue by Physalia77** [rauenzi/BetterDiscordApp#517]
So every now and then BetterDiscord just disappears from my discord and I have to install BetterDiscord over again. This happens maybe once every week, it's not that bad but it's getting very annoying.

I don't know if the problem is on my side or the development side, thanks for your time!

**Comment by Vsyncrooo** [comment]
Got same issue here. Began happening since last update

**Comment by rauenzi** [comment]
It shouldn't occur this frequently on stable Discord. It can occur frequently on Canary/PTB though. You didn't use the issue template and I have no version information for this issue.
