### ISSUE TITLE
It Doesn't Work No More

### ISSUE THREAD

**Issue by Musicmanlogo** [rauenzi/BetterDiscordApp#52]
When I Updated Discord It Removed Better Discord and Then I Installed It Again It Didn't Work When It Finished

**Comment by EllexideCodes** [comment]
Here, here. I just restarted my computer today and now it won't work.

**Comment by EllexideCodes** [comment]
I did. I've been doing it repeatedly since last night. I run it as Admin. I tried the non admin exe file. I did as instructed and moved it out of downloads. It says the installation is complete but BD is not on Discord

**Comment by EllexideCodes** [comment]
@Lubieerror

**Comment by Musicmanlogo** [comment]
okay

**Comment by Musicmanlogo** [comment]
ok
