### ISSUE TITLE
Hide/show channel list.

### ISSUE THREAD

**Issue by Drexl** [rauenzi/BetterDiscordApp#523]
I'm using the beta branch and see no option to hide the channel list. I'd like a button to hide/show the channel list like I can with the user list.

**Comment by Tropix126** [comment]
This is also a plugin. [https://betterdiscordlibrary.com/plugins/Hide%20Channels](https://betterdiscordlibrary.com/plugins/Hide%20Channels)

**Comment by Drexl** [comment]
Thanks. ^_^
