### ISSUE TITLE
Decrease minimum window width

### ISSUE THREAD

**Issue by Drexl** [rauenzi/BetterDiscordApp#524]
I'd like the minimum window width to be much smaller than it is. Ideally, assuming the user list is hidden and (eventually, hopefully) the channel list as well a 400px wide window will fit perfectly in the space I want it to and still display all the text I need.

**Comment by Tropix126** [comment]
This is already available through a plugin, and probably should be left to it..

**Comment by Drexl** [comment]
Thanks. I was confused because the home page doesn't list where to get plugins clearly. In fact, is sort of made it sound like there is no official list of plugins. I didn't realize the rauenzi maintains a list of plugins on another repo.
