### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by JanzenJohn** [rauenzi/BetterDiscordApp#529]
**Is your feature request related to a problem? Please describe.**

**Describe the feature you'd like**

 Background transparency blur

**Additional context**
The Transparency Feature can't blur the background right now, wich makes Discord fit in less with the other transparent and blurred applications I use

**Comment by Lucasamiel0406** [comment]
You can use CSS for that, getting the lowest class and then adding blur to it.

**Comment by JanzenJohn** [comment]
How would I do this ? I don't work much with CSS and didn't find something about a lowest class

**Comment by rauenzi** [comment]
Use a 3rd party alternative like Glasscord.
