### ISSUE TITLE
Emotes from alternating emote categories not working

### ISSUE THREAD

**Issue by Lombra** [rauenzi/BetterDiscordApp#53]
When posting a message containing emotes from alternating emote sets, it doesn't seem to work as intended. For example this message:
`Kappa KappaCool Kappa KappaCool Kappa KappaCool`
It seems to be a bit "random" which category works, but for me all the Kappas (Twitch global) work, but only the last KappaCool. (BTTV) Sometimes the message is fixed later when new messages are posted.

**Comment by rauenzi** [comment]
Yeah it's a bit finicky for some reason. If you switch channels and come back it should look fine. This is unfortunately low on the priority list as it is mostly cosmetic and I have other things to work on.
