### ISSUE TITLE
[Bug] Whenever I download for mac it says “BandagedBD” cannot be opened because the developer cannot be verified.

### ISSUE THREAD

**Issue by jackpanda7** [rauenzi/BetterDiscordApp#532]
**Describe the Bug**
Makes me delete it because it says “BandagedBD” cannot be opened because the developer cannot be verified.

**To Reproduce**
Please fix this

**Expected Behavior**
I thought it would work because I turned off my firewall

**Screenshots**
None.

**Discord Version**
Stable

**Additional Context**

**Comment by ObserverOfTime** [comment]
> In macOS Catalina and macOS Mojave, when an app fails to install because it hasn’t been notarized or is from an unidentified developer, it will appear in System Preferences > Security & Privacy, under the General tab. Click Open Anyway to confirm your intent to open or install the app.
> The warning prompt reappears, and you can click Open.

https://support.apple.com/en-us/HT202491

**Comment by rauenzi** [comment]
Please see that answer above.
