### ISSUE TITLE
[Bug] Auto Maximize Snap Not Working (Windows)

### ISSUE THREAD

**Issue by patrickh39** [rauenzi/BetterDiscordApp#534]
**Describe the Bug**
Usually on any Windows application, you can bump the window to the top, left, right of your screen to auto fullscreen or scale with which window you want but it is not working on BetterDiscord.

**To Reproduce**
Try to bump the window to the top or sides of your screen with BetterDiscord injected.

**Expected Behavior**
The below GIF is the expected behaviour. Installing BetterDiscord breaks that function. This GIF was recorded without BetterDiscord installed.
![1a2d988cd2ab74bbed7e6a1f961cf17c](https://user-images.githubusercontent.com/61527626/104074734-b3177c00-51c5-11eb-8512-492ee64c7253.gif)

**Screenshots**
This is what happens instead of the expected behaviour. This GIF was recorded with BetterDiscord installed.
![ezgif-3-96bf42111b1c](https://user-images.githubusercontent.com/61527626/104074567-4d2af480-51c5-11eb-922a-ee5eb401a2ab.gif)

**Discord Version**
Stable

**Additional Context**
Stable 74090 (e293442)
BBD 0.3.5
Host 0.0.309
Injector 0.6.2
Windows 10 64-Bit (10.0.19042)

**Comment by rauenzi** [comment]
This is a side effect of enabling the "transparent window" setting. It is an issue with electron itself and not something I can fix. If you'd like to restore that functionality, disable that setting.
