### ISSUE TITLE
Support discord_arch_electron aur package

### ISSUE THREAD

**Issue by advaithm** [rauenzi/BetterDiscordApp#536]
**Is your feature request related to a problem? Please describe.**

discord arch electron is a aur(arch users repository) build of discord that patches discord to use the system version of electron which fixes some issues and improves the performance of discord. when I attempt to install betterdiscord via `betterdiscordctl` and pointing it to the location of discord with the patches(`/usr/lib/discord/`) a error about `injector.js `not being found is shown. I would like betterdiscord to support this patched version as it feels like it would be the best version of discord too me

**Comment by rauenzi** [comment]
Perhaps @ObserverOfTime would have some insight towards this as `betterdiscordctl` is their installer and I am unfamiliar with linux discord.

**Comment by ObserverOfTime** [comment]
See bb010g/betterdiscordctl#84. I can't fix it but if someone finds a way, do submit a pull request.

**Comment by rauenzi** [comment]
@advaithm if you could provide more information on the structure of how the `discord_arch_electron` package works, such as where the discord modules are stored (specifically `discord_desktop_core`), that would help move this along. I am going to move this over to the installer repository as it more likely requires a change there than here.

**Comment by rauenzi** [comment]
I guess GitHub won't let me transfer it for whatever reason... So @advaithm please open a new issue at https://github.com/BetterDiscord/Installer with the information above

**Comment by advaithm** [comment]
I've moved to powercord but it should be pretty easy to figure it out based on the PKGBUILD, its a bash scripts. functions are called in the order of prepare()->packager()
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=discord_arch_electron

**Comment by ObserverOfTime** [comment]
Submitted in BetterDiscord/Installer#41.
