### ISSUE TITLE
[Bug] Cannot find module when using manual installation on Windows

### ISSUE THREAD

**Issue by steamsyyy** [rauenzi/BetterDiscordApp#538]
**Describe the Bug**
Dependency issue when using the manual Windows installation instead of the .exe

**To Reproduce**
Follow the manual Windows installation guide, or in an elevated Powershell prompt:

```powershell
Set-Location "C:\Windows\Temp"
Invoke-WebRequest -Uri https://github.com/rauenzi/BetterDiscordApp/archive/injector.zip -OutFile "injector.zip"
Expand-Archive -LiteralPath "C:\Windows\Temp\injector.zip" -DestinationPath "C:\Windows\Temp"
Rename-Item "C:\Windows\Temp\BetterDiscordApp-injector" "C:\Windows\Temp\app"
Set-Location $env:LOCALAPPDATA; Set-Location ".\Discord\app*\resources"
Remove-Item "./app*" -Recurse -ErrorAction Ignore
Move-Item "C:\Windows\Temp\app" .
Stop-Process -Name "Discord" -Force
Start-Process "../discord.exe"
```

**Expected Behavior**
Read from `%APPDATALOCAL%\Discord\app*\resources\app\` instead of   `%APPDATALOCAL%\Discord\app*\resources\app.asar\`

**Screenshots**
![image](https://user-images.githubusercontent.com/54457902/104691726-68699880-56cc-11eb-9614-34b7bebc2a2b.png)

**Discord Version**
Latest Stable version

**Comment by steamsyyy** [comment]
This is the conflicting code:

```javascript
// Use Discord's info to run the app
if (process.platform == "win32" || process.platform == "darwin") {
    const basePath = path.join(__dirname, "..", **"app.asar"**);
    const pkg = require(path.join(basePath, "package.json"));
    electron.app.setAppPath(basePath);
    electron.app.name = pkg.name;
    Module._load(path.join(basePath, pkg.main), null, true);
}
```

Maybe changing `app.asar` to just `app` will fix the problem.

**Comment by rauenzi** [comment]
> Read from `%APPDATALOCAL%\Discord\app*\resources\app\` instead of `%APPDATALOCAL%\Discord\app*\resources\app.asar\`

The error from the screenshot indicates it is correctly loading from `%APPDATALOCAL%\Discord\app*\resources\app\`. However when trying to grab some data from the Discord package (in `%APPDATALOCAL%\Discord\app*\resources\app.asar\`) it fails because you deleted the `app.asar` package with this command:

```powershell
Remove-Item "./app*" -Recurse -ErrorAction Ignore
```

Whereas the manual instructions explicitly state to remove an existing folder called `app`.

Restore the `app.asar` and your issue is resolved.
