### ISSUE TITLE
Discord completely closes when using Shift+Enter

### ISSUE THREAD

**Issue by JG-GIT** [rauenzi/BetterDiscordApp#540]
**Describe the Bug**

Whenever I use Shift+Enter for a new line, it closes Discord. No crash message, no crash log, not even a warning.
After reinstalling BandagedBD, Discord will completely fail to open. It won't even make it past the first second of loading.

**To Reproduce**

Shift+Enter. I can't find the exact conditions that this started on, but it started an hour ago.

**Expected Behavior**

I was expecting it to make a new line in my message.

**Screenshots**

**No screenshots available.**

**Discord Version**

Canary. Testing with Stable lead to no bugs.

**Additional Context**

I had installed a plugin that was meant to unlock localStorage before BBD could secure it, but the bug suddenly started after about 3 months of usage. It did work, but this bug just sprouted from nonexistence on Canary.

**Comment by VistaOnTen2007** [comment]
Same here, its also happen when you type a Longer message.

**Comment by Masono03** [comment]
same here also does it when i go into the custon css section of the options.

**Comment by TheLetslook** [comment]
Same here. 

Canary 74763 (e08c4da)
BBD 0.3.5
Host 1.0.17
Injector 0.6.2
Windows 10 64-Bit (10.0.19042)

**Comment by khuldraeseth** [comment]
Same here.

Canary 74766 (1425870)
BBD 0.3.5
Host 0.0.116
Injector 0.6.2
Linux 64-Bit (5.10.6-Arch1-1)

**Comment by JG-GIT** [comment]
I completely reinstalled Discord Canary, and reinstalled BBD. It worked until it refreshed, where the newline bug returned. An update pushed, and Discord Canary is back to being unusable.

**Comment by JG-GIT** [comment]
Re-comment: It's probably due to the CSS change in Canary (issue #541).
Conclusion: Rewrite the CSS for Canary injections, and close once finished.

**Comment by TheyNay** [comment]
My Discord also crash without log or warning, but I'm on Stable. Whenever I shift+enter, my client completely close and it happens again and again. I still don't know the issue or how to resolve it. Can we have a support?

**Comment by rauenzi** [comment]
Try reinstalling BD, your injector may be an old version

**Comment by TheyNay** [comment]
> Try reinstalling BD, your injector may be an old version

It worked, thanks (I never would have thought of it ^^")
