### ISSUE TITLE
[Bug] BDFDB Causing startup crash loop

### ISSUE THREAD

**Issue by UltraBlackLinux** [rauenzi/BetterDiscordApp#544]
**Describe the Bug**
The BDFDB library is recently causing a crash loop when starting up discord. It's trying to load the library, and is instandly crashing, and restarting. It works when starting discord via the terminal, for some weird reason.

**To Reproduce**
Install BDFDB

**Expected Behavior**
Just start up

**Discord Version**
Stable

**Additional Context**
Manjaro Linux, 64 Bit
BBD 0.3.5 Stable

**Comment by rauenzi** [comment]
Issues with BDFDB should be directed to the creator at the library's location here: https://github.com/mwittrien/BetterDiscordAddons
