### ISSUE TITLE
[Feature] Text replacement

### ISSUE THREAD

**Issue by Aurora-Aureus** [rauenzi/BetterDiscordApp#545]
**Is your feature request related to a problem? Please describe.**
 So this is less of a feature request, I just don't know what else to tag this.
I want to make a plugin which displays certain words as other, something like: person a writes keyword, person b(with the plugin enabled) receives message with keyword but it gets replaced with another, specified, word.
Is this even possible?

**Describe the feature you'd like**

**Additional context**

**Comment by Infinidoge** [comment]
There is actually a plugin already capable of this, [ChatFilter by mwritten](https://github.com/mwittrien/BetterDiscordAddons/tree/master/Plugins/ChatFilter) being the one I perticularly remember

You can probably look through the plugin file there to see how they accomplish it

**Comment by Aurora-Aureus** [comment]
Thank you very much!

**Comment by MahdeenSky** [comment]
Opening this thread as I've created a plugin that basically replaces text using regex before your message is sent.
[TextReplacer by Me](https://github.com/MahdeenSky/BDPlugins/tree/main/TextReplacer).
