### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by LilTruck** [rauenzi/BetterDiscordApp#546]
**Describe the Bug**

I get this message when i try to download The BBD On My Laptop "Download seems to have failed, will try once more." But After i get this message it trys to reinstall once again but i get this other message "Download error: The underlying connection was closed: An unexpected error occurred on a send." .

**To Reproduce**
 i dont know .

**Expected Behavior**
 Wont Let me Download

**Screenshots**
 
![image](https://user-images.githubusercontent.com/77990283/105757423-607ce480-5f67-11eb-9d99-3cbe9dde9c21.png)

**Discord Version**
 Stable , PTB

**Additional Context**
 As You Said On The Project to move the file to a file that isnt "DOWNLOADS" i did that but still same problem

**Comment by rikusen0335** [comment]
Could you try this installer: https://github.com/rauenzi/BBDInstaller/releases/tag/v1.0.5

**Comment by rauenzi** [comment]
Make sure you use the latest installer and can connect to that endpoint in your region.
