### ISSUE TITLE
So.. this is your discord support server?

### ISSUE THREAD

**Issue by JoeyDagger** [rauenzi/BetterDiscordApp#547]
![2](https://user-images.githubusercontent.com/67937427/106178187-4e10cf80-614e-11eb-8319-a98a5d11f9f0.PNG)
![Capture](https://user-images.githubusercontent.com/67937427/106178191-4ea96600-614e-11eb-94ea-8efb8fc60675.PNG)

**Comment by rauenzi** [comment]
Nope

**Comment by JoeyDagger** [comment]
> 
> 
> Nope

That's where this sent me
![image](https://user-images.githubusercontent.com/67937427/106179408-dc398580-614f-11eb-8f4d-a446f43ad745.png)

**Comment by rauenzi** [comment]
That's not my website, that's run by someone else.

**Comment by JoeyDagger** [comment]
Why does this button send me there then
![image](https://user-images.githubusercontent.com/67937427/106179748-510cbf80-6150-11eb-8a22-0703e93cc35f.png)

**Comment by rauenzi** [comment]
Because it is a community tool.

**Comment by JoeyDagger** [comment]
Maybe concider changing or removing it

**Comment by rauenzi** [comment]
As I said, it is not my site to change, the information on there has been helpful to users.

**Comment by JoeyDagger** [comment]
Not as in change the site. As in the program. Maybe add some information on the program instead of having a misleading link. Just a suggestion so this wouldn't happen again.

**Comment by rauenzi** [comment]
The link isn't misleading, it still goes where it intends to.

**Comment by JoeyDagger** [comment]
> 
> 
> The link isn't misleading, it still goes where it intends to.

The discord link though does not go to the intended place however. Possibly add a disclaimer for people going to the website for help and their problem isn't listed, as the discord server link is where it advises them to go.

**Comment by intrnl** [comment]
That server either just happened to stumble upon the invite code we had previously or it's a vanity code given all the boosts it has, will be replacing it later

For now, the support server invite is https://discord.gg/sbA3xCJ

**Comment by JoeyDagger** [comment]
Woah. Thanks for being helpful intrnl. Much appreciated.
