### ISSUE TITLE
[Bug] BetterDiscord incompatible with Canary & PTB

### ISSUE THREAD

**Issue by JoeyDagger** [rauenzi/BetterDiscordApp#548]
On the latest Canary version of Discord, every time I select install or repair on Canary and it runs through it's process, it has been completely unusable. I'm not sure what happened but it all started maybe during the last weekend if I remember correctly. 

There's multiple problems that this causes that makes it practically useless. The first few obviously noticeable problems I'm having is that the zoom is incredibly high and can't be changed and it has no bar at the top to close, maximize, or minimize. I am permanently muted and can't unmute myself. Going into settings shows that discord doesn't pick up any of my microphones or my camera. Not to mention none of my settings are able to be changed and do anything in reference to my audio or size. In the bottom images, it also shows that my discord is acting like it's open in a browser tab instead of the actual app which is absolutely unbelievable. 

When I try and join a call or server voice channel, I doesn't say I'm connected in the badge on my taskbar with the green circle. Not to mention I can hear them still, but still can't unmute or say anything. And on top of all that, in settings, it doesn't even show that BandadgedBD is even installed.

Now despite all of this, regular discord surprisingly works just fine. Nothing has changed at all for it. I even tried uninstalling, ridding of all of my plugins and themes, etc. Doing the same for both has done nothing to fix Canary and regular Discord still works just like how it and Canary is supposed to.

![image](https://user-images.githubusercontent.com/67937427/106179829-6da8f780-6150-11eb-8c4a-ad5a723471b5.png)
![image](https://user-images.githubusercontent.com/67937427/106180379-0e97b280-6151-11eb-9a6f-4c7e153dccfc.png)
![image](https://user-images.githubusercontent.com/67937427/106181267-3dfaef00-6152-11eb-8978-647f575bb664.png)
![image](https://user-images.githubusercontent.com/67937427/106181399-65ea5280-6152-11eb-8d31-7b57ceddea83.png)
![image](https://user-images.githubusercontent.com/67937427/106181427-6edb2400-6152-11eb-92d9-72a348d59ecc.png)
![image](https://user-images.githubusercontent.com/67937427/106183932-bd3df200-6155-11eb-8c0d-fbb0d8a68f60.png)
![image](https://user-images.githubusercontent.com/67937427/106183960-c5962d00-6155-11eb-8cec-ad18b75a9dbe.png)
![image](https://user-images.githubusercontent.com/67937427/106184327-3b9a9400-6156-11eb-9e57-6266fbaef491.png)

**Comment by rauenzi** [comment]
Correct, BD is incompatible with latest Canary.

**Comment by JoeyDagger** [comment]
Not entirely, my girlfriend is actually using canary too and it works just fine.

**Comment by rauenzi** [comment]
Then their Canary is not at the latest host version.

**Comment by kamil2289** [comment]
Not working for me on Canary, latest Host Version: 1.0.21

**Comment by Nxybi** [comment]
Not working for me either, latest Host version: 1.0.21
Kinda annoying because I don't really wanna switch to PTB/Stable

**Comment by rauenzi** [comment]
It will be some time before it works on Canary again, so if you want to use BD, switch to either stable or ptb.

**Comment by Ghost-Bit** [comment]
Same here, gonna have to wait i suppose

**Comment by rauenzi** [comment]
That's more or less what I just indicated.

**Comment by JoeyDagger** [comment]
Relax. People are just confirming that they too have an issue and it doesn't work for them either and subscribing to the thread.

**Comment by rauenzi** [comment]
Users are much better off indicating they face a similar issue by reacting with 👍 to the original issue post. They can also click the button on the right hand side if they wish to subscribe to the issue.

**Comment by JoeyDagger** [comment]
Some people want to be noticed. The more widespread a problem is the more important it seems to people. Let people feel important.

**Comment by rauenzi** [comment]
Sorry, that's not what Github issues are for.

**Comment by rauenzi** [comment]
For those that want more information on what the underlying issues are, you can read some discussion in #442 and also in [this issue](https://github.com/powercord-org/powercord/issues/386#issuecomment-690740610) in the powercord repo.

**Comment by rauenzi** [comment]
This has finally been fixed. You can install the new version using https://github.com/BetterDiscord/Installer
