### ISSUE TITLE
Not Working Anymore

### ISSUE THREAD

**Issue by LotteBestGirl** [rauenzi/BetterDiscordApp#55]
When i try to install, it just says that is extracting core.asar and never ends it, what happened?

**Comment by intrnl** [comment]
Redownload the [installer](https://github.com/rauenzi/BetterDiscordApp/releases/latest), and move it to another folder before running it with or without administrator rights.

**Comment by ggukbloom** [comment]
it seems to be funny with me too. sometimes it works then it breaks. but for the past 2 weeks it hasnt worked at all and ive tried everything :(
