### ISSUE TITLE
What the Discord link for the support server?

### ISSUE THREAD

**Issue by martinGITHUBER** [rauenzi/BetterDiscordApp#550]
The Discord Link that is provided in the Wiki leads to a bird emoji server where I can't chat... I'm confused

**Comment by dav1312** [comment]
Nice "bug"... don't open a Github issue for this... you are just wasting your time and devs time that could be user for something else

discord.gg/0Tmfo5ZbOR8bKrMJ

**Comment by intrnl** [comment]
Duplicate of #547

The new invite for the support server is https://discord.gg/sbA3xCJ
