### ISSUE TITLE
Plugins Wont Install or Load when placed Into the plugins folder

### ISSUE THREAD

**Issue by Warblingpants67** [rauenzi/BetterDiscordApp#553]
None of the plugins I place into the folder will load into BD. When I try to run the plugins to install them, It says that it cannot find the plugin folder. I have tried refreshing discord after putting the plugins into the folder. I had these exact same plugins working before. I have no idea how to recreate this, and this issue persists after deleting and reinstalling discord and BD multiple times. The only thing that could possibly have messed up something is installing a Java IDE, but I've never messed with any settings regarding java files.

**Comment by rauenzi** [comment]
Please follow the issue template and provide the important information asked for there. You are not supposed to run plugins, you are supposed to put them in the folder yourself.
