### ISSUE TITLE
[Bug] Crashing with screenshare

### ISSUE THREAD

**Issue by UltraBlackLinux** [rauenzi/BetterDiscordApp#554]
**Describe the Bug**
BD is crashing when I am screensharing a program, I have no clue why :/
I removed all my plugins, and it's still broken.

**To Reproduce**
Screenshare

**Expected Behavior**
obvious

**Discord Version**
Stable 75681 (2b1749b)

**Additional Context**
I got that one google material design installed, you can get via the theme repo

**Comment by rauenzi** [comment]
This will be pushed out until after the restructure

**Comment by UltraBlackLinux** [comment]
also @rauenzi If you are still somewhat interested, when this crash is happening, I got some better infos now:
BD crashes discord, when the screenshared window looses focus or gets closed (was able to reproduce with minecraft)
