### ISSUE TITLE
[Feature] Allow changing date format in settings

### ISSUE THREAD

**Issue by PreciousWarrior** [rauenzi/BetterDiscordApp#558]
**Is your feature request related to a problem? Please describe.**
Yeah, I don't live in the US and since I look at old messages to refer back to something, the format of mm/dd/yyyy is very frustrating to deal with, and I've made mistakes referring back to the wrong date because of this format.

**Describe the feature you'd like**
I'd like a feature (very similar to enable 24 hour timestamps) in BD settings, where when enabled, changes the date format to dd/mm/yyyy for messages older than yesterday. It could be placed right below the "24 hour timestamp" setting.

**Additional context**
none

**Comment by HitGub-Shiro** [comment]
Add custom Layout so you could do stuff like "(dd) of (mm) or somethin in year (yyyy)" im sure people can some up with weird stuff.

**Comment by mwittrien** [comment]
A plugin for that exists CompleteTimestamps

**Comment by rauenzi** [comment]
I think this is better left to plugins like the one mentioned above.
