### ISSUE TITLE
[Bug] Setting: "Hide Gift button" doesnt seem to work.

### ISSUE THREAD

**Issue by Marfjeh** [rauenzi/BetterDiscordApp#559]
**Describe the Bug**
In settings there is an option for `Hide Gift button` doesn't seem to work.

**To Reproduce**
Open settings > BetterDiscord > Settings > Hide gift button. enable it. 
Then go back, to a text channel. 

**Expected Behavior**
After toggling `Hide gift button` the button should be gone in the text area. 

**Screenshots**
![image](https://user-images.githubusercontent.com/10206878/107854000-5d17a300-6e19-11eb-8aff-e1f1261685e7.png)
![image](https://user-images.githubusercontent.com/10206878/107854011-6c96ec00-6e19-11eb-89ca-2fe83986ba82.png)

**Discord Version**
Stable.
I'm using the beta version of BD. only version string I could find is below here.
```
Stable 76771 (f5e89dd)
BD 1.0.0 (086482f)
Host 0.0.13
Injector 0.6.2
Linux 64-Bit (5.9.16-1-MANJARO)
```

**Additional Context**
I have enabled those settings in betterdiscord:
(Apperance)
* 24-hour Timestamps
* Hide gift button
* Minimal Mode
* Dark Mode

**Comment by Marfjeh** [comment]
You can however select the button with:

Forexample in JS
```JS
document.querySelector("#app-mount > div.app-1q1i1E.da-app > div > div.layers-3iHuyZ.da-layers.layers-3q14ss > div > div > div > div > div.chat-3bRxxu.da-chat > div > main > form > div > div > div > div > div > div.buttons-3JBrkn.da-buttons > button")
```
so probably discord may changed the classes for the text area buttons?

**Comment by Strencher** [comment]
Yes, discord updated their textarea recently which broke that setting. Please be patient for fixes.

Also: We didn't use classNames for that, we patched the react component and removed that children.

**Comment by Marfjeh** [comment]
Alrighty, just wanted to report it. 

and I didnt know you're using the react component instead, i'm not familair with react, but only wanted to help really.

**Comment by shinji257** [comment]
I'm just going to note that the Show GIF option is also affected but likely due to the same reason.

**Comment by Strencher** [comment]
Yes, maybe the next updates includes a fix for both settings.

**Comment by rauenzi** [comment]
This has been fixed in the latest update.

**Comment by cmd430** [comment]
This has broken again with the latest Discord update

**Comment by programmer2514** [comment]
As a workaround until it's fixed, adding this to your custom CSS should hide both buttons:
```
/* Hides the gift button */
[aria-label="Send a gift"] {
    display: none;
}

/* Hides the GIF button */
[aria-label="Open GIF picker"] {
    display: none;
}
```
