### ISSUE TITLE
Account-Bound-Settings(idea, local)

### ISSUE THREAD

**Issue by EngineLessCC** [rauenzi/BetterDiscordApp#56]
Could you add a feature what keeps themes, plugins and settings of each discord account seperated?
Im using Discord-Stable and DiscordCanary and each of them uses a different account, but have to use the same theme and plugin.

**Comment by rauenzi** [comment]
Ah that was an oversight on my part a long while ago, they should be different per-installation so stable and canary should have different settings. Will fix at some point.
