### ISSUE TITLE
discord server is replaced by bird emoji?

### ISSUE THREAD

**Issue by eksynn** [rauenzi/BetterDiscordApp#560]
what happened to the server? the invite link on the twitter account, as well as the one on discord itself, leads to a bird emoji server, with nothing but bird emojis. can we get this updated soon?

**Comment by Tropix126** [comment]
Some idiots got their server boosted, then claimed the old invite as their vanity URL. New invite => https://discord.gg/sbA3xCJ

**Comment by eksynn** [comment]
that's messed up lol - thank you
is the link gonna be fixed on twitter and betterdiscord itself?
