### ISSUE TITLE
[Bug] Sharing sound in Screenshare stopped working

### ISSUE THREAD

**Issue by cherry25565** [rauenzi/BetterDiscordApp#564]
**Describe the Bug**
Sharing sound in Screenshare stopped working suddenly.

**To Reproduce**
Start a screenshare in the latest BandagedBD-compatible Discord PTB or Discord Canary Version.

**Expected Behavior**
Sound should work

**Screenshots**
![grafik](https://user-images.githubusercontent.com/16520483/109392955-6cb9e000-791f-11eb-9fa3-8f93cf1eda04.png)

**Discord Version**
Reproducable on:
Canary 77990 (5bbd133)
Ptb 77962 (c886d3c)

**Additional Context**
On the Discord PTB Version from yesterday screenshare with sound still worked.

**Comment by rauenzi** [comment]
BetterDiscord/BandagedBD is not currently compatible with Canary or PTB.

**Comment by cherry25565** [comment]
> BetterDiscord/BandagedBD is not currently compatible with Canary or PTB.

This was tested on the last Betterdiscord-compatible Discord versions from PTB and Canary

**Comment by rauenzi** [comment]
Reopen after the restructure launches and this is still an issue.
