### ISSUE TITLE
Can't install BBD on latest discord version.

### ISSUE THREAD

**Issue by Rlbgs** [rauenzi/BetterDiscordApp#569]
**Describe the Bug**
I've got a new update that crashed when using emojis etc it's fully restarted it removed BBD and I had to reinstall it which to my surprise the install was fine but nothing changed on discord.
**To Reproduce**
Reinstall BBD on the latest discord version

**Expected behavior**
N/A

**Screenshots**
N/A

**Discord Version**
Stable

**Additional Context**
N/A

**Comment by Aboda7m** [comment]
Stable 79500 (0a6057d)
same thing cant install BBD on the latest discord version, it was working fine before the update

**Comment by rauenzi** [comment]
This is duplicate of #548 / #442
