### ISSUE TITLE
[Bug] Themes settings hidden and infinite loading

### ISSUE THREAD

**Issue by ngocanthony** [rauenzi/BetterDiscordApp#572]
**Describe the Bug**

Betterdiscord starts with discord but doesn't show in the settings,  themes and etc...
**To Reproduce**

Start discord
**Expected Behavior**

To have themes settings
**Screenshots**

![image](https://user-images.githubusercontent.com/63907917/110241568-cccd0980-7f51-11eb-8713-221481988889.png)

**Discord Version**

Stable 78727 (b2380a5)
**Additional Context**

**Comment by Tropix126** [comment]
We need more information here.

- Have you attempted to run the repair options in the installer (theres an option specifically for infinite loading).
- Does the console contain any errors? (access it through Ctrl + Shift + I then going to the console tab at the top).
- Are you absolutely sure you have the latest installer?
