### ISSUE TITLE
Getting stuck while installing on stable version

### ISSUE THREAD

**Issue by sejgnosGN** [rauenzi/BetterDiscordApp#574]
It says something like 
"Starting installation for Discord
Killing Discord Processes
Downloading BandagedBD package
Download seems to have failed, will try once more.
Downloading BandagedBD package"

**Screenshots**
![ss](https://user-images.githubusercontent.com/77606444/110310508-a4640e80-8028-11eb-8334-c1f3c42ad4fe.PNG)

**Discord Version**
<!-- Stable

**Comment by rauenzi** [comment]
Do you h ave access to GitHub in your region?
