### ISSUE TITLE
Crashing!! [Bug]

### ISSUE THREAD

**Issue by AustinGitHub** [rauenzi/BetterDiscordApp#575]
Better Discord keeps on crashing, usually happens when I start typing into a chat. Everything is updated so I don't know how to fix this issue.

**Comment by TakoShimiyo** [comment]
the same thing happens to me. every 10 messages crash my discord

**Comment by rauenzi** [comment]
Reinstall Better Discord. If the issue persists, remove all plugins.

**Comment by Endlesszombiez** [comment]
I had this same issue, reinstall fixed.
Bug was happening when the chat box would go to a 2nd line.
