### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by ICExFS** [rauenzi/BetterDiscordApp#578]
When you use CTRL + V to paste it automatic-crash

Using discord stable

**Comment by ICExFS** [comment]
I tried uninstalling, reinstalling but nothing worked

**Comment by i9bonsai** [comment]
getting the same problem

**Comment by ND-64** [comment]
I have the same issue, with just discord links.

**Comment by armoha** [comment]
Maybe duplicate of #568, #571, or #575
Reinstalling BD fixed for me.

**Comment by TheTrueShadow** [comment]
> When you use CTRL + V to paste it automatic-crash
> 
> Using discord stable

same issue but when I go onto a new line of text crash

**Comment by rauenzi** [comment]
The issue is fixed by a reinstall when possible

**Comment by ICExFS** [comment]
No, I tried uninstalling but it didn’t worked.



-- 
L'absence de virus dans ce courrier électronique a été vérifiée par le logiciel antivirus Avast.
https://www.avast.com/antivirus
