### ISSUE TITLE
[Feature] Add an experiments button option directly into BetterDiscord

### ISSUE THREAD

**Issue by HRudyPlayZ** [rauenzi/BetterDiscordApp#583]
**Is your feature request related to a problem? Please describe.**
When using the Beta, it seems the plugin to add the Discord Experiments settings tab doesn't work anymore.

**Describe the feature you'd like**
Have this fixed and integrated directly into BetterDiscord.

**Comment by rauenzi** [comment]
I'm not sure if this is a good idea to add. In order to do this you essentially flag yourself as a discord developer, and enabling experiments just adds to the telemetry. It would be rather trivial for Discord to detect and ban such accounts. Perhaps other perspectives would be useful here. Maybe @Inve1951 or @Tropix126

**Comment by Tropix126** [comment]
This is rather hard to judge... If we do decide to add it, it should be with proper warning (similar to what Powercord does.)

**Comment by Tropix126** [comment]
Main thing in question is if discord actually cares. Powercord can likely get away with it because of it's smaller community. Then again, there has been no evidence of bans from our current official experiments plugin.

**Comment by Inve1951** [comment]
IMO it's perfectly fine to keep it as a plugin. BD should stay what it is: A plugin/theme loader with a user-friendly UI.
I don't see any reason to bloat it even further.
If the plugin broke then let's just fix it...

**Comment by Tropix126** [comment]
> IMO it's perfectly fine to keep it as a plugin. BD should stay what it is: A plugin/theme loader with a user-friendly UI.
> I don't see any reason to bloat it even further.
> If the plugin broke then let's just fix it...

Going to have to agree here. Once plugins are made more accessable to people this will be less of an issue.

**Comment by UntitledMorgue** [comment]
lmai
