### ISSUE TITLE
[Bug]Missing plugin and theme settings

### ISSUE THREAD

**Issue by zany130** [rauenzi/BetterDiscordApp#584]
**Describe the Bug**
Plugin and theme settings are missing from the discord settings
**To Reproduce**
Sometimes randomly happens on stable, always seems to happen on beta

**Expected Behavior**
plugin and theme settings show up in discord settings

**Screenshots**
![discord](https://user-images.githubusercontent.com/25832539/110863853-4ab14d80-828f-11eb-8d32-e2766d64212f.png)

**Discord Version**
Stable 

Forgot to mention that I have tried moving out all plugins and themes from the ```~.config/betterdiscord/``` folder to make sure the issue isn't from a theme or plugin

**Comment by Inve1951** [comment]
Is it once they appear it's fine or do they vanish during the session?
Please also provide any error details you can find in the console (ctrl+shift+i)

**Comment by zany130** [comment]
well on the beta it never loads the plugins and I just noticed that I also get a little icon on the bottom right corner saying better discord is loading but it never does here are some error from the console 

on stable, it randomly loses the plugin and theme settings permanently although this has only happened to me once, and I haven't been able to replicate it.  I however was able to get back the plugin and theme settings by restarting discord a few times, this does not work on the beta however

I'm thinking it's probably the same issue it's just more likely to show up on the beta for some reason/

```
db89e25088f573131a1d.js:2 [BetterDiscord] [PublicServers] Can't find GuildList component
(anonymous) @ db89e25088f573131a1d.js:2
db89e25088f573131a1d.js:2 [PublicServers] Could not be enabled TypeError: Cannot read property 'prototype' of undefined
    at Object.enabled (remote.js:1)
    at Object.enable (remote.js:1)
    at Object.initialize (remote.js:1)
    at Object.init (remote.js:1)
(anonymous) @ db89e25088f573131a1d.js:2
db89e25088f573131a1d.js:2 [BetterDiscord] [DarkMode] Enabled
db89e25088f573131a1d.js:2 [BetterDiscord] [Emotes] Enabled
db89e25088f573131a1d.js:2 [BetterDiscord] [EmoteMenu] Enabled
db89e25088f573131a1d.js:2 [Custom CSS] Could not be enabled Error: ENOSPC: System limit for number of file watchers reached, watch '/home/zany130/.config/BetterDiscord/data/stable/custom.css'
    at FSWatcher.start (internal/fs/watchers.js:165)
    at Object.watch (fs.js:1329)
    at Object.watchContent (remote.js:1)
    at Object.enabled (remote.js:1)
    at Object.enable (remote.js:1)
    at Object.initialize (remote.js:1)
    at Object.init (remote.js:1)
(anonymous) @ db89e25088f573131a1d.js:2
db89e25088f573131a1d.js:2 [BetterDiscord] [Startup] Loading Plugins
db89e25088f573131a1d.js:2 [BDFDB] (v1.4.5) Loading library
db89e25088f573131a1d.js:2 [BetterDiscord] [PluginManager] Starting to watch plugin addons.
internal/fs/watchers.js:165 Uncaught (in promise) Error: ENOSPC: System limit for number of file watchers reached, watch '/home/zany130/.config/BetterDiscord/plugins'
    at FSWatcher.start (internal/fs/watchers.js:165)
    at Object.watch (fs.js:1329)
    at Object.watchAddons (remote.js:1)
    at Object.loadAllAddons (remote.js:1)
    at Object.initialize (remote.js:1)
    at Object.initialize (remote.js:1)
    at Object.init (remote.js:1)
```

**Comment by rauenzi** [comment]
This was fixed
