### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by SebasyianMikx** [rauenzi/BetterDiscordApp#588]
After installing BDA and restart Discord, it refuses to load.

Yesterday I just installed BDA on my clean installation of Discord, and it worked fine, I installed some plugins and themes [Screenshots], but today when I tried to load it again, it just refuses to load.

![image](https://user-images.githubusercontent.com/80762939/111315354-4a6ad680-8630-11eb-9abc-e542f80686c7.png) 
![image](https://user-images.githubusercontent.com/80762939/111315768-b0eff480-8630-11eb-9500-223a23b53387.png)
![image](https://user-images.githubusercontent.com/80762939/111315530-771eee00-8630-11eb-8a1c-8d0027483e17.png)

Discord Stable, last version.

I'm going to download again the installer and trying to repair BDA, if it don't work I'm just going to reinstall.

**Comment by SebasyianMikx** [comment]
Update: 
Repairing don't work, and unistalling just made Discord stay like this:
![image](https://user-images.githubusercontent.com/80762939/111317203-ecd78980-8631-11eb-85c9-ae7630abf522.png)
Trying to restart again...

**Comment by Tropix126** [comment]
![image](https://user-images.githubusercontent.com/42101043/111552286-fb1bc780-874f-11eb-942a-96e02f08e382.png)
https://cdn.discordapp.com/attachments/119918741516451840/814871571498795058/config.json

**Comment by SebasyianMikx** [comment]
Trying...
¡Thanks dude!
If it works i'm going to close the issue

**Comment by SebasyianMikx** [comment]
> ![image](https://user-images.githubusercontent.com/42101043/111552286-fb1bc780-874f-11eb-942a-96e02f08e382.png)
> https://cdn.discordapp.com/attachments/119918741516451840/814871571498795058/config.json
> 
> Note that this will be fixed upon the release of the development branch being merged.

¡Looks like it works!

Thanks a lot, really

Closing issue...

**Comment by SebasyianMikx** [comment]
Issue closed
