### ISSUE TITLE
Uninstalling BandagedBD

### ISSUE THREAD

**Issue by Shana195** [rauenzi/BetterDiscordApp#59]
Im having problems unistalling the program ive tried uninstalling it the same way as better discord and went into appdata (local and roaming) deleted the full discord folder in local and the better discord folder in roaming and installed a complete fresh version of discord and it was still there. how do i fix this? and btw im on win8

**Comment by rauenzi** [comment]
Just delete this folder `%appdata%\discord\0.0.301` and fully restart discord

**Comment by Shana195** [comment]
thanks alot this worked nice. althought i have to ask how come it didnt work when i deleted the full folder?

**Comment by Shana195** [comment]
the full discord folder i mean

**Comment by rauenzi** [comment]
because you deleted from local and not roaming, BD injects in roaming

**Comment by Shana195** [comment]
oooh i see. interesting

**Comment by Shana195** [comment]
thanks again btw
