### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by NotPetyaPog** [rauenzi/BetterDiscordApp#593]
**Describe the Bug**
I get a javascript error every time i try to launch and after i tried to use bandagedbd repair, it now doesn't start.

**To Reproduce**
I don't know

**Expected Behavior**
it to open

**Screenshots**
https://pays-host.bingus.host/NoOOtrdz

**Discord Version**
Stable

**Additional Context**

sorry about the last issue i don't know why it didn't work

**Comment by rauenzi** [comment]
That screenshot indicates you did not install the project in this repository, but an abandoned version of the project from another location. Please see the README for installation instructions.
