### ISSUE TITLE
[Bug] BetterDiscord with Discord Stable/PTB not working with macOS Big Sur

### ISSUE THREAD

**Issue by EmreTech** [rauenzi/BetterDiscordApp#594]
**Describe the Bug**
So I have macOS Big Sur 11.0.1, and Discord PTB installed. When I used the file from the latest pre-release, the app opens, but no window opens. I then tried Discord Stable and macOS prompted me to delete the app because it's not working properly.

**To Reproduce**
Attempt to install the pre-release on macOS Big Sur.

**Expected Behavior**
I expected the window to open and Discord would launch.

**Discord Version**
Tried both Discord Stable and PTB.

**Comment by EmreTech** [comment]
Update: After using the BBD installer on stable, it's working now. Still not working on PTB though.

**Comment by rauenzi** [comment]
Not working on PTB is known and duplicate of #548

**Comment by EmreTech** [comment]
Ah okay. Guess I'll wait for that to be fixed.
