### ISSUE TITLE
[Bug] Classes don't appear to be normalized on startup

### ISSUE THREAD

**Issue by Barbarossa93** [rauenzi/BetterDiscordApp#595]
**Describe the Bug**

I use lightcord, so perhaps the problem lies there, but when I launch lightcord, the themes are incomplete. When I go to settings under BandagedBD section, BetterDiscord settings, turning off then on the normalize classes applies the theme correctly.

**To Reproduce**

Start lightcord with normalize classes already enabled. See that theme is incomplete.

**Expected Behavior**

Starting lightcord should apply the theme correctly.

**Screenshots**

Here's what it looks like on startup:
![1616360085](https://user-images.githubusercontent.com/57952969/111920604-42fb6100-8a66-11eb-89c3-923d9b0eb3b0.png)
Here's what it looks like after disabling, then re-enabling normalize classes"
![1616360103](https://user-images.githubusercontent.com/57952969/111920613-53134080-8a66-11eb-8b99-1280eb523f0a.png)

**Discord Version**

Lightcord 0.0.12

**Additional Context**

The theme in question:
```
/**
 * @name Minimal Nord Discord
 * @description A Dicord theme based on the Nord colorscheme
 * @author TheAvidDev
 * @version 1.0
 *
 * @source https://raw.githubusercontent.com/TheAvidDev/dotfiles/master/Lightcord_BD/themes/DiscordNord.theme.css
 * @website https://theavid.dev/
**/

:root {
    --background-primary: #2e3440;
    --channeltextarea-background: #242831;
    --background-secondary: #242831;
    --background-secondary-alt: #2e3440;
    --background-tertiary: #2e3440;
    
    --border-radius: 15px;
}

.da-video, .da-peopleColumn, .da-tabBody {
    background-color: var(--background-primary);
}

.da-wrapper.da-video, .da-sidebar, .da-members, .da-nowPlayingColumn {
    border-radius: var(--border-radius);
}

.da-panels {
    background-color: var(--background-secondary);
}

/*
 * Change selected channel name and icons
 */
.da-selected > .da-wrapper > .da-content > .da-mainContent > .da-name,
.da-selected > .da-wrapper > .da-content > .da-children > .da-iconItem > .da-actionIcon {
    color: var(--background-primary);
}

.da-selected > .da-wrapper > .da-content {
    background-color: #88c0d0;
}

/* Remove margin for typing indicator */
.da-channelTextArea {
    margin-bottom: 0;
}

/* Channel name */
.da-name {
    color: #d8dee9;
}

/* Add a small line at the top of chat */
.da-chatContent {
  border-top: 1px solid var(--background-secondary);
}

#bd-pub-li, /* BetterDiscord public vutton */
#private-channels-1, /* Nitro button */
.da-toolbar > .da-anchor, /* Help button */
.da-typing, /* Removing typing indicator */
.da-content:before { /* Tiny black line in header */
    display: none;
}


/* Change divider and pill */
.da-divider {
    border-color: #bf616a;
}

.da-divider > span.da-content {
    color: #bf616a;
}

.da-unreadPill {
    background-color: #bf616a;
}

.da-unreadPillCapStroke {
    color: #bf616a;
    fill: #bf616a;
}

/**
 * Change server folder icon colors
 */
#app-mount > .da-app > div > .da-layers > div > div > nav > .da-scroller > div:nth-child(3) > div:nth-child(1) > .da-listItem > div:nth-child(2) > div > svg > foreignObject > div > div > div > svg {
    color: #bf616a!important;
}

#app-mount > .da-app > div > .da-layers > div > div > nav > .da-scroller > div:nth-child(3) > div:nth-child(2) > .da-listItem > div:nth-child(2) > div > svg > foreignObject > div > div > div > svg {
    color: #d08770!important;
}

#app-mount > .da-app > div > .da-layers > div > div > nav > .da-scroller > div:nth-child(3) > div:nth-child(3) > .da-listItem > div:nth-child(2) > div > svg > foreignObject > div > div > div > svg {
    color: #ebcb8b!important;
}

#app-mount > .da-app > div > .da-layers > div > div > nav > .da-scroller > div:nth-child(3) > div:nth-child(4) > .da-listItem > div:nth-child(2) > div > svg > foreignObject > div > div > div > svg {
    color: #a3be8c!important;
}

#app-mount > .da-app > div > .da-layers > div > div > nav > .da-scroller > div:nth-child(3) > div:nth-child(5) > .da-listItem > div:nth-child(2) > div > svg > foreignObject > div > div > div > svg {
    color: #b48ead!important;
}

#app-mount > .da-app > div > .da-layers > div > div > nav > .da-scroller > div:nth-child(3) > div:nth-child(6) > .da-listItem > div:nth-child(2) > div > svg > foreignObject > div > div > div > svg {
    color: #88c0d0!important;
}
```

**Comment by rauenzi** [comment]
I don't support Lightcord.

**Comment by Tropix126** [comment]
This likely won't be considered unless you test this on a vanilla version of discord with **BD beta** injected. We don't support lightcord even though it uses this codebase for several reasons. It's also highly suggested against using normalized classes and these are mainly only there for backwards compatibility.

**Comment by Barbarossa93** [comment]
Thanks @Tropix126, I tried it with vanilla discord and bandagedBD. It all works fine, including having normalized classes enabled. Looks like it is indeed an issue with lightcord.

@rauenzi, Would you consider adding a note to your README about your stance on lightcord? I think it would be helpful in preventing wasted time both on your end and for others who stumble here from lightcord.

**Comment by rauenzi** [comment]
> Would you consider adding a note to your README about your stance on lightcord?

No. Lightcord needs to make more clear that they have no official standing with me or the BD project. They use a completely separate codebase of BD and not the official product, so any issue faced should be directed entirely at that project.

**Comment by Barbarossa93** [comment]
Suit yourself.
