### ISSUE TITLE
Discord not showing custom background in settings and breaking microphone settings

### ISSUE THREAD

**Issue by jdog7679** [rauenzi/BetterDiscordApp#596]
i install and it breaks discords microphone settings and its not showing discord background customizations.

**Comment by pineapple254** [comment]
I got the same problem

**Comment by Technoblazed** [comment]
Related to https://github.com/rauenzi/BetterDiscordApp/issues/442, just that it's been put on the stable branch too now.

**Comment by rauenzi** [comment]
This does not follow issue format, nor does it provide any helpful information.
