### ISSUE TITLE
[Bug] Showing blank screen after updating to 0.0.14

### ISSUE THREAD

**Issue by ByteDream** [rauenzi/BetterDiscordApp#597]
**Describe the Bug**
I've updated Linux Discord to Stable 0.0.14 and it shows a semi empty screen with a button which takes me to the Discord download website. I've tried reinstalling Discord, reinstalling betterdiscordcli, deleting Discord config folder, but nothing.
My OS is Arch Linux 5.11.8-arch1-1

**To Reproduce**
Update Linux Discord to 0.0.14

**Expected Behavior**
Discord should start normally

**Screenshots**
![Screenshot_20210324_021610](https://user-images.githubusercontent.com/63594396/112239859-8f51c700-8c47-11eb-8aa8-75096d39e0e6.png)

**Discord Version**
Stable 0.0.14

**Comment by AlexHaber** [comment]
Duplicate of #589

**Comment by ByteDream** [comment]
Downgrading to 0.0.13 and setting the version in /opt/discord/resources/build_info.json to 0.0.14 fixed it
