### ISSUE TITLE
[Bug]Better Discord not work with last update (app-1.0.9001)

### ISSUE THREAD

**Issue by LouHen1** [rauenzi/BetterDiscordApp#599]
after installing better discord and restarting discord it doesn't start with discord and window become right half of screen &
it doesn't show top bar that have Exit,Minimize,Maximize,Hide and 

![image](https://user-images.githubusercontent.com/21263713/112355543-0df14780-8cce-11eb-953a-d045f5a814d6.png)

**Comment by GalacticB69** [comment]
It seems to be showing discord as a web site instead because I got the message saying to download the desktop version.

**Comment by matoqueimado** [comment]
same to me

**Comment by 99r** [comment]
Same here

**Comment by creepylove** [comment]
Same here (on archlinux)
Also the Game Activity thing in the settings seems to be missing.

**Comment by Narice** [comment]
yes, same thing on linux (NixOS)

**Comment by hazlema** [comment]
Same, running on Linux here too

**Comment by not-here-dev** [comment]
For me: 

Normal Discord: not detected by the BBD installer on MacOS
Canary Discord: thinks it is a browser on MacOS

however BBD is working as normal for me on Windows on both Canary + Normal Discord

**Comment by rauenzi** [comment]
Try to install BetterDiscord using this new beta installer: https://github.com/BetterDiscord/Installer

**Comment by hazlema** [comment]
Downloading the Appimage installer and doing a repair fixed BetterDiscord for me.  Thanks

**Comment by creepylove** [comment]
Thanks. Worked for me perfectly fine.
