### ISSUE TITLE
Plugins dont work

### ISSUE THREAD

**Issue by iishoku** [rauenzi/BetterDiscordApp#6]
everytime i want to enable the GoogleTranslator plugin its not working - when I close the settings window its disabled again so like its not staying enabled 

can someone help me to fix that?

**Comment by rauenzi** [comment]
update the plugin

**Comment by iishoku** [comment]
okay, how can I do that?

**Comment by rauenzi** [comment]
download it from his github again

**Comment by iishoku** [comment]
thank you, it's working now! I dont know much about plugins n' stuff -
