### ISSUE TITLE
STUCK ON EXTRACTING

### ISSUE THREAD

**Issue by ghost** [rauenzi/BetterDiscordApp#60]
Looked at all of these threads and googled everywhere for tutorials. I've seen the following threads and tried their solutions but it didn't work: 

https://github.com/rauenzi/BetterDiscordApp/issues/55
https://github.com/rauenzi/BetterDiscordApp/issues/35
https://github.com/rauenzi/BetterDiscordApp/issues/22
https://github.com/rauenzi/BetterDiscordApp/issues/14
https://github.com/rauenzi/BetterDiscordApp/issues/8
https://github.com/rauenzi/BetterDiscordApp/issues/7

None of these work and I'm stumped. Help.

**Comment by geds3169** [comment]
Same to me on Windows 11
