### ISSUE TITLE
[Bug] BetterDiscord incompatible with latest Stable on Mac

### ISSUE THREAD

**Issue by Delta-official** [rauenzi/BetterDiscordApp#600]
**Describe the Bug**
After updating to the latest Discord version, BetterDiscord refuses to work and its installer. Installer doesn't allow to re-install BD since it displays an error that shows `Failed to install to : ReferenceError: cannot access 'fs' before initialization`. Even after reinstalling the installer the bug is still present.

**To Reproduce**
1. Download latest discord version on any MacOS version
2. Download BandagedBD
3. Press "Install BandagedBD"
4. Click install
5. Errors are shown

**Expected Behavior**
BBD installs BD and on Discord startup BD launches

**Screenshots**

![](https://cdn.discordapp.com/attachments/119918741516451840/824376755980468304/Screen_Shot_2021-03-24_at_13.18.49.png)

**Discord Version**
Stable, latest

**Additional Context**
Problem only occurs on MacOS (Any versions)

**Comment by testheyheyhey** [comment]
I got the same problem & I can’t fix it

**Comment by EmreTech** [comment]
I'm pretty sure I also had this error, but it somehow fixed itself.

**Comment by Shotobai** [comment]
I am pretty sure is because you dont have discord.app but idk

**Comment by Kinue72** [comment]
i got same problem

**Comment by rauenzi** [comment]
Instead of adding a new comment, please react :+1: to the original issue if you have the same issue.

**Comment by Kinue72** [comment]
<img width="1424" alt="image" src="https://user-images.githubusercontent.com/40353755/112416767-eabfaa00-8d58-11eb-92a9-56dc6c6fcd49.png">
[25849:0325/103402.306936:INFO:CONSOLE(115)] "Unable to load preload script: /Applications/Discord.app/Contents/Resources/app/betterdiscord/preload.js", source: electron/js2c/renderer_init.js (115)
[25849:0325/103402.307075:INFO:CONSOLE(115)] "TypeError: Cannot read property 'app' of undefined", source: electron/js2c/renderer_init.js (115)

**Comment by RenLeaf544** [comment]
basically, we all have the same problem

**Comment by Kinue72** [comment]
I think its electron problem. See more in #442

**Comment by br0kenpixel** [comment]
I just updated Discord and somehow BetterDiscord was "uninstalled". I'm getting the same error too. Manual installation doesn't work either. Maybe Discord changed how the app loads up. Or as @Kinue72 mentioned, it's probably related to electron.

**Comment by JungleTECH1** [comment]
When I try to install it manually, it puts my discord into the web browser version running on the app. I know this because I can't zoom, and I can't set custom keybinds

**Comment by scarscar1** [comment]
has this been fixed yet ? because my better discord is still bugging since the update.

**Comment by rauenzi** [comment]
Please see my earlier comment.

**Comment by Franxineeeh** [comment]
i'm also having the same problem whenever i click install it does nothing

**Comment by Nova767** [comment]
Yeah, same here. I didn't know how to fix it so I thought I'd wait a day until it is. I won't put the creator under pressure though because he's probably trying to fix it as we speak.

**Comment by ginodorantes** [comment]
Won't install.

**Comment by SwiftWinds** [comment]
Current workarounds for macOS is to download this file https://cdn.discordapp.com/attachments/410788958277074944/821690118468272168/patch.zip and extract it. You should get an app folder; you only have to paste that app folder in /Applications/Discord.app/Contents/Resources

Credits: @lukasbableck of the BetterDiscord2 server

**Comment by chris-larsen** [comment]
> Current workaround for macOS is to:
> 
> 1. close discord
> 2. download this file: https://cdn.discordapp.com/attachments/410788958277074944/821690118468272168/patch.zip and extract it.
> 3. You should get an app folder; paste that app folder in `/Applications/Discord.app/Contents/Resources`.
> 4. restart discord
> 5. you may need to go to settings to reenable the themes/plugins
> 
> Credits: @lukasbableck of the BetterDiscord2 server

Thanks for this. Custom CSS causes my Discord to just reload, but this is still 90% of the way to happy again so I'll take it. Cheers!

**Comment by ProofHF** [comment]
> Current workaround for macOS is to:
> 
> 1. close discord
> 2. download this file: https://cdn.discordapp.com/attachments/410788958277074944/821690118468272168/patch.zip and extract it.
> 3. You should get an app folder; paste that app folder in `/Applications/Discord.app/Contents/Resources`.
> 4. restart discord
> 5. you may need to go to settings to reenable the themes/plugins
> 
> Credits: @lukasbableck of the BetterDiscord2 server

Have tried this, unfortunately yielded the same issue. No BetterDiscord section in settings.

**Comment by Xenthio** [comment]
> > Current workaround for macOS is to:
> > 
> > 1. close discord
> > 2. download this file: https://cdn.discordapp.com/attachments/410788958277074944/821690118468272168/patch.zip and extract it.
> > 3. You should get an app folder; paste that app folder in `/Applications/Discord.app/Contents/Resources`.
> > 4. restart discord
> > 5. you may need to go to settings to reenable the themes/plugins
> > 
> > Credits: @lukasbableck of the BetterDiscord2 server
> 
> Have tried this, unfortunately yielded the same issue. No BetterDiscord section in settings.
> 
> Going to drop this here since I posted it in a duplicate issue:
> 
> Same issue, tried the manual injector as well-- can get discord to launch, but the BetterDiscord settings section is missing under settings. For some reason adding the app folder into resources on Mac causes you to lose further ability to close the app without a force quit.
> 
> Hopefully this will get resolved soon.

i was about to say this didn't work for me either but it just takes a really long time for it to load

**Comment by orblazer** [comment]
Thanks a lot for your fix @SwiftWinds !

Tips for linux user : this need extracted at `~/.local/share/betterdiscordctl/bd/0`

**Comment by alexis-evelyn** [comment]
From what I can tell on the OSX version, the app folder no longer exists at all. I've tried to use the injector, even so far as renaming the app.asar that comes with Discord (to old-app.asar) and then renaming the app.asar in the injector's index.js file to old-app.asar in order to attempt to force bd to load first.

This is what the original app.asar's contents look like. I haven't messed with betterbd installation manually enough to know exactly how it should work, so I don't know how to fix it. I just believe that betterbd is being cleared out by Discord on load and I may have to find my backup modified Discord app in the meantime while waiting for the fix.

![Screen Shot 2021-03-29 at 8 29 25 AM](https://user-images.githubusercontent.com/6305346/112836683-e6e99b80-9068-11eb-8343-5605bfc98a8f.png)

**Comment by Gizmoeve** [comment]
> I just updated Discord and somehow BetterDiscord was "uninstalled". I'm getting the same error too. Manual installation doesn't work either. Maybe Discord changed how the app loads up. Or as @Kinue72 mentioned, it's probably related to electron.

Thats exactly what happened to me. The better discord app was removed and now I'm having same errors above

**Comment by SwiftWinds** [comment]
> > I just updated Discord and somehow BetterDiscord was "uninstalled". I'm getting the same error too. Manual installation doesn't work either. Maybe Discord changed how the app loads up. Or as @Kinue72 mentioned, it's probably related to electron.
> 
> Thats exactly what happened to me. The better discord app was removed and now I'm having same errors above

Did you try https://github.com/rauenzi/BetterDiscordApp/issues/600#issuecomment-807927487?

**Comment by Gizmoeve** [comment]
> > > I just updated Discord and somehow BetterDiscord was "uninstalled". I'm getting the same error too. Manual installation doesn't work either. Maybe Discord changed how the app loads up. Or as @Kinue72 mentioned, it's probably related to electron.
> > 
> > 
> > Thats exactly what happened to me. The better discord app was removed and now I'm having same errors above
> 
> Did you try [#600 (comment)](https://github.com/rauenzi/BetterDiscordApp/issues/600#issuecomment-807927487)?

I did with manually injecting and still didn't work

**Comment by SwiftWinds** [comment]
Hmm... Idk then, it works for me. Maybe ask in #support in the [official BetterDiscord discord server](https://discord.com/invite/sbA3xCJ).

**Comment by Gizmoeve** [comment]
> Hmm... Idk then, it works for me. Maybe ask in #support in the [official BetterDiscord discord server](https://discord.com/invite/sbA3xCJ).

already did ty for your help

**Comment by X5Panther** [comment]
> Current workaround for macOS is to:
> 
> 1. close discord
> 2. download this file: https://cdn.discordapp.com/attachments/410788958277074944/821690118468272168/patch.zip and extract it.
> 3. You should get an app folder; paste that app folder in `/Applications/Discord.app/Contents/Resources`.
> 4. restart discord
> 5. you may need to go to settings to reenable the themes/plugins
> 
> Credits: @lukasbableck of the BetterDiscord2 server

THATS WHAT I DID :))) I KNEW SOMONE WOULD FIND IT I USED XCODE :DDDDDDD

**Comment by X5Panther** [comment]
IM SO HAPPY

**Comment by X5Panther** [comment]
:DDDDD

**Comment by jkrosado** [comment]
> Current workaround for macOS is to:
> 
> 1. close discord
> 2. download this file: https://cdn.discordapp.com/attachments/410788958277074944/821690118468272168/patch.zip and extract it.
> 3. You should get an app folder; paste that app folder in `/Applications/Discord.app/Contents/Resources`.
> 4. restart discord
> 5. you may need to go to settings to reenable the themes/plugins
> 
> Credits: @lukasbableck of the BetterDiscord2 server

not doing anything at all on catalina 10.15.7

**Comment by Nicotra-Jack** [comment]
> La soluzione attuale per macOS è:
> 
> 1. chiudere la discordia
> 2. scarica questo file: https://cdn.discordapp.com/attachments/410788958277074944/821690118468272168/patch.zip ed estrailo.
> 3. Dovresti ottenere una cartella dell'app; incolla quella cartella dell'app in `/Applications/Discord.app/Contents/Resources`.
> 4. riavviare discord
> 5. potrebbe essere necessario accedere alle impostazioni per riattivare i temi / plug-in
> 
> Crediti: @lukasbableck del server BetterDiscord2

**Comment by Nicotra-Jack** [comment]
Dove lo cerco il comando /Applications/Discord.app/Contents/Resources ?

**Comment by Tropix126** [comment]
![image](https://user-images.githubusercontent.com/42101043/113211698-7050c780-923b-11eb-8e05-881423eb9202.png)
https://github.com/BetterDiscord/Installer/
