### ISSUE TITLE
[Bug] Server Side bar isn't working properly with some themes

### ISSUE THREAD

**Issue by DoubleSmoothStoneSlab** [rauenzi/BetterDiscordApp#603]
**Describe the Bug**
the side bar of all the servers don't function correctly with some themes
**To Reproduce**
1) download sunset theme
2) active the sunset theme 
3) look to see if the sidebar is grey

**Expected Behavior**
expected the sidebar to match the rest of the theme

**Screenshots**
![2021-03-25 (4)](https://user-images.githubusercontent.com/81389331/112543241-dcd74c80-8d8b-11eb-84d8-63d7f41bbc35.png)

**Discord Version**
Stable latest

**Additional Context**

**Comment by Tropix126** [comment]
This is not related to BD itself. Discord updated their guilds classes. Wait for the theme developers to fix their themes.

**Comment by DoubleSmoothStoneSlab** [comment]
oh ok thanks
