### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by matoqueimado** [rauenzi/BetterDiscordApp#604]
**Not working i reinstalled betterdiscord and discord but don't work**

**Don't work **

**Don't work **

**Don't work **

**Stable 80597 (app-1.0.9001)**

**Don't load**

**Comment by lZevex** [comment]
Already being worked on

**Comment by Swishilicous** [comment]
what seems to be the issue?

**Comment by rauenzi** [comment]
Try to install BetterDiscord using this new beta installer: https://github.com/BetterDiscord/Installer
