### ISSUE TITLE
Custom CSS editor crashes on opening[Bug]

### ISSUE THREAD

**Issue by StarrKiss** [rauenzi/BetterDiscordApp#606]
**Describe the Bug**
Whenever I launch the custom CSS editor, better-discord crashes. This happens AS SOON as I click on the button - I click it, discord becomes unresponsive, and closes. I tried launching Discord through terminal and checking the BetterDiscord logs, but neither gave me ANY error messages - it was just click, and boom - it crashes and promptly restarts.

**To Reproduce**
Click the button "custom css editor" at the bottom of the Discord settings menu.

**Expected Behavior**
The customCSS opens.

**Discord Version**
Stable

**Comment by rauenzi** [comment]
Try to install BetterDiscord using this new beta installer: https://github.com/BetterDiscord/Installer
