### ISSUE TITLE
[Bug] Custom Themes partially overwritten by default Theme

### ISSUE THREAD

**Issue by 5trgV** [rauenzi/BetterDiscordApp#607]
**Describe the Bug**
Default sidebar overrides Custom Themed one

**To Reproduce**
Apply Custom Theme

**Expected Behavior**
Show Custom Server-List Sidebar

**Screenshots**
![image](https://user-images.githubusercontent.com/32174410/112661714-19bc4580-8e57-11eb-800d-52165c2d1bd7.png)

**Discord Version**
Stable 80597 (01cdb2c)

**Comment by Tropix126** [comment]
Not related to BD itself. Discord refreshed their guilds classes. Wait for your theme developer to fix it.

**Comment by 5trgV** [comment]
Thought so didnt find a change so figured could possibly be BD related as I tried own custom ones too... but oh well gotta look into that then can't always be that easy...
