### ISSUE TITLE
[Bug] When I open discord it doesnt works it infinitely loading in the bottom right 

### ISSUE THREAD

**Issue by BlaztiBoi** [rauenzi/BetterDiscordApp#609]
**Describe the Bug**

**To Reproduce**

**Expected Behavior**

**Screenshots**

**Discord Version**

**Additional Context**

**Comment by LividJava** [comment]
there are issues with BD at the current moment,
I would suggest to try reinstalling. If not you're just gonna have to wait until an update is pushed.

Ref #600

**Comment by rauenzi** [comment]
Try to install BetterDiscord using this new beta installer: https://github.com/BetterDiscord/Installer

**Comment by randomdiscorduser** [comment]
> Try to install BetterDiscord using this new beta installer: https://github.com/BetterDiscord/Installer

had the problem with the beta as well on ptb
![Screen Shot 2021-03-31 at 5 08 29 PM](https://user-images.githubusercontent.com/81717531/113217576-bad64200-9243-11eb-9138-5a958a39d8f6.png)

**Comment by rauenzi** [comment]
Remove your plugins and try again

**Comment by randomdiscorduser** [comment]
> Remove your plugins and try again

just installed it for the first time, no plugins

**Comment by rauenzi** [comment]
Can you ensure these folders exist:
`~/Library/Application Support/BetterDiscord`
`~/Library/Application Support/BetterDiscord/data`
`~/Library/Application Support/BetterDiscord/data/plugins`
`~/Library/Application Support/BetterDiscord/themes`

And can you check console for errors?

**Comment by randomdiscorduser** [comment]
~/Library/Application Support/BetterDiscord does exist, but is lowercase (`betterdiscord`), and data/plugins does not exist
![Screen Shot 2021-03-31 at 5 39 47 PM](https://user-images.githubusercontent.com/81717531/113220058-2d492100-9248-11eb-9bc0-1ea8fa8407a8.png)

**Comment by rauenzi** [comment]
Your terminal shows you are actually in the `data` folder

**Comment by randomdiscorduser** [comment]
> Your terminal shows you are actually in the `data` folder

![Screen Shot 2021-03-31 at 5 45 39 PM](https://user-images.githubusercontent.com/81717531/113220509-e9a2e700-9248-11eb-90f1-1609bb03c0ec.png)
the betterdiscord/plugins folder does exist though, if thats what you meant

as for errors in the console
![Screen Shot 2021-03-31 at 5 44 03 PM](https://user-images.githubusercontent.com/81717531/113220493-e3146f80-9248-11eb-98ba-7f61da835f28.png)

**Comment by rauenzi** [comment]
I think I misunderstood your comment here:
> and data/plugins does not exist

The path should be `~/Library/Application Support/BetterDiscord/plugins` not `~/Library/Application Support/BetterDiscord/data/plugins` as I said in https://github.com/rauenzi/BetterDiscordApp/issues/609#issuecomment-811511348

**Comment by rauenzi** [comment]
Are you injecting anything else into Discord? I see an error in your screenshot for `inject.js` which does not exist in BD. It also is attempting to use `sessionStorage` which BD does not use. It seems something is interfering with BD's attempt to remove the CSP.

**Comment by randomdiscorduser** [comment]
I had attempted to install the old version of betterdiscord, with lots of errors (in case that could affect it). I'm not injecting anything else myself, but my school district injects a script to delete all aspects of the site if they want to block it (in this case, the site is blocked during the school day)

**Comment by rauenzi** [comment]
Then it seems your school's script is breaking things. I would suggest using a personal computer.

**Comment by randomdiscorduser** [comment]
That isn't really an option for me, is there any other way?

**Comment by randomdiscorduser** [comment]
![Screen Shot 2021-03-31 at 6 44 38 PM](https://user-images.githubusercontent.com/81717531/113224528-44404100-9251-11eb-9f99-049549760764.png)
this happened as well

**Comment by Tropix126** [comment]
> ![Screen Shot 2021-03-31 at 6 44 38 PM](https://user-images.githubusercontent.com/81717531/113224528-44404100-9251-11eb-9f99-049549760764.png)
> this happened as well

This is unrelated to BD and is actually expected. They are warnings, not errors.

**Comment by randomdiscorduser** [comment]
> > ![Screen Shot 2021-03-31 at 6 44 38 PM](https://user-images.githubusercontent.com/81717531/113224528-44404100-9251-11eb-9f99-049549760764.png)
> > this happened as well
> 
> This is unrelated to BD and is actually expected. They are warnings, not errors.

i see. do you know if there is any way to get it working without using another computer?

**Comment by randomdiscorduser** [comment]
An update on this:
    I used powercord for a little while so I knew that it was possible to use client mods on my device. After some more research, it was rather the proxy that caused issues. Since I knew that [powercord's solution for CSP](https://github.com/powercord-org/powercord/blob/v2/src/patcher.js#L56-L62) worked, I took the source code for that and put it into BD, which enabled it to finish loading. However, this wasn't a complete fix. A bunch of requests are failing for some reason, but all of the ones that were broken with the old code *are* working now. Guilds, channels, and users load just fine still (as well as their avatars), but images, messages, and such are stuck loading. Many BD aspects, such as emojis, public servers, and updates do not load as well. Also, DevTools does not open, no matter what I try, and the window is buggy sometimes (won't close when I click the button to close the window, etc.).
