### ISSUE TITLE
[Bug] Better Discord won't load at all - Windows latest stable

### ISSUE THREAD

**Issue by CarlitaNebula** [rauenzi/BetterDiscordApp#611]
**Describe the Bug**
After a few month of using, Better Discord won't launch anymore. I don't even have anything. Screen: 
![image](https://user-images.githubusercontent.com/81053537/112739458-cf30eb00-8f74-11eb-9f3c-45cfe80e975c.png)

**To Reproduce**
Updated to last version
Already uninstalled multiple times discord and betterdiscord, with cleaning every files of discord remaining. Same issue. 

**Expected Behavior**
Working ? 
Reinstalling, fixing, or uninstalling / reinstalling BD doesn't seems to work. 
Installations of discord and BD goes fine both. 

**Screenshots**
![image](https://user-images.githubusercontent.com/81053537/112739456-ccce9100-8f74-11eb-91bc-b081397e9470.png)

**Discord Version**
Stable

**Comment by xPiwel** [comment]
Got the exact same issue over here ! (identical specs and stuff)

**Comment by LividJava** [comment]
#600 latest version is having issues

**Comment by ed-zsi** [comment]
same problem here

**Comment by xPiwel** [comment]
> #600 latest version is having issues

Issue #600 is a Mac issue. And not describing the exact same problem.

**Comment by Helhest** [comment]
I have the same issue for over a month now the only solution i've found it to uninstall discord and re-install it only fixes it for a short period

**Comment by xPiwel** [comment]
> I have the same issue for over a month now the only solution i've found it to uninstall discord and re-install it only fixes it for a short period

It fixed it for like an hour for me.

**Comment by Helhest** [comment]
> > I have the same issue for over a month now the only solution i've found it to uninstall discord and re-install it only fixes it for a short period
> 
> It fixed it for like an hour for me.

Let's hope they solve this issue it's really annoying

**Comment by LoganDark** [comment]
Discord's new update breaks BBD because it relied on insecure features that Discord has now disabled. The `restructure` branch contains a version that works for new Discord, but it hasn't been officially released yet.

**Comment by rauenzi** [comment]
Try to install BetterDiscord using this new beta installer: https://github.com/BetterDiscord/Installer

**Comment by xBytez** [comment]
Using that new installer fixed this (so far) for me, thanks.
