### ISSUE TITLE
its not starting and i tried reinstalling it and repairing but nothing works[Bug]

### ISSUE THREAD

**Issue by BradleyyyWRLD** [rauenzi/BetterDiscordApp#612]
**Describe the Bug**

**To Reproduce**

**Expected Behavior**

**Screenshots**

**Discord Version**

**Additional Context**

**Comment by LoganDark** [comment]
Discord's new update breaks BBD because it relied on insecure features that Discord has now disabled. The `restructure` branch contains a version that works for new Discord, but it hasn't been officially released yet.

**Comment by rauenzi** [comment]
Try to install BetterDiscord using this new beta installer: https://github.com/BetterDiscord/Installer
