### ISSUE TITLE
[Bug] Windows snap not functioning

### ISSUE THREAD

**Issue by galantelorenzo97** [rauenzi/BetterDiscordApp#615]
**Describe the Bug**
Normally when you drag Discord to the side of a window it snaps into place. Since I installed BandagedBD it no longer does this. 

**To Reproduce**
Try to drag Discord to the top, side or corner of the screen. 

**Expected Behavior**
Discord should maximize, snap to the side of the screen, or the corner of the screen.

**Discord Version**
Stable 80728 (81b6702)
BBD 0.3.5
Host 0.0.309
Injector 0.6.2
Windows 10 64-Bit (10.0.19042)

**Additional Info**
Just to show what I'm talking about exactly: https://support.microsoft.com/en-us/windows/snap-your-windows-885a9b1e-a983-a3b1-16cd-c531795e6241

**Comment by Tropix126** [comment]
This is an issue with the transparency module in chromium. There's nothing we can do about it. If you don't use the "Enable Transparency" setting, then you should probably disable it.

**Comment by galantelorenzo97** [comment]
Noted, thank you!
