### ISSUE TITLE
[Bug] I have done the manual installation for mac, and I know I did it right and then I restarted discord but I didn't have BD, tried this many times

### ISSUE THREAD

**Issue by DELVRADIO** [rauenzi/BetterDiscordApp#616]
**Describe the Bug**

**To Reproduce**

**Expected Behavior**

**Screenshots**

**Discord Version**

**Additional Context**

**Comment by veloaf** [comment]
I'm glad to see people are having some of the same bugs I'm experiencing, it'll increase the likely hood of a fix being pushed out.

**Comment by LoganDark** [comment]
Discord's new update breaks BBD because it relied on insecure features that Discord has now disabled. The `restructure` branch contains a version that works for new Discord, but it hasn't been officially released yet.

**Comment by rauenzi** [comment]
Try to install BetterDiscord using this new beta installer: https://github.com/BetterDiscord/Installer
