### ISSUE TITLE
Glitch ! ( NOT WORKING FOR MY MAC ) !

### ISSUE THREAD

**Issue by lolMemeBBC** [rauenzi/BetterDiscordApp#618]
Okay, so I am a Mac user, and I'm running into a bit of trouble. Which is whenever I open BandagedBD, I want to install BetterDiscord it would not work. I could open the application, I click on install then I follow by going to "Install Stable" as the tutorial tells me to. I click Browse nothing happens. I can't do anything. So I just type in the following ~/Library/Application Support/discord. I follow that up by clicking onto clicking install. And the answer it gives me every time is "Installing BandagedBD ---------- Installing to Stable. Failed to Install to: ReferenceError: Cannot access 'fs' before initalization". If you know how to solve this please answer this report.

**Comment by rauenzi** [comment]
Try to install BetterDiscord using this new beta installer: https://github.com/BetterDiscord/Installer

**Comment by lZevex** [comment]
How do you run the installer?
