### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by AddiFratz** [rauenzi/BetterDiscordApp#620]
I tried to reinstall better discord, but when discord starts up againe, im muted and cant unmute and these plugin and theme settings arent available so i guess BD did not installed correctly. 
Tried the newest installer and also an older one

**Comment by adamvsb** [comment]
Same, tried repairing BD, reinstalling BD, had to reinstall discord as well. If i install it into app-0.0.309 then it does nothing and in app-1.0.9001 it does exactly what you said. Cant unmute, no options for BD available. The only thing that fixes the mute thing is uninstalling.

**Comment by IAmLemonade** [comment]
I have exactly the same issue. After updating discord the BD deleted. I tried reinstalling it and it opens in the browser versions. I'm muted and can't unmute. Some of my friends says that BD is working normally for them and some says they don't have it.

**Comment by LoganDark** [comment]
Discord's new update breaks BBD because it relied on insecure features that Discord has now disabled. The `restructure` branch contains a version that works for new Discord, but it hasn't been officially released yet.

**Comment by Tropix126** [comment]
> > Discord's new update breaks BBD because it relied on insecure features that Discord has now disabled. The `restructure` branch contains a version that works for new Discord, but it hasn't been officially released yet.
> 
> Has there been any ETA of when it will be released?

today or tomorrow

**Comment by CobreDev** [comment]
Well I was messing around with trying to compile the `restructure` branch, and *right as I went to clone it*, it was deleted. hopefully that means that it's going to be released soon!

**Comment by rauenzi** [comment]
Try to install BetterDiscord using this new beta installer: https://github.com/BetterDiscord/Installer

**Comment by MrEaqz** [comment]
I had the same problem, but by using the beta my problems are solved ;)
