### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by HertZxD** [rauenzi/BetterDiscordApp#621]
![image](https://user-images.githubusercontent.com/53701922/113145262-7012f500-9258-11eb-9724-8639b21c75a9.png)
this happend when i install Betterdiscord

how do i fix this?

**Comment by altoms** [comment]
![image](https://user-images.githubusercontent.com/44924377/113299179-cb131d80-9326-11eb-830d-f7c77288aa48.png)
this happend when i install with BD Installer Beta

**Comment by rauenzi** [comment]
Your Discord version (0.0.306) is severely out of date (1.0.9) @altoms and is no longer supported
