### ISSUE TITLE
[Bug] BetterDiscord crashing Discord even with no plugins

### ISSUE THREAD

**Issue by 23Aaron** [rauenzi/BetterDiscordApp#623]
**Describe the Bug**
Launching Discord causes you to be met with an alert telling you BetterDiscord has crashed, and that you should remove all your plugins and restart.

Using restructure branch to inject.

**To Reproduce**
Launch discord.

**Expected Behavior**
Discord should launch with BetterDiscord installed, even with no plugins.

**Screenshots**
<img width="372" alt="image" src="https://user-images.githubusercontent.com/36976487/113213992-c5f39700-9270-11eb-8cf7-6a2dea4c306a.png">

**Discord Version**
Stable, 0.0.262

**Comment by rauenzi** [comment]
`restructure` was renamed to `main`. Can you check if `~/Library/Application Support/BetterDiscord` exists?

**Comment by 23Aaron** [comment]
It does!

**Comment by rauenzi** [comment]
And do the subdirectories `data`, `plugins`, and `themes` all exist?

**Comment by 23Aaron** [comment]
Inside the folder is `data` and `Dictionaries` but no `plugins` or `themes`

**Comment by rauenzi** [comment]
Is there anything inside the `data` folder? (recursively)

**Comment by 23Aaron** [comment]
Entirety of the folder contents.

<img width="516" alt="image" src="https://user-images.githubusercontent.com/36976487/113214912-0a336700-9272-11eb-8e43-13739eba34a5.png">

**Comment by rauenzi** [comment]
Can you try manually creating the plugins and themes directories and restarting Discord?

**Comment by 23Aaron** [comment]
Inside `data` or adjacent to it?

**Comment by rauenzi** [comment]
adjacent

**Comment by 23Aaron** [comment]
Issue fixed!
