### ISSUE TITLE
BandagedBD's injector (1.0.0)

### ISSUE THREAD

**Issue by rexcsgo** [rauenzi/BetterDiscordApp#624]
Prompt me to update the injector and restart the app, and i still got prompt to update again . This can go on forever unless i ignore it but it is quite annoying 
![image](https://user-images.githubusercontent.com/65408320/113237762-05a29900-92da-11eb-8a3e-5f189ada6c29.png)

**Comment by Tropix126** [comment]
Try manually reinstalling using our new cross-platform installer: https://github.com/betterdiscord/installer

**Comment by rexcsgo** [comment]
That helped me , Thank you.
