### ISSUE TITLE
Anti Virus False Alarm

### ISSUE THREAD

**Issue by dolkilu** [rauenzi/BetterDiscordApp#625]
Edited title to Anti Virus False Alarm as a PSA. As people said because the installer is new, etc.
![image](https://user-images.githubusercontent.com/16611027/113260942-6e513c00-9301-11eb-8630-c7d034d71a11.png)

**Comment by rSh4d0w** [comment]
just a false alarm, no detection on virustotal(0/66).
https://www.virustotal.com/gui/file/acaff4359db07784f208dd818fccffaa33afbb9e9e432c7b85965e7b8c5833e5/details
Your AV might flag it during runtime because it interacts with the files of discord.

**Comment by rauenzi** [comment]
It is a false alarm. You can check virus total like the person above suggested. I've already had the installer whitelisted by Microsoft themselves.
