### ISSUE TITLE
[Bug] Custom Theme not loading as previously

### ISSUE THREAD

**Issue by sruPL** [rauenzi/BetterDiscordApp#626]
**Describe the Bug**

so I read in changelog that something about CSS has changed. I have my custom theme that's been working for years, but not since the 1.0 update today. I can enable the theme, but nothing changes. When I click edit, first line is highlighted with red:

//META{"name":"Witcher Theme Clean"}*//

This may not be entirely bug, but it's an issue I ran into after updating the BD version.

**Screenshots**

https://imgur.com/JnyEkxQ

**Discord Version**
 Stable

**Comment by sruPL** [comment]
I managed to fix it by updating some of the code from original template.

**Comment by sdfg2** [comment]
Could you explain how?

**Comment by sruPL** [comment]
> Could you explain how?

Basically I went back to the original template that I used for modifying the theme and pasted back the stuff that I took for irrelevant and deleted earlier. Maybe something has changed there too and it got updated since author updates his stuff. I have no idea what broke it doe since it worked like that fine for years.

**Comment by sdfg2** [comment]
> > Could you explain how?
> 
> Basically I went back to the original template that I used for modifying the theme and pasted back the stuff that I took for irrelevant and deleted earlier. Maybe something has changed there too and it got updated since author updates his stuff. I have no idea what broke it doe since it worked like that fine for years.

Mine doesn't work, same thing with red in the //META line, no clue what to change.

`//META{"name":"Paranoia","description":"Generated Automatically using https://0x71.cc/bd/theme | Original theme [BasicBackground] made by DevilBro","author":"0x71, DevilBro","version":"1.0.5"}*//
`

**Comment by rauenzi** [comment]
Reinstall BD and try again

**Comment by sdfg2** [comment]
> Reinstall BD and try again

Thanks!

**Comment by sruPL** [comment]
> > > Could you explain how?
> > 
> > 
> > Basically I went back to the original template that I used for modifying the theme and pasted back the stuff that I took for irrelevant and deleted earlier. Maybe something has changed there too and it got updated since author updates his stuff. I have no idea what broke it doe since it worked like that fine for years.
> 
> Mine doesn't work, same thing with red in the //META line, no clue what to change.
> 
> `//META{"name":"Paranoia","description":"Generated Automatically using https://0x71.cc/bd/theme | Original theme [BasicBackground] made by DevilBro","author":"0x71, DevilBro","version":"1.0.5"}*// `

Go to DevilBro website and copy source code from this Theme, it will fix it.
