### ISSUE TITLE
BandageDB installing v0.3.5 instead of v1.0.5[Bug]

### ISSUE THREAD

**Issue by IrregularGamer** [rauenzi/BetterDiscordApp#628]
**Describe the Bug**
So I run Discord and I see a message saying there is a new version for the BandageDB injector and I click update and it gave me an error so I went to the BetterDiscord site to download BandageDB and it pointed me here: https://github.com/rauenzi/BetterDiscordApp/releases
So after downloading the windows installer I opened the .exe and it gave me a notification that there is a newer version available so I click the option to download it and it takes me to a google site and starts the download automatically and after it download s I run it and it says v1.0.5 and I proceed to install it. But before this I did uninstall BandageDB. So after I see that the installer is v1.0.5 I proceed to install it after I install it I run Discord (With Administrator) Discord loads normally and a changelog pops up saying that the current installed version of BandageDB is v0.3.5. So I went and uninstalled BandageDB again and redownloaded the .exe and same thing happens.

**To Reproduce**
For me it's like this:
1.Uninstall BandageDB
2.Go to https://github.com/rauenzi/BetterDiscordApp/releases
and download the latest release witch is v1.0.0 (Windows Installer)
After opening the Windows Installer that you've just downloaded from github it should show a small windows saying that a newer version is available witch is v1.0.5 if this pops up click yes because if you click no the Installer just closes.
3.After clicking Yes it should take u to a link on google and the download should start automatically. After download finishes run the installer it should be on v.1.0.5 If it says v1.0.5 you are on the correct path.
4.Install BandageDB and choose the option Install to Stable.
5.After installation finishes run discord. It should display a window saying a newer version is available first or it could display the changelog first. And in the changelog it says v.0.3.5

**Expected Behavior**
I expect it to happen to you to but that is not a 100% guarantee.

**Screenshots**
![Screenshot 2021-04-01 164232](https://user-images.githubusercontent.com/78437962/113311472-a3fa2300-9309-11eb-9b21-7c6009913342.jpg)
![Screenshot 2021-04-01 164259](https://user-images.githubusercontent.com/78437962/113311478-a52b5000-9309-11eb-8510-3319754e7e7c.jpg)
![Screenshot 2021-04-01 164342](https://user-images.githubusercontent.com/78437962/113311481-a65c7d00-9309-11eb-9d12-b05045d0b2e5.jpg)
![Screenshot 2021-04-01 164412](https://user-images.githubusercontent.com/78437962/113311493-a8264080-9309-11eb-9db8-540ae5203962.jpg)
![Screenshot 2021-04-01 164442](https://user-images.githubusercontent.com/78437962/113311498-a8bed700-9309-11eb-9e13-a9c0e52183f8.jpg)
![Screenshot 2021-04-01 164502](https://user-images.githubusercontent.com/78437962/113311500-a9576d80-9309-11eb-8e03-f0f123680688.jpg)

**Discord Version**
Stable 

**Additional Context**
I don't know if this will happen to everyone but it happens to me.

**Comment by snappyapple632** [comment]
A workaround for this issue is to download the new autoinstaller from the readme. The releases page hasn't been updated.

**Comment by IrregularGamer** [comment]
Thanks for the help.
Issue is resolved.
