### ISSUE TITLE
[Bug] BandagedBD Injector Available

### ISSUE THREAD

**Issue by Reqon** [rauenzi/BetterDiscordApp#629]
Well i guess this photo will be enough to answer all of those questions : https://imgur.com/a/CtuOS9J Even if you click on update it will keep poppin up

**Comment by snappyapple632** [comment]
A workaround for this issue is to download the new autoinstaller from the readme.

**Comment by rauenzi** [comment]
Download the latest installer and install https://github.com/BetterDiscord/Installer/releases/latest
