### ISSUE TITLE
betterDiscord

### ISSUE THREAD

**Issue by SnowDynay** [rauenzi/BetterDiscordApp#63]
**I do not understand why but "BetterDiscord" will not run for me** _I don't understand why please explain_

**Comment by rauenzi** [comment]
I don't understand what isn't running

**Comment by VulpixHeart** [comment]
It's not working for me either. the installer ran, and discord restarted, but in the settings there is no option for betterdiscord's settings

**Comment by rauenzi** [comment]
Without further info, there is nothing I can do. Closing this.

**Comment by SYED-HASAN-IS-TAKEN** [comment]
I cant download it When I click "Download" it takes me to this website https://github.com/rauenzi/BetterDiscordApp/releases
What do I do

**Comment by rauenzi** [comment]
That is the correct page, download the installer from there.

**Comment by SYED-HASAN-IS-TAKEN** [comment]
Thanks!****
