### ISSUE TITLE
[Bug] betterdiscord not work

### ISSUE THREAD

**Issue by NotAllowIce1102** [rauenzi/BetterDiscordApp#630]
![unknown](https://user-images.githubusercontent.com/70061295/113331270-5229bb00-9352-11eb-985a-0afd9614870f.png)
**Describe the Bug**

install better discord not work
**To Reproduce**

**Expected Behavior**

i cant open mic cant close discord
**Screenshots**

**Discord Version**

**Additional Context**

**Comment by Tropix126** [comment]
Use the new cross-platform installer. ====>>>> https://github.com/BetterDiscord/Installer/releases/tag/v1.0.0-beta

**Comment by NotAllowIce1102** [comment]
it work thank you so much !

Tropical ***@***.***> 于2021年4月2日周五 上午1:27写道：

**Comment by Wristing** [comment]
> Use the new cross-platform installer. ====>>>> https://github.com/BetterDiscord/Installer/releases/tag/v1.0.0-beta

it works on linux too ty
