### ISSUE TITLE
[Bug] Custom css not loading from save in detached window

### ISSUE THREAD

**Issue by WIPocket** [rauenzi/BetterDiscordApp#632]
**Describe the Bug**
The custom css window shows up empty (doesnt load the saved css).

**To Reproduce**
- Save any custom css
- Set the Custom CSS Editor Location to Detached Window
- Open the Custom CSS editor

**Expected Behavior**
It should load.

**Screenshots**
![Screenshot](https://user-images.githubusercontent.com/18397681/113351523-4bdc1480-933b-11eb-8e9c-125e3fd7d4ce.png)

**Discord Version**
Stable 81171 (2a43a4e)
BD 1.0.0 (stable)
Host 0.0.14
Injector 0.6.0
Linux 64-Bit (5.10.0-5-Amd64)

**Comment by Tropix126** [comment]
Enable live update or save your changes before detaching.

**Comment by rauenzi** [comment]
Fixed in this commit https://github.com/rauenzi/BetterDiscordApp/commit/a2238060607a98720b761672f603bbff4a40f99b

It will go live in the next update
