### ISSUE TITLE
[Bug] Update not posible

### ISSUE THREAD

**Issue by thegame4craft** [rauenzi/BetterDiscordApp#634]
**Describe the Bug**
if i open discord, bd says, that is an update avaiable. if i press update now, bd restarts and nothing happend. i have tryed to reinstall it, but it didn't help

**To Reproduce**
open discord if bd is installed and bd update is avaialbe

**Discord Version**
stable 0.0.309

**Comment by Daxorinator** [comment]
+1 Infinite update loop

**Comment by Akasiek** [comment]
Same problem here. Attaching screenshot for reference
![image](https://user-images.githubusercontent.com/37307597/113417271-53470080-93c3-11eb-95d1-7eaa70a85921.png)

**Comment by QuantumWarpCode** [comment]
This is fixed if you reinstall from here. https://github.com/BetterDiscord/Installer

**Comment by rauenzi** [comment]
Please install using the latest installer linked above.
