### ISSUE TITLE
I have the bug, that when i download the new version, then in discord stands i need the new version, and when i restart my pc i have to redownload all[Bug]

### ISSUE THREAD

**Issue by NosslDo** [rauenzi/BetterDiscordApp#637]
**Describe the Bug**

**To Reproduce**

**Expected Behavior**

**Screenshots**

**Discord Version**

**Additional Context**

**Comment by rauenzi** [comment]
Please try the new installers listed on the README and also format your issue properly...

**Comment by NosslDo** [comment]
i tried, but there is always that i need the new version


Zack ***@***.***> schrieb am Fr., 2. Apr. 2021, 20:15:

**Comment by rauenzi** [comment]
I don't understand the issue.

Have you tried these? They are brand new as of 2 days ago https://github.com/BetterDiscord/Installer/releases/latest

**Comment by NosslDo** [comment]
tysm, now it is working, in dc there doensnt stand that i need the new
version

tysm

Am Fr., 2. Apr. 2021 um 20:24 Uhr schrieb Zack ***@***.***>:
