### ISSUE TITLE
[Bug] Cannot access 'fs' before initialization

### ISSUE THREAD

**Issue by TheGeekMan962** [rauenzi/BetterDiscordApp#638]
**Describe the Bug**

**To Reproduce**

**Expected Behavior**

**Screenshots**

**Discord Version**

**Additional Context**

**Comment by rauenzi** [comment]
Sounds like you are using the old mac installer, please use the new one found here: https://github.com/BetterDiscord/Installer/releases/latest

**Comment by TheGeekMan962** [comment]
I have an installation problem (file compression)

**Comment by TheGeekMan962** [comment]
Safari Cannot Unzip This File Safari is unable to open the "BetterDiscordMacInstaller.zip" file because it is still being downloaded.

**Comment by rauenzi** [comment]
That is not the filename of the new installer, not sure what you're downloading.
