### ISSUE TITLE
[Bug] Update for BandagedBD's Injector (1.0.0)

### ISSUE THREAD

**Issue by AColtZz** [rauenzi/BetterDiscordApp#639]
**Describe the Bug**

BandagedBD's injector update panel not going away

**To Reproduce**

Starting up discord, clicking on update now and the message then reappears after it restarts itself. Hard to describe how to reproduce since this opens up when opening discord.

**Expected Behavior**

You click on Update Now it updates whatever the injector is and then it doesn't reappear the message. Quick note I noticed when looking at versions it just doesn't update.

**Screenshots**

![image](https://user-images.githubusercontent.com/36159762/113445334-fc0e5380-93f5-11eb-97cf-20127cc1b6ab.png)

**Discord Version**

![image](https://user-images.githubusercontent.com/36159762/113445492-44c60c80-93f6-11eb-9f51-38898518db69.png)

**Additional Context**

I believe this update started popping up on April 1st.

**Comment by rauenzi** [comment]
Reinstall using the new installers https://github.com/BetterDiscord/Installer/releases/latest

**Comment by rauenzi** [comment]
This check has been eliminated in the old branch
