### ISSUE TITLE
Crashes at installation[Bug]

### ISSUE THREAD

**Issue by bnn-lab** [rauenzi/BetterDiscordApp#641]
If I try to install BetterDiscord Discord crashes instantly at the first time I open it, BetterDiscord seems to be installed in that crashing version ( I can see the small watermark )

If I open Discord again after it crashing it does open and works just fine, but BetterDiscord isn´t installed.

If I try to Repair the Installation the exact same happens and BetterDiscord doesn´t install.

**Comment by rauenzi** [comment]
Are you using the latest installers? Can you show the installer log?

**Comment by bnn-lab** [comment]
I am using the latest installer, here is the installer log and a Video of me trying to install Betterdiscord

Starting Install...

Creating required directories...
✅ Directory exists: C:\Users\benkr\AppData\Roaming\BetterDiscord
✅ Directory exists: C:\Users\benkr\AppData\Roaming\BetterDiscord\data
✅ Directory exists: C:\Users\benkr\AppData\Roaming\BetterDiscord\themes
✅ Directory exists: C:\Users\benkr\AppData\Roaming\BetterDiscord\plugins
✅ Directories created

Downloading asar file
✅ Package downloaded

Injecting shims...
Injecting into: C:\Users\benkr\AppData\Local\Discord\app-0.0.309\resources
✅ Injection successful
✅ Shims injected

Restarting Discord...
Attempting to kill Discord
✅ Discord not running
✅ Discord restarted

Install completed!


https://user-images.githubusercontent.com/71351879/113725991-24e36100-96f4-11eb-8825-d697bb460440.mp4

Like already said, if I try to open discord a second time after installing Betterdiscord it is just the vanilla discord without Betterdiscord
installed.

**Comment by rauenzi** [comment]
Please try removing all existing plugins and Launching Discord. If that still fails rename this directory (`C:\Users\benkr\AppData\Roaming\BetterDiscord`) to something else and reinstall

**Comment by bnn-lab** [comment]
Tried both, still shows the same behavior.
 I also deleted the old betterdiscord directory, but that didn´t work either

**Comment by rauenzi** [comment]
Close out Discord via the task manager. Make sure any process called Discord is shut down. Delete or rename the BD directory `C:\Users\benkr\AppData\Roaming\BetterDiscord`. Reinstall BD and post the install logs from that instance.

**Comment by bnn-lab** [comment]
Starting Install...

Creating required directories...
✅ Directory exists: C:\Users\benkr\AppData\Roaming\BetterDiscord
✅ Directory created: C:\Users\benkr\AppData\Roaming\BetterDiscord\data
✅ Directory created: C:\Users\benkr\AppData\Roaming\BetterDiscord\themes
✅ Directory created: C:\Users\benkr\AppData\Roaming\BetterDiscord\plugins
✅ Directories created

Downloading asar file
✅ Package downloaded

Injecting shims...
Injecting into: C:\Users\benkr\AppData\Local\Discord\app-1.0.9001\resources
✅ Injection successful
✅ Shims injected

Restarting Discord...
Attempting to kill Discord
✅ Discord not running
✅ Discord restarted

Install completed!


Ok, seems like the issue is fixed, discord does start and didn´t crash either. 
Thanks a lot
