### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by GrimWolf47** [rauenzi/BetterDiscordApp#642]
**Describe the bug***
I can't activate my theme's/plugin's I go to the setting and activate my theme it says its activated but nothing changes.

**To Reproduce**
1. Go to 'settings'
2. Click on 'Themes/plugins'
3. Activate the 'Theme/plugins'
4. See error, theme/plugin just doesn't activate

**Expected behavior**
When I activate my themes/plugins I usually expect them to work,.

**Screenshots**
![image](https://user-images.githubusercontent.com/81835212/113460728-50f29f80-93df-11eb-854e-8996905f9e4f.png)
![image](https://user-images.githubusercontent.com/81835212/113460749-5fd95200-93df-11eb-93e6-fb2a6467f1e9.png)

**System Information:**
 - OS: [Windows]
- Discord Version: [Newest]

If possible a Fix would be appreciated 
(Just noticed the Themes and Plugin area no longer show up)

**Comment by rauenzi** [comment]
Check console for errors. This sounds more like an issue with the plugins/themes than with BD

**Comment by GrimWolf47** [comment]
> Check console for errors. This sounds more like an issue with the plugins/themes than with BD

How exactly do I do that?

**Comment by rauenzi** [comment]
The same as you would in any browser, ctrl+shift+i.

**Comment by RaidenQuad** [comment]
Same issue. Themes and plugins worked on past version, now they don't.

**Comment by Aida-Enna** [comment]
Same issue here, nothing in the console about them. They just don't load.

**Comment by Maxallica** [comment]
My theme is only partially working at the moment. Background, PopUps and all is working apart from the custom Fonts from https://fonts.google.com/ aren't working anymore with the new beta BetterDiscord installer.
Please fix this.

**Comment by rauenzi** [comment]
Can you all define what you mean by "don't load"? Are they not showing in the plugin/theme list? Or is the desired effect not achieved when enabling?

**Comment by rauenzi** [comment]
Hi, please try reinstalling BD and see if the issue persists. @GrimWolf47

**Comment by SamLam140330** [comment]
I have the same issue too

**Comment by rauenzi** [comment]
Can you try the proposed solution then?

**Comment by GrimWolf47** [comment]
> Hi, please try reinstalling BD and see if the issue persists. @GrimWolf47

I'll try that

**Comment by GrimWolf47** [comment]
> Hi, please try reinstalling BD and see if the issue persists. @GrimWolf47

The Proposed Solution fixed my Issue thanks! I appreciate the help!

**Comment by rauenzi** [comment]
You're welcome!
