### ISSUE TITLE
msafee detects better discord as virus.

### ISSUE THREAD

**Issue by zanezonair** [rauenzi/BetterDiscordApp#643]
info on this i think its a false positvie but im listing the info here to be safe
index.js Real-Protect-EC!CB3993BBFBFC

**Comment by Tropix126** [comment]
This is indeed a false-positive. McAfee is all-around a poor antivirus, recommend using something like malwarebytes or just windows defender. All code for the BD injector and features are open source in this repo.

**Comment by Tropix126** [comment]
If you are still suspicious, I guess you can run the file in question through https://virustotal.com/

**Comment by rauenzi** [comment]
> i think its a false positvie

I think you're right, unless you've downloaded BD from some unofficial location. We've already been verified and whitelisted through Microsoft.

**Comment by zanezonair** [comment]
thank you for letting me know. and im still going to stick with msafee as its done good for me in the past comapred to other anti virus. once again thank you for letting me know it was a fase positive.
