### ISSUE TITLE
"BetterDiscord seems to have crashed your Discord Client" Pop-Up

### ISSUE THREAD

**Issue by Th3St1g** [rauenzi/BetterDiscordApp#644]
**Describe the Bug**
Pop-up with the title "Better Discord seems to have crashed your Discord Client" and a description "BetterDiscord has automatically disabled itself temporarily. Try removing all your plugins then restarting Discord."

**To Reproduce**
Not entirely sure (Look at Additional Context).

**Expected Behavior**
Expected a clean installation of the update (stated that it was cross-platform and honestly didn't really understand what that meant)

**Screenshots**
![image](https://user-images.githubusercontent.com/50114689/113466714-7ee9db00-9403-11eb-8d00-e5d380ab29c9.png)
^Pop-up

**Discord Version**
Stable 81329 (b80bbff)
Windows x64

**Additional Context**
I had BandagedBD (latest version) before this and had a popup to "update" which was this program. Downloaded and installed it. Re-opened Discord and got the pop-up. Tried the repair function and removing my plugins from the "Plugins" folder with no luck. After closing the pop-up window, Discord is returned to the original form.

**Comment by rauenzi** [comment]
Please take these steps:

1. Fully close Discord.
2. Remove all plugins from the `plugins` folder.
3. Start Discord

Should that not work, please attach a screenshot of the contents of the `BetterDiscord` folder

**Comment by Th3St1g** [comment]
The BD verision of Discord will show after loading for about half a second then return back to normal version along with the popup.
![image](https://user-images.githubusercontent.com/50114689/113466934-42b77a00-9405-11eb-88bd-aea9c2d6b7b4.png)

**Comment by rauenzi** [comment]
Please try this: rename the `betterdiscord` folder to something else (as a backup). Then run the new installer again.

**Comment by Th3St1g** [comment]
Installation was successful and plugins work. 

Side Note: Noticed that the file name went from "betterdiscord" to a capitalized "BetterDiscord". Minimal Mode, doesn't seem to work properly, but that's a very minor issue and maybe one for a different thread.

Thank you for the help and appreciate all the effort and work!!!
