### ISSUE TITLE
[Bug] Installer doesn't auto-detect Discord installed through Scoop

### ISSUE THREAD

**Issue by ghost-420** [rauenzi/BetterDiscordApp#645]
**To Reproduce**
* Open PowerShell (no administrator).
* `Set-ExecutionPolicy RemoteSigned -scope CurrentUser;Invoke-Expression (New-Object System.Net.WebClient).DownloadString('https://get.scoop.sh')`
* `scoop bucket add extras`
* `scoop install discord`
> PTB: `discord-ptb` \
Canary: `discord-canary`

**Expected Behavior**
Installer detects Discord Stable installation at `$USER/scoop/apps/discord/current`

**Discord Version**
Stable, PTB, Canary

**Comment by Tropix126** [comment]
Issues regarding the installler should be opened at https://github.com/betterdiscord/installer.

**Comment by rauenzi** [comment]
Read the above. Also the installer is generally not meant to detect every edge case, but rather standard installs.
