### ISSUE TITLE
[Bug] Opening plugins folder using button causes GUI lockup

### ISSUE THREAD

**Issue by Meister1593** [rauenzi/BetterDiscordApp#647]
**Describe the Bug**
When you go to Settings -> BetterDiscord -> Plugins and press `Open Plugins Folder`, it opens plugins folder as it should do and... entire Discord UI is frozen.
I can still exit Discord using systray just fine, and open discord again, but GUI will still be frozen.
Also, when i hover mouse over frozen GUI - it shows as i'm about to click a button. 

**Discord Version**
Stable, Canary

**OS**
Archlinux

**Comment by Meister1593** [comment]
UPD: It actually unfroze after some time, after about 2-5 mins

**Comment by rauenzi** [comment]
Hm this does not happen for me, however I am not on Linux. Can anyone else on Linux confirm this?

**Comment by Meister1593** [comment]
It seems that issue resolved by itself, i don't have such lockup now...

**Comment by rauenzi** [comment]
Weird, must have been a one-off thing. If this repeats itself please reopen.

**Comment by Meister1593** [comment]
> @Meister1593 & @rauenzi can we can get this reopened. The issue as initially described still persists on Linux

I personally don't use BD anymore and not sure if I will have any use from it for myself
