### ISSUE TITLE
[Bug]I can't install BetterDiscord

### ISSUE THREAD

**Issue by Commands-Cat** [rauenzi/BetterDiscordApp#648]
**Describe the Bug**
- The installer did not succeed in installing BetterDiscord.

**To Reproduce**
- 1. Open the installation program
- 2. Install BetterDiscord > Discord > Install

**Expected Behavior**
- BetterDiscord cannot be installed

**Screenshots**
![image](https://user-images.githubusercontent.com/72594971/113478462-84a2f780-94bb-11eb-9edb-35ef05fb474d.png)

**Discord Version**
- Stable

**Additional Context**
- None

**Comment by rauenzi** [comment]
Fully close Discord before running the installer. Installer issues belong in the corresponding repo https://github.com/BetterDiscord/Installer
