### ISSUE TITLE
[Bug] Timestamps in japanese

### ISSUE THREAD

**Issue by SKProCH** [rauenzi/BetterDiscordApp#650]
**Describe the Bug**
"Today" timestamps are displayed in Japanese, language in settings are English

**To Reproduce**
Start discord, wait ~30 seconds and "Today" will be replaced with hieroglyphs

**Expected Behavior**
"Today" timestamps must be displayed in selected language

**Screenshots**
![image](https://user-images.githubusercontent.com/29896317/113489814-00f30600-94cf-11eb-9564-6e1a02376ade.png)
![image](https://user-images.githubusercontent.com/29896317/113489837-34359500-94cf-11eb-88c4-5e612331df12.png)

**Discord Version**
Stable

**Comment by rauenzi** [comment]
I believe this is the side effect of a plugin, but I forget which one. Please try loading without any plugins.

**Comment by SKProCH** [comment]
Yes, you are right. This is `DiscordFreeEmojis` plugin. Thanks
