### ISSUE TITLE
[Bug] Discord acting like website and BD doesn't lunch up

### ISSUE THREAD

**Issue by DexyAnimations** [rauenzi/BetterDiscordApp#651]
**Describe the Bug**

**To Reproduce**

**Expected Behavior**

**Screenshots**

**Discord Version**

**Additional Context**

**Comment by rauenzi** [comment]
Use the latest installers as dictated in the README at http://github.com/BetterDiscord/Installer

**Comment by DexyAnimations** [comment]
> Use the latest installers as dictated in the README at [http://github.com/BetterDiscord/Installer](https://github.com/BetterDiscord/Installer)

i did and it's doing same thing and when i use beta BD its crashing a lot, without BD my normal discord crashing a lot too

**Comment by rauenzi** [comment]
> without BD my normal Discord is crashing too

Then it sounds like you're having more issues than BD. Reinstall Discord.

**Comment by DexyAnimations** [comment]
> > without BD my normal Discord is crashing too
> 
> Then it sounds like you're having more issues than BD. Reinstall Discord.

i actually did and it said some error https://gyazo.com/29ccedf3996adc21fea0569e52f5ca0e and when i restarted pc it disappeared and BD did luck up but discord wanted update and than it happened again act like website and wanted me download discord app even i was using it, now i use beta BD and it didn't crash yet, i will show how that discord acted https://gyazo.com/15d33c84685ecea6b4b47f91f5730cf6 pls ignor my dms with people just look what it doing, its doing idh how long almost month
