### ISSUE TITLE
[Bug] [Google Translate] Problem trying to maximize application in full screen mode

### ISSUE THREAD

**Issue by patrickxfranco** [rauenzi/BetterDiscordApp#653]
**Describe the Bug**
**[Google Translate]** After installing Better Discord, minimizing an application that works in full screen, like games for example, to maximize the screen again is difficult because when clicking on the application icon on the taskbar, the screen is black as if the app were to open, but then go back to the desktop, it doesn't happen when Discord is completely closed.

**To Reproduce**
**[Google Translate]** First, with Discord using Better Discord open, open a game and leave it in full screen mode, after it is already in the game menu or during gameplay, minimize it and after going to the desktop, try to maximize the game, you might even be able to, but only after 6 or 7 attempts.

**Expected Behavior**
**[Google Translate]** When trying to maximize the game, I expected it to maximize without me having to try it 7 times, that is, clicking on the game icon on the taskbar.

**Discord Version**
Stable

**Additional Context**
**[Google Translate]** Sometimes this bug doesn't happen and the game ends up opening on the first try.

**Comment by rauenzi** [comment]
Do you have window transparency enabled?
