### ISSUE TITLE
[Bug] Download stuck

### ISSUE THREAD

**Issue by xXChezyXx** [rauenzi/BetterDiscordApp#654]
**Describe the Bug**

If I try to install BetterDiscord, it will download but it stucks on "Downloading asar file".

**To Reproduce**

No idea.

**Expected Behavior**

It will download BetterDiscord without any errors.

**Screenshots**

[https://prnt.sc/113y37q](url)

**Discord Version**

Stable (app-0.0.309)

**Comment by rauenzi** [comment]
This is an issue with the installer: https://github.com/BetterDiscord/Installer
