### ISSUE TITLE
[Bug] The installer is stuck

### ISSUE THREAD

**Issue by Ultra-Drago** [rauenzi/BetterDiscordApp#656]
I just tried installing the latest version of BD and it's stuck on attempting to kill discord.
I hope you guys can fix this minor issue

![image](https://user-images.githubusercontent.com/72343592/113541940-d4d7a200-9600-11eb-902c-d10da003dcaf.png)

**Discord Version**
Stable

**Comment by rauenzi** [comment]
This can happen with permissions being funky. Try making sure Discord is already fully closed (with task manager) before running the installer. Also in the future, be sure to put issues with the installer in the correct repo ==> https://github.com/BetterDiscord/Installer
