### ISSUE TITLE
Takes control of my game launching

### ISSUE THREAD

**Issue by Soitora** [rauenzi/BetterDiscordApp#66]
I can attach more files later but gonna add this real quick as it just releaseD;

When I start a game (in this case, League, in the game loading screen) it makes the screen completely grey and you can see BD loading in the bottom-right corner, only way to fix is to reload Discord

**Comment by Soitora** [comment]
https://i.imgur.com/X7Izjwj.png

**Comment by rauenzi** [comment]
Redownload the installer, just implemented a fix in the injection.
