### ISSUE TITLE
[Bug] BD incompatible with Latest Discord Update.

### ISSUE THREAD

**Issue by SgtSparky** [rauenzi/BetterDiscordApp#660]
**Describe the Bug**
 Wont load or anything and can't move or close the windows and the application think your are in a Browser.

**To Reproduce**
 Install latest BD version and have fun.

**Expected Behavior**
 Make the Discord App like on a browser, so can't close or move the window and nothing load about BD.

**Discord Version**
 Stable 81452 (1c03382)

**Additional Context**
 Are you guys working on it ?

**Comment by rauenzi** [comment]
Please try the latest installers: https://github.com/BetterDiscord/Installer/releases/latest

**Comment by SgtSparky** [comment]
FIXED. Thanks.
