### ISSUE TITLE
[Feature] CSS Detachable Window. ( That is actually Detached from the discord app )

### ISSUE THREAD

**Issue by xFadedxShadow** [rauenzi/BetterDiscordApp#661]
**Is your feature request related to a problem? Please describe.**

The Detach Feature in the custom CSS isn't 100% detachable it has to stay within the discord window.
I would like it to be possible to move this window onto another monitor or even separate it from the window so when creating custom themes will be easier for creators.

**Comment by xFadedxShadow** [comment]
I'm also on the Linux Build.

**Comment by rauenzi** [comment]
It is not meant to move to another window. This feature was considered, and I will say it is unlikely to happen. If you truly want your custom css in a separate window or separate monitor, just  open it in your system editor.

**Comment by xFadedxShadow** [comment]
Alright thanks.

**Comment by LoganDark** [comment]
I was actually just about to suggest this. I use system-wide shortcuts to move my windows and the behavior of the custom CSS window (only movable by titlebar, unable to go even partially off-screen) is quite annoying, I'd prefer to at least have the *option* to make it a regular window.

As for "just use your system editor" there's no way to apply changes without saving like you can in the BD popout.

Is there a reason why you won't implement this?
