### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Resortia** [rauenzi/BetterDiscordApp#662]
It says "BetterDiscord seems to have crashed your discord client"
"BetterDiscord has automatically disabled itself temporarily. Try removing all your plugins then restarting discord"
Help?

**Comment by rauenzi** [comment]
Have you tried removing your plugins? Please in the future be sure to fill out the issue template properly so we have more information to go off.

**Comment by Vekla02** [comment]
> Have you tried removing your plugins? Please in the future be sure to fill out the issue template properly so we have more information to go off.

there is a bug, when someone sends this site: https://tornadus.net/orange it converts into gif and when someone sees it, it completly crashes discord

**Comment by Tropix126** [comment]
> > Have you tried removing your plugins? Please in the future be sure to fill out the issue template properly so we have more information to go off.
> 
> there is a bug, when someone sends this site: https://tornadus.net/orange it converts into gif and when someone sees it, it completly crashes discord

Are you sure this is related to BD? Does it happen with BD uninjected?

**Comment by Vekla02** [comment]
> > > Have you tried removing your plugins? Please in the future be sure to fill out the issue template properly so we have more information to go off.
> > 
> > 
> > there is a bug, when someone sends this site: https://tornadus.net/orange it converts into gif and when someone sees it, it completly crashes discord
> 
> Are you sure this is related to BD? Does it happen with BD uninjected?

yes, it gives the message from the original post "BetterDiscord seems to have crashed your discord client"

**Comment by Tropix126** [comment]
Try troubleshooting by doing this:
![image](https://user-images.githubusercontent.com/42101043/113920967-13a95b80-97ab-11eb-99d3-143012e81746.png)

**Comment by Vekla02** [comment]
tried that already

**Comment by Resortia** [comment]
> Try troubleshooting by doing this:
> ![image](https://user-images.githubusercontent.com/42101043/113920967-13a95b80-97ab-11eb-99d3-143012e81746.png)

thanks that helped, it works now
