### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by ImmuneLion318** [rauenzi/BetterDiscordApp#664]
Discord Crashing When I Attempt To Type I Removed All Plugins And Still Didn't Work
Discord Stable Edition

**Comment by aldarmak** [comment]
Thanks for the feedback,yes I will do it thanks again

**Comment by rauenzi** [comment]
Try renaming the BD folder and reinstalling.

**Comment by ImmuneLion318** [comment]
> 
> 
> Try renaming the BD folder and reinstalling.

I Have Found Out Canary Works Fine But Stable This Has Issue And I Will Try Your Solution In A Bit

**Comment by ImmuneLion318** [comment]
Renaming And Installing Didn't Work But I Switched To Canary Which Works Perfectly Fine
