### ISSUE TITLE
better discord seems to have crashed your discord client

### ISSUE THREAD

**Issue by Pista-afk** [rauenzi/BetterDiscordApp#666]
**Describe the Bug**

i start discord and pop out message better discord seems to have crashed your discord client
**To Reproduce**

**Expected Behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/82143750/113991546-dc8e8500-9852-11eb-96f9-79704a6f293e.png)

**Discord Version**

Stable 81648 (183bc30)
**Additional Context**

i try to delete all plugins and themes and even a uninstal and instal bd but no luck

**Comment by rauenzi** [comment]
Rename the existing BD folder and reinstall BD

**Comment by 1Charon0** [comment]
i rename the setup and reinstall but still same problem
