### ISSUE TITLE
BetterDiscord crashing

### ISSUE THREAD

**Issue by Yangee12** [rauenzi/BetterDiscordApp#668]
When i launch up BetterDiscord it come up with this error message:
![image](https://user-images.githubusercontent.com/79055909/114005735-bfa88080-9857-11eb-9d08-b9a0ecea8a8d.png)
After the error message normal discord starts up. It tells me to disable all plugins but i can't because it launches normal discord which doesn't have that feature. I have tried uninstalling and deleting everything (discord, betterdiscord, plugin folder, themes folder) and reinstalling but it doesn't work.
Can someone please help?
p.s. im using discord stable

**Comment by Switch1024** [comment]
I have the same problem, appears when sending a single text message.

**Comment by saiv123** [comment]
ya i have the same thing

**Comment by saiv123** [comment]
i fixed it by uninstalling discord deleting all of discord files in the romeing folder in appdata and reinstalling it
it seems to be an error with the discord version

**Comment by Yangee12** [comment]
oh ty saiv

**Comment by Yangee12** [comment]
It still doesn't work.

**Comment by rauenzi** [comment]
Close Discord, rename your betterdiscord folder, then reinstall.

**Comment by Switch1024** [comment]
> Close Discord, rename your betterdiscord folder, then reinstall.

the funny thing is, a gif crashed my BD client. This is the gif; https://tornadus.net/assets/video/how.mp4

**Comment by Tropix126** [comment]
> > Close Discord, rename your betterdiscord folder, then reinstall.
> 
> the funny thing is, a gif crashed my BD client. This is the gif; https://tornadus.net/assets/video/how.mp4

When that gif is played back, it is causing a renderer crash which is then caught by BD, which automatically disables itself to prevent your from being placed in a possible crash loop. In reality, the dialog catches all renderer crashes regardless of whether they are BD related or not, so in reality that gif crashing discord has nothing to do with BD.

Best thing you can do right now is go to Settings > Accessability and disable automatic gif playback, then ban anyone who posts the gifs in servers you moderate to discourage people from posting it further.

**Comment by Yangee12** [comment]
thanks so much. I've fixed it now.
