### ISSUE TITLE
 Custom CSS, themes, and plugins do not appear under discord settings [Bug]

### ISSUE THREAD

**Issue by vellaG** [rauenzi/BetterDiscordApp#669]
**Describe the Bug**
Toggle Custom CSS, themes, and plugins do not appear under discord settings

**To Reproduce**
Simply doing a manual install results in the inability to edit custom css and access the plugins/themes tab.

**Expected Behavior**
Expected the ability to access the custom css tab from the settings page. Aswell as plugins and themes.

**Screenshots**

![image](https://user-images.githubusercontent.com/61596989/114022416-5ca6f180-9837-11eb-9c04-d1887c11efc3.png)
![image](https://user-images.githubusercontent.com/61596989/114022581-8829dc00-9837-11eb-9ebc-7cf3a7061b4a.png)

**Discord Version**
Stable Discord

**Comment by ramonGonzEdu** [comment]
add some sort of title that isnt just [Bug] so that people can tell what the issue is about at a glance

**Comment by ZaPeZaPe** [comment]
Its happening with me too

**Comment by vellaG** [comment]
I went to a server and it loaded in for some reason. Try that.

**Comment by ZaPeZaPe** [comment]
> I went to a server and it loaded in for some reason. Try that.

got it

**Comment by rauenzi** [comment]
Close discord, rename your BetterDiscord folder (to backup the files), and reinstall.

**Comment by rauenzi** [comment]
After re-reading I see this bug is actually a duplicate of #627 and will be fixed in the next update
