### ISSUE TITLE
[bandaged betterdiscord not working on stable]

### ISSUE THREAD

**Issue by DetectiveAlice** [rauenzi/BetterDiscordApp#671]
the BetterDiscord settings just aren't showing up; there's the space for them but it just doesn't work. i updated discord because one of my plugins broke and now BetterDiscord in general doesn't work at all.

upon reinstalling it says i'm using the browser client rather than the desktop install???? i'm not sure what to do.

I've repaired and re-installed and it doesn't fix the issue

completely reinstalling discord did absolutely nothing to help. i'm not sure what else to do.

**Comment by Donthackplsty** [comment]
Same problem here. Fresh install of betterdiscord, it says its been injected but when It restarted discord, it didn't appear. 
Also i have this problem too, "upon reinstalling it says i'm using the browser client rather than the desktop install"

**Comment by rauenzi** [comment]
> upon reinstalling it says i'm using the browser client rather than the desktop install???? i'm not sure what to do

This means you are using the old version. Please reinstall using https://github.com/BetterDiscord/Installer/releases/latest
