### ISSUE TITLE
Better Discord Installer Dosent even Open

### ISSUE THREAD

**Issue by OfficialDesh** [rauenzi/BetterDiscordApp#672]
**Describe the Bug**
I end up having to find an old outdated version of better discord aka bandagedb
when I try to open the new installer the .exe does nothing
the old download works but now it doesn't and instead reinstalls my discord into a "web version"???
reinstalling didn't fix and i now have to clean uninstall discord this new beta 1.0.0 version or whatever has been utter problems and my friends seem to have the same exact issue (happens on Windows 10)

**To Reproduce**
I went to this https://github.com/BetterDiscord/installer/releases/
which is where I got the download 
I tried other downloads and those didn't work either

after downloading I simply double click and it does nothing i even left it alone for 1 hour to see if it was just taking a while to load
despite my PC not lagging or having any issues

I've had to resort to downloading older versions
and recently when I tried it turned my normal discord into the web version

the installer simply won't open at least the new releases, and the old one does but now makes my discord into a web version

**Expected Behavior**
i expected the installer to open, and allow me to select which version of discord i wanted to have better discord on
then have a speedy install and simply get back to chatting with friends with my addons and themes

**Screenshots**
![image](https://user-images.githubusercontent.com/82183329/114100709-b2f54e00-9892-11eb-879f-31295df91796.png)
I click that like I tried double-clicking and also running as administrator to no avail

then nothing happens
I even had to clean reinstall discord as older versions magically made discord into web version
even then it won't work

**Discord Version**
Stable

**Additional Context**
not much additional context aside from it being 100% broken

**Comment by OfficialDesh** [comment]
please fix or at least tell me something I'm doing wrong I cant figure out what's wrong

**Comment by rauenzi** [comment]
Try extracting it as if it were a zip file and launch the resulting file. If this does not work, please open an issue over at https://github.com/BetterDiscord/Installer
