### ISSUE TITLE
[Bug] Lags and slow performance

### ISSUE THREAD

**Issue by BlueStarBRS** [rauenzi/BetterDiscordApp#673]
**Describe the Bug**
laggs and slow proformance since the big update

**To Reproduce**
update to the new BDdiscord 

**Expected Behavior**
before this update its just laging on startup 10 sek and then its all smooth

**Discord Version**
app-1.0.9001 i think

**Additional Context**
now its lagging the mush time and i ,ust wait 20-30 sec that the start up big lag stops and then its all not smooth and laggy and the animations are laggy too (and its lagging mush if you open and close settings)

the most time:
![image](https://user-images.githubusercontent.com/25110093/114116030-3be8a580-98e4-11eb-856b-cdc73c80f5cc.png)

**Comment by BlueStarBRS** [comment]
![image](https://user-images.githubusercontent.com/25110093/114116170-77836f80-98e4-11eb-9aa8-f26833deed6e.png)

**Comment by rauenzi** [comment]
Does this persist with plugins and themes disabled?

**Comment by TRaSH-** [comment]
hmm, think you're right.
I disabled all the plugins and it's running now 10 minutes without any lag.

so it might be a plugin that worked fine with the old app but not anymore with the new one.

going to let it run a bit longer and enable a few apps a time to see what's going to happen.

**Comment by BlueStarBRS** [comment]
> Does this persist with plugins and themes disabled?

If i load nothing yes but if i enable plugins or themes (not special one then its laggs und Works not smooth)

**Comment by BlueStarBRS** [comment]
Before that Update i have only 10 sec load lag and then smooth but now not more  do you want my plugin list and theme list ?

**Comment by BlueStarBRS** [comment]
Maybe the plugin\theme loader have a Problem or the injection Method

**Comment by rauenzi** [comment]
> Maybe the plugin\theme loader have a Problem or the injection Method

These both did not fundamentally change. They still designate the plugin to run as needed. It's possible your plugins were not optimized for context isolation changes.

**Comment by BlueStarBRS** [comment]
so this problem have not only me my friends too after you activate more then 12-15 plugins discord is slow and laggy bofore this big update instant loading  adn no laggs but now everything is laoding long and transitions are laggy

**Comment by BlueStarBRS** [comment]
![image](https://user-images.githubusercontent.com/25110093/116815583-86191b80-ab5e-11eb-8dd9-56eb290a1c35.png)
this section loaded as example 3 times faster then now

**Comment by BlueStarBRS** [comment]
![image](https://user-images.githubusercontent.com/25110093/116815633-b8c31400-ab5e-11eb-9e76-964be148b03f.png)
or here this problem that this videos stop every time on normal discord its playing without stops but here i wait 2 mins for4 sec playing

**Comment by BlueStarBRS** [comment]
and the biggest issue is its takes max 10 mins after starting discord thats stops lagging btw i found one bug more is there sometimes the taskbar icon on the infocenter is not more responding anymore then i must kill discord with the task manager if discord himself is not responding too
![image](https://user-images.githubusercontent.com/25110093/116815738-2a9b5d80-ab5f-11eb-89cd-f9fe43017a08.png)

**Comment by BlueStarBRS** [comment]
actually the most times its after starting a time and yeah some features like the emoji board will load slow all time but the general transition laggs are no more so mush only after startup 10-15min

**Comment by BlueStarBRS** [comment]
idk maybe you and the team can fix it i hope

**Comment by BlueStarBRS** [comment]
update: i updated today my BD Discord and its run so mush better only videos lagging if the have a good quality like 1080p
