### ISSUE TITLE
[Bug] BD crashing with no plugins

### ISSUE THREAD

**Issue by saiv123** [rauenzi/BetterDiscordApp#675]
**Describe the Bug**

i was trying to make changes to server setting when it randomly started crashing

**To Reproduce**

Open your user settings or open server setting in server

**Expected Behavior**

for it not to crash my discord

**Screenshots**

https://cdn.discordapp.com/attachments/280806472928198656/829891068588720188/unknown.png this is the only error i get when it crashes but i dont have any plugins

**Discord Version**

Stable

**Additional Context**

**Comment by saiv123** [comment]
i fixed it by uninstalling discord deleting all of discord files in the romeing folder in appdata and reinstalling it
it seems to be an error with the discord virstion

**Comment by aldarmak** [comment]
> i fixed it by uninstalling discord deleting all of discord files in the romeing folder in appdata and reinstalling it
> 
> it seems to be an error with the discord version

Thanks,
