### ISSUE TITLE
Hiding blocked messages

### ISSUE THREAD

**Issue by Arbalah** [rauenzi/BetterDiscordApp#68]
It's not rly an issue, but before one of discord updates it was possible to hide messages from blocked users by adding: `(function hideBlocked(){document.querySelectorAll('.message-group-blocked').forEach(div => div.setAttribute("style", "display: none;"));setTimeout(hideBlocked,500);})();` 
into custom CSS. 
Would it be possible to do that again?

**Comment by rauenzi** [comment]
Well you could never put that in css and have it work, it needs to go into console. To fix that to make it work in console you need to update `message-group-blocked` to `messageGroupBlocked-3wrQQX`
