### ISSUE TITLE
[Bug] BD Tab and Options not showing up In Settings, Upper Most Tabs Not Showing As Well

### ISSUE THREAD

**Issue by KennywasTaken** [rauenzi/BetterDiscordApp#682]
Better Discord Tab and options don't show up in settings. The buttons to close, minimize, and make the tab smaller don't show up at the either. I already tried to reinstall BD and also end all discord clients but nothing worked it still not showing both things. My themes and plugins don't work because of this as well.

Stable

It just started happening as soon as I updated my discord

![Screenshot_3](https://user-images.githubusercontent.com/66582694/114275256-75560980-99e7-11eb-9762-a866aacb4e4e.png)
![Screenshot_5](https://user-images.githubusercontent.com/66582694/114275262-7b4bea80-99e7-11eb-9fa1-a5a941bb0cd5.png)
 ^This was the highest part of discord that shows. It should normally show the close, minimize, restore down options but they don't.

**Comment by Trexity** [comment]
This is also an issue on Arch linux or any 64 bit linux distribution. It seems the injector isn't working due to a recent discord update?
I'm running Stable 81972 (9bccc1c)
Linux 64-Bit
.
![QsRN6Bp](https://user-images.githubusercontent.com/12123572/114280934-2e750d80-9a01-11eb-9de4-59e892564793.png)

**Comment by Tropix126** [comment]
You most likely have an outdated installer. Get the latest one from here: https://github.com/BetterDiscord/Installer/

**Comment by KennywasTaken** [comment]
Yea getting the latest installer worked everything is back to normal, thanks!
The new gui and stuff looks sick btw
