### ISSUE TITLE
[Bug] - Only showing "Settings" and no themes/plugins etc.

### ISSUE THREAD

**Issue by RyanHipkiss** [rauenzi/BetterDiscordApp#689]
**Describe the Bug**
After installing, only the settings tab is available. I don't see the Themes, Plugins, Custom CSS tabs etc.

**To Reproduce**
Fresh install of Discord & Better Discord, through the BetterDiscord installer.

**Expected Behavior**
All tabs to appear.

**Screenshots**
![image](https://user-images.githubusercontent.com/6339498/114303073-0d292580-9ac4-11eb-9e32-7776ad15afe1.png)

**Discord Version**
Stable 81962 (9bccc1c) 
![image](https://user-images.githubusercontent.com/6339498/114303103-46619580-9ac4-11eb-9beb-f24004497821.png)

**Comment by rauenzi** [comment]
Can you try reinstalling BD?
