### ISSUE TITLE
Installer is stuck at "Old Injection Deleted"

### ISSUE THREAD

**Issue by FloopyDisk** [rauenzi/BetterDiscordApp#69]
`Killing Discord Processes
Killing Discord process 14196
Killing Discord process 29492
Killing Discord process 20784
Killing Discord process 28948
Old injection detected in C:\Users\PlsDontHackmepc\AppData\Roaming\discordptb\0.0.43`

**Comment by rauenzi** [comment]
Try running it as admin (right click the installer and select run as administrator)

**Comment by Inve1951** [comment]
known issue.
for now simply restart the installer.

**Comment by MaximeDawn** [comment]
Also, get it out of "Download" folder if you're on Windows, as mentionned in release notes. If problem occurs, just relaunch it several times until it works. Worked at 3rd time for me :)

**Comment by HerrEurobeat** [comment]
Even the release description says how to fix that.
