### ISSUE TITLE
[Bug] BetterDiscord not Working in PTB

### ISSUE THREAD

**Issue by MiniToggled** [rauenzi/BetterDiscordApp#690]
**Describe the Bug**
I injected BD into Discord PTB and when i went to settings to apply my theme, the themes tab wasn't showing up.

**To Reproduce**
1. Inject BD into Discord PTB
2. Head to settings
3. Voila! No Themes

**Expected Behavior**
I expected to see the themes tab.

**Screenshots**
![image](https://user-images.githubusercontent.com/61615177/114303529-c987e900-9ace-11eb-93b4-0a860b537250.png)

**Discord Version**
Ptb 81972 (9bccc1c)
Host 1.0.1005
Windows 10 64-Bit (10.0.19042)

**Additional Context**
I wanted to use PTB to help discord improve!

**Comment by rauenzi** [comment]
@MiniToggled Can you try reinstalling BD?
