### ISSUE TITLE
Betterdiscord starting like it's in a browser

### ISSUE THREAD

**Issue by botii16** [rauenzi/BetterDiscordApp#693]

**Comment by KyrianDev** [comment]
yeah betterdiscord also starts like a browser on my pc as well, using windows 8.1 pro, latest version of discord canary.

**Comment by LoKaRoGacha** [comment]
+ windows 10

**Comment by rauenzi** [comment]
Please use the latest version of the installer found at https://github.com/BetterDiscord/Installer/releases/latest
