### ISSUE TITLE
[Bug] AppImage complaining about not being sandboxed.

### ISSUE THREAD

**Issue by cutieshy** [rauenzi/BetterDiscordApp#694]
**Describe the Bug**
[13926:0412/043252.496243:FATAL:setuid_sandbox_host.cc(158)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /tmp/.mount_BetterkTftXU/chrome-sandbox is owned by root and has mode 4755.

**To Reproduce**
use the shitty appimage

**Expected Behavior**
to install

**Discord Version**
stable

**Additional Context**
I just have a question, why the redesign. It was all a mistake the previous one just worked, its an installer not a AAA game developed by EA.

**Comment by rauenzi** [comment]
> I just have a question, why the redesign. It was all a mistake the previous one just worked, its an installer not a AAA game developed by EA.


To clarify, on Linux, there was no official installer before. So it's not really a redesign, it's one single cross-platfotm installer. And while it may be on the larger size, it's nowhere near the bloat of a game by EA.

**Comment by rauenzi** [comment]
A quick search shows that this is an issue that can happen for certain Linux users with electron and that there is a workaround I can add to the AppImage.

https://github.com/electron/electron/issues/17972

I will add that to the AppImage when I can and provide that version to you for to try.

**Comment by ObserverOfTime** [comment]
See [here](https://wiki.archlinux.org/index.php/Linux_Containers#Unpriviledged_containers_on_linux-hardened_and_custom_kernels) for details on the issue and a way to fix it on your own.

**Comment by rauenzi** [comment]
@cutieshy were you able to use the workaround posted above?

**Comment by rauenzi** [comment]
Can you please reopen the issue on the Installer repo (https://github.com/BetterDiscord/Installer) if this issue still persists? I am unable to transfer to an org repo.
