### ISSUE TITLE
BetterDiscord suddenly crashed and doesn't work anymore

### ISSUE THREAD

**Issue by Ironnix** [rauenzi/BetterDiscordApp#695]
**Describe the Bug**

Discord was open and suddenly crashed while i talked, i did nothing on the app itself. When it restarted and Better Discord wasn't here andymore. I tried to restart Disord and reinstalling both, Discord itself and Better Discord, i also delete my personal BD Data. WHen i tried to start Discord with BD it isn't working and Discord found no Input and Output Devices, so i was force muted....
The Task bar was also buggy and wasn't working as normal.
Without BD was eveything fine. 
Any ideas?

Sry for my bad english and thanks for the supplies....

**Comment by rauenzi** [comment]
If you have no plugins, then I am unsure, I have never heard of any such behavior from vanilla BD.

**Comment by Ironnix** [comment]
> 
> 
> If you have no plugins, then I am unsure, I have never heard of any such behavior from vanilla BD.



> 
> 
> If you have no plugins, then I am unsure, I have never heard of any such behavior from vanilla BD.

I found the problem, i just had the old installer. Now everything is fine...
