### ISSUE TITLE
BD broken on latest update 04/12/21[Bug]

### ISSUE THREAD

**Issue by Wizerdz** [rauenzi/BetterDiscordApp#697]
The latest update for Discord has broken Better Discord as of April 12, 2021

Bottom Text

**Comment by rauenzi** [comment]
Are you installing the latest version of BD with the latest installer from https://github.com/BetterDiscord/Installer/releases/latest ?

**Comment by Detergent13** [comment]
Just to add, I was having this same issue with the latest Discord update but solved it by updating my installer.

**Comment by chromevdokuro** [comment]
BD isn't working after discords new update, no matter if you try doing new installer :(

**Comment by Wizerdz** [comment]
> Are you installing the latest version of BD with the latest installer from https://github.com/BetterDiscord/Installer/releases/latest ?

Yeah I made sure to try the latest version

**Comment by Wizerdz** [comment]
> > Are you installing the latest version of BD with the latest installer from https://github.com/BetterDiscord/Installer/releases/latest ?
> 
> Yeah I made sure to try the latest version

for some reason it decided to work today when I tried to reinstall it

**Comment by chromevdokuro** [comment]
> > Are you installing the latest version of BD with the latest installer from https://github.com/BetterDiscord/Installer/releases/latest ?
> 
> Yeah I made sure to try the latest version

i did do latest verison it still doesn't work after discord updated, i do not know why either cause usually it works after i reinstall after a update.
