### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by alleropabo12** [rauenzi/BetterDiscordApp#699]
BD keep crshing and it says:
better discord seems to have crashed your discord client

**Screenshots**

![image](https://user-images.githubusercontent.com/82469409/114600111-4617f480-9c94-11eb-85d8-d43e8f6b64af.png)

**Comment by Uruknara** [comment]
same thing I can use betterdiscord, I always crash

**Comment by rauenzi** [comment]
Try renaming your existing BD folder and reinstalling.

**Comment by Uruknara** [comment]
doesn't work sorry

**Comment by Uruknara** [comment]
i try bt i think the problem is the plugin not bandage

**Comment by rauenzi** [comment]
> i try bt i think the problem is the plugin not bandage

You weren't supposed to put the plugins back immediately after renaming the folder...

**Comment by Uruknara** [comment]
i know that, i try and i think the problem was the plugin cause when i don't have any plugin bandage work
