### ISSUE TITLE
BandagedBD is getting stuck on extracting the core

### ISSUE THREAD

**Issue by Likeabozz123** [rauenzi/BetterDiscordApp#7]
BetterDiscord isn't working and when I googled for some answers I found "Use BandagedBD", when I did it just got stuck on extracting the core. Can anyone help me with this?

**Comment by rauenzi** [comment]
try moving the installer out of the downloads folder before running and make sure you have the latest version of the installer it was updated recently

**Comment by Likeabozz123** [comment]
Okay thank you so much for the fix, for some reason it didn't work before but now it is.
