### ISSUE TITLE
Discord Update

### ISSUE THREAD

**Issue by jeeyeung** [rauenzi/BetterDiscordApp#70]
After injecting, discord keeps looking for an update, then downloading it, then restarting to look for an update just to update it and then the whole process repeats.

**Comment by HerrEurobeat** [comment]
Same here

**Comment by Shaxd** [comment]
same

**Comment by HerrEurobeat** [comment]
So i reinstalled Discord and then installed BBD and now it works

**Comment by Metadorius** [comment]
reinstalling didn't help, still bootloops

**Comment by Metadorius** [comment]
SOLUTION: reinstall both Discord and BBD, then restart your PC

**Comment by rauenzi** [comment]
Next time kill it in task manager and try to restart it.

**Comment by Metadorius** [comment]
lol, dare to assume that I hadn't do this. I killed and restarted it like 4-5 times.

**Comment by rauenzi** [comment]
Little to no information was given, I cannot assume that any specific action was taken.

**Comment by Metadorius** [comment]
ok then, it rapidly restarted after BBD update, killing and restarting didn't help, reinstalling BBD didn't help, reinstalling both Discord and BBD didn't help, manually deleting Discord both via deinstalltor and via deleting AppData/Local/Discord folder and installing it again didn't help, installing BBD over it didn't help, after restart it worked, hope that's enough information lol

**Comment by Metadorius** [comment]
also why is that closed when it's still not fixed?

**Comment by rauenzi** [comment]
Someone posted a solution and someone else posted that same solution which seems to confirm a solution and the original issue had not enough information to diagnose. Best bet is to go to the support servers for live help
