### ISSUE TITLE
[Bug] BD Not Working at all after 4/12

### ISSUE THREAD

**Issue by chromevdokuro** [rauenzi/BetterDiscordApp#700]
BD doesn't start up or show in the settings
BD did not work. I even unistalled&reinstalled with new BD andit  didn't show BD mark at bottom right after reinstalling.
I was hoping that it would work again after i restarted discord.

Stable Verison
![BDbug](https://user-images.githubusercontent.com/82437035/114631204-c97c1a80-9c81-11eb-97fd-d5abe9095b8d.png)

**Comment by DrigiZ** [comment]
Same issue, don't know what this is :|
Let's hope they fix it

**Comment by uNbearably** [comment]
so right from what i did, i took out all my plugins and themes, put em into a separate folder on desktop, then deleted the entire betterdiscord folder in %appdata%, reinstalled betterdiscord, then placed everything back in and it seems to have worked; hope it works for yall

**Comment by rauenzi** [comment]
Please use the latest version of the installer found at https://github.com/BetterDiscord/Installer/releases/latest

**Comment by fsk10** [comment]
> Please use the latest version of the installer found at https://github.com/BetterDiscord/Installer/releases/latest

This fixed the issue for me

**Comment by chromevdokuro** [comment]
> so right from what i did, i took out all my plugins and themes, put em into a separate folder on desktop, then deleted the entire betterdiscord folder in %appdata%, reinstalled betterdiscord, then placed everything back in and it seems to have worked; hope it works for yall

thats what i did too that had not worked either.
