### ISSUE TITLE
This file contains "Real Protect" virus. Please look into it.

### ISSUE THREAD

**Issue by SiddNem** [rauenzi/BetterDiscordApp#701]
![image](https://user-images.githubusercontent.com/79246390/114824178-27277880-9de2-11eb-98b1-c25979be1982.png)

**Comment by SiddNem** [comment]
![image_2021-04-15_120225](https://user-images.githubusercontent.com/79246390/114824393-7077c800-9de2-11eb-8ee9-41ae759289db.png)

**Comment by aldarmak** [comment]
Don’t email me pleas I was dealing with you before you didn’t even teach me how to use the app so now duck off

**Comment by SiddNem** [comment]
but what happened?
I was jus making people aware of it.
I apologise for that.
