### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by zackbriccs** [rauenzi/BetterDiscordApp#702]
![image](https://user-images.githubusercontent.com/82574558/114839143-4a263e00-9d8a-11eb-9901-6ebb963faefc.png)
So, when I enabled the theme on my BetterDiscord settings in discord, it doesn't change/apply, even though I rebooted discord.

**Comment by rauenzi** [comment]
Try reinstalling BD. If that fails, upload the theme file.
