### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Cristianzara** [rauenzi/BetterDiscordApp#704]
**Describe the Bug**
when the bandagebd installation finished, I open discord and its activity was strange, first it says "get the desktop app" (obviously appears when you're connected to the browser) but I'm in the desktop app.
![Screenshot_11](https://user-images.githubusercontent.com/68141639/114904923-c18db900-9dee-11eb-938d-46aaa5c51216.png)

the second issue was that the close, minimize and maximize buttons disappeared, making it impossible for me to close the app

the third issue is that game activity disappeared from my settings
![Screenshot_12](https://user-images.githubusercontent.com/68141639/114907612-a4a6b500-9df1-11eb-9e67-4edc480fccd9.png)

the fourth issue is that no settings from bandagebd appear

**To Reproduce**
I just download the bandagebd installer, click on install and open discord

**Expected Behavior**
a normal installation of the program?

**Screenshots**
![image](https://user-images.githubusercontent.com/68141639/114906299-462d0700-9df0-11eb-9ebc-2b2cdc8e642d.png) (the buttons disappeared)

**Discord Version**
Stable

**Additional Context**
Literally  bandagedbd make my discord desktop app a portable version of browser

**Comment by rauenzi** [comment]
Please use the latest version of the installer found at https://github.com/BetterDiscord/Installer/releases/latest

**Comment by Chroma67** [comment]
I had the same issue, it was working yesterday but today I logged on and had these same issues. I reinstalled with the latest installer but it changed nothing.

**Comment by rauenzi** [comment]
https://rauenzi.github.io/BetterDiscordApp/ is not an official website or documentation.
