### ISSUE TITLE
[Bug] stuck on downloading asar file

### ISSUE THREAD

**Issue by hotq0** [rauenzi/BetterDiscordApp#708]
**Describe the Bug**
 When i try to download betterdiscord the installer is stuck on ''downloading asar file''

**To Reproduce**
 i tried reinstalling discord a few times but that doesn't help

**Expected Behavior**
 i thought reinstalling discord would help the problem but that doesn't help

**Screenshots**
  

**Discord Version**
 Stable

**Additional Context**

![bs](https://user-images.githubusercontent.com/82647380/115004085-bbf3aa00-9ea6-11eb-8c76-e18220e3d733.png)

**Comment by rauenzi** [comment]
This is an issue with the installer, not BD. Please open up an issue there https://github.com/BetterDiscord/Installer
