### ISSUE TITLE
[Bug] Discord Crashing

### ISSUE THREAD

**Issue by Zelkyyy** [rauenzi/BetterDiscordApp#709]
**Describe the Bug**
 The Discord just crashed and says that I should try to remove all my plugins did that reinstalled Better discord still says that even tho I have no plugins in my folder
**To Reproduce**
 I honestly don't know it just happened yesterday and today Better discord won't start at all every time I open discord it says the same thing that I should remove all my plugins even tho I already did that 

**Expected Behavior**
Im pretty sure it shouldn't crash without a reason I mean I removed all my plugins reinstalled it and tried to repair it with the installation tool 

**Screenshots**
 https://gyazo.com/60d3835cf172a563d442a9ca63d10867 
**Discord Version**
 I honestly dont know just the Normal discord downloaded from Google 

**Additional Context**

**Comment by rauenzi** [comment]
Rename your existing BD folder then reinstall.

**Comment by AndreasTheTeuton** [comment]
> Rename your existing BD folder then reinstall.

What would we rename it to? I've been having this exact issue too repeatedly.

**Comment by KyubeX** [comment]
> > Rename your existing BD folder then reinstall.
> 
> What would we rename it to? I've been having this exact issue too repeatedly.

Rename it to anything you want, doesnt matter, After i renamed it, it fixed the issue for me.

**Comment by brian6932** [comment]
After reinstall, the folder name in `C:\Users\username\AppData\Roaming` goes from `betterdiscord` -> `BetterDiscord`, so you could try that if you're too lazy to retransfer your preferences + themes + plugins. Although, it could definitely be due to something else.
![image](https://user-images.githubusercontent.com/18603393/115114720-bd80a900-9f5e-11eb-8c7b-5cf69319fe82.png)

**Comment by KayshiAri** [comment]
It does the exact same thing on Linux too, renaming stuff and repair + reinstall didn't fix this
Version: Stable 82590 (bf3e4f7)
Host 0.0.14
Linux 64-Bit (5.11.10-200.Fc33.X86_64)
Distro is Fedora 33, got the 0.0.14-1.fc33 version from RPMFusion

**Comment by brian6932** [comment]
For me renaming + reinstalling seemed to work, so idk

**Comment by rohsaurus** [comment]
I have the same bug but with the PTB version. I tried renaming, reinstalling, repairing but none of those seemed to work.

**Comment by brian6932** [comment]
Yea it looks like renaming helps, however, it doesn't fully fix the issue, still happening after BD updates too

Stable 83040 (f19e353)
BetterDiscord 1.1.0
Host 1.0.9001
Windows 10 64-Bit (10.0.20152)
