### ISSUE TITLE
Linux - Not working

### ISSUE THREAD

**Issue by yumenetwork** [rauenzi/BetterDiscordApp#71]
## Environment

- Solus OS 
- Discord Stable Oct. 16. 2018

## Problem

Since the last update, Better Discord no longer works on Linux.... Can you patch this problem?

## What I did ?

I tried to update betterdiscord but it didn't work. I also downloaded the new version but I didn't find how to install it on Linux

## Screen

http://tinyimg.io/i/Cn0aEY1.png

**Comment by yumenetwork** [comment]
I figured out how to patch the problem. 

I reinstalled discord and launched
`betterdiscordctl update -s /usr/share -v -v`

**Comment by onedementedsmurf** [comment]
`betterdiscordctl update -s /usr/share -v -v` does indeed update, but on my end none of the BD menu options work, Themes, Plugins, Core, etc.

**Comment by intrnl** [comment]
@onedementedsmurf Your issue is related to the currently open issue #80
