### ISSUE TITLE
Off-center question mark on "Help" button in "Open Logs" window

### ISSUE THREAD

**Issue by xRitsu** [rauenzi/BetterDiscordApp#711]
![image_2021-04-17_134858](https://user-images.githubusercontent.com/26928100/115112025-a86a4100-9f83-11eb-847a-9be13ca8b955.png)
The question mark on the button is off-center. I checked the style and it seems that the `margin-right: 4px` property applies to both svg path and the button itself. I would be glad if you could fix it.

**Comment by kekkodance** [comment]
lmao

**Comment by respecting** [comment]
Man, if people realized that plugin is unofficial, we would be in a better place.

**Comment by rauenzi** [comment]
Agreed
