### ISSUE TITLE
[Bug] Colored Text setting not working

### ISSUE THREAD

**Issue by DanBTechnology** [rauenzi/BetterDiscordApp#713]
**Describe the Bug**
When I go into the Discord settings (bottom left gear), there is a setting called "Colored Text" that I've been using, which makes the messages of all users match their role colors. I noticed a few days ago that it hasn't been working for me. Not sure if there is a solution, but I wanted to post a report anyway just in case

**To Reproduce**
1. Go to settings (bottom left gear icon)
2. Scroll down to the BetterDiscord section and click on Settings
3. Enable the Colored Text setting

**Expected Behavior**
When the setting is enabled, all of the messages a user has sent should be the same color text as their role color

**Screenshots**
![image](https://user-images.githubusercontent.com/6370453/115129793-49beba80-9fb7-11eb-9b5a-21fa65d45fd9.png)
![image](https://user-images.githubusercontent.com/6370453/115129807-6bb83d00-9fb7-11eb-96b0-e0197c7079cf.png)

**Discord Version**
Stable 82590 (bf3e4f7)

**Comment by Tropix126** [comment]
This is a known issue and will be fixed once BD 1.1.0 is pushed to users.

**Comment by rauenzi** [comment]
This has been pushed out and can be fixed by reinstalling.
