### ISSUE TITLE
[Bug] Discord RPC not working

### ISSUE THREAD

**Issue by rogue-agent** [rauenzi/BetterDiscordApp#715]
**Describe the Bug**
Discord does not recognise games that are being played. For some reason it is still showing that I would be playing on my phone the app is closed... But that is not the issue, the issue is about Desktop programs not showing with RPC

**To Reproduce**
1. Install discord
2. Install BD
3. Open Destiny 2 through Steam

**Expected Behavior**
User profile is to show Destiny 2 as being played.

**Screenshots**
![image](https://user-images.githubusercontent.com/9405663/115156625-c6bc6380-a08d-11eb-93ce-23b48b16389a.png)
![image](https://user-images.githubusercontent.com/9405663/115156659-05521e00-a08e-11eb-9533-aaa3fef152e5.png)

**Discord Version**
Stable latest

**Additional Context**
DRPC works without BD installed.

**Comment by rauenzi** [comment]
What plugins are you using? Are you using DoNotTrack?

**Comment by rogue-agent** [comment]
![image](https://user-images.githubusercontent.com/9405663/115157701-5a446300-a093-11eb-9de8-55af1f927a52.png)

**Comment by rauenzi** [comment]
So yes you are using DoNotTrack. What you're seeing is a feature of DoNotTrack that can be turned off in the plugin's settings. Turn that setting off and restart Discord.

**Comment by rogue-agent** [comment]
> 
> 
> So yes you are using DoNotTrack. What you're seeing is a feature of DoNotTrack that can be turned off in the plugin's settings. Turn that setting off and restart Discord.

Issue solved. Disabling "Disable Process monitor" solved.
