### ISSUE TITLE
[Bug] Installing BBD loads browser discord

### ISSUE THREAD

**Issue by Kimochii-x3** [rauenzi/BetterDiscordApp#716]
For somewhat reason, after my pc had blue screen, restarted it, then I started discord, I saw BBD was missing, so I re-installed it by downloading the latest version from the first link on google, after that discord was loading a browser version inside the client rather a client version with bbd on it, have tried complete re-install of discord and bbd but no solution, what else could I do?

**Comment by rauenzi** [comment]
> the latest version from the first link on google

Here's where  you went wrong. Use the installers linked on the README... https://github.com/BetterDiscord/Installer

**Comment by Kimochii-x3** [comment]
Yup, got that and it worked, I thought you'd still call it BandagedBetterDiscord rather than just BetterDiscord. Its all working great now!
