### ISSUE TITLE
BD Crash

### ISSUE THREAD

**Issue by DexyAnimations** [rauenzi/BetterDiscordApp#718]
Hi again. my BD crashing on normal and canary versions every time i screen share or turn camera on, error  saying: try remove all your plugins. Even if i do it, it still do same thing. if there is any help i will thank you

https://gyazo.com/984fc7f93a3c88a58da2dd8e54e33749

**Comment by rauenzi** [comment]
I've only had a few people with similar issues however I'm not sure what the root cause is because I cannot recreate.
