### ISSUE TITLE
[Bug] Cant install on Linux Mint Debian Edition

### ISSUE THREAD

**Issue by deep8787** [rauenzi/BetterDiscordApp#719]
Hi,

I have LMDE on my laptop and wanted to install this app. I tried the Linux image but it seems to be incompatible. I tried the manual install guide but I get this on the 2nd step:

_deep@deep:~/discord$ npm install
Command 'npm' not found, did you mean:
  command 'apm' from snap atom (1.55.0)
  command 'nsm' from snap nift (2.4.12)
See 'snap info <snapname>' for additional versions._

Help? Thank you.

**Comment by Lulonaut** [comment]
The error message says the npm command doesn't exist, so install nodejs and try again.

**Comment by rauenzi** [comment]
Please see the above. I don't see why the AppImage would be incompatible however.
