### ISSUE TITLE
[Bug] just dosent work

### ISSUE THREAD

**Issue by Kraleemil** [rauenzi/BetterDiscordApp#720]
**Describe the Bug**
The bar en the top where you can close it is not there and where the BD plugins is not there

**To Reproduce**
?

**Expected Behavior**
Just installed it

**Screenshots**
Nop uninsalled it angin

**Discord Version**
Stable

**Additional Context**
nop

**Comment by xMistt2** [comment]
Same /w me, it just randomly went away one day and If I install it, there is no changes to my discord.

**Comment by bob-carter** [comment]
Same, happened after newest update

**Comment by rauenzi** [comment]
> he bar en the top where you can close it is not there and where the BD plugins is not there

No clue what this means. Please install using the newest installer linked on the README

**Comment by chromevdokuro** [comment]
BD isn't working after newset update even if you repair, unistall, install, do reccomended things. Ig what the mean possibly is BD not showing up when launching where settings are???

**Comment by ehAsuna** [comment]
The same is happeneing for me too.

**Comment by Kraleemil** [comment]
> The same is happeneing for me too.

Use the installer on the discord
