### ISSUE TITLE
[Feature Request] Windows Installer Should Have Checkboxes for installation

### ISSUE THREAD

**Issue by jzkmath** [rauenzi/BetterDiscordApp#721]
I was trying to help someone install better discord and we were struggling to get it installed. The reason was that to install BetterDiscord, you need to set the directory and then actually _click_ on the word "Discord" to select it for installation. 
It would probably be a good idea to implement some sort of tick box or check box to indicate to the user that they need to select the application.
Either that or the installation instructions need to be more specific.

**Comment by rauenzi** [comment]
Please open this over on the Installer's repo https://github.com/BetterDiscord/Installer
