### ISSUE TITLE
[Feature] Rich Presence

### ISSUE THREAD

**Issue by siltentassasin** [rauenzi/BetterDiscordApp#722]
Is it possible to add an option in bd to activate rich presence? 

Like the emote tab in the menu one for rich presence? Where you can configure ID, Picture, Name, details and co? Because I think this would be very helpful and a very cool feature

**Comment by rauenzi** [comment]
There is already a plugin for this called AutoStartRichPresence

**Comment by aldarmak** [comment]
Hi rich configure number shall i put to do it
