### ISSUE TITLE
[Bug]Better Discord Not Installing.

### ISSUE THREAD

**Issue by ehAsuna** [rauenzi/BetterDiscordApp#724]
**Describe the Bug**

Whenever I install better discord on stable using the newest installer I open discord and there's no plugin. 
I've tried repairing, uninstalling and reinstalling, and really everything. 
**To Reproduce**

Install betterdiscord on stable using the newest installer.
**Expected Behavior**

I expected better discord to be usable when I opened discord.
**Screenshots**

![image](https://user-images.githubusercontent.com/74951182/115792483-ff12b900-a38f-11eb-8dca-01a4be200ea4.png)
![image](https://user-images.githubusercontent.com/74951182/115792641-41d49100-a390-11eb-9c1b-d6f99ce46ac8.png)

**Discord Version**

Stable
**Additional Context**

**Comment by rauenzi** [comment]
> Whenever I install better discord on stable using the newest installer

Your screenshots clearly show the outdated installer. Please use the latest installer found here: https://github.com/BetterDiscord/Installer/releases/latest

**Comment by ehAsuna** [comment]
> > Whenever I install better discord on stable using the newest installer
> 
> Your screenshots clearly show the outdated installer. Please use the latest installer found here: https://github.com/BetterDiscord/Installer/releases/latest

Im so sorry I was just starting to figure that out too. 
While I'm at it is there anywhere I can find a list of plugins?

**Comment by klioxide-lol** [comment]
> > Whenever I install better discord on stable using the newest installer
> 
> Your screenshots clearly show the outdated installer. Please use the latest installer found here: https://github.com/BetterDiscord/Installer/releases/latest

The most recent installer doesnt even complete install. It simply freezes on "killing discord" and never completes
![image](https://user-images.githubusercontent.com/80074052/115805234-29717000-a3aa-11eb-8461-73b978c709e7.png)

**Comment by rauenzi** [comment]
Make sure you use the latest installer, and if you have an issue with that installer it should be filed over at https://github.com/BetterDiscord/Installer
