### ISSUE TITLE
Doesnt download

### ISSUE THREAD

**Issue by Neel11223** [rauenzi/BetterDiscordApp#725]
**Describe the Bug**

Ive had betterdiscord for months, and never had it crash. Its just randomly crashing and going away from the discord app, and it doesnt let me redownload
**To Reproduce**

**Expected Behavior**

**Screenshots**

**Discord Version**

**Additional Context**

**Comment by rauenzi** [comment]
Download the latest installer from our website https://betterdiscord.app
