### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by klioxide-lol** [rauenzi/BetterDiscordApp#726]
**Describe the Bug**
BetterDiscord newest installer simply doesnt work. It gets stuck on "killing discord" everytime. I tried installing with admin and still no success. Ive tried restarting and more to no success.

**To Reproduce**
I dont know how you could reproduce this.

**Expected Behavior**
I simply tried installing/repairing/uninstalling to being stuck on "Killing Discord"

**Screenshots**
![image](https://user-images.githubusercontent.com/80074052/115805835-5d00ca00-a3ab-11eb-926b-093ab911cd97.png)

**Discord Version**
All of them

**Additional Context**
I once requested this before but forgot to come check back.

**Comment by rauenzi** [comment]
Close Discord before launching the installer and you should be fine. Future installer issues should go on https://github.com/BetterDiscord/Installer
