### ISSUE TITLE
[Feature] Fix for notifications not showing on all dekstop devices?

### ISSUE THREAD

**Issue by ItsCubeTime** [rauenzi/BetterDiscordApp#729]
So this is kinda unrelevant to BetterDiscordApp but rather relevant to the Discord app iself, however the issue seems to be kinda ignored by the Discord developers.

Basically my Discord notifications for Win 10 stopped working back in like 2018-2019 and havent worked since, Ive tried pretty much every "fix" posted in various articles across the internet with no success.

What Ive tried is checking that I have the correct Windows notification settings and correct Discord notification settings as well as the steps described here: https://www.partitionwizard.com/partitionmanager/win-10-notifications-not-working.html as well as that Ive tried deleting .../appdata/local/discord and .../appdata/roaming/discord.

Would it be possible for BetterDiscrd to create an alternative toast notification system for those that are in my situation? It seems like a relatively common issue looking around the web there are many forums of people having the same issue as I do

**Comment by rauenzi** [comment]
This is technically possible--to have in-app notifications--but is better suited to a plugin. Try the plugin-ideas channel on the server.
