### ISSUE TITLE
0.3.0 Installer doesn't continue.

### ISSUE THREAD

**Issue by Drflash55** [rauenzi/BetterDiscordApp#73]
![image](https://user-images.githubusercontent.com/13694448/47237597-9c4e9a00-d3ad-11e8-8c36-356f61eef50f.png)

After a few minutes of it killing all processes of Discord, it detects an old injection in the Roaming folder for Discord... but it hasn't progressed since.

Not sure what's going on with it.

**Comment by Drflash55** [comment]
It seems to have fixed itself when the installer was restarted after Discord was killed, but in this case, it doesn't talk about an old injection anymore, and it has completed successfully.

**Comment by rauenzi** [comment]
Be sure to run the installer as Admin

**Comment by Drflash55** [comment]
Yeah, I'll try doing that next time I go to run the installation again. Thanks for your help.
