### ISSUE TITLE
[Bug] BetterDiscord isn't starting with discord

### ISSUE THREAD

**Issue by FireNuke** [rauenzi/BetterDiscordApp#731]
**Describe the Bug**
Every time discord starts up, better discord is not being injected. I have this problem for a week or 2. I've tried installing a new better discord installer (version 1.1.0 i guess) but nothing. The installer is the latest I was downloading it 20 minutes ago. A lot of times tried "repair" also deleted all btd files and installed it again. Nothing helped!

**To Reproduce**
^^

**Expected Behavior**
I expected the same thing as before. Every time discord starts with Better Discord being injected.

**Screenshots**
![image](https://user-images.githubusercontent.com/56696555/115910145-c5fc4680-a46c-11eb-8bbe-3b65e20707a6.png)
![image](https://user-images.githubusercontent.com/56696555/115910288-f47a2180-a46c-11eb-9eb3-af7a5a91cce4.png)

**Discord Version**
Stable

**Additional Context**
nope

**Comment by FlashlightET** [comment]
same

**Comment by AnthraxRobin** [comment]
Same issue, hope there is a fix soon somehow. Really miss my background

**Comment by FireNuke** [comment]
Okay here's an update, it still isn't fixed but I've found the solution! Basically, install Discord Canary and then better discord. It works just fine.

**Comment by rauenzi** [comment]
It seems likely that you are installing to a different version than you are running. In the future installer issues should be filed on that repo.
