### ISSUE TITLE
[Bug] Can't install better discord

### ISSUE THREAD

**Issue by nyuusuki** [rauenzi/BetterDiscordApp#732]
I've tried running it in compatibility mode, running as an admin. It simply won't install, it opens the do you want to run this file, and that's it, even unblocked it -- nothing is stopping it from running at all and I cannot join either the discord or secondary discord for assistance over the matter.

**Comment by ChaoticHolon** [comment]
Exact same thing is happening to me.

**Comment by Loxbey** [comment]
Not possible to install either. Installer tells me it worked but nah

**Comment by Loxbey** [comment]
managed to fix it.

Head over to _C:\Users\[NAME]\AppData\Local\Discord_   and delete every folder with the name of _app-XXXX_  _except app-1.0.9001_ .

Reboot discord and run the BD installer

**Comment by rauenzi** [comment]
Installer issues should be filed on that repo https://github.com/BetterDiscord/Installer

**Comment by Sadcato** [comment]
> 安装程序问题应提交到该存储库https://github.com/BetterDiscord/Installer

thanks，help me a lot
