### ISSUE TITLE
[Bug] Discord Canary Crashing When Joining A VC

### ISSUE THREAD

**Issue by iFireMonkey** [rauenzi/BetterDiscordApp#734]
**Describe the Bug**

When joining a server voice chat, my discord would simply crash and after that loop crashing unless I managed to leave the voice chat before I fully connected. The voice chat I was in was a 256kbps voice chat. I only crashed once a friend joined the voice chat, but if I was alone I was perfectly fine. Unlike other reports my friend didn't even need to screenshare or have a camera enabled for this crash to occur.

**To Reproduce**

Have a fresh install of Better Discord on Canary
Join a Voice Chat with another person in it
Crash

**Expected Behavior**

You can voice chat perfectly fine without crashing.

**Screenshots**

**Discord Version**

Canary

**Additional Context**

**Comment by gstand** [comment]
Can reproduce: M1 MacBook Pro, Discord Canary build 83043 (5c3abdb), latest BDInstaller install.

**Comment by cherry25565** [comment]
I can reproduce the same on Canary and PTB (both on latest version)

**Comment by koumaza** [comment]
It happens same error.

When
1. Join a voice channel.
2. Join a voice channel that two or more users are livestreaming.
3. Join a voice channel that two or more users are livestreaming then watch its stream.

```py
Canary 83055 (b5aa889)
Host 1.0.28
Windows 10 64-Bit (10.0.21364)
```

I hope to get BetterDiscord's log.
How to do...?It happens same error.

When
1. Join a voice channel.
2. Join a voice channel that two or more users are livestreaming.
3. Join a voice channel that two or more users are livestreaming then watch its stream.

```py
Canary 83055 (b5aa889)
Host 1.0.28
Windows 10 64-Bit (10.0.21364)
```

I hope to get BetterDiscord's log.
How to do...?

**Comment by Airfishy** [comment]
Can also reproduce, Happens at random. Windows 20H2

**Comment by rauenzi** [comment]
I have seen others with this issue, but I myself have not had this issue on any Discord release

**Comment by cherry25565** [comment]
It seems that the latest BD updated has fixed the bug (for me on the latest Canary version)
