### ISSUE TITLE
A Second Better Discord Discord Server

### ISSUE THREAD

**Issue by Doge126** [rauenzi/BetterDiscordApp#735]
The Better Discord Server Has Reached The Max 100,000 Member Could You Send Another Invite To The Backup Server?

**Comment by ihxzey** [comment]
same problem :/

**Comment by Zekkkken** [comment]
link to the backup on the github doesnt work.

**Comment by Overimagine1** [comment]
https://discord.gg/sbA3xCJ

**Comment by rauenzi** [comment]
This has been resolved
