### ISSUE TITLE
Installer can't find discord on Linux (Zorin OS)

### ISSUE THREAD

**Issue by Aplicat0r** [rauenzi/BetterDiscordApp#736]
![Screenshot from 2021-04-25 19-38-16](https://user-images.githubusercontent.com/76044844/116001747-b9a7f300-a5fe-11eb-86a2-a4d0125c7b84.png)

**Comment by ObserverOfTime** [comment]
I'm willing to bet you installed it via snap which is not supported.

**Comment by Aplicat0r** [comment]
it was an appimage

**Comment by ObserverOfTime** [comment]
I mean Discord, not the installer.

**Comment by Aplicat0r** [comment]
yeah i found it out. I had to download Discord from there site.
