### ISSUE TITLE
Can't Install

### ISSUE THREAD

**Issue by CancerWeeb** [rauenzi/BetterDiscordApp#74]
Whenever I open it and accept it, it'll tell me that it can't find the latest version of discord. I go to discords file (C:\Users\<user name>\AppData\Roaming\discord) and select it. Even when I do that, it still doesn't let me install. I figure its because its the wrong file, but I wouldn't know where said file would be. I've also tried selecting every file in it. As well as that, I've moved it from my download file.

Also, my dumb ass put this for the wrong thing, I thought this was on the Bandaged BD. Whoops.

**Comment by rauenzi** [comment]
The new installer does not inject to roaming, it injects to local appdata

**Comment by Kallyopae** [comment]
> Whenever I open it and accept it, it'll tell me that it can't find the latest version of discord. I go to discords file (C:\Users<user name>\AppData\Roaming\discord) and select it. Even when I do that, it still doesn't let me install. I figure its because its the wrong file, but I wouldn't know where said file would be. I've also tried selecting every file in it. As well as that, I've moved it from my download file.
> 
> Also, my dumb ass put this for the wrong thing, I thought this was on the Bandaged BD. Whoops.

Uninstall discord and clean any residue of it from your PC, then reinstall it and install BD from this release as is the latest one. Your issues should be gone after doing these steps.

**Comment by fernandog555** [comment]
> > Whenever I open it and accept it, it'll tell me that it can't find the latest version of discord. I go to discords file (C:\Users\AppData\Roaming\discord) and select it. Even when I do that, it still doesn't let me install. I figure its because its the wrong file, but I wouldn't know where said file would be. I've also tried selecting every file in it. As well as that, I've moved it from my download file.
> > Also, my dumb ass put this for the wrong thing, I thought this was on the Bandaged BD. Whoops.
> 
> Uninstall discord and clean any residue of it from your PC, then reinstall it and install BD from this release as is the latest one. Your issues should be gone after doing these steps.

Thanks, it actually worked. I was worried i had to flush out my hard drive to install this, as I'm not that smart with computers. Just uninstall discord, press winkey+r and type %appdata%, scroll to discord and better discord and delete those folders. Then u install discord and better discord and it worked ;)

**Comment by Kallyopae** [comment]
> > > Whenever I open it and accept it, it'll tell me that it can't find the latest version of discord. I go to discords file (C:\Users\AppData\Roaming\discord) and select it. Even when I do that, it still doesn't let me install. I figure its because its the wrong file, but I wouldn't know where said file would be. I've also tried selecting every file in it. As well as that, I've moved it from my download file.
> > > Also, my dumb ass put this for the wrong thing, I thought this was on the Bandaged BD. Whoops.
> > 
> > 
> > Uninstall discord and clean any residue of it from your PC, then reinstall it and install BD from this release as is the latest one. Your issues should be gone after doing these steps.
> 
> Thanks, it actually worked. I was worried i had to flush out my hard drive to install this, as I'm not that smart with computers. Just uninstall discord, press winkey+r and type %appdata%, scroll to discord and better discord and delete those folders. Then u install discord and better discord and it worked ;)

You are welcome and glad that i could help.

**Comment by rauenzi** [comment]
@Kallyopae thanks for giving support on several of these issues

**Comment by Kallyopae** [comment]
> @Kallyopae thanks for giving support on several of these issues

You are welcome and i am glad that i can help.
