### ISSUE TITLE
Discord loads as a web browser

### ISSUE THREAD

**Issue by blokowy3000** [rauenzi/BetterDiscordApp#741]
As a result, you can't have a microphone and the BD itself doesn't work

**Comment by Tropix126** [comment]
You very likely have an outdated installer version. Get the latest release from here: 

| [Windows (7+)](https://github.com/BetterDiscord/Installer/releases/latest/download/BetterDiscord-Windows.exe)  | [macOS (10.10+)](https://github.com/BetterDiscord/Installer/releases/latest/download/BetterDiscord-Mac.zip) | [Linux](https://github.com/BetterDiscord/Installer/releases/latest/download/BetterDiscord-Linux.AppImage) |
| ------------- | ------------- | ------------- |

**Comment by Legitti** [comment]
I started to have this same problem weeks ago, trying now to install discord fresh along with the linked installer.

**Comment by Tropix126** [comment]
> I started to have this same problem weeks ago, trying now to install discord fresh along with the linked installer.
> 
> Edit: Got it working again with the linked installer. So confusing to have many similar GitHub projects so maybe it was just outdated. My plugins and themes also loaded automatically after re-install.

Yeah hopefully once the new site is more widely used people will be able to find the correct installer easier.

**Comment by Irresplendence** [comment]
> 
> 
> I started to have this same problem weeks ago, trying now to install discord fresh along with the linked installer.
> 
> Edit: Got it working again with the linked installer. So confusing to have many similar GitHub projects so maybe it was just outdated. My plugins and themes also loaded automatically after re-install.

Same issue! I was sure I'd grabbed from the right repo, but either way, thanks!
