### ISSUE TITLE
[Feature] a plugin that makes discord not crash

### ISSUE THREAD

**Issue by Vortecked** [rauenzi/BetterDiscordApp#743]
so basically, there are a bunch of gifs that crash discord when played, im not sure what exactly causes it, but a plugin that makes discord not do that would be REALLY nice

**Comment by Overimagine1** [comment]
<img src="https://cdn.discordapp.com/attachments/119918741516451840/836661294923907112/Screenshot_2021-04-27_at_10.52.41_AM.png">

**Comment by Overimagine1** [comment]
Also #plugin-ideas in the discord exists for a reason

**Comment by Vortecked** [comment]
my bad, i didnt know there was a discord
