### ISSUE TITLE
Website was down

### ISSUE THREAD

**Issue by yahu1031** [rauenzi/BetterDiscordApp#744]
![image](https://user-images.githubusercontent.com/35523357/116645142-c9bf2a00-a992-11eb-92ac-6ad64c23a583.png)
 
I guess website was down!!!! I have tried in all my devices but still 408 issue.

**Comment by hello1337h** [comment]
Still down...

**Comment by itsChix** [comment]
Still down.

**Comment by Tropix126** [comment]
Use our new website, http://betterdiscord.app/.

**Comment by rauenzi** [comment]
See above
