### ISSUE TITLE
[Bug] BD is installed but not usable in Discord.

### ISSUE THREAD

**Issue by Yen3108** [rauenzi/BetterDiscordApp#745]
I dont know if this is issue from BD or from Discord app, just want to make sure. I did install the BD completely but somehow it's not in the Discord. All the functions in BD like Themes, Plug-in, Settings,.... dont appear in Discord. Maybe BD  doesnt hook my Discord yet?!

**Comment by rauenzi** [comment]
Please make sure you are using the latest installer from https://betterdiscord.app
