### ISSUE TITLE
[Installer not starting]

### ISSUE THREAD

**Issue by JakShirrak** [rauenzi/BetterDiscordApp#749]
So i wanted to repair BetterDiscord since it wasn't launching with discord anymore and downloaded the installer. But i cannot even launch it, it just doesn't want to.

I just need to double click on the installer and it doesn't even start. There is the loading logo but it never launched
(I also checked if it would appear on the task manager and it doesn't).

So is there a way to fix that?

![unknown](https://user-images.githubusercontent.com/83484290/116768439-d006e200-aa36-11eb-9b45-7fae119782b1.png)

Discord version: Stable

**Comment by Tropix126** [comment]
Have a look at my comment on https://github.com/BetterDiscord/Installer/issues/113.

**Comment by rauenzi** [comment]
Please see the above. That is the location for installer issues as well.
