### ISSUE TITLE
[Bug] BetterDiscord crashes when using Markdown syntax in the chat's text box

### ISSUE THREAD

**Issue by kamekku14** [rauenzi/BetterDiscordApp#752]
**Describe the Bug**
For some reason, BetterDiscord crashes when using a new Discord feature, namely called "Use slash commands and preview emojis, mentions, and markdown syntax as you type".

**To Reproduce**
Enable "Use slash commands and preview emojis, mentions, and markdown syntax as you type" via **App Settings** \> **Text \& Images**, then try using the Markdown syntax (italics, code lines, etc...) in the chat's text box.

**Expected Behavior**
For a few seconds (or minutes), the app suddenly crashes when/after using Markdown in the chat's text box.

**Screenshots**
A few seconds before the app crashes:
![image](https://user-images.githubusercontent.com/66167734/116882239-ca87e280-ac56-11eb-8c40-39bfafebda46.png)
_(it's using the italics, if that's the case)_

**Discord Version**
Stable 83364 (9af39da)

**Comment by Tropix126** [comment]
Have you narrowed this down to being strictly a BD issue, or could this be a plugin problem. Never seen this happen specifically.

Also: Are there any errors in the console when the crash occurs (access the console through the "Console Tab" after presssing <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>I</kbd>)

**Comment by kamekku14** [comment]
Alright, time to check.

But right now, be sure to turn off this Discord feature shown in this image below:
![image](https://user-images.githubusercontent.com/66167734/116988574-2740d700-ad03-11eb-886d-c9aa341fc0fc.png)

**Comment by dav1312** [comment]
I don't have that issue whatsoever

**Comment by rauenzi** [comment]
Have you tried recreating this after removing all plugins from the plugin folder?
