### ISSUE TITLE
[Feature] PLUGIN REQUEST Search option but for multiple servers/DMs at once

### ISSUE THREAD

**Issue by voidplayer212121** [rauenzi/BetterDiscordApp#753]
**Describe the feature you'd like**
 A plugin that search keywords and the result would bring up multiple selected servers at once with specific keyword instead of 1 server that you searched in.

**Additional context**
Tabs to choose between DMs and servers would be nice and blacklist/whitelist feature would be nice too.

**Comment by dav1312** [comment]
This is not an issue with BetterDiscord
