### ISSUE TITLE
[Bug] BROKE DISCORD

### ISSUE THREAD

**Issue by FreshImmuc** [rauenzi/BetterDiscordApp#761]
![image](https://user-images.githubusercontent.com/65733898/117477225-a4fc2100-af55-11eb-85b1-fdfa3b689999.png)

**To Reproduce**
Discord crashed and then this comes when I try to open it

**Expected Behavior**
That discord opens lmao

**Screenshots**
^^^^^^^^^^^^^^^^

**Discord Version**
Stable

**This thing is still there as a 2nd window:**
![image](https://user-images.githubusercontent.com/65733898/117477402-e096eb00-af55-11eb-9b50-91f65bf09990.png)

**Comment by rauenzi** [comment]
Reinstall Discord.
