### ISSUE TITLE
[Feature] Option to disable discord auto updates

### ISSUE THREAD

**Issue by siltentassasin** [rauenzi/BetterDiscordApp#764]
Is it possible to make an option that disables the discord updates, the betterdiscord updates should auto done. 
And if there is a new update for discord you get only a notification like when a plugin has an update.

So you can make the discord updates manually.

Advantage:

If discord makes an update that will crash betterdiscord or ban betterdiscord users, you can first check if the update do this before you done it finally.

**Comment by rauenzi** [comment]
We've decided this is not something we want to implement at this time.

**Comment by xx88xx** [comment]
> We've decided this is not something we want to implement at this time.

well if you won't allow people to toggle on/off auto update. can you make it that if your connection drops and discord crashes for a number of reasons, it doesn't go through the auto update process?

**Comment by sbaurem** [comment]
> We've decided this is not something we want to implement at this time.

why ??? us intel mac users r dying 😭

**Comment by doggybootsy** [comment]
You can manually make discord not update but this is something bd will not add as its out of scope.

**Comment by sbaurem** [comment]
> You can manually make discord not update but this is something bd will not add as its out of scope.

can u help me out then cuz im tryna download dicord on mac os 11 and the legacy version for mac os 11 keep updating and auto unsupports and ive tried creating json files in its support file but it doesnt work what do i do now

**Comment by doggybootsy** [comment]
You can join the support discord https://discord.gg/bnSUxedypU but BD does not support this, so you may not get support with doing that
