### ISSUE TITLE
[Bug]Get emotes Download FAILED error on Discord Startup.

### ISSUE THREAD

**Issue by jblanc88** [rauenzi/BetterDiscordApp#766]
**Describe the Bug**

Get Emoji Download FAILED error on Discord Startup.
**To Reproduce**

Startup discord.
**Expected Behavior**

Emoji's should download and not get the arror.
**Screenshots**

**Discord Version**

**Additional Context**

**Comment by jblanc88** [comment]
Discord version
Stable 84336 (eeeadc8)

**Comment by jblanc88** [comment]
![betterdiscord](https://user-images.githubusercontent.com/31604547/117564497-27bdd280-b061-11eb-8ad5-05b8dfffd460.PNG)
Here is the pop up I get

**Comment by rauenzi** [comment]
Please try reinstalling BD and see if the issue persists.
