### ISSUE TITLE
[Bug] Javascript error in latest version

### ISSUE THREAD

**Issue by Ari24-cb24** [rauenzi/BetterDiscordApp#767]
**Describe the Bug**
I just downloaded the installer for the latest version and got this error after the installing process:  https://imgur.com/a/Sh9G7KX
I also tried building bandaged myself but that did not work either.

**To Reproduce**
Install the latest version of BetterDiscord on windows

**Expected Behavior**
A javascript  error occurs

**Screenshots**
https://imgur.com/a/Sh9G7KX (the error itself)

**Discord Version**
Stable 84336 (eeeadc8)
Host 0.0.308
Windows 10 64-Bit (10.0.19042)

**Comment by rauenzi** [comment]
Your Discord version is out of date (and still was at the time of writing the issue) the syntax used in versions going forward was not compatible with the older versions.
