### ISSUE TITLE
[Feature] Add support for old Discord UI

### ISSUE THREAD

**Issue by Delta-official** [rauenzi/BetterDiscordApp#769]
**Is your feature request related to a problem? Please describe.**

With the new Discord UI, many users would like to be able to revert to the old one because of various reasons.

**Describe the feature you'd like**

I would like for BD to have built-in support for old UI

**Additional context**

**Comment by leo848** [comment]
Yes, we need this

**Comment by Tropix126** [comment]
This would be published in the form of a theme, but not be built-in to BD. I would be willing to make it but I would wait until discord pushes their shitty blurple/font rebranding to stable before doing so.

**Comment by GoudronViande24** [comment]
There is already a theme for this, it reverts the styling to before the update:
BetterDiscord website: https://betterdiscord.app/theme/Revert%20Rebrand
GitHub: https://github.com/Goose-Nest/GT-RevertRebrand
