### ISSUE TITLE
Unable to continue installation: discord_desktop_core core.asar does not exist

### ISSUE THREAD

**Issue by mrwallace888** [rauenzi/BetterDiscordApp#77]
wtf?
I went to install it and I get this message. The first time it said it found the old injector and it was stuck. Then I tried again and got this:
Searching for Discord core in: C:\Users\miste\AppData\Roaming\Discord\0.0.301\modules\discord_desktop_core
core.asar does not exist in: C:\Users\miste\AppData\Roaming\Discord\0.0.301\modules\discord_desktop_core!
Unable to continue installation.

What the hell?

**Comment by steamp0rt** [comment]
![capture](https://user-images.githubusercontent.com/25724666/47248419-d3e33380-d3f9-11e8-988d-dfafcbe381e0.PNG)

Hm

**Comment by rauenzi** [comment]
Download the latest installer

**Comment by steamp0rt** [comment]
I did. No errors but infinite loading icon

**Comment by rauenzi** [comment]
Go to the support servers for additional help. I am currently swamped unfortunately

**Comment by rauenzi** [comment]
@mrwallace888 that installer is outdated, please use the latest.
