### ISSUE TITLE
[Bug] This Stupid Bug that doesn't let BD Run in any Discord Client

### ISSUE THREAD

**Issue by GabrielMadrigal** [rauenzi/BetterDiscordApp#774]
**Describe the Bug**
Everytime I try to open a Client with BD, it crashes, no matter if there are plugins or not

**To Reproduce**
Launch Client

**Expected Behavior**
It Tends to Crash Discord and reverts to non-BD Discord

**Screenshots**
![image](https://user-images.githubusercontent.com/30850866/117912101-190f2f80-b29c-11eb-81d4-b96e1d1696c6.png)

**Discord Version**
Stable, Canary, and PTB

**Comment by unknown821** [comment]
Same it doesn't work :/

**Comment by rauenzi** [comment]
Reinstall and try with the latest version of BD, also please provide your version numbers.
