### ISSUE TITLE
[Bug] Injection fails on Gentoo Linux

### ISSUE THREAD

**Issue by octoman90** [rauenzi/BetterDiscordApp#776]
**Describe the Bug**
Discord data directory is placed in `/opt` by default, while the injector looks for it in `/usr/share`.

**To Reproduce**
1. Have Discord installed from the Gentoo Linux official repository
2. Follow the BetterDiscordApp manual installation steps

**Expected Behavior**
Command `npm run inject` succeeds.

**Screenshots**
![image](https://user-images.githubusercontent.com/82229068/117943966-fb2de300-b30c-11eb-9422-c5dd63bcda55.png)

**Discord Version**
Any

**Comment by octoman90** [comment]
Fixed in pull request #775

**Comment by ObserverOfTime** [comment]
You can use [`betterdiscordctl`](https://github.com/bb010g/betterdiscordctl/tree/beta) or the new cross-platform [installer](https://github.com/BetterDiscord/Installer/releases/tag/v1.0.0-beta).

**Comment by octoman90** [comment]
> You can use [`betterdiscordctl`](https://github.com/bb010g/betterdiscordctl/tree/beta) or the new cross-platform [installer](https://github.com/BetterDiscord/Installer/releases/tag/v1.0.0-beta).

Should this be added to README.md then? Is there a reason why those projects are not a part of this project?

**Comment by ObserverOfTime** [comment]
The README used to mention `betterdiscordctl` but it was [replaced](https://github.com/rauenzi/BetterDiscordApp/commit/59d9ec3deaeebc63d67ed4a8d2d2656a285539c7#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R34) by the new installer.
