### ISSUE TITLE
[Bug] Transitioning Guilds

### ISSUE THREAD

**Issue by LordFarquhar** [rauenzi/BetterDiscordApp#781]
**Describe the Bug**
When moving between guilds, it no longer remembers the channel you were previously viewing in that guild and instead always takes you to the topmost channel

**To Reproduce**
Join 2 or more guilds
View a channel lower than the top channel in one guild
Move to the second guild
Return to the first and see it back at the top channel

**Expected Behavior**
It remembers the channel you were just viewing per guild and keeps you there instead of moving you to another

**Versions**
Stable 84785 (fe5e237)
BetterDiscord 1.1.0
Host 1.0.9001
Windows 10 64-Bit (10.0.19042)

**Comment by Tropix126** [comment]
Are you sure this is related to BD?

**Comment by LordFarquhar** [comment]
farily certain. I reinstalled discord and BD to be safe and after installing discord (before bd) this issue was not occuring. As soon as BD was activated then the issue began again
I also made sure it was not a plugin causing the issue either

**Comment by dav1312** [comment]
I can't reproduce it

**Comment by LordFarquhar** [comment]
I must apologise, I still have no idea what caused the issue but I boot up today to find the issue has resolved itself. Thank you to anyone who may have been looking into this. Again sorry for the bother.
