### ISSUE TITLE
BetterDiscord Tab doesn't appears in Discord [Bug] [Awaiting Response]

### ISSUE THREAD

**Issue by SleepyLuc** [rauenzi/BetterDiscordApp#783]
**Describe the Bug**
The BetterDiscord Tab doesn't appears in Discord Configuration Tab

**Expected Behavior**
I expected the BetterDiscord Tab would appear in the Discord Configuration Tab

**Screenshots**
![image](https://user-images.githubusercontent.com/82110500/118200357-45a58180-b42b-11eb-93c4-8c01388096cb.png)

**Discord Version**
Stable

**Additional Context**
After reinstalling Discord because of an error, i decided to reinstall BetterDiscord, when i finished installing it, i already had some plugins and themes, so i oppened the configurations to find the BetterDiscord tab, but it doesn't appears

**Comment by Osyruu** [comment]
Go there : `%AppData%\BetterDiscord\data\stable` and try deleting `plugins.json`

**Comment by SleepyLuc** [comment]
@Osyruu it worked! Thanks! :)
