### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by wrystic** [rauenzi/BetterDiscordApp#784]
**Describe the Bug**
 My discord will not open

**To Reproduce**
 

**Expected Behavior**
 Whenever i open my discord, it says a fatal javascript error has occurred 

**Screenshots**
 
![wtf](https://user-images.githubusercontent.com/84160998/118203676-652fb080-b411-11eb-82f4-41e8339c6d38.png)

**Discord Version**
 Stable

**Additional Context**
 Just Please help

**Comment by FourInchKnife** [comment]
Please change the name to something that describes the error better. Maybe something like "InconsistentInstallerState crash on startup"

**Comment by rauenzi** [comment]
Reinstall Discord, this is not something that BD touches.
