### ISSUE TITLE
Discord Canary not compatible with latest version [Bug]

### ISSUE THREAD

**Issue by fellowish** [rauenzi/BetterDiscordApp#785]
**Description**
Discord Canary no longer opens properly with its latest update. Even when deleting all files related to BD, and uninstalling BD from Discord Canary, any reinstallations to Canary causes it to crash due to BD again. This occurs whether or not plugins or themes are installed.

**Reproduction**
- Install BD to Discord Canary
- Restart Discord Canary (ctrl + r)
- Discord Canary no longer properly launches

**Expected Behavior**
- Install BD to Discord Canary
- Restart Discord Canary (ctrl + r)
- Discord Canary opens with BD properly

**Screenshots**
![Crash](https://user-images.githubusercontent.com/28973978/118223078-6af3b900-b446-11eb-9fb7-150b65c6526c.gif)
![image](https://user-images.githubusercontent.com/28973978/118223183-85c62d80-b446-11eb-8aa0-b60627d2216f.png)
![image](https://user-images.githubusercontent.com/28973978/118223207-89f24b00-b446-11eb-939d-82ebdd88abb9.png)

**Discord Version**
Canary

**Additional Context**
The issue with restarting Discord seems to occur with the other versions as well, however, these are easily resolved with the removal of certain plugins. Discord Canary in particular simply does not load properly upon restarting the client.

**Comment by rauenzi** [comment]
Merging to #821
