### ISSUE TITLE
[Bug]Hide Gift Feature not working

### ISSUE THREAD

**Issue by joesphan** [rauenzi/BetterDiscordApp#786]
Hi! I just installed betterdiscord to remove the minimum window size limit, however I found that the hide gift feature is not working. Keep up the good work, devs!

Stable 84785 (fe5e237)
BetterDiscord 1.1.0
Host 1.0.9001
Windows 10 64-Bit (10.0.19042)

**Comment by HopsTheThird** [comment]
kinda sucks the official settings are broken, for now you can just use css snippets, this one works really well that i found

`/* 🠗 Hide GIF button 🠗*/
.buttonContainer-28fw2U:not(.send-button) .button-3AYNKb,
/* 🠗 Hide GIft button 🠗*/
.buttons-3JBrkn > .button-38aScr > :not(.translateButton-DhP9x8)
{display: none;}`

**Comment by rauenzi** [comment]
This has been fixed at latest level
