### ISSUE TITLE
Don't want to nag, but is this bannable?

### ISSUE THREAD

**Issue by ThatFlySamurai** [rauenzi/BetterDiscordApp#787]
As the title says, I don't wanna be a dick or a debbie downer but I remember reading in the TOS that custom clients weren't allowed. I just wanna make sure I won't get banned for using this as it looks cool. Thanks!

**Comment by drowosi** [comment]
there's always a chance, but it's rather slim.

**Comment by Tropix126** [comment]
https://betterdiscord.app/FAQ

**Comment by Kreijstal** [comment]
maybe

**Comment by rauenzi** [comment]
See answer from Tropix.
