### ISSUE TITLE
[Bug] Wrong injection location for inject script on linux

### ISSUE THREAD

**Issue by Mm2PL** [rauenzi/BetterDiscordApp#789]
**Describe the Bug**

After building and injecting BetterDiscord using `npm run build` and `npm run inject` Discord crashes with the following message:
```
A JavaScript error occurred in the main process
Uncaught Exception:                                                                                                                      
Error: Session can only be received when app is ready                                                                                    
    at Object.get [as defaultSession] (electron/js2c/browser_init.js:117:366)
    at Function.remove (webpack-internal:///./src/modules/csp.js:11:64)
    at eval (webpack-internal:///./src/index.js:34:60)
    at Object../src/index.js (/home/mm2pl/git/BetterDiscordApp/dist/injector.js:29:1)
    at __webpack_require__ (/home/mm2pl/git/BetterDiscordApp/dist/injector.js:142:41)                                                   
    at /home/mm2pl/git/BetterDiscordApp/dist/injector.js:194:37
    at Object.<anonymous> (/home/mm2pl/git/BetterDiscordApp/dist/injector.js:196:12)
    at Module._compile (internal/modules/cjs/loader.js:967:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1004:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
```

`discordPath` was overridden to be the true path for my system (`~/Discord/resources`). BD was cloned to `~/git/BetterDiscordApp`.

**To Reproduce**

It just doesn't work, I have no idea if this bug is reproducible.

**Expected Behavior**

Discord actually working.

**Screenshots**

N/A

**Discord Version**

Stable

**Additional Context**

I'm using Ubuntu 20.04.1 LTS (Focal Fossa)

<details>
<summary>Contents of `~/git/BetterDiscordApp/dist`:</summary>

```
drwxrwxr-x  2 mm2pl mm2pl 4,0K maj 19 09:11 .
drwxrwxr-x 13 mm2pl mm2pl 4,0K maj 19 09:32 ..
-rw-rw-r--  1 mm2pl mm2pl  55K maj 19 09:11 injector.js
-rw-rw-r--  1 mm2pl mm2pl   45 maj 19 09:11 package.json
-rw-rw-r--  1 mm2pl mm2pl 1,1K maj 19 09:11 preload.js
-rw-rw-r--  1 mm2pl mm2pl 1,9M maj 19 09:32 renderer.js
```

[injector.js](https://kotmisia.pl/haste/raw/6fho2MlUWln4GzA)
[package.json](https://kotmisia.pl/haste/raw/U8yYl9Z3hKFAWgr)
[preload.js](https://kotmisia.pl/haste/raw/OEIh64owL7qdQS3)
[renderer.js](https://kotmisia.pl/haste/raw/Q7kFuo4UoO0I7kr)

</details>
Update: I managed to get the installer working but not `npm run ...`

**Comment by rauenzi** [comment]
The `inject` script is still using the incorrect injection style for linux.

**Comment by ItsDrike** [comment]
Could you release some quick patch we could use in the meanwhile in a separate branch until the proper one is released which will support snap installation and other forms of discord installs?

**Comment by rauenzi** [comment]
No there is no quick patch for this, the fix is just the fix. This will not include support for snap installs however. Those are not supported by the injector, installer, or renderer at this time.

**Comment by ItsDrike** [comment]
> No there is no quick patch for this, the fix is just the fix. This will not include support for snap installs however. Those are not supported by the injector, installer, or renderer at this time.

Oh, I thought #828 had a fix, just incomplete because it didn't support some special ways of installations, so I figured it would just be a matter of keeping that branch and mentioning it in README, guess I misunderstood it, alright then.
