### ISSUE TITLE
better discord not loading correctly

### ISSUE THREAD

**Issue by jasem65434** [rauenzi/BetterDiscordApp#790]
ive been having this problem from like yesterday of that i cant see my plugins tab or themes tab or any other tab and also ive tried to uninstall BD with deleting the folder 3 times already nothing worked ive also tried to disable BD emotes and still nothing

i told my friend to install better discord and he also has the same problem as me the problem witch i said here
and also it keeps loading for a long time like its been 2-3 hours
![BD1](https://user-images.githubusercontent.com/84439464/118784638-3c8c3880-b8a1-11eb-9c96-1754239241de.PNG)
![BD2](https://user-images.githubusercontent.com/84439464/118785047-883ee200-b8a1-11eb-81e1-9a5d8d36ca95.PNG)

https://user-images.githubusercontent.com/84439464/118785126-9d1b7580-b8a1-11eb-9878-2cf81158f573.mp4

![BD3](https://user-images.githubusercontent.com/84439464/118823675-33639180-b8ca-11eb-8e88-149fb701a2a2.PNG)

**Comment by rauenzi** [comment]
Looking at the console output your internet (or something on your end) is blocking requests to the CDN to get the resources BD uses. The latest version of BD (requires reinstall) should allow loading to still progress however.
