### ISSUE TITLE
Discord broke settings menu on canary.

### ISSUE THREAD

**Issue by Strencher** [rauenzi/BetterDiscordApp#795]
Discord updated their `SettingsView` Component and broke bd's injection. I've done some researching and found out that the fix is pretty easy. All you have to do is explained below.

In line [`ui/settings.js` **L#64**](https://github.com/rauenzi/BetterDiscordApp/blob/main/renderer/src/ui/settings.js#L64) you need to replace it with `WebpackModules.getByDisplayName("SettingsView")`

The last part is that they renamed `UserSettings.prototype.generateSections` => `UserSettings.prototype.getPredicateSections`. So you need to update two lines [`ui/settings.js` **L#68**](https://github.com/rauenzi/BetterDiscordApp/blob/main/renderer/src/ui/settings.js#L68) and [`ui/settings.js` **L#100**](https://github.com/rauenzi/BetterDiscordApp/blob/main/renderer/src/ui/settings.js#L100) and replace `generateSections` with `getPredicateSections`.

**Comment by Overimagine1** [comment]
Looks like this is on all discord versions now

**Comment by jeffplays2005** [comment]
Just as Strencher commented,
Heres all the instructions for the noobs:
MacOS:
1) In the app called terminal, run `git clone https://github.com/rauenzi/BetterDiscordApp.git`
2) Open the directory
3) Open renderer->src->ui->settings.js
4) Open the settings.js file in textedit
5) Find line 64
6) Replace `const UserSettings = await ReactComponents.get("UserSettings", m => m.prototype && m.prototype.generateSections);` with `const UserSettings = await WebpackModules.getByDisplayName("SettingsView");`
7) Find line 68 
8) Replace 
```js
Patcher.after("SettingsManager", UserSettings.prototype, "generateSections", (thisObject, args, returnValue) => {
``` 
with 
```js
Patcher.after("SettingsManager", UserSettings.prototype, "getPredicateSections", (thisObject, args, returnValue) => {
```
9) Find line 100
10) Replace
```js
const stateNode = Utilities.findInReactTree(Utilities.getReactInstance(node), m => m && m.generateSections, {walkable: ["return", "stateNode"]});
```
with
```js
const stateNode = Utilities.findInReactTree(Utilities.getReactInstance(node), m => m && m.getPredicateSections, {walkable: ["return", "stateNode"]});
```
11) Save the file
12) In terminal, run `npm I`
13) If you don't have npm, go to https://nodejs.org/en/ and download that lol
14) After `npm i` run `npm run build`
15) Then run `npm run inject` or canary = `npm run inject canary`

Windows kiddies can go suck their lil 8D lool, jk lmfao, just follow the same step, terminal becomes command prompt and text edit is just notepad.exe

**Comment by jkrosado** [comment]
> better discord mods go suck their pp bye
you spammed the link to this and got salty when you were muted

**Comment by jeffplays2005** [comment]
> better discord mods go suck their pp bye
> you spammed the link to this and got salty when you were muted

bruh r u retarded, if I'm muted, how can I be salty lmfao, and what's wrong with this link??

**Comment by jkrosado** [comment]
> > better discord mods go suck their pp bye
> > you spammed the link to this and got salty when you were muted
> 
> bruh r u retarded, if I'm muted, how can I be salty lmfao, and what's wrong with this link??

the problem is that you spammed it, and you were salty when you were *told* you were going to be muted
and lets not forget

> better discord mods go suck their pp bye

**Comment by paz** [comment]
Cool
