### ISSUE TITLE
[Bug] Unable to view plugins menu after installing a theme

### ISSUE THREAD

**Issue by BubblemintEDM** [rauenzi/BetterDiscordApp#796]
**Describe the Bug**
After installing Material_Discord I have lost access to all the Better Discord features except the plugins and themes repos. Removing the theme does not help

**To Reproduce**
Install the theme Material_Discord

**Expected Behavior**
Removes the plugins section and the other sections that Better Discord adds

**Screenshots**
https://addicted-to-hentai.life/4sq445P0

**Discord Version**
Stable

**Comment by rauenzi** [comment]
Try reinstalling BetterDiscord.

**Comment by BubblemintEDM** [comment]
Tried that and now it doesn't install anymore, just launches regular discord. I tried using the repair button but that did nothing

**Comment by justinjohn0306** [comment]
Use 3rd party uninstaller like IObit Uninstaller

**Comment by BubblemintEDM** [comment]
didn't work, whenever I install BetterDiscord now it removes the close, restore and minimise buttons.

**Comment by BubblemintEDM** [comment]
okay got it to work by using the BetterDiscord installer instead of BandageBD
