### ISSUE TITLE
The plugins and themes settings don't show up anymore.

### ISSUE THREAD

**Issue by daddyploaie** [rauenzi/BetterDiscordApp#797]
I wanted to change the theme and when I got to the bottom of the settings the better discord options were no longer there.

![unknown](https://user-images.githubusercontent.com/75731725/119222892-3a271a00-baff-11eb-8d4f-88713bad9acc.png)

**Comment by Kery5** [comment]
Same thing happening to me.

**Comment by kamekku14** [comment]
Wait a second—it is? *[sees BD settings missing from the settings menu]* It is! I have no idea what's going on here!

**Comment by smowtenshi** [comment]
Repairing BD installation seems to fix it.

**Comment by Drflash55** [comment]
Can confirm that repairing the BD installation fixes the issue with the settings missing.

**Comment by avyuktbmgo** [comment]
its 2024, still the plugin and theme setting does not showed up

Uploading Screen Recording 2024-09-16 at 8.58.16 PM.mov…

**Comment by dskxkzn** [comment]
repairing and even uninstalling/installing won't work here...

**Comment by KillerTheFlareon** [comment]
Also having same issue. Repair/reinstall isn't working, the settings just are not showing up
