### ISSUE TITLE
[Bug] BetterDiscord settings tabs show in Server Settings dialog

### ISSUE THREAD

**Issue by QbDesu** [rauenzi/BetterDiscordApp#798]
## If you are also experiencing this bug, there is no need to comment +1 or anything please. Reinstalling BetterDiscord fixes the issue.

**Describe the Bug**
The recent hotfix overshot a bit and the BetterDiscord settings tabs are now also added to the server settings dialog.

**To Reproduce**
Update to the recent hotfix (v.1.1.1) and open the Server Settings on any server you have admin access to.

**Expected Behavior**
There shouldn't be BetterDiscord settings tabs. (Themes, Plugins, etc)

**Screenshots**
![image](https://user-images.githubusercontent.com/5641607/119232316-4c5f8300-bb14-11eb-9104-4443fc1382c3.png)

**Discord Version**
Tested on Canary; there are also reports from stable users; PTB should also be affected

**Additional Context**
I know the update was a hotfix and it's not too bad, and something like this breaking might have been expected considering there wasn't time for extensive testing. Mostly just documenting this here so I can call it known bug and have something to link to when the question comes up in the support server.

**Comment by Reubzz** [comment]
Can Reproduce - Discord Stable (BD Hotfix Version - 1.1.1)

**Comment by rauenzi** [comment]
Try reinstalling BetterDiscord

**Comment by QbDesu** [comment]
Alright, that fixes it. Closing.
