### ISSUE TITLE
pls help

### ISSUE THREAD

**Issue by M8troid** [rauenzi/BetterDiscordApp#8]
hi, when i run bandagedbd it stops on extracting core.asar
i really would appreciate some help.

**Comment by PoorPocketsMcNewHold** [comment]
Place bandagedbd somewhere else on your hard drive, Outside of the Downloads folder for example. And launch it again normally.
Considering that you seem to be unfamiliar with GitHub according to the absence of Profile Picture, Here's a little tip. When you have an issue with a certain project on GitHub.
Check for the already closed issues in the issues page, by researching them with `is:issue is:closed`.
[Here's the response to your issue that you've could found without opening another ticket. ](https://github.com/rauenzi/BetterDiscordApp/issues/7)

**Comment by rauenzi** [comment]
What he said
