### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by k1nd1** [rauenzi/BetterDiscordApp#800]
**Describe the Bug**
i installed BD on version 1.1.1 and in settings was only BD settings button.

**To Reproduce**

**Expected Behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/84695490/119293289-ef7ade80-bc73-11eb-8cd4-2d3b5157ea17.png)

**Discord Version**
1.0.9001

**Additional Context**

**Comment by genrihx2** [comment]
does not work   betterdiscord  
    
![image](https://user-images.githubusercontent.com/3043207/119536311-9c974900-bd91-11eb-8a2b-26fe958db7d3.png)

**Comment by k1nd1** [comment]
> does not work betterdiscord
> 
> ![image](https://user-images.githubusercontent.com/3043207/119536311-9c974900-bd91-11eb-8a2b-26fe958db7d3.png)

Да он не работает у меня.

**Comment by genrihx2** [comment]
@k1nd1  + reinstall

**Comment by genrihx2** [comment]
betterdiscord crash 
screenshots   
![image](https://user-images.githubusercontent.com/3043207/120026210-6a3c5480-bffa-11eb-906f-c2a419718637.png)
