### ISSUE TITLE
[Bug] meme

### ISSUE THREAD

**Issue by spira007** [rauenzi/BetterDiscordApp#801]
panel of bd disappeared 

![изображение](https://user-images.githubusercontent.com/73871136/119363252-44d7df80-bcb6-11eb-9d2c-726efa6f716c.png)

**Discord Version**
stable

fucking bd panel doesnt exist

**Comment by QbDesu** [comment]
Reinstall using the new installer https://github.com/BetterDiscord/Installer/releases/latest
The current version is `BetterDiscord 1.1.1` (shown in the bottom left of the settings) not `BD 1.0.0`.
The version of the installer is 1.0.0, that's just the version of the installer and not the verison of BetterDiscord it installs. It will install the latest version BetterDiscord.
Uninstalling/Reinstalling will not remove your plugins, themes and settings, so don't worry about that.
