### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by ATotalFailure** [rauenzi/BetterDiscordApp#807]
**Describe the Bug**
BD seems to not be working with the new discord update, after starting BD on discord the app would appear to run in browser mode with no access to the close or minimise buttons in the upper right corner of the app. The BD logo also doesnt appear on the top left corner of the app and themes do not run properly

**To Reproduce**
On running discord with BD installed

**Expected Behavior**
The app should start with BD and run themes etc.

**Screenshots**

**Discord Version**
Stable

**Additional Context**
Only started recently today when i turned on my pc. I assumed it might be due to a discord update

**Comment by Osyruu** [comment]
You need to reinstall BD.

**Comment by FrostBid** [comment]
Same problem here, tried reinstalling and repair as well as restarting the computer, doesn't seem to work for me.

**Comment by Osyruu** [comment]
Ok so, press `Win + R` type: `%appdata%\BetterDiscord\data\stable` and delete `plugins.json` and reload Discord.

**Comment by FrostBid** [comment]
Finally worked for me. Uninstalled discord and BD altogether, and a fresh reinstall fixed it.

**Comment by rauenzi** [comment]
See the above
