### ISSUE TITLE
Option Remove Stage Discovery and Nitro on the front page

### ISSUE THREAD

**Issue by zroncarij** [rauenzi/BetterDiscordApp#808]
Remove the stage discovery and nitro boost tabs on the front page of Discord so that users can automatically open into the friends tab should they wish.

**Comment by parkuristt** [comment]
yeah!

**Comment by jodri-code** [comment]
great feature that should definitely be added

**Comment by rhystedstone** [comment]
Bump

**Comment by Tropix126** [comment]
This is already possible with CSS, and probably shouldn't be built into the client.

**Comment by re11ding** [comment]
```
a[href="/discovery"] {
  visibility: hidden;
  width: 0px;
  height: 0px;
}
```
This hides the Stage Discovery if you weren't willing to figure out how to create the CSS on your own.

**Comment by rauenzi** [comment]
@rhystedstone this is not the kind of issue tracker that uses or needs "bump"s. Please react to the original issue with 👍 instead.

This will not be built into the client.
