### ISSUE TITLE
[Question] Removal of the class normalizer

### ISSUE THREAD

**Issue by johnnycocas** [rauenzi/BetterDiscordApp#810]
This is not a bug nor a feature request, it is a question made out of curiosity :P

I see that the class normalizer was removed in BD v1.1.0 as it "does more harm than good", to which I'd like to ask what were the reasons behind removing this feature?

I understand it may have been buggy or cause issues that you may have deemed too big to ignore and would warrant the removal of the feature, but as far as I have experienced I've never noticed any issue that I assume could have been caused by it, hence my curiosity!

**Comment by l0c4lh057** [comment]
![grafik](https://user-images.githubusercontent.com/42084688/119841696-51eb0d80-bf06-11eb-9566-bc35ee2a1705.png)

**Comment by johnnycocas** [comment]
Thanks for the explanation, I understand and agree with it. Also, I did not know of that selector trick, I guess I have learned something new today 😄
