### ISSUE TITLE
BetterDiscord not uninstalling

### ISSUE THREAD

**Issue by jodri-code** [rauenzi/BetterDiscordApp#811]
**Describe the Bug**
When installing, uninstalling or attempting to repair BetterDiscord, the installer goes as far as 'Killing Discord... Attempting to kill Discord...' and won't advance.

**To Reproduce**
Download and attempt to install BetterDiscord with, or without, the Discord (unmodified) client open.

**Expected Behavior**
The installer runs through and finishes the setup.

**Screenshots**
![BD00](https://user-images.githubusercontent.com/79205320/119969752-3e47b180-bfaf-11eb-8823-e9a7204696c6.png)
![BD01](https://user-images.githubusercontent.com/79205320/119969765-43a4fc00-bfaf-11eb-88c2-0d86410b1133.png)

**Discord Version**
Stable

**Comment by DinoTheDevOfficial** [comment]
does it delete tho?

**Comment by rauenzi** [comment]
If you get stuck there, manually close Discord before running the uninstall. Also in the future, issues for the installer should be opened on that repo.

**Comment by cheesykirah** [comment]
Closing Discord manually does not help, I still have this issue

**Comment by Strencher** [comment]
Make sure discord was closed from system tray too.

**Comment by cheesykirah** [comment]
I did that

**Comment by Strencher** [comment]
That's odd. Please try running the installer as admin as well.

**Comment by cheesykirah** [comment]
I reinstalled Discord and it it kinda worked now
