### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by RINSU0KA** [rauenzi/BetterDiscordApp#813]
discord crashing too much when I launch it, i installed BD on this too, tried reinstalling both apps, but the crashing still happens, turned off my pc, restarted it too, nothing worked.

**Comment by ProofHF** [comment]
Same on my end.

**Comment by rhystedstone** [comment]
Try uninstalling BetterDiscord, then see if it crashes as often. If it does, try reinstalling Discord. If it continues to crash afterwards, it's not Discord or BetterDiscord.

**Comment by abbeybabbey** [comment]
same on my end tried reinstalling many times, running vanilla discord now

**Comment by Bananaz21** [comment]
#821 If you are running Canary, it breaks BD. It's being fixed, but for now use pbt, stable, or run vanilla.
