### ISSUE TITLE
[Bug] Window Snapping not working on Windows 10

### ISSUE THREAD

**Issue by rhystedstone** [rauenzi/BetterDiscordApp#816]
**Describe the Bug**
The window does not "snap" to a screen when dragged. This works on the official Discord program, but for some reason doesn't work on BetterDiscord.

**To Reproduce**
Try snapping the window to a display while dragging it's title bar.

**Expected Behavior**
The window to "snap" to the entire display, or to the side of it.

**Screenshots**
After dragging the window to the top of a display, it doesn't resize or go fullscreen as expected, it just stays there.
![Not resizing](https://user-images.githubusercontent.com/12123847/120329527-da412800-c2e3-11eb-8625-41c0886e6dab.png)

**Discord Version**
Stable 86447 (6b2c76f), running BetterDiscord 1.1.1.

**Additional Context**
I have three displays, hence why I find display snapping so useful.

**Comment by Tropix126** [comment]
This is a limitation with electron's transparency module, which has some inconsistent side-effects on most window managers. If you aren't actively using the `transparency` option in BD settings, I suggest you disable it.

**Comment by rhystedstone** [comment]
> This is a limitation with electron's transparency module, which has some inconsistent side-effects on most window managers. If you aren't actively using the `transparency` option in BD settings, I suggest you disable it.

Thank you, this was the problem. I had no idea that was enabled.

![image](https://user-images.githubusercontent.com/12123847/120416646-66d7fe80-c355-11eb-9033-371b44762bd6.png)
