### ISSUE TITLE
[Bug] Failed to download package / can't connect to EACES

### ISSUE THREAD

**Issue by Otaxu** [rauenzi/BetterDiscordApp#820]
![better discord issue](https://user-images.githubusercontent.com/84841869/120620933-bbff3780-c45d-11eb-9072-e6e6aebecae1.PNG)

Hello, I tried to install BD several times, restart my pc, re-download the installer. Nothing works. 
Can anybody explain to me how to solve this problem?

Thanks

**Comment by Tropix126** [comment]
Very likely an issue with your firewall, or your antivirus intercepting the request.
