### ISSUE TITLE
[Bug] Discord Canary Refusing To Start

### ISSUE THREAD

**Issue by mihirgarg01** [rauenzi/BetterDiscordApp#825]
**Describe the Bug**

Discord Canary refusing to start after betterdiscord install (using betterdiscordctl). I tested this 3 times, once using the betterdiscord appimage, another time with the ctl using [discord-canary-electron-bin](https://aur.archlinux.org/packages/discord-canary-electron-bin/), and another time with regular [discord-canary](https://aur.archlinux.org/packages/discord-canary/)

**To Reproduce**

1. Visit ArchLinux AUR for [discord-canary](https://aur.archlinux.org/packages/discord-canary/)
2. Open a terminal, run yay -S discord-canary 
3. Visit ArchLinux AUR for [betterdiscordctl-git](https://aur.archlinux.org/packages/betterdiscordctl-git/)
4. Open a terminal and run yay -S betterdiscordctl-git
5. Run betterdiscordctl -f canary install
6. Open Discord, and get fatal error. (In Screenshot)

**Expected Behavior**

Follow Steps 1-5, then open discord. Discord should open, and in settings, better discord settings should be present.

**Screenshots**

[error screenshot](https://imgur.com/a/r1LpKyU)

**Discord Version**

Discord Flavor: Canary v0.0.124
OS: ArchLinux w/ Gnome 40.01

**Additional Context**

Discord was working before this, I closed the client. Discord promted me to download an update, so I redid yay -S discord-canary. The install was a success, when I opened discord canary, better discord was not present. When I installed it with the command line tool and opened discord, I got the error in the screenshot. Would love a solution, thanks for any help! :D

**Comment by WafflesDev** [comment]
i have the exact same error on windows via installer

**Comment by mihirgarg01** [comment]
Thanks, I was not sure if this was a repeat question from the other bugs I saw, as I was running arch, while everyone else was able to reproduce with windows.
