### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by FireNuke** [rauenzi/BetterDiscordApp#826]
**Describe the Bug**
While trying to launch discord it gives me an error ! Discord does not launch. btw repairing, uninstalling and installing again don't work either !

**To Reproduce**

**Expected Behavior**
expected to launch

**Screenshots**
![image](https://user-images.githubusercontent.com/56696555/120892576-56eb4380-c60f-11eb-9ecf-de833600fce2.png)

**Discord Version**
Canary

**Additional Context**

**Comment by jakey1995abc** [comment]
I've been having the same issue. Even tried completely uninstalling all Discord versions + Better Discord and doing clean install. That didn't make a difference for me :(

**Comment by rauenzi** [comment]
Duplicate of #821
