### ISSUE TITLE
[Bug]Profile Card Issue 

### ISSUE THREAD

**Issue by canerolu2019** [rauenzi/BetterDiscordApp#830]
**Describe the Bug**
Discord apperantly changed their user popout again and when i open the profile card its not coresponding with the theme anymore.

**To Reproduce**
it reproduces this glitch when i click on a user profile.

**Expected Behavior**
i expected that maybe enabling then disabling the theme might fix the issue but it didnt

**Screenshots**
![image](https://user-images.githubusercontent.com/57676524/121250625-9d120280-c8ae-11eb-878c-9d6619fa3152.png)

 

**Discord Version**
Stable

**Additional Context**
i hope that it can be fixed

**Comment by dav1312** [comment]
This is not an issue with BetterDiscord, its an issue with your theme.

**Comment by canerolu2019** [comment]
> This is not an issue with BetterDiscord, its an issue with your theme.

ah ok. I didnt know that. Thx for clarification.
