### ISSUE TITLE
[Question] How would one make a plugin with a message event?

### ISSUE THREAD

**Issue by Atlas7005** [rauenzi/BetterDiscordApp#834]
I'm trying to create a plugin that notifies me when a specific message is sent in a specific channel on a specific server, but I have no idea how I would make that happen without constantly being in the channel...
Does anyone know?
(Before you say it's not possible, I highly doubt that since Message Logger V2 can do something like this, but its code is too unfamiliar for me to try to debug)

**Comment by developomp** [comment]
This is not the right place.
I suggest closing the issue.

BD discord server: https://discord.com/invite/0Tmfo5ZbORCRqbAd
plugin creation wiki: https://github.com/rauenzi/BetterDiscordApp/wiki/Creating-Plugins

**Comment by Atlas7005** [comment]
It can only be the right place, as plugins run on BetterDiscord.

**Comment by Atlas7005** [comment]
I figured it out.
