### ISSUE TITLE
[Bug]   BetterRoleColors Don't colored mention

### ISSUE THREAD

**Issue by turgutersoz34** [rauenzi/BetterDiscordApp#836]
**Describe the Bug**
This betterrolecolors plugin has don't colored as mention. 

**Screenshots**
![image](https://user-images.githubusercontent.com/42961782/121813659-b1227f00-cc75-11eb-8b83-f224cb6b2928.png)

**Discord Version**
 Stable,  PTB

**Comment by dav1312** [comment]
This is not an issue with Betterdiscord, its an issue with a plugin.
Close this issue, and keep track of this one https://github.com/rauenzi/BetterDiscordAddons/issues/397
