### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by PustakP** [rauenzi/BetterDiscordApp#837]
**Describe the Bug**
Javascript error

**To Reproduce**
I just installed BD while discord was running and this error came up. Now even after repairing this error comes up.

**Expected Behavior**
discord is supposed to open

**Screenshots**
![image](https://user-images.githubusercontent.com/74170759/121892366-45eeb080-cd3a-11eb-9099-854340bc7d2e.png)

**Comment by vortechdev** [comment]
I have the exact same problem. Very strange

**Comment by doggybootsy** [comment]
i know this is pretty late, but reinstall discord its outdated

**Comment by rauenzi** [comment]
Your Discord used here is out of date and unsupported, please reinstall Discord.
