### ISSUE TITLE
BetterDiscord doesn't work at all!

### ISSUE THREAD

**Issue by marcocorriero** [rauenzi/BetterDiscordApp#84]
it gives me a error that BD is not compatible with the latest JS.

Fix please?

**Comment by ToniTurnerr** [comment]
Installing the latest release (https://github.com/rauenzi/BetterDiscordApp/releases/tag/0.3.0) fixes this issue for me.

**Comment by Kallyopae** [comment]
Due to constant micro updates that Discord constantly push to us, BD functionality is easily broken and reinstalling BD will fix most of the issues you might have

**Comment by rauenzi** [comment]
Do try reinstalling, as that fixes the error described in the OP.

**Comment by marcocorriero** [comment]
I had to delete all my files (from ‘Everything’) calling or mentioning discord, then reinstalled discord and betterdiscord , that worked for me.


________________________________
Da: Zack <notifications@github.com>
Inviato: sabato, ottobre 20, 2018 9:38 PM
A: rauenzi/BetterDiscordApp
Cc: marcocorriero; Author
Oggetto: Re: [rauenzi/BetterDiscordApp] BetterDiscord doesn't work at all! (#84)


Do try reinstalling, as that fixes the error described in the OP.
