### ISSUE TITLE
Do you have to install normal discord for BD?

### ISSUE THREAD

**Issue by NorthernV4** [rauenzi/BetterDiscordApp#844]
**Describe the Bug**

**To Reproduce**

**Expected Behavior**

**Screenshots**

**Discord Version**

**Additional Context**

**Comment by Wolfhound905** [comment]
Yes. 
You install Discord first, then you use the BetterDiscord Installer.

**Comment by NathanTurnYT** [comment]
why is this open?

**Comment by rauenzi** [comment]
Yes
