### ISSUE TITLE
Idk what happened

### ISSUE THREAD

**Issue by Seewak342** [rauenzi/BetterDiscordApp#845]
**Describe the Bug**
IDK

**To Reproduce**
i just updated BD then it happened

**Expected Behavior**
IDK

**Screenshots**
<img width="416" alt="eee7cd7f-b2bc-4e50-b109-62800c1b1afa" src="https://user-images.githubusercontent.com/72716065/123046026-d0639e00-d425-11eb-8332-3a51564536f9.png">

**Discord Version**
Canary

**Additional Context**

**Comment by boehs** [comment]
Duplicate of #821

**Comment by NathanTurnYT** [comment]
why is this still open?
