### ISSUE TITLE
Audio Interface Fix Request

### ISSUE THREAD

**Issue by InSovietCS** [rauenzi/BetterDiscordApp#848]
Bug description: audio interface users on all branches of discord, whether it be vanilla or BD, have an iussue where the voice phases in and out for no reason.

Reproduction: automatic. No additional steps needed to reproduce. Join any voice channel or take a test.

Expected behavior: Voice is clear and consistent with no fluctuations in volume, just like when OBS picks it up.

Screenshots: Non applicable. Here's a video link instead that I had sent to discord support, who did absolutely nothing about it: https://youtu.be/KgI040TWAu8

Versions: All. Canary, ptb, stable and BD in conjuction with all of these.

This is an issue with how noise removal (echo removal specifically) works in discord as of the latest two or three updates (and for some reason in Guilded too). If possible, perhaps it would be good to explore solutions to this issue. 
If not, please close this ticket.

I would like to also preface this that this is consistent among many users who use external audio cards, or have ever done so. A system reinstall does not fix this problem. Yes, everything else is functional and tested.

**Comment by rauenzi** [comment]
This is not something that will make it into BD's scope. You're better off reaching out to Discord support.
