### ISSUE TITLE
[Feature] Installer command line arguments

### ISSUE THREAD

**Issue by Balls0fSteel** [rauenzi/BetterDiscordApp#849]
It would be great if the installer would support command line arguments. Think nothing fancy...

**An example:**
Of course, the syntax is only a matter of preference and taste.
Ie.: BetterDiscord-Windows.exe /install-ptb

Would also work. For simplicity's sake, I'd probably do options for each case.
- /install-stable
- /install-ptb
- /install-all
- /repair-stable
- /repair-ptb
- /repair-all
- /uninstall-stable
- /uninstall-beta
- /uninstall-all

If the EULA/agreement is an issue, you can simply implement a switch that implies the user accepts the EULA/agreement.
Ie.: BetterDiscord-Windows.exe /eula /install-ptb

**Why?!**
I use PTB version because I rely on two accounts daily. And while BD installs and remains just fine on Stable, it keeps disappearing from PTB. I pretty much run the installer every second day. This way, I could just have a shortcut, or task scheduler it, anything really.

**Comment by rauenzi** [comment]
Please see my comments on #382
