### ISSUE TITLE
'A fatal javascript error occured' after latest update

### ISSUE THREAD

**Issue by MammothJerk** [rauenzi/BetterDiscordApp#85]
I'm getting this error right after trying to installing the latest update

https://i.imgur.com/azPEaCQ.png

any ideas?

**Comment by luxidoptera** [comment]
Completely uninstall and reinstall Discord (by deleting its folders from AppData/Local and AppData/Roaming), then reinstall BandagedBD. That worked for me when I was having this issue.

**Comment by MammothJerk** [comment]
would that make me lose all my settings, themes, custom css, etc? or are they stored somewhere else?

**Comment by MammothJerk** [comment]
> 
> 
> Update Discord too as the number in that link should have 301 in it not 300 so this might be part of reason of the error message you get

This fixed it for me, all i had to do was install the discord update and now it works as normal, thanks!
