### ISSUE TITLE
Discord loads but BetterDiscord loads infinitely

### ISSUE THREAD

**Issue by zThunderZ** [rauenzi/BetterDiscordApp#86]
The first time I opened the discord it normally loaded with the betterdiscord But after I closed it completely and opened it again was infinitely loading the BetterDiscord any way to solve that?

**Comment by Zynlor** [comment]
Was it right after the installation? I just installed it and i'm inside discord again

**Comment by rauenzi** [comment]
Try reinstalling, some errors were fixed.

**Comment by zThunderZ** [comment]
Do I need to reinstall Discord? if not how do I reinstall BetterDiscord?

**Comment by zThunderZ** [comment]
I just deleted the better discord folder but it still did not work
I followed this path: C: Users\user\AppData\Local\ Discord \ app-0.0.301\ resources\ app\node_modules\ there was the folder betterdiscord so I deleted it and started the discord but it still did not work help me ?

**Comment by NextdoorPsycho** [comment]
Reinstalling Bandage (i have the same issue) installing BD again will fix this issue

Bug was
1)get the error and are told to reinstall BD
2)install it from the git
3)Discord reloads but nothing on Bandage is working

Fix:
reinstall Bandage as of
10/20/18
2:41pm PST

Will prevent BD from loading
well it loads but as you see

And @zThunderZ  dont go and delete things you dont know if you should delete
ie: node_modules that will not solve anything... and may just cause more problems

**Comment by rauenzi** [comment]
A forced reset of BD and reinstall would look like this.
1. Fully close Discord.
2. Delete this directory `%appdata%\discord\0.0.301`
3. Delete this directory `%localappdata%\Discord\app-0.0.301\resources\app`
4. Open Discord
5. Redownload and run the BBD installer

**Comment by NextdoorPsycho** [comment]
> Delete this directory %appdata%\discord\0.0.301
the number might be different 
https://i.imgur.com/iCsIP49.png

**Comment by rauenzi** [comment]
0.0.43 is for PTB, they didn't indicate which release channel they were using and if they were using ptb the directory would be `%appdata%\discordptb\0.0.43` as opposed to just changing the number like `%appdata%\discord\0.0.43`

**Comment by zThunderZ** [comment]
I did all the right steps of **rauenzi** yet the discord carries normal but the betterdiscord is eternally carrying what I do?

**Comment by Italicz** [comment]
How would I go about this on macOS?

**Comment by rauenzi** [comment]
@zThunderZ I don't understand your message.

@Italicz you don't. For mac go to your betterdiscord folder and delete bdstorage.json and reload.

**Comment by Ryonez** [comment]
> A forced reset of BD and reinstall would look like this.
> 
> 1. Fully close Discord.
> 2. Delete this directory `%appdata%\discord\0.0.301`
> 3. Delete this directory `%localappdata%\Discord\app-0.0.301\resources\app`
> 4. Open Discord
> 5. Redownload and run the BBD installer

This hasn't resolved the issue, BD still remains stuck while loading.
I've been having the same issue.

**Comment by markthewolf90** [comment]
> A forced reset of BD and reinstall would look like this.
> 
> 1. Fully close Discord.
> 2. Delete this directory `%appdata%\discord\0.0.301`
> 3. Delete this directory `%localappdata%\Discord\app-0.0.301\resources\app`
> 4. Open Discord
> 5. Redownload and run the BBD installer
Well, I don't have an app folder so that adds further confusion to the issue.

**Comment by markthewolf90** [comment]
> A forced reset of BD and reinstall would look like this.
> 
> 1. Fully close Discord.
> 2. Delete this directory `%appdata%\discord\0.0.301`
> 3. Delete this directory `%localappdata%\Discord\app-0.0.301\resources\app`
> 4. Open Discord
> 5. Redownload and run the BBD installer

Well, I don't have an app folder so that adds further confusion to the issue.

**Comment by rauenzi** [comment]
@Ryonez @zThunderZ delete bdstorage.json from the betterdiscord folder and try it again

**Comment by rauenzi** [comment]
This has gone stale, closing.
