### ISSUE TITLE
Transparency Not working

### ISSUE THREAD

**Issue by LividJava** [rauenzi/BetterDiscordApp#88]
I was aware of a transparency option in the latest update of BBD. from what i can tell its not working properly? I suppose i need more information? if you could respond with what i'd need to provide i will be happy to do so.

OS: Windows 10
BBD Version: 0.2.2

**Comment by rauenzi** [comment]
Be sure to fully restart discord after enabling

**Comment by LividJava** [comment]
Wasn't properly restarting discord.
