### ISSUE TITLE
[Bug] injector.js fails on gentoo linux: Cannot find directory for Discord

### ISSUE THREAD

**Issue by ItsDrike** [rauenzi/BetterDiscordApp#880]
**Describe the Bug**
I've followed the instructions to compile BetterDiscord installer using `npm`, the building process was successful, however after running `npm run inject` (tested with `sudo` too), the installer failed with: `Cannot find directory for Discord`, even though discord is installed properly and its files are under `/opt/discord`, which is common for most Linux distributions.

**To Reproduce**
1. Install discord using gentoo's portage package manager: `emerge net-im/discord-bin`
2. Install nodejs with `npm` use flag with portage: `emerge net-libs/nodejs` (package version: 14.16.1, `npm --version`: 6.14.12)
3. Clone the repository (main branch)
4. Run `npm install` & `npm run build`
5. Run `npm run inject` and encounter this error.

**Expected Behavior**
Discord is installed, it should therefore detect the proper path and inject it with needed files for betterdiscord.

**Screenshots**
![image](https://user-images.githubusercontent.com/20902250/124978202-ffcafb00-e020-11eb-9aa7-036229c83226.png)

**Discord Version**
- Package version: `net-im/discord-bin-0.0.15`, 
- Discord version: `Stable 89550 (3c2108a)`

**Additional Context**
<details>

<summary>
Error log file generated by npm (after running with sudo): 
</summary>

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'inject' ]
2 info using npm@6.14.12
3 info using node@v14.16.1
4 verbose run-script [ 'preinject', 'inject', 'postinject' ]
5 info lifecycle betterdiscord@1.1.1~preinject: betterdiscord@1.1.1
6 info lifecycle betterdiscord@1.1.1~inject: betterdiscord@1.1.1
7 verbose lifecycle betterdiscord@1.1.1~inject: unsafe-perm in lifecycle true
8 verbose lifecycle betterdiscord@1.1.1~inject: PATH: /usr/lib64/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/itsdrike/.local/src/BetterDiscordApp/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin:/usr/lib/llvm/12/bin:/usr/lib/llvm/11/bin
9 verbose lifecycle betterdiscord@1.1.1~inject: CWD: /home/itsdrike/.local/src/BetterDiscordApp
10 silly lifecycle betterdiscord@1.1.1~inject: Args: [ '-c', 'node scripts/inject.js' ]
11 silly lifecycle betterdiscord@1.1.1~inject: Returned: code: 1  signal: null
12 info lifecycle betterdiscord@1.1.1~inject: Failed to exec inject script
13 verbose stack Error: betterdiscord@1.1.1 inject: `node scripts/inject.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib64/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib64/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1048:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid betterdiscord@1.1.1
15 verbose cwd /home/itsdrike/.local/src/BetterDiscordApp
16 verbose Linux 5.12.14-arch1-1
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "inject"
18 verbose node v14.16.1
19 verbose npm  v6.14.12
20 error code ELIFECYCLE
21 error errno 1
22 error betterdiscord@1.1.1 inject: `node scripts/inject.js`
22 error Exit status 1
23 error Failed at the betterdiscord@1.1.1 inject script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

</details>

I'm not sure if it's relevant, it probably shouldn't be, but I was using chroot from an arch system to execute commands in gentoo system, which means the arch kernel was in place, not the gentoo one, if relevant, kernel version: `5.12.14-arch1-1`

**Comment by rauenzi** [comment]
This is the same root cause as #789 it can't find Discord because it's not looking in the correct location. I plan to fix this soon and am tracking it under that issue.
