### ISSUE TITLE
"Not Supported" even after updated

### ISSUE THREAD

**Issue by harjitmoe** [rauenzi/BetterDiscordApp#89]
> Not Supported  
> BetterDiscord v0.2.82 (your version) is not supported by the latest js (0.2.2).
> 
> Please download the latest version from GitHub

This appears upon starting Discord. (Running on Linux (Ubuntu) if this is relevant.)

Re-installing using betterdiscordctl, either from the default `stable16` branch or the `master` branch, does not change this.

Of interest, it appears to temporarily load *something* (displaying the "BetterDiscord is loading" corner icon and also the above message in a modal), but that's it.

**Comment by rauenzi** [comment]
Should try using the `update` command of betterdiscordctl and stable16 is the branch you want

**Comment by harjitmoe** [comment]
I should probably have considered that :woman_facepalming:. Thanks.

**Comment by rauenzi** [comment]
No problem!
