### ISSUE TITLE
Will themes be fixed?

### ISSUE THREAD

**Issue by mrwallace888** [rauenzi/BetterDiscordApp#90]
Will you ever fix the themes so that they work properly?
![image](https://user-images.githubusercontent.com/39398330/47269504-451f0580-d524-11e8-93d7-32062dc9b8b7.png)
This a bit annoying. I heard that the layout update that happened to Discord a while back was what broke it. But can it be fixed at some point? Is there already a fix?

**Comment by rauenzi** [comment]
Theme updates to keep up with discord changes are up to the individual theme authors, not something BBD has control over. Ask the developer of your theme.
