### ISSUE TITLE
Issues with BetterDiscord after update 

### ISSUE THREAD

**Issue by thales720** [rauenzi/BetterDiscordApp#92]
after the last update, BD did not start anymore, it was loading infinitely and it just did not start, after that I tried to relaunch the installer but nothing happened, and then I uninstalled the discord, and deleted all files in the %localAppData% and %AppData% and the installer did not work (I installed the setup on the desktop)

**Comment by thales720** [comment]
> Delete %appdata%\BetterDiscord\bdstorage.json

this folder no longer exists and now, that i try to install BD it is loading infinitely

**Comment by rauenzi** [comment]
Can you come to the support servers? It is much easier that way
