### ISSUE TITLE
Installing on Linux?

### ISSUE THREAD

**Issue by antflga** [rauenzi/BetterDiscordApp#93]
As a Linux user, I don't really expect to get pre-packaged installers for things, but I *do* expect instructions, which there are currently none on the page I get linked to when I start discord.

How do I reinstall?

**Comment by intrnl** [comment]
[betterdiscordctl](https://github.com/bb010g/betterdiscordctl)

**Comment by rauenzi** [comment]
There is a link to the instructions on the readme of this repo.
