### ISSUE TITLE
The new release breaks my discord

### ISSUE THREAD

**Issue by smolplant** [rauenzi/BetterDiscordApp#94]
So after the update with discord, my BD stopped working in the settings and it was also loading forever(but i didnt bother about the loading that much) so i installed the newest release and when i tried to launch it says it just freezes and when i try to launch the previous BD release, it breaks my discord. My discord opens, says "checking for updates" and then it will download updates 1 out of 1, then close and do it all over again and i know someone else had the same issue. Ive uninstalled and reinstalled both discord and BD multiple times, but BD just seems to not fully work.
I just reinstalled discord and its doing the "downloading updates 1 of 1" again.

**Comment by Fordola** [comment]
this helped me too! thanks!

**Comment by smolplant** [comment]
Oki i deleted both discord and betterdiscord and all the folders and stuff i could find in my pc, redownloaded discord and BBD then the newer release and it works fine now! Thanks!!
