### ISSUE TITLE
Updating?

### ISSUE THREAD

**Issue by Lillievela** [rauenzi/BetterDiscordApp#95]
So i have followed https://gist.github.com/ObserverOfTime/d7e60eb9aa7fe837545c8cb77cf31172 to update but it never updates and all Any help at all???

**Comment by rauenzi** [comment]
try running `betterdiscordctl update -v -v`

**Comment by Lillievela** [comment]
Came up with this:
lillie@lillie-HP-BS015dx:~$ betterdiscord update -v -v
betterdiscord: command not found
lillie@lillie-HP-BS015dx:~$ betterdiscordctl update -v -v
VV: Scanning /opt
VV: Trying flavor ''
ERROR: Discord installation not found.
lillie@lillie-HP-BS015dx:~$ betterdiscordctl update -v -v /home/lillie/.config
VV: Scanning /opt
VV: Trying flavor ''
ERROR: Discord installation not found.
lillie@lillie-HP-BS015dx:~$

**Comment by Lillievela** [comment]
I found the command that worked:  betterdiscordctl update -s /home/lillie/.config/discord
