### ISSUE TITLE
Transparency not working

### ISSUE THREAD

**Issue by MrMeeseesks** [rauenzi/BetterDiscordApp#98]
The option to make the main window in discord transparent doesn't work. Any fixes?

**Comment by rauenzi** [comment]
What is your operating system? Have you enabled it and restarted (not reloaded) Discord? Have you ensured your css is sufficient? Here's some test css that might help see through the window:
```css
:root {
    opacity: 0.6;
}
```

**Comment by RedbearPlayz** [comment]
im having this problem too.
Windows 10. Yes. How do you do that? where is that.

**Comment by rauenzi** [comment]
Go to settings > Zere's Fork > enable transparency and **restart** discord. Then put that code above into settings > custom css
